.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 24.0.16410.22266

[24.0] Update BCArtifact version. New value: 24.0.16410.22266

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 24.3.21374.22263

[24.3] Update BCArtifact version. New value: 24.3.21374.22263

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 24.4.22260.0

[24.4] Update BCArtifact version. New value: 24.4.22260.0

---

src/Business Foundation/App/NoSeries/src/Single/NoSeries.Codeunit.al
src/Business Foundation/App/NoSeries/src/Single/NoSeriesImpl.Codeunit.al

This pull request backports #1656 to releases/24.x
Fixes [AB#539307](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/539307)

[releases/24.x] add function to check if number series is in date order

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 24.1.18927.22354

[24.1] Update BCArtifact version. New value: 24.1.18927.22354

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 24.0.16410.22356

[24.0] Update BCArtifact version. New value: 24.0.16410.22356

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 24.2.20227.22380

[24.2] Update BCArtifact version. New value: 24.2.20227.22380

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 24.3.21374.22374

[24.3] Update BCArtifact version. New value: 24.3.21374.22374

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 24.5.22386.0

[24.x] Update BCArtifact version. New value: 24.5.22386.0

---

build/Packages.json

- Update app baselines package version. New value: 23.5.16502.22345

[24.0] Update app baselines package version. New value: 23.5.16502.22345

---

build/Packages.json

- Update app baselines package version. New value: 24.0.16410.22356

[24.1] Update app baselines package version. New value: 24.0.16410.22356

---

src/System Application/App/AI/src/Azure OpenAI/AzureOpenAIImpl.Codeunit.al

Add `[NonDebuggable]` to `CheckJsonModeCompatibility` function.
Fixes [AB#542575](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/542575)

[AI] Add nondebuggable to function

---

build/Packages.json

- Update app baselines package version. New value: 24.2.20227.22380

[24.3] Update app baselines package version. New value: 24.2.20227.22380

---

build/Packages.json

- Update app baselines package version. New value: 24.3.21374.22374
- Update translation package version. New value: 24.4.20240726.3

[24.4] Update app baselines package version. New value: 24.3.21374.22374 (+ 1 more update(s))

---

build/Packages.json

- Update app baselines package version. New value: 24.4.22260.0
- Update translation package version. New value: 24.4.20240726.3

[24.x] Update app baselines package version. New value: 24.4.22260.0 (+ 1 more update(s))

---

build/Packages.json

- Update app baselines package version. New value: 24.1.18927.22354

[24.2] Update app baselines package version. New value: 24.1.18927.22354

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 24.3.21374.22401

[24.3] Update BCArtifact version. New value: 24.3.21374.22401

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 24.1.18927.22400

[24.1] Update BCArtifact version. New value: 24.1.18927.22400

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 24.2.20227.22398

[24.2] Update BCArtifact version. New value: 24.2.20227.22398

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 24.5.22406.0

[24.x] Update BCArtifact version. New value: 24.5.22406.0

---

.github/workflows/UpdateBCArtifactVersion.yaml
.github/workflows/UpdatePackageVersions.yaml
build/scripts/DevEnv/NewDevEnv.psm1

Pin checkout dependencies and add missing docs
This will help address the remaining code scanning alerts 
Fixes [AB#543070](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/543070)

Pin checkout dependencies and add missing docs

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 24.1.18927.22463

[24.1] Update BCArtifact version. New value: 24.1.18927.22463

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 24.5.22483.0

[24.x] Update BCArtifact version. New value: 24.5.22483.0

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 24.0.16410.22464

[24.0] Update BCArtifact version. New value: 24.0.16410.22464

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 24.2.20227.22462

[24.2] Update BCArtifact version. New value: 24.2.20227.22462

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 24.3.21374.22480

[24.3] Update BCArtifact version. New value: 24.3.21374.22480

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 24.0.16410.22532

[24.0] Update BCArtifact version. New value: 24.0.16410.22532

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 24.2.20227.22536

[24.2] Update BCArtifact version. New value: 24.2.20227.22536

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 24.1.18927.22531

[24.1] Update BCArtifact version. New value: 24.1.18927.22531

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 24.5.22533.0

[24.x] Update BCArtifact version. New value: 24.5.22533.0

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 24.3.21374.22530

[24.3] Update BCArtifact version. New value: 24.3.21374.22530

---

src/Business Foundation/App/NoSeriesCopilot/src/Copilot/NoSeriesCopilotImpl.Codeunit.al

Fixes [AB#543285](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/543285)

[No Series Copilot] Uptake new AI SDK changes to tool calling

---

src/System Application/App/Email/src/Email/EmailImpl.Codeunit.al
src/System Application/App/Email/src/Message/EmailMessageImpl.Codeunit.al

Remove `m` from `EmailImpl` and add `r` to `EmailMessageImpl`.

[Email] Fix permissions

---

src/Tools/AI Test Toolkit/src/AITCommandLineCard.Page.al
src/Tools/AI Test Toolkit/src/TestSuite/AITTestMethodLines.Page.al
src/Tools/AI Test Toolkit/src/TestSuite/AITTestSuite.Page.al
src/Tools/AI Test Toolkit/src/TestSuite/AITTestSuiteMgt.Codeunit.al
src/Tools/Test Framework/Test Runner/src/DataDrivenTest/DataInputs/TestInputsManagement.Codeunit.al

1. **Discovered**
- Whenever the page is opened
2. **Set Up**
- Whenever running the start suite or start suite line
- Custom dimensions:
- Run ID (only for suite header)
- Version
- Number of test lines (only for suite header)
3. **Used**
- Test suite is finished running
- Custom dimensions:
- Run ID (only for suite header)
- Version
- Number of tests executed
- Number of tests passed
- Total time taken
4. **Log Usage**
- Dataset imported
- CD: Number of lines imported, Filetype
Fixes [AB#533358](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/533358)

AI Test Toolkit: Update telemetry

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 24.1.18927.22603

[24.1] Update BCArtifact version. New value: 24.1.18927.22603

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 24.0.16410.22602

[24.0] Update BCArtifact version. New value: 24.0.16410.22602

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 24.3.21374.22601

[24.3] Update BCArtifact version. New value: 24.3.21374.22601

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 24.5.22610.0

[24.x] Update BCArtifact version. New value: 24.5.22610.0

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 24.2.20227.22600

[24.2] Update BCArtifact version. New value: 24.2.20227.22600

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 24.5.22632.0

[24.x] Update BCArtifact version. New value: 24.5.22632.0

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 24.4.22295.22621

[24.4] Update BCArtifact version. New value: 24.4.22295.22621

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 24.1.18927.22617

[24.1] Update BCArtifact version. New value: 24.1.18927.22617

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 24.3.21374.22624

[24.3] Update BCArtifact version. New value: 24.3.21374.22624

---

build/Packages.json

- Update app baselines package version. New value: 24.3.21374.22624

[24.4] Update app baselines package version. New value: 24.3.21374.22624

---

build/Packages.json

- Update app baselines package version. New value: 24.0.16410.22602

[24.1] Update app baselines package version. New value: 24.0.16410.22602

---

build/Packages.json

- Update app baselines package version. New value: 24.2.20227.22625

[24.3] Update app baselines package version. New value: 24.2.20227.22625

---

build/Packages.json

- Update app baselines package version. New value: 24.4.22295.22621

[24.x] Update app baselines package version. New value: 24.4.22295.22621

---

build/Packages.json

- Update app baselines package version. New value: 24.1.18927.22617

[24.2] Update app baselines package version. New value: 24.1.18927.22617

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 24.2.20227.22625

[24.2] Update BCArtifact version. New value: 24.2.20227.22625

---

build/Packages.json

- Update app baselines package version. New value: 23.5.16502.22599

[24.0] Update app baselines package version. New value: 23.5.16502.22599

---

src/Business Foundation/App/Entitlements/AzureADApplicationApi.Entitlement.al
src/Business Foundation/App/Entitlements/AzureADApplicationAutomation.Entitlement.al
src/Business Foundation/App/Entitlements/D365BusinessCentralInfrastructure.Entitlement.al
src/Business Foundation/App/Entitlements/DelegatedAdminagentPartner.Entitlement.al
src/Business Foundation/App/Entitlements/DelegatedBCAdminAgentPartner.Entitlement.al
src/Business Foundation/App/Entitlements/DelegatedHelpdeskagentPartner.Entitlement.al
src/Business Foundation/App/Entitlements/Dynamics365AccountantHub.Entitlement.al
src/Business Foundation/App/Entitlements/Dynamics365AdminPartner.Entitlement.al
src/Business Foundation/App/Entitlements/Dynamics365Administrator.Entitlement.al
src/Business Foundation/App/Entitlements/Dynamics365BusinessCentralBasicFinancials.Entitlement.al
src/Business Foundation/App/Entitlements/Dynamics365BusinessCentralDevice.Entitlement.al
src/Business Foundation/App/Entitlements/Dynamics365BusinessCentralDeviceEmbedded.Entitlement.al
src/Business Foundation/App/Entitlements/Dynamics365BusinessCentralEssentialAttach.Entitlement.al
src/Business Foundation/App/Entitlements/Dynamics365BusinessCentralEssentialEmbedded.Entitlement.al
src/Business Foundation/App/Entitlements/Dynamics365BusinessCentralEssentials.Entitlement.al
src/Business Foundation/App/Entitlements/Dynamics365BusinessCentralExternalAccountant.Entitlement.al
src/Business Foundation/App/Entitlements/Dynamics365BusinessCentralPremium.Entitlement.al
src/Business Foundation/App/Entitlements/Dynamics365BusinessCentralPremiumEmbedded.Entitlement.al
src/Business Foundation/App/Entitlements/Dynamics365BusinessCentralPremiumPartnerSandbox.Entitlement.al
src/Business Foundation/App/Entitlements/Dynamics365BusinessCentralTeamMember.Entitlement.al
src/Business Foundation/App/Entitlements/Dynamics365BusinessCentralTeamMemberEmbedded.Entitlement.al
src/Business Foundation/App/Entitlements/Dynamics365BusinessCentralforIWs.Entitlement.al
src/Business Foundation/App/Entitlements/InternalAdministrator.Entitlement.al
src/Business Foundation/App/Entitlements/InternalBCAdministrator.Entitlement.al
src/Business Foundation/App/Entitlements/Microsoft365.Entitlement.al

entitlements for Business Foundation
Fixes [AB#540205](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/540205)

entitlements for Business Foundation

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 24.4.22295.22671

[24.4] Update BCArtifact version. New value: 24.4.22295.22671

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 24.3.21374.22670

[24.3] Update BCArtifact version. New value: 24.3.21374.22670

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 24.2.20227.22674

[24.2] Update BCArtifact version. New value: 24.2.20227.22674

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 24.0.16410.22672

[24.0] Update BCArtifact version. New value: 24.0.16410.22672

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 24.1.18927.22673

[24.1] Update BCArtifact version. New value: 24.1.18927.22673

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 24.5.22668.0

[24.x] Update BCArtifact version. New value: 24.5.22668.0

---

src/System Application/Test Library/AI/src/CopilotTestLibrary.Codeunit.al

To be able to run SLS tests in pipeline, we need overwritten procedure "Register Copilot Capability", that will allow us to register copilot capability for specifi app id.
[AB#543582](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/543582) Add Register Copilot Capability for specific app id  procedure to "Copilot Test Library"

Add Register Copilot Capability procedure for specific app id to Copilot Test Library

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 24.5.22728.0

[24.x] Update BCArtifact version. New value: 24.5.22728.0

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 24.0.16410.22726

[24.0] Update BCArtifact version. New value: 24.0.16410.22726

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 24.1.18927.22708

[24.1] Update BCArtifact version. New value: 24.1.18927.22708

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 24.2.20227.22710

[24.2] Update BCArtifact version. New value: 24.2.20227.22710

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 24.3.21374.22729

[24.3] Update BCArtifact version. New value: 24.3.21374.22729

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 24.1.18927.22747

[24.1] Update BCArtifact version. New value: 24.1.18927.22747

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 24.5.22759.0

[24.x] Update BCArtifact version. New value: 24.5.22759.0

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 24.3.21374.22745

[24.3] Update BCArtifact version. New value: 24.3.21374.22745

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 24.2.20227.22746

[24.2] Update BCArtifact version. New value: 24.2.20227.22746

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 24.4.22295.22744

[24.4] Update BCArtifact version. New value: 24.4.22295.22744

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 24.0.16410.22743

[24.0] Update BCArtifact version. New value: 24.0.16410.22743

---

.github/actions/RunAutomation/SubmitStabilityJob/run.ps1
.github/actions/RunAutomation/UpdateALGo/run.ps1
.github/workflows/SubmitStabilityJobs.yaml
.github/workflows/UpdateALGoOnOfficialBranches.yaml
.github/workflows/UpdateBCArtifactVersion.yaml
.github/workflows/UpdatePackageVersions.yaml
.github/workflows/scorecard-analysis.yml
build/scripts/EnlistmentHelperFunctions.psm1

* Allow the "artifact" setting to use latest available version instead of a hardcoded version 
* Run stability jobs on all official branches 

Allow using latest BCArtifact instead of hardcoded version

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 25.0.22800.0

[main] Update BCArtifact version. New value: 25.0.22800.0

---

.github/AL-Go-Settings.json

[24.x] Update BC Artifact to latest

---

.github/AL-Go-Settings.json

[24.4] Update BC Artifact to latest

---

.github/AL-Go-Settings.json

[24.3] Update BC Artifact to latest

---

.github/AL-Go-Settings.json

[24.2] Update BC Artifact to latest

---

.github/AL-Go-Settings.json

[24.1] Update BC Artifact to latest

---

.github/AL-Go-Settings.json

[24.0] Update BC Artifact to latest

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 25.0.22882.0

[main] Update BCArtifact version. New value: 25.0.22882.0

---

build/Packages.json

- Update app baselines package version. New value: 23.5.16502.22860

[24.0] Update app baselines package version. New value: 23.5.16502.22860

---

build/Packages.json

- Update app baselines package version. New value: 24.5.22880.0

[main] Update app baselines package version. New value: 24.5.22880.0

---

build/Packages.json

- Update app baselines package version. New value: 24.2.20227.22873

[24.3] Update app baselines package version. New value: 24.2.20227.22873

---

build/Packages.json

- Update app baselines package version. New value: 24.1.18927.22867

[24.2] Update app baselines package version. New value: 24.1.18927.22867

---

build/Packages.json

- Update app baselines package version. New value: 24.3.21374.22870

[24.4] Update app baselines package version. New value: 24.3.21374.22870

---

build/Packages.json

- Update app baselines package version. New value: 24.4.22295.22879

[24.x] Update app baselines package version. New value: 24.4.22295.22879

---

build/Packages.json

- Update app baselines package version. New value: 24.0.16410.22868

[24.1] Update app baselines package version. New value: 24.0.16410.22868

---

src/System Application/App/Extension Management/src/ExtensionSettings.Page.al

Fixes [AB#543124](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/543124)

Add Source Control details to Extension Settings

---

.github/AL-Go-Settings.json
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.0] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  0fa5d001900cac6ce60dcb2170b620dd3694dafd

---

.github/AL-Go-Settings.json
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.2] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  0fa5d001900cac6ce60dcb2170b620dd3694dafd

---

.github/AL-Go-Settings.json
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.4] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  0fa5d001900cac6ce60dcb2170b620dd3694dafd

---

.github/AL-Go-Settings.json
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.x] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  0fa5d001900cac6ce60dcb2170b620dd3694dafd

---

.github/AL-Go-Settings.json
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.3] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  0fa5d001900cac6ce60dcb2170b620dd3694dafd

---

.github/AL-Go-Settings.json
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.1] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  0fa5d001900cac6ce60dcb2170b620dd3694dafd

---

.github/AL-Go-Settings.json
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/AI Test Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/AI Test Toolkit/.AL-Go/localDevEnv.ps1
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[main] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  0fa5d001900cac6ce60dcb2170b620dd3694dafd

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 25.0.22930.0

[main] Update BCArtifact version. New value: 25.0.22930.0

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 25.0.22978.0

[main] Update BCArtifact version. New value: 25.0.22978.0

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 25.0.23006.0

[main] Update BCArtifact version. New value: 25.0.23006.0

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 25.0.23040.0

[main] Update BCArtifact version. New value: 25.0.23040.0

---

src/System Application/App/AppSource Gallery/src/AppSourceExtensionManagement.PageExt.al

Action is not visible in online environments but should be.
Fixes [AB#543755](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/543755)

Show action

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 25.0.23100.0

[main] Update BCArtifact version. New value: 25.0.23100.0

---

build/Packages.json

- Update app baselines package version. New value: 23.5.16502.23069

[24.0] Update app baselines package version. New value: 23.5.16502.23069

---

build/Packages.json

- Update app baselines package version. New value: 24.0.16410.23074

[24.1] Update app baselines package version. New value: 24.0.16410.23074

---

build/Packages.json

- Update app baselines package version. New value: 24.1.18927.23075

[24.2] Update app baselines package version. New value: 24.1.18927.23075

---

build/Packages.json

- Update app baselines package version. New value: 24.5.23101.0

[main] Update app baselines package version. New value: 24.5.23101.0

---

build/Packages.json

- Update app baselines package version. New value: 24.4.22295.23050

[24.x] Update app baselines package version. New value: 24.4.22295.23050

---

build/Packages.json

- Update app baselines package version. New value: 24.2.20227.23090

[24.3] Update app baselines package version. New value: 24.2.20227.23090

---

build/Packages.json

- Update app baselines package version. New value: 24.3.21374.23073

[24.4] Update app baselines package version. New value: 24.3.21374.23073

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 25.0.23141.0

[main] Update BCArtifact version. New value: 25.0.23141.0

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 25.0.23170.0

[main] Update BCArtifact version. New value: 25.0.23170.0

---

src/Business Foundation/App/NoSeriesCopilot/app.json
src/Business Foundation/App/NoSeriesCopilot/src/Copilot/NoSeriesCopilotImpl.Codeunit.al
src/Business Foundation/App/NoSeriesCopilot/src/Copilot/NoSeriesGeneration.Page.al
src/Business Foundation/App/NoSeriesCopilot/src/Register/NoSeriesCopilotCap.EnumExt.al
src/Business Foundation/Test Library/NoSeriesCopilot/app.json
src/Business Foundation/Test Library/NoSeriesCopilot/src/LibraryNoSeriesCopilot.Codeunit.al
src/Business Foundation/Test/NoSeriesCopilot/app.json
src/Business Foundation/Test/NoSeriesCopilot/src/NoSeriesCopilotAccuTests.Codeunit.al
src/Business Foundation/Test/NoSeriesCopilot/src/NoSeriesCopilotHarmsTests.Codeunit.al
src/Business Foundation/Test/app.json
src/System Application/Test/DisabledTests/NoSeriesSuggestionsTest.json

This PR addesses the following issues:
- We should not return free-text from the model. Free-text replies have hence been replaced by canned error messages - which also render better in the prompt dialog now.
- The feature registration may not include the work Copilot. The capability is not a copilot, it a capability of the Copilot.
- Add simple AI test automation added.
Fixes [AB#544083](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/544083), [AB#544055](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/544055)

[No. Series Copilot] Bundled modifications to the No. Series Copilot

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 25.0.23210.0

[main] Update BCArtifact version. New value: 25.0.23210.0

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 25.0.23234.0

[main] Update BCArtifact version. New value: 25.0.23234.0

---

src/System Application/App/Performance Profiler/src/PerformanceProfilerDelete.Codeunit.al

Add retention policy delete codeunit for performance profiler scheduler
Fixes [AB#545001](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/545001)

Add retention policy delete codeunit for performance profiler scheduler

---

src/Business Foundation/Test/NoSeriesCopilot/app.json
src/Business Foundation/Test/app.json

Add 2nd level dependencies to unblock uptake
[AB#545765](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/545765)

Add dependencies for Business Foundation Tests

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 25.0.23312.0

[main] Update BCArtifact version. New value: 25.0.23312.0

---

build/Packages.json

- Update app baselines package version. New value: 23.5.16502.23278

[24.0] Update app baselines package version. New value: 23.5.16502.23278

---

build/Packages.json

- Update app baselines package version. New value: 24.4.22295.23299
- Update translation package version. New value: 24.5.20240823.1

[24.x] Update app baselines package version. New value: 24.4.22295.23299 (+ 1 more update(s))

---

build/Packages.json

- Update app baselines package version. New value: 24.0.16410.23275

[24.1] Update app baselines package version. New value: 24.0.16410.23275

---

build/Packages.json

- Update app baselines package version. New value: 24.3.21374.23291

[24.4] Update app baselines package version. New value: 24.3.21374.23291

---

build/Packages.json

- Update app baselines package version. New value: 24.5.23302.0
- Update translation package version. New value: 25.0.20240826.4

[main] Update app baselines package version. New value: 24.5.23302.0 (+ 1 more update(s))

---

build/Packages.json

- Update app baselines package version. New value: 24.1.18927.23298

[24.2] Update app baselines package version. New value: 24.1.18927.23298

---

src/Business Foundation/App/NoSeriesCopilot/src/Copilot/NoSeriesExt.PageExt.al
src/Business Foundation/App/NoSeriesCopilot/src/Register/NoSeriesCopilotInstall.Codeunit.al
src/Business Foundation/App/NoSeriesCopilot/src/Register/NoSeriesCopilotRegister.Codeunit.al

Disable the "Suggest No. Series" feature until we've got all necessary sign-offs and approvals.
Fixes [AB#545893](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/545893)

Disable Suggest No. Series features for now.

---

src/System Application/Test/AI/src/AzureOpenAITest.Codeunit.al

Modify test that checks if Copilot Capabilities are enabled when the privacy notice is "not set"
Fixes [AB#537341](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/537341/)

Modify test that checks if Copilot Capabilities are enabled when the privacy notice is "not set"

---

.github/AL-Go-Settings.json

Add CLEAN26 as a preprocessor symbol
Related to [AB#545842](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/545842)

Add CLEAN26 as a preprocessor symbol

---

src/System Application/App/Guided Experience/src/Checklist Banner/ChecklistBannerImpl.Codeunit.al

This procedure can overflow and it was causing any user having that in their RC to not be able to use the system. Exiting with a Max value if overflowing.
Fixes [AB#542605](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/542605)

Check for overflow on expected duration in milliseconds

---

src/System Application/App/Email/src/Message/EmailMessage.Codeunit.al
src/System Application/App/Email/src/Message/EmailMessageImpl.Codeunit.al
src/System Application/Test/Email/src/EmailTest.Codeunit.al

This pull request backports #1894 to releases/25.0

[releases/25.0] [Email] Add subject to API and docs

---

src/System Application/App/Email/src/Message/EmailMessage.Codeunit.al
src/System Application/App/Email/src/Message/EmailMessageImpl.Codeunit.al
src/System Application/Test/Email/src/EmailTest.Codeunit.al

1. Missing docs for the new email APIs
2. Add `subject` parameter

[Email] Add subject to API and docs

---

src/System Application/App/VS Code Integration/src/VsCodeIntegrationImpl.Codeunit.al

Fixes [AB#546667](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/546667)

Fix get app id for object

---

build/Packages.json

- Update app baselines package version. New value: 23.5.16502.23392

[24.0] Update app baselines package version. New value: 23.5.16502.23392

---

build/Packages.json

- Update translation package version. New value: 25.0.20240828.4

[25.0] Update translation package version. New value: 25.0.20240828.4

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 25.1.23411.0

[25.x] Update BCArtifact version. New value: 25.1.23411.0

---

build/Packages.json

- Update app baselines package version. New value: 24.0.16410.23401

[24.1] Update app baselines package version. New value: 24.0.16410.23401

---

build/Packages.json

- Update app baselines package version. New value: 24.2.20227.23405

[24.3] Update app baselines package version. New value: 24.2.20227.23405

---

build/Packages.json

- Update app baselines package version. New value: 24.3.21374.23388

[24.4] Update app baselines package version. New value: 24.3.21374.23388

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 25.0.23371.0

[25.0] Update BCArtifact version. New value: 25.0.23371.0

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.23521.0

[main] Update BCArtifact version. New value: 26.0.23521.0

---

src/System Application/App/AppSource Gallery/src/AppSourceProductManager.Codeunit.al

Introduce a few more IsSaaS tests to ensure we do not get to the Entra retrieval.
Fixes [AB#545722](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/545722)

Microsoft AppSource Apps shows error on docker.

---

src/System Application/App/Security Groups/src/InheritedPermissionSetsPart.Page.al
src/System Application/App/Security Groups/src/UserSecurityGroupsPart.Page.al

Moving user subparts to system app - Fixing internal methods on the pages

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: bcinsider/Sandbox/24.6/base/latest

[24.x] Update BCArtifact version. New value: bcinsider/Sandbox/24.6/base/latest

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.23634.0

[main] Update BCArtifact version. New value: 26.0.23634.0

---

build/Packages.json

- Update app baselines package version. New value: 23.5.16502.23612

[24.0] Update app baselines package version. New value: 23.5.16502.23612

---

build/Packages.json

- Update app baselines package version. New value: 24.0.16410.23611

[24.1] Update app baselines package version. New value: 24.0.16410.23611

---

build/Packages.json

- Update app baselines package version. New value: 25.0.23364.23629
- Update translation package version. New value: 25.1.20240902.2

[25.x] Update app baselines package version. New value: 25.0.23364.23629 (+ 1 more update(s))

---

build/Packages.json

- Update app baselines package version. New value: 24.3.21374.23624

[24.4] Update app baselines package version. New value: 24.3.21374.23624

---

build/Packages.json

- Update app baselines package version. New value: 25.1.23628.0
- Update translation package version. New value: 26.0.20240902.5

[main] Update app baselines package version. New value: 25.1.23628.0 (+ 1 more update(s))

---

build/Packages.json

- Update app baselines package version. New value: 24.2.20227.23631

[24.3] Update app baselines package version. New value: 24.2.20227.23631

---

build/Packages.json

- Update app baselines package version. New value: 24.4.22295.23627
- Update translation package version. New value: 24.5.20240902.6

[24.5] Update app baselines package version. New value: 24.4.22295.23627 (+ 1 more update(s))

---

build/Packages.json

- Update app baselines package version. New value: 24.1.18927.23610

[24.2] Update app baselines package version. New value: 24.1.18927.23610

---

build/Packages.json

- Update app baselines package version. New value: 24.5.23596.0
- Update translation package version. New value: 24.5.20240902.6

[24.x] Update app baselines package version. New value: 24.5.23596.0 (+ 1 more update(s))

---

src/System Application/App/Performance Profiler/src/SamplingPerfProfilerImpl.Codeunit.al
src/System Application/Test/Performance Profiler/src/SamplingPerfProfilerTest.Codeunit.al

Wrap deserialize in a try function to show better error to user
Fixes [AB#545042](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/545042/)

[Perf Profiler] Wrap deserialize in a try function

---

src/System Application/App/VS Code Integration/src/VsCodeIntegrationImpl.Codeunit.al

This pull request backports #1900 to releases/25.x
Fixes [AB#547340](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/547340)

[releases/25.x] Fix get app id for object

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.23679.0

[main] Update BCArtifact version. New value: 26.0.23679.0

---

src/Business Foundation/App/NoSeriesCopilot/src/Copilot/NoSeriesCopilotImpl.Codeunit.al

Change from 4o-mini to 4o.
Fixes [AB#485736](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/485736)

Change AOAI Deployment to 4o

---

.github/workflows/powershell.yaml

Run PSScriptAnalyzer only on when there are PS changes
Fixes [AB#547544](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/547544)

Run PSScriptAnalyzer only on when there are PS changes

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.23743.0

[main] Update BCArtifact version. New value: 26.0.23743.0

---

src/System Application/Test/User Login Times/src/UserLoginTimeTrackerTest.Codeunit.al

USER LOGIN VIEW ps was replaced by inherent permissions
Fixes [AB#547561](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/547561)

User Login View was replaced by inherent permissions

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.4] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  9308ffb724a39179ea32dd55c838f176903a2a5c

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.0] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  9308ffb724a39179ea32dd55c838f176903a2a5c

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/25.0] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  9308ffb724a39179ea32dd55c838f176903a2a5c

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/25.x] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  9308ffb724a39179ea32dd55c838f176903a2a5c

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.1] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  9308ffb724a39179ea32dd55c838f176903a2a5c

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[main] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  9308ffb724a39179ea32dd55c838f176903a2a5c

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.2] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  9308ffb724a39179ea32dd55c838f176903a2a5c

---

src/System Application/App/Page Summary Provider/src/PageSummaryProviderImpl.Codeunit.al

Fixes [AB#547731](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/547731)

Page Summary Provider - Remove the error

---

.github/workflows/_BuildALGoProject.yaml

[main] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  73f489ec1d9a34fa2ed69fbafd5e0ec9bd67f48b

---

src/System Application/App/AppSource Gallery/src/AppSourceProductDetails.Page.al
src/System Application/App/AppSource Gallery/src/AppSourceProductList.Page.al
src/System Application/App/AppSource Gallery/src/AppSourceProductManager.Codeunit.al
src/System Application/App/Extension Management/src/ExtensionInstallation.Page.al

Fixes the following bugs:
- Installed column on the AppSource Apps list page is only set after clicking on record.
- Bad formatting of currencies in the AppSource card page.
- Extension Installation page is not closed after (un)successful installation.
- Error when opening AppSource list page OnPrem.
Fixes [AB#547459](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/547459)

[releases/25.x] Minor bugs on AppSource module

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.23813.0

[main] Update BCArtifact version. New value: 26.0.23813.0

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.23872.0

[main] Update BCArtifact version. New value: 26.0.23872.0

---

build/Packages.json

- Update app baselines package version. New value: 24.4.22295.23964

[24.5] Update app baselines package version. New value: 24.4.22295.23964

---

build/Packages.json

- Update app baselines package version. New value: 24.3.21374.23931

[24.4] Update app baselines package version. New value: 24.3.21374.23931

---

build/Packages.json

- Update app baselines package version. New value: 24.2.20227.23933

[24.3] Update app baselines package version. New value: 24.2.20227.23933

---

build/Packages.json

- Update app baselines package version. New value: 25.0.23364.23971
- Update translation package version. New value: 25.1.20240905.2

[25.x] Update app baselines package version. New value: 25.0.23364.23971 (+ 1 more update(s))

---

build/Packages.json

- Update app baselines package version. New value: 23.5.16502.23914

[24.0] Update app baselines package version. New value: 23.5.16502.23914

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.23945.0

[main] Update BCArtifact version. New value: 26.0.23945.0

---

build/Packages.json

- Update translation package version. New value: 24.6.20240905.3

[24.x] Update translation package version. New value: 24.6.20240905.3

---

src/System Application/App/Data Administration/src/MediaCleanup.Codeunit.al
src/System Application/App/Data Administration/src/MediaCleanupImpl.Codeunit.al

port from #1990
Fixes [AB#548335](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/548335)

[24.4] Delete TenantMediaSet in Batch and safeguard loading detached media

---

src/System Application/App/Data Administration/src/MediaCleanup.Codeunit.al
src/System Application/App/Data Administration/src/MediaCleanupImpl.Codeunit.al

port from #1990 
Fixes [AB#548336](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/548336)

[24.5] Delete TenantMediaSet in Batch and safeguard loading detached media

---

src/System Application/App/Data Administration/src/MediaCleanup.Codeunit.al
src/System Application/App/Data Administration/src/MediaCleanupImpl.Codeunit.al

port from #1990
Fixes [AB#548337](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/548337)

[24.x] Delete TenantMediaSet in Batch and safeguard loading detached media

---

src/System Application/App/Data Administration/src/MediaCleanupImpl.Codeunit.al

Fix Split list to include the leftovers in Media Cleanup
Fixes [AB#548445](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/548445)

fix split list to include the leftovers

---

src/System Application/App/Data Administration/src/MediaCleanupImpl.Codeunit.al

Port from #2001
Fixes [AB#548455](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/548455)

[25.x] fix split list to include the leftovers

---

src/System Application/App/Data Administration/src/MediaCleanupImpl.Codeunit.al

port from #2001
Fixes [AB#548456](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/548456)

[25.0] fix split list to include the leftovers

---

src/System Application/App/Data Administration/src/MediaCleanupImpl.Codeunit.al

port from #2001
Fixes [AB#548440](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/548440)

[24.x] fix split list to include the leftovers

---

src/System Application/App/Data Administration/src/MediaCleanupImpl.Codeunit.al

port from #2001
Fixes [AB#548441](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/548441)

[24.5] fix split list to include the leftovers

---

src/System Application/App/Data Administration/src/MediaCleanupImpl.Codeunit.al

port from #2001
Fixes [AB#548442](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/548442)

[24.4] fix split list to include the leftovers

---

src/System Application/App/Azure AD Plan/src/AzureADPlanImpl.Codeunit.al
src/System Application/App/Azure AD User Management/src/User sync/AzureADUserSyncImpl.Codeunit.al

Improve telemetry logging for troubleshooting.
Fixes [AB#547958](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/547958/)

[User Sync] Improve telemetry logging

---

src/Tools/AI Test Toolkit/src/AITTestContextImpl.Codeunit.al

Problem:
After changes to support multi-turn testing, SetTestOutput throws an error since json is expected.
Solution:
Add test output as json.
Fixes [AB#547285](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/543296)

[AI Test Tool] Fix SetTestOutput

---

src/System Application/App/ControlAddIns/Resources/PowerBIManagement/js/PowerBIManagement.js
src/System Application/App/ControlAddIns/src/PowerBIManagement.ControlAddin.al
src/System Application/App/Resources/PowerBIManagement/js/PowerBIManagement.js

Until now, the Power BI add-in did not support specifying a locale. We are adding that support.
Fixes [AB#548452](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/548452)

[PowerBIAddin] Add support for language config

---

src/Tools/AI Test Toolkit/src/AITCommandLineCard.Page.al
src/Tools/AI Test Toolkit/src/TestSuite/AITTestSuite.Page.al

Remove the hard checks on the UI for OnPrem or  (SaaS and sandbox).
Instead, we rely on Installation code to check this.
Fixes [AB#548709](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/548709)

AI Test Toolkit: Remove the hard checks on the UI. Instead, we rely on Installation code

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.24149.0

[main] Update BCArtifact version. New value: 26.0.24149.0

---

build/Packages.json
src/System Application/App/Email/src/Message/EmailMessage.Codeunit.al
src/System Application/App/Email/src/Message/EmailMessageImpl.Codeunit.al
src/System Application/Test/Email/src/EmailTest.Codeunit.al

[AB#548140](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/548140)

Reapply "[Email] Add subject to API and docs (#1894)" (#1919)

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: bcartifacts/Sandbox/24.5/base/latest

[24.5] Update BCArtifact version. New value: bcartifacts/Sandbox/24.5/base/latest

---

src/Business Foundation/Test/NoSeriesCopilot/src/NoSeriesCopilotHarmsTests.Codeunit.al

Improves the harm tests. Makes it capable of both dealing with exceptions and empty result sets.
Fixes [AB#503148](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/503148)

Improve harms test

---

build/Packages.json

- Update app baselines package version. New value: 23.5.16502.24244

[24.0] Update app baselines package version. New value: 23.5.16502.24244

---

build/Packages.json

- Update app baselines package version. New value: 24.1.18927.24243

[24.2] Update app baselines package version. New value: 24.1.18927.24243

---

build/Packages.json

- Update app baselines package version. New value: 24.5.23489.24267

[25.0] Update app baselines package version. New value: 24.5.23489.24267

---

build/Packages.json

- Update app baselines package version. New value: 24.3.21374.24238

[24.4] Update app baselines package version. New value: 24.3.21374.24238

---

build/Packages.json

- Update app baselines package version. New value: 24.2.20227.24248

[24.3] Update app baselines package version. New value: 24.2.20227.24248

---

build/Packages.json

- Update app baselines package version. New value: 24.4.22295.24242

[24.5] Update app baselines package version. New value: 24.4.22295.24242

---

build/Packages.json

- Update app baselines package version. New value: 25.1.24274.0
- Update translation package version. New value: 26.0.20240916.5

[main] Update app baselines package version. New value: 25.1.24274.0 (+ 1 more update(s))

---

build/Packages.json

- Update app baselines package version. New value: 25.0.23364.24269
- Update translation package version. New value: 25.1.20240917.3

[25.x] Update app baselines package version. New value: 25.0.23364.24269 (+ 1 more update(s))

---

src/System Application/App/Page Summary Provider/src/PageSummaryProviderImpl.Codeunit.al

Fixes [AB#549213](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/549213)

Page summary telemetry - fix wrong condition

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.24318.0

[main] Update BCArtifact version. New value: 26.0.24318.0

---

src/System Application/App/ControlAddIns/Resources/PowerBIManagement/js/PowerBIManagement.js
src/System Application/App/ControlAddIns/src/PowerBIManagement.ControlAddin.al
src/System Application/App/Resources/PowerBIManagement/js/PowerBIManagement.js

Until now, the Power BI add-in did not support specifying a locale. We are adding that support.
Fixes [AB#549136](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/549136)

[25.x][PowerBIAddin] Add support for language config (#2020)

---

build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1

[releases/25.x] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  ff5817559912b8a13b51c09368f01a623acd2082

---

build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1

[main] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  ff5817559912b8a13b51c09368f01a623acd2082

---

build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1

[releases/24.x] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  ff5817559912b8a13b51c09368f01a623acd2082

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.24443.0

[main] Update BCArtifact version. New value: 26.0.24443.0

---

src/System Application/Test Library/AI/src/CopilotTestLibrary.Codeunit.al

Use rename to change the primary key
Fixes [AB#549398](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/549398)

Bug: AI Test Capability Registration from Test Library does not work

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.24595.0

[main] Update BCArtifact version. New value: 26.0.24595.0

---

build/Packages.json

- Update app baselines package version. New value: 23.5.16502.24567

[24.0] Update app baselines package version. New value: 23.5.16502.24567

---

build/Packages.json

- Update app baselines package version. New value: 24.1.18927.24578

[24.2] Update app baselines package version. New value: 24.1.18927.24578

---

build/Packages.json

- Update app baselines package version. New value: 24.3.21374.24583

[24.4] Update app baselines package version. New value: 24.3.21374.24583

---

build/Packages.json

- Update app baselines package version. New value: 24.0.16410.24582

[24.1] Update app baselines package version. New value: 24.0.16410.24582

---

build/Packages.json

- Update app baselines package version. New value: 25.0.23364.24593
- Update translation package version. New value: 25.1.20240918.4

[25.x] Update app baselines package version. New value: 25.0.23364.24593 (+ 1 more update(s))

---

build/Packages.json

- Update app baselines package version. New value: 24.2.20227.24581

[24.3] Update app baselines package version. New value: 24.2.20227.24581

---

build/Packages.json

- Update app baselines package version. New value: 24.4.22295.24579

[24.5] Update app baselines package version. New value: 24.4.22295.24579

---

build/Packages.json

- Update app baselines package version. New value: 25.1.24594.0
- Update translation package version. New value: 26.0.20240919.5

[main] Update app baselines package version. New value: 25.1.24594.0 (+ 1 more update(s))

---

src/System Application/App/AppSource Gallery/src/AppSourceProductDetails.Page.al
src/System Application/App/AppSource Gallery/src/AppSourceProductList.Page.al

Updates to the AppSource apps UX
Fixes
[AB#548204](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/548204)

Updates to the AppSource apps UX (#1975)

---

src/System Application/App/AppSource Gallery/src/AppSourceProductList.Page.al

Fixes [AB#548204](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/548204)

Shorten the caption for refresh apps

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.24720.0

[main] Update BCArtifact version. New value: 26.0.24720.0

---

src/Tools/AI Test Toolkit/src/TestSuite/AITTestMethodLine.Table.al
src/Tools/AI Test Toolkit/src/TestSuite/AITTestSuite.Table.al

When updating the input dataset of the suite, we should update the lines to clearly reflect what dataset will be used for each line.
Fixes [AB#547352](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/543079/)

[AI Test Tool] Update lines when changing input dataset

---

src/System Application/App/Azure AD Plan/src/AzureADPlanImpl.Codeunit.al
src/System Application/App/Azure AD User Management/src/User sync/AzureADUserSyncImpl.Codeunit.al

Improve telemetry logging for troubleshooting.
Fixes [AB#548561](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/548561)

[25.x] [User Sync] Improve telemetry logging

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.24770.0

[main] Update BCArtifact version. New value: 26.0.24770.0

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.24822.0

[main] Update BCArtifact version. New value: 26.0.24822.0

---

src/System Application/Test/Data Administration/src/MediaCleanupTest.Codeunit.al

Add Indirect permission in the codeunit instead.
SUPER permission doesn't exist in System App.
Fixes [AB#551003](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/551003)

fix permission in test

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.24908.0

[main] Update BCArtifact version. New value: 26.0.24908.0

---

build/Packages.json

- Update app baselines package version. New value: 23.5.16502.24854

[24.0] Update app baselines package version. New value: 23.5.16502.24854

---

build/Packages.json

- Update app baselines package version. New value: 24.5.23489.24909

[25.0] Update app baselines package version. New value: 24.5.23489.24909

---

build/Packages.json

- Update app baselines package version. New value: 24.2.20227.24862

[24.3] Update app baselines package version. New value: 24.2.20227.24862

---

build/Packages.json

- Update app baselines package version. New value: 24.0.16410.24853

[24.1] Update app baselines package version. New value: 24.0.16410.24853

---

build/Packages.json

- Update app baselines package version. New value: 25.1.24906.0
- Update translation package version. New value: 26.0.20240926.4

[main] Update app baselines package version. New value: 25.1.24906.0 (+ 1 more update(s))

---

build/Packages.json

- Update app baselines package version. New value: 24.4.22295.24910

[24.5] Update app baselines package version. New value: 24.4.22295.24910

---

build/Packages.json

- Update translation package version. New value: 24.6.20240926.8

[24.x] Update translation package version. New value: 24.6.20240926.8

---

build/Packages.json

- Update app baselines package version. New value: 24.1.18927.24857

[24.2] Update app baselines package version. New value: 24.1.18927.24857

---

src/System Application/Test/DisabledTests/RestClientTests.DisabledTest.json

gatejob -Id 3161715 | gatetask -TaskStatus Completed | ft
Test have passed instability
Fixes [AB#542400](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/542400)

Reenable Rest Client tests

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: bcartifacts/Sandbox/25.0/base/latest

[25.0] Update BCArtifact version. New value: bcartifacts/Sandbox/25.0/base/latest

---

src/System Application/App/AI/src/Copilot/CopilotCapabilitiesGA.Page.al
src/System Application/App/Azure AD Plan/src/Plan Configuration/PlanConfiguration.Table.al
src/System Application/App/Azure AD Plan/src/Plan Configuration/PlanConfigurationCard.Page.al
src/System Application/App/Azure AD User Management/src/User sync/AzureADUserUpdateWizard.Page.al
src/System Application/App/Data Classification/app.json
src/System Application/App/Data Classification/src/DataClassificationMgtImpl.Codeunit.al
src/System Application/App/Feature Key/app.json
src/System Application/App/Feature Key/src/FeatureManagementImpl.Codeunit.al
src/System Application/App/Permission Sets/src/PermissionImpl.Codeunit.al
src/System Application/App/Permission Sets/src/PermissionSet.Page.al
src/System Application/App/Permission Sets/src/PermissionSetCopyImpl.Codeunit.al
src/System Application/App/Privacy Notice/app.json
src/System Application/App/Privacy Notice/src/PrivacyNoticeApproval.Codeunit.al
src/System Application/App/Retention Policy/src/Apply Retention Policy/ApplyRetentionPolicyImpl.Codeunit.al
src/System Application/App/Retention Policy/src/Retention Policy Setup/RetentionPolicySetup.Table.al
src/System Application/App/Security Groups/src/SecurityGroupPermissionSets.Page.al
src/System Application/App/User Settings/src/UserSettingsImpl.Codeunit.al
src/System Application/App/Web Service Management/src/WebServiceManagementImpl.Codeunit.al

This PR adapts the PR [here](https://github.com/microsoft/BCApps/pull/1859) to 24.x
It requires the use of DotNet wrappers for audit logging.
Those wrappers will be made available with the PR [here](https://github.com/microsoft/BCApps/pull/2064)
Fixes [AB#538235](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/538235)

Adding Purview telemetry to the System apps (24.x)

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.25030.0

[main] Update BCArtifact version. New value: 26.0.25030.0

---

src/Tools/AI Test Toolkit/src/TestSuite/AITTestMethodLine.Table.al

Previous PR #1933 sets the line input dataset to the suite dataset. This should only be done when it's not already set on the line, as it will otherwise be overwritten.
Fixes [AB#550964](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/550964)

[AI Test Tool] Only update input dataset if not set

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.25082.0

[main] Update BCArtifact version. New value: 26.0.25082.0

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.25124.0

[main] Update BCArtifact version. New value: 26.0.25124.0

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.25229.0

[main] Update BCArtifact version. New value: 26.0.25229.0

---

build/Packages.json

- Update app baselines package version. New value: 23.5.16502.25173

[24.0] Update app baselines package version. New value: 23.5.16502.25173

---

build/Packages.json

- Update app baselines package version. New value: 24.1.18927.25172

[24.2] Update app baselines package version. New value: 24.1.18927.25172

---

build/Packages.json

- Update app baselines package version. New value: 24.0.16410.25171

[24.1] Update app baselines package version. New value: 24.0.16410.25171

---

build/Packages.json

- Update app baselines package version. New value: 24.2.20227.25182

[24.3] Update app baselines package version. New value: 24.2.20227.25182

---

build/Packages.json

- Update app baselines package version. New value: 24.3.21374.25178

[24.4] Update app baselines package version. New value: 24.3.21374.25178

---

build/Packages.json

- Update app baselines package version. New value: 24.4.22295.25180

[24.5] Update app baselines package version. New value: 24.4.22295.25180

---

build/Packages.json

- Update app baselines package version. New value: 25.0.23364.25217

[25.x] Update app baselines package version. New value: 25.0.23364.25217

---

src/System Application/App/User Settings/src/UserSettings.Page.al
src/System Application/App/User Settings/src/UserSettingsImpl.Codeunit.al

Deprecate modern action bar survey
Fixes [AB#551374](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/551374/)

[CES] Remove modern action bar survey

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.25286.0

[main] Update BCArtifact version. New value: 26.0.25286.0

---

src/System Application/App/AppSource Gallery/app.json
src/System Application/App/AppSource Gallery/src/AppSourceProductDetails.Page.al
src/System Application/App/AppSource Gallery/src/AppSourceProductManager.Codeunit.al

Always allow installation of app source apps for delegated admins.
Fixes [AB#551407](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/551407)

Allow install

---

src/Tools/AI Test Toolkit/Permissions/AITestToolkitObj.PermissionSet.al
src/Tools/AI Test Toolkit/src/TestSuite/AITBatchRunDialog.Page.al
src/Tools/AI Test Toolkit/src/TestSuite/AITTestSuite.Page.al
src/Tools/AI Test Toolkit/src/TestSuite/AITTestSuiteMgt.Codeunit.al

Allow multiple iterations of the same suite in AI Test Tool. New action "Batch Run" allows specifying number of iterations.
Fixes [AB#543079](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/543079)

[AI Test Tool] Add support for multiple iterations of suite

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.25345.0

[main] Update BCArtifact version. New value: 26.0.25345.0

---

src/System Application/App/AppSource Gallery/src/AppSourceProductDetails.Page.al
src/System Application/App/AppSource Gallery/src/AppSourceProductList.Page.al
src/System Application/App/AppSource Gallery/src/AppSourceProductManager.Codeunit.al
src/System Application/App/Extension Management/src/ExtensionInstallation.Page.al

This pull request backports #1951 to releases/25.0
Fixes [AB#548904](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/548904)

[releases/25.0] Minor bugs on AppSource module

---

build/Packages.json

- Update app baselines package version. New value: 24.4.22295.25426

[24.5] Update app baselines package version. New value: 24.4.22295.25426

---

build/Packages.json

- Update app baselines package version. New value: 25.0.23364.25488

[25.x] Update app baselines package version. New value: 25.0.23364.25488

---

build/Packages.json

- Update app baselines package version. New value: 24.0.16410.25451

[24.1] Update app baselines package version. New value: 24.0.16410.25451

---

build/Packages.json

- Update app baselines package version. New value: 24.2.20227.25447

[24.3] Update app baselines package version. New value: 24.2.20227.25447

---

build/Packages.json

- Update app baselines package version. New value: 25.1.25484.0

[main] Update app baselines package version. New value: 25.1.25484.0

---

build/Packages.json

- Update app baselines package version. New value: 24.1.18927.25448

[24.2] Update app baselines package version. New value: 24.1.18927.25448

---

build/Packages.json

- Update app baselines package version. New value: 24.5.23489.25450

[25.0] Update app baselines package version. New value: 24.5.23489.25450

---

build/Packages.json

- Update app baselines package version. New value: 24.3.21374.25449

[24.4] Update app baselines package version. New value: 24.3.21374.25449

---

build/Packages.json

- Update app baselines package version. New value: 23.5.16502.25446

[24.0] Update app baselines package version. New value: 23.5.16502.25446

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.25490.0

[main] Update BCArtifact version. New value: 26.0.25490.0

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.25535.0

[main] Update BCArtifact version. New value: 26.0.25535.0

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.25585.0

[main] Update BCArtifact version. New value: 26.0.25585.0

---

src/System Application/App/AI/src/Copilot/CopilotCapabilitiesGA.Page.al
src/System Application/App/Permission Sets/src/PermissionImpl.Codeunit.al
src/System Application/App/Privacy Notice/src/PrivacyNoticeApproval.Codeunit.al
src/System Application/App/Retention Policy/src/Retention Policy Setup/RetentionPolicySetup.Table.al
src/System Application/App/User Settings/src/UserSettingsImpl.Codeunit.al
src/System Application/App/Web Service Management/src/WebServiceManagementImpl.Codeunit.al

The PR intents to fix misc typos or smaller Purview category bugs.
Fixes [AB#554698](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/554698)

Fixing Purview misc mistakes in System apps

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.25660.0

[main] Update BCArtifact version. New value: 26.0.25660.0

---

src/System Application/App/AI/src/Copilot/CopilotCapabilitiesGA.Page.al
src/System Application/App/Permission Sets/src/PermissionImpl.Codeunit.al
src/System Application/App/Privacy Notice/src/PrivacyNoticeApproval.Codeunit.al
src/System Application/App/Retention Policy/src/Retention Policy Setup/RetentionPolicySetup.Table.al
src/System Application/App/User Settings/src/UserSettingsImpl.Codeunit.al
src/System Application/App/Web Service Management/src/WebServiceManagementImpl.Codeunit.al

The PR intents to fix misc typos or smaller Purview category bugs.
Fixes [AB#555028](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/555028)

[25.x] Fixing Purview misc mistakes in System apps

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.25733.0

[main] Update BCArtifact version. New value: 26.0.25733.0

---

build/Packages.json

- Update app baselines package version. New value: 23.5.16502.25695

[24.0] Update app baselines package version. New value: 23.5.16502.25695

---

build/Packages.json

- Update app baselines package version. New value: 24.0.16410.25686

[24.1] Update app baselines package version. New value: 24.0.16410.25686

---

build/Packages.json

- Update app baselines package version. New value: 24.1.18927.25706

[24.2] Update app baselines package version. New value: 24.1.18927.25706

---

build/Packages.json

- Update app baselines package version. New value: 24.2.20227.25710

[24.3] Update app baselines package version. New value: 24.2.20227.25710

---

build/Packages.json

- Update app baselines package version. New value: 25.0.23364.25714

[25.x] Update app baselines package version. New value: 25.0.23364.25714

---

build/Packages.json

- Update app baselines package version. New value: 25.1.25729.0
- Update translation package version. New value: 26.0.20241017.3

[main] Update app baselines package version. New value: 25.1.25729.0 (+ 1 more update(s))

---

build/Packages.json

- Update app baselines package version. New value: 24.3.21374.25708

[24.4] Update app baselines package version. New value: 24.3.21374.25708

---

build/Packages.json

- Update app baselines package version. New value: 24.4.22295.25705

[24.5] Update app baselines package version. New value: 24.4.22295.25705

---

src/System Application/App/AppSource Gallery/src/AppSourceProductManager.Codeunit.al

Fixes [AB#551407](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/551407)

Add missing init for the GetProductDetails method.

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.25774.0

[main] Update BCArtifact version. New value: 26.0.25774.0

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.25821.0

[main] Update BCArtifact version. New value: 26.0.25821.0

---

src/Tools/AI Test Toolkit/src/TestSuite/AITTestSuite.Page.al
src/Tools/AI Test Toolkit/src/TestSuite/AITTestSuite.Table.al

Only show dialog asking to update lines when:
- Input dataset is changed
- Test lines exist
Fixes [AB#555181](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/555181)

[AI Test Tool] Only show dialog when test lines exist

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.25853.0

[main] Update BCArtifact version. New value: 26.0.25853.0

---

src/System Application/App/Azure Key Vault/app.json
src/System Application/App/Azure Key Vault/src/AzureKeyVaultImpl.Codeunit.al
src/System Application/Test/Azure Key Vault/src/AzureKeyVaultTest.Codeunit.al
src/System Application/Test/Satisfaction Survey/src/SatisfactionSurveyTests.Codeunit.al

Fixes #
[AB#544481](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/544481)

Get rid of allowedsecretslist from app KV

---

build/Packages.json

- Update app baselines package version. New value: 23.5.16502.26011

[24.0] Update app baselines package version. New value: 23.5.16502.26011

---

build/Packages.json

- Update app baselines package version. New value: 24.5.23489.26005

[25.0] Update app baselines package version. New value: 24.5.23489.26005

---

build/Packages.json

- Update app baselines package version. New value: 25.2.26015.0
- Update translation package version. New value: 26.0.20241024.4

[main] Update app baselines package version. New value: 25.2.26015.0 (+ 1 more update(s))

---

build/Packages.json

- Update app baselines package version. New value: 24.2.20227.26013

[24.3] Update app baselines package version. New value: 24.2.20227.26013

---

build/Packages.json

- Update app baselines package version. New value: 24.4.22295.26006

[24.5] Update app baselines package version. New value: 24.4.22295.26006

---

build/Packages.json

- Update translation package version. New value: 24.7.20241024.8

[24.x] Update app translations package version. New value: 24.7.20241024.8

---

build/Packages.json

- Update app baselines package version. New value: 24.1.18927.26012

[24.2] Update app baselines package version. New value: 24.1.18927.26012

---

build/Packages.json

- Update app baselines package version. New value: 24.3.21374.26004

[24.4] Update app baselines package version. New value: 24.3.21374.26004

---

build/Packages.json

- Update app baselines package version. New value: 25.1.25885.0
- Update translation package version. New value: 25.1.20241024.3

[25.x] Update app baselines package version. New value: 25.1.25885.0 (+ 1 more update(s))

---

build/Packages.json

- Update app baselines package version. New value: 25.0.23364.26007
- Update translation package version. New value: 25.1.20241024.3

[25.1] Update app baselines package version. New value: 25.0.23364.26007 (+ 1 more update(s))

---

build/Packages.json

- Update app baselines package version. New value: 24.0.16410.26010

[24.1] Update app baselines package version. New value: 24.0.16410.26010

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.25899.0

[main] Update BCArtifact version. New value: 26.0.25899.0

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: bcinsider/Sandbox/25.2/base/latest

[25.x] Update BCArtifact version. New value: bcinsider/Sandbox/25.2/base/latest

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.26081.0

[main] Update BCArtifact version. New value: 26.0.26081.0

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.26183.0

[main] Update BCArtifact version. New value: 26.0.26183.0

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: bcinsider/Sandbox/24.8/base/latest

[24.x] Update BCArtifact version. New value: bcinsider/Sandbox/24.8/base/latest

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: bcartifacts/Sandbox/25.1/base/latest

[25.1] Update BCArtifact version. New value: bcartifacts/Sandbox/25.1/base/latest

---

src/Tools/AI Test Toolkit/README.md

Add README.
Fixes [AB#556533](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/556533)

[AI Test Tool] Add README

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.26361.0

[main] Update BCArtifact version. New value: 26.0.26361.0

---

build/Packages.json

- Update app baselines package version. New value: 23.5.16502.26318

[24.0] Update app baselines package version. New value: 23.5.16502.26318

---

build/Packages.json

- Update app baselines package version. New value: 24.5.23489.26336

[25.0] Update app baselines package version. New value: 24.5.23489.26336

---

build/Packages.json

- Update app baselines package version. New value: 24.0.16410.26322

[24.1] Update app baselines package version. New value: 24.0.16410.26322

---

build/Packages.json

- Update app baselines package version. New value: 25.0.23364.26337

[25.1] Update app baselines package version. New value: 25.0.23364.26337

---

build/Packages.json

- Update app baselines package version. New value: 24.4.22295.26321

[24.5] Update app baselines package version. New value: 24.4.22295.26321

---

build/Packages.json

- Update app baselines package version. New value: 24.5.23489.26370

[24.x] Update app baselines package version. New value: 24.5.23489.26370

---

build/Packages.json

- Update app baselines package version. New value: 24.2.20227.26314

[24.3] Update app baselines package version. New value: 24.2.20227.26314

---

build/Packages.json

- Update app baselines package version. New value: 24.1.18927.26317

[24.2] Update app baselines package version. New value: 24.1.18927.26317

---

build/Packages.json

- Update app baselines package version. New value: 24.3.21374.26316

[24.4] Update app baselines package version. New value: 24.3.21374.26316

---

build/Packages.json

- Update app baselines package version. New value: 25.2.26357.0
- Update translation package version. New value: 26.0.20241104.4

[main] Update app baselines package version. New value: 25.2.26357.0 (+ 1 more update(s))

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.26448.0

[main] Update BCArtifact version. New value: 26.0.26448.0

---

src/System Application/App/Email/src/EmailInstaller.Codeunit.al

This pull request backports #2324 to releases/25.1
Fixes [AB#557159](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/557159)

[releases/25.1] [Email/RetPol] Harden retention policy for Email Inbox setup.

---

src/System Application/App/Email/src/EmailInstaller.Codeunit.al

This pull request backports #2324 to releases/25.0
Fixes [AB#557158](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/557158)

[releases/25.0] [Email/RetPol] Harden retention policy for Email Inbox setup.

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.26581.0

[main] Update BCArtifact version. New value: 26.0.26581.0

---

build/Packages.json

- Update app baselines package version. New value: 24.5.23489.26544

[25.0] Update app baselines package version. New value: 24.5.23489.26544

---

build/Packages.json

- Update app baselines package version. New value: 23.5.16502.26542

[24.0] Update app baselines package version. New value: 23.5.16502.26542

---

build/Packages.json

- Update app baselines package version. New value: 24.0.16410.26547

[24.1] Update app baselines package version. New value: 24.0.16410.26547

---

build/Packages.json

- Update app baselines package version. New value: 24.1.18927.26545

[24.2] Update app baselines package version. New value: 24.1.18927.26545

---

build/Packages.json

- Update app baselines package version. New value: 24.2.20227.26543

[24.3] Update app baselines package version. New value: 24.2.20227.26543

---

build/Packages.json

- Update app baselines package version. New value: 24.4.22295.26465

[24.5] Update app baselines package version. New value: 24.4.22295.26465

---

build/Packages.json

- Update app baselines package version. New value: 25.0.23364.26558

[25.1] Update app baselines package version. New value: 25.0.23364.26558

---

build/Packages.json

- Update app baselines package version. New value: 24.3.21374.26548

[24.4] Update app baselines package version. New value: 24.3.21374.26548

---

build/Packages.json

- Update app baselines package version. New value: 24.5.23489.26635

[24.x] Update app baselines package version. New value: 24.5.23489.26635

---

build/Packages.json

- Update app baselines package version. New value: 25.2.26565.0
- Update translation package version. New value: 26.0.20241111.6

[main] Update app baselines package version. New value: 25.2.26565.0 (+ 1 more update(s))

---

build/Packages.json

- Update translation package version. New value: 25.2.20241111.2

[25.x] Update translation package version. New value: 25.2.20241111.2

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.26661.0

[main] Update BCArtifact version. New value: 26.0.26661.0

---

src/System Application/App/VS Code Integration/src/VsCodeIntegrationImpl.Codeunit.al

Find() wouldn't iterate through the rows, FindSet does.
Fixes [AB#548696](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/548696)

[Open in VS Code] Fix dependencies not found

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.26706.0

[main] Update BCArtifact version. New value: 26.0.26706.0

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.26919.0

[main] Update BCArtifact version. New value: 26.0.26919.0

---

build/Packages.json

- Update app baselines package version. New value: 24.5.23489.26915

[25.0] Update app baselines package version. New value: 24.5.23489.26915

---

build/Packages.json

- Update app baselines package version. New value: 23.5.16502.26904

[24.0] Update app baselines package version. New value: 23.5.16502.26904

---

build/Packages.json

- Update app baselines package version. New value: 24.1.18927.26899

[24.2] Update app baselines package version. New value: 24.1.18927.26899

---

build/Packages.json

- Update app baselines package version. New value: 24.0.16410.26903

[24.1] Update app baselines package version. New value: 24.0.16410.26903

---

build/Packages.json

- Update app baselines package version. New value: 24.2.20227.26898

[24.3] Update app baselines package version. New value: 24.2.20227.26898

---

build/Packages.json

- Update app baselines package version. New value: 25.0.23364.26909

[25.1] Update app baselines package version. New value: 25.0.23364.26909

---

build/Packages.json

- Update app baselines package version. New value: 24.4.22295.26900

[24.5] Update app baselines package version. New value: 24.4.22295.26900

---

build/Packages.json

- Update app baselines package version. New value: 24.3.21374.26901

[24.4] Update app baselines package version. New value: 24.3.21374.26901

---

build/Packages.json

- Update translation package version. New value: 25.2.20241115.1

[25.x] Update translation package version. New value: 25.2.20241115.1

---

build/Packages.json

- Update app baselines package version. New value: 24.7.26253.0
- Update translation package version. New value: 24.8.20241115.2

[24.x] Update app baselines package version. New value: 24.7.26253.0 (+ 1 more update(s))

---

build/Packages.json

- Update app baselines package version. New value: 25.2.26921.0
- Update translation package version. New value: 26.0.20241118.4

[main] Update app baselines package version. New value: 25.2.26921.0 (+ 1 more update(s))

---

src/System Application/App/Edit in Excel/src/EditinExcelImpl.Codeunit.al

Change the text of the invalid filter error
Fixes [AB#548153](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/548153/)

Change the text of the invalid filter error

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.26951.0

[main] Update BCArtifact version. New value: 26.0.26951.0

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.27067.0

[main] Update BCArtifact version. New value: 26.0.27067.0

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.27113.0

[main] Update BCArtifact version. New value: 26.0.27113.0

---

build/Packages.json

- Update app baselines package version. New value: 24.5.23489.27157

[25.0] Update app baselines package version. New value: 24.5.23489.27157

---

build/Packages.json

- Update app baselines package version. New value: 24.0.16410.27158

[24.1] Update app baselines package version. New value: 24.0.16410.27158

---

build/Packages.json

- Update app baselines package version. New value: 24.5.23489.27157

[24.x] Update app baselines package version. New value: 24.5.23489.27157

---

.github/ISSUE_TEMPLATE/bcidea.yaml
.github/ISSUE_TEMPLATE/bug_report.yaml
.github/ISSUE_TEMPLATE/contribution_bug.yaml

Uptake issue types
Fixes [AB#555781](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/555781)

Uptake issue types

---

src/Business Foundation/App/NoSeries/src/Setup/NoSeriesSetupImpl.Codeunit.al
src/Business Foundation/App/NoSeries/src/Single/NoSeries.Codeunit.al
src/Business Foundation/App/NoSeries/src/Single/NoSeriesImpl.Codeunit.al

Backport of #2361
Fixes [AB#558934](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/558934)

Bug 558934: [25.x][BCApps #2361]No. Series: Ability to extend filters on finding No. Series Lines when getting new numbers

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.27339.0

[main] Update BCArtifact version. New value: 26.0.27339.0

---

src/Tools/AI Test Toolkit/src/AITCommandLineCard.Page.al
src/Tools/AI Test Toolkit/src/API/AITLogEntryAPI.Page.al
src/Tools/AI Test Toolkit/src/API/AITTestMethodLinesAPI.Page.al
src/Tools/AI Test Toolkit/src/Logs/AITLogEntry.Table.al

1. Make the command line card page accessible from tell me
1. Show the test method lines on the page for the selected suite
1. Support basic filtering using test method line no. for running the next test.
1. Expose the suite and test method line description in the AI Log Entry API
1. Create a new API to access the test method lines
Screenshot:
Fixes [AB#558560](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/558560)

AI Test Toolkit: Improve command line tool

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.27451.0

[main] Update BCArtifact version. New value: 26.0.27451.0

---

build/Packages.json

- Update app baselines package version. New value: 24.5.23489.27482

[25.0] Update app baselines package version. New value: 24.5.23489.27482

---

build/Packages.json

- Update app baselines package version. New value: 25.2.27518.0
- Update translation package version. New value: 26.0.20241202.6

[main] Update app baselines package version. New value: 25.2.27518.0 (+ 1 more update(s))

---

build/Packages.json

- Update translation package version. New value: 25.2.20241128.3

[25.x] Update translation package version. New value: 25.2.20241128.3

---

build/Packages.json

- Update app baselines package version. New value: 25.0.23364.27490

[25.1] Update app baselines package version. New value: 25.0.23364.27490

---

build/Packages.json

- Update app baselines package version. New value: 24.1.18927.27481

[24.2] Update app baselines package version. New value: 24.1.18927.27481

---

build/Packages.json

- Update app baselines package version. New value: 24.4.22295.27487

[24.5] Update app baselines package version. New value: 24.4.22295.27487

---

build/Packages.json

- Update app baselines package version. New value: 24.0.16410.27488

[24.1] Update app baselines package version. New value: 24.0.16410.27488

---

build/Packages.json

- Update app baselines package version. New value: 24.2.20227.27484

[24.3] Update app baselines package version. New value: 24.2.20227.27484

---

build/Packages.json

- Update app baselines package version. New value: 24.5.23489.27522
- Update translation package version. New value: 24.8.20241127.3

[24.x] Update app baselines package version. New value: 24.5.23489.27522 (+ 1 more update(s))

---

.github/AL-Go-Settings.json
src/System Application/App/DotNet Aliases/src/dotnet.al
src/System Application/App/Email/src/Account/EmailAccountImpl.Codeunit.al
src/System Application/App/Email/src/Account/EmailAccounts.Page.al
src/System Application/App/Email/src/Connector/DefaultEmailConnectorv2.Codeunit.al
src/System Application/App/Email/src/Connector/EmailConnector.Enum.al
src/System Application/App/Email/src/Connector/EmailConnectorv3.Interface.al
src/System Application/App/Email/src/Email/Email.Codeunit.al
src/System Application/App/Email/src/Email/EmailImpl.Codeunit.al
src/System Application/App/Email/src/Email/Inbox/EmailInbox.Table.al
src/System Application/App/Email/src/Email/Inbox/EmailRetrievalFilters.Table.al
src/System Application/App/Email/src/Email/SendEmail.Codeunit.al
src/System Application/App/Email/src/Message/EmailMessage.Codeunit.al
src/System Application/App/Email/src/Message/EmailMessageImpl.Codeunit.al
src/System Application/Test Library/Email/app.json
src/System Application/Test Library/Email/src/TestEmailConnector.EnumExt.al
src/System Application/Test Library/Email/src/TestEmailConnectorv3.Codeunit.al
src/System Application/Test/Email/src/EmailTest.Codeunit.al

This pull request backports #2415 to releases/25.x
Fixes [AB#550315](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/550315)

[releases/25.x] [Email] Add email retrieval filters

---

src/System Application/App/AI/src/Copilot/CopilotAICapabilities.Page.al
src/System Application/App/AI/src/Copilot/CopilotCapabilitiesGA.Page.al

Fixes [AB#545996](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/545996/)

[main] Copilot FWS: address customer feedback/FUD with Copilot & AI Capabilities page

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.27531.0

[main] Update BCArtifact version. New value: 26.0.27531.0

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/25.1] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  bbc88d84c6c206b79a63ce535897e97c394d7059

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.5] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  bbc88d84c6c206b79a63ce535897e97c394d7059

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.4] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  bbc88d84c6c206b79a63ce535897e97c394d7059

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.3] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  bbc88d84c6c206b79a63ce535897e97c394d7059

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/25.x] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  bbc88d84c6c206b79a63ce535897e97c394d7059

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.x] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  bbc88d84c6c206b79a63ce535897e97c394d7059

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[main] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  bbc88d84c6c206b79a63ce535897e97c394d7059

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.2] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  bbc88d84c6c206b79a63ce535897e97c394d7059

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.1] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  bbc88d84c6c206b79a63ce535897e97c394d7059

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.0] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  bbc88d84c6c206b79a63ce535897e97c394d7059

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.27646.0

[main] Update BCArtifact version. New value: 26.0.27646.0

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.27706.0

[main] Update BCArtifact version. New value: 26.0.27706.0

---

src/System Application/App/Email/src/EmailInstaller.Codeunit.al

This pull request backports #2475 to releases/25.x
Fixes [AB#560014](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/560014)

[releases/25.x] Remove emailinbox retention policy, just keep allowed tables

---

src/System Application/App/Email/src/EmailInstaller.Codeunit.al

This pull request backports #2475 to releases/25.2
Fixes [AB#560013](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/560013)

[releases/25.2] Remove emailinbox retention policy, just keep allowed tables

---

src/System Application/App/Email/src/EmailInstaller.Codeunit.al

This pull request backports #2475 to releases/25.1
Fixes [AB#560012](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/560012)

[releases/25.1] Remove emailinbox retention policy, just keep allowed tables

---

src/System Application/App/Email/src/EmailInstaller.Codeunit.al

This pull request backports #2475 to releases/25.0
Fixes [AB#560011](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/560011)

[releases/25.0] Remove emailinbox retention policy, just keep allowed tables

---

build/Packages.json

- Update app baselines package version. New value: 23.5.16502.27802

[24.0] Update app baselines package version. New value: 23.5.16502.27802

---

build/Packages.json

- Update app baselines package version. New value: 24.5.23489.27799

[25.0] Update app baselines package version. New value: 24.5.23489.27799

---

build/Packages.json

- Update app baselines package version. New value: 24.2.20227.27791

[24.3] Update app baselines package version. New value: 24.2.20227.27791

---

build/Packages.json

- Update app baselines package version. New value: 24.3.21374.27773

[24.4] Update app baselines package version. New value: 24.3.21374.27773

---

build/Packages.json

- Update translation package version. New value: 25.2.20241206.5

[25.2] Update translation package version. New value: 25.2.20241206.5

---

build/Packages.json

- Update app baselines package version. New value: 24.5.23489.27799
- Update translation package version. New value: 24.8.20241205.3

[24.x] Update app baselines package version. New value: 24.5.23489.27799 (+ 1 more update(s))

---

build/Packages.json

- Update app baselines package version. New value: 24.0.16410.27776

[24.1] Update app baselines package version. New value: 24.0.16410.27776

---

build/Packages.json

- Update app baselines package version. New value: 25.2.27707.0
- Update translation package version. New value: 25.2.20241206.5

[25.x] Update app baselines package version. New value: 25.2.27707.0 (+ 1 more update(s))

---

build/Packages.json

- Update app baselines package version. New value: 25.0.23364.27822

[25.1] Update app baselines package version. New value: 25.0.23364.27822

---

build/Packages.json

- Update app baselines package version. New value: 24.4.22295.27800

[24.5] Update app baselines package version. New value: 24.4.22295.27800

---

build/Packages.json

- Update app baselines package version. New value: 24.1.18927.27794

[24.2] Update app baselines package version. New value: 24.1.18927.27794

---

build/Packages.json

- Update app baselines package version. New value: 25.2.27707.0
- Update translation package version. New value: 26.0.20241206.6

[main] Update app baselines package version. New value: 25.2.27707.0 (+ 1 more update(s))

---

src/Business Foundation/App/NoSeries/src/Legacy/NoSeriesObsolete.TableExt.al
src/Business Foundation/App/NoSeries/src/Setup/NoSeries.Page.al
src/Business Foundation/App/NoSeries/src/Setup/NoSeriesSetup.Codeunit.al
src/Business Foundation/App/NoSeries/src/Setup/NoSeriesSetupImpl.Codeunit.al
src/Business Foundation/App/NoSeries/src/Single/NoSeries.Codeunit.al

Adds Drilldown to facade
Fixes [AB#559484](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/559484)

add Drilldown to facade

---

src/Business Foundation/App/NoSeries/src/Legacy/NoSeriesObsolete.TableExt.al
src/Business Foundation/App/NoSeries/src/Setup/NoSeries.Page.al
src/Business Foundation/App/NoSeries/src/Setup/NoSeriesSetupImpl.Codeunit.al
src/Business Foundation/App/NoSeries/src/Single/NoSeries.Codeunit.al

This pull request backports #2442 to releases/25.x
Fixes [AB#560151](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/560151)

[releases/25.x] add Drilldown to facade

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.27885.0

[main] Update BCArtifact version. New value: 26.0.27885.0

---

.github/AL-Go-Settings.json
.github/dependabot.yml

Add Commit Options to pull requests created by AL-Go.

Add Commit Options to AL-Go created pull requests

---

build/Packages.json

Update baseline to 25.1.25873.27898
[AB#560352](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/560352)

[25.2] Update baseline to 25.1.25873.27898

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.27941.0

[main] Update BCArtifact version. New value: 26.0.27941.0

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: bcinsider/Sandbox/25.3/base/latest

[25.x] Update BCArtifact version. New value: bcinsider/Sandbox/25.3/base/latest

---

build/Packages.json

- Update app baselines package version. New value: 24.2.20227.27979

[24.3] Update app baselines package version. New value: 24.2.20227.27979

---

build/Packages.json

- Update app baselines package version. New value: 24.4.22295.27981

[24.5] Update app baselines package version. New value: 24.4.22295.27981

---

build/Packages.json

- Update app baselines package version. New value: 24.3.21374.27964

[24.4] Update app baselines package version. New value: 24.3.21374.27964

---

build/Packages.json

- Update app baselines package version. New value: 25.2.27733.27975

[25.x] Update app baselines package version. New value: 25.2.27733.27975

---

build/Packages.json

- Update app baselines package version. New value: 25.0.23364.27966

[25.1] Update app baselines package version. New value: 25.0.23364.27966

---

build/Packages.json

- Update app baselines package version. New value: 25.3.27986.0

[main] Update app baselines package version. New value: 25.3.27986.0

---

build/Packages.json

- Update app baselines package version. New value: 24.0.16410.27978

[24.1] Update app baselines package version. New value: 24.0.16410.27978

---

build/Packages.json

- Update app baselines package version. New value: 24.5.23489.27972

[24.x] Update app baselines package version. New value: 24.5.23489.27972

---

build/Packages.json

- Update app baselines package version. New value: 25.1.25873.27974

[25.2] Update app baselines package version. New value: 25.1.25873.27974

---

build/Packages.json

- Update app baselines package version. New value: 24.5.23489.27972

[25.0] Update app baselines package version. New value: 24.5.23489.27972

---

build/Packages.json

- Update app baselines package version. New value: 23.5.16502.27931

[24.0] Update app baselines package version. New value: 23.5.16502.27931

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.28000.0

[main] Update BCArtifact version. New value: 26.0.28000.0

---

build/Packages.json
src/System Application/App/Agent/TaskPane/AgentTaskDetails.Page.al
src/System Application/App/Agent/TaskPane/AgentTaskTimeline.Page.al
src/System Application/App/Agent/TaskPane/AgentTasks.Page.al

Rename agent task objects
Fixes [AB#536497](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/536497)

[25.x] Renaming agent objects

---

src/Business Foundation/App/NoSeries/src/Setup/NoSeriesSetupImpl.Codeunit.al

Fixes an issue when comparing a blank no. series code to a filter for blank
Fixes [AB#560685](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/560685)

Fixes an issue when comparing a blank no. series code to a filter for blank

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: bcartifacts/Sandbox/25.2/base/latest

[25.2] Update BCArtifact version. New value: bcartifacts/Sandbox/25.2/base/latest

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.28053.0

[main] Update BCArtifact version. New value: 26.0.28053.0

---

src/System Application/App/Email/src/Email/Inbox/EmailRetrievalFilters.Table.al

This pull request backports #2547 to releases/25.x
Fixes [AB#560755](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/560755)

[releases/25.x] [Email] Add Last Message Only into the email filters table

---

build/Packages.json
src/System Application/App/Agent/TaskPane/AgentTaskDetails.Page.al
src/System Application/App/Agent/TaskPane/AgentTaskTimeline.Page.al
src/System Application/App/Agent/TaskPane/AgentTasks.Page.al

Agent Task Rename  - Uptake new baseline
Fixes [AB#536497](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/536497)

Agent Task Rename - Uptake new baseline

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.28108.0

[main] Update BCArtifact version. New value: 26.0.28108.0

---

build/Packages.json

- Update app baselines package version. New value: 23.5.16502.28063

[24.0] Update app baselines package version. New value: 23.5.16502.28063

---

build/Packages.json

- Update app baselines package version. New value: 24.5.23489.28101

[25.0] Update app baselines package version. New value: 24.5.23489.28101

---

build/Packages.json

- Update app baselines package version. New value: 24.3.21374.28100

[24.4] Update app baselines package version. New value: 24.3.21374.28100

---

build/Packages.json

- Update app baselines package version. New value: 24.5.23489.28101

[24.x] Update app baselines package version. New value: 24.5.23489.28101

---

build/Packages.json

- Update app baselines package version. New value: 24.0.16410.28095

[24.1] Update app baselines package version. New value: 24.0.16410.28095

---

build/Packages.json

- Update app baselines package version. New value: 25.0.23364.28103

[25.1] Update app baselines package version. New value: 25.0.23364.28103

---

build/Packages.json

- Update app baselines package version. New value: 24.1.18927.28104

[24.2] Update app baselines package version. New value: 24.1.18927.28104

---

build/Packages.json

- Update app baselines package version. New value: 24.4.22295.28065

[24.5] Update app baselines package version. New value: 24.4.22295.28065

---

build/Packages.json

- Update app baselines package version. New value: 25.2.27733.28023
- Update translation package version. New value: 25.3.20241213.1

[25.x] Update app baselines package version. New value: 25.2.27733.28023 (+ 1 more update(s))

---

build/Packages.json

- Update app baselines package version. New value: 25.1.25873.28105

[25.2] Update app baselines package version. New value: 25.1.25873.28105

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.28149.0

[main] Update BCArtifact version. New value: 26.0.28149.0

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.1] Update AL-Go System Files

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.2] Update AL-Go System Files

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.4] Update AL-Go System Files

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.5] Update AL-Go System Files

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.x] Update AL-Go System Files

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/25.2] Update AL-Go System Files

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/25.1] Update AL-Go System Files

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/25.0] Update AL-Go System Files

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/25.x] Update AL-Go System Files

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[main] Update AL-Go System Files

---

src/Business Foundation/App/NoSeries/src/Setup/NoSeriesSetupImpl.Codeunit.al

This pull request backports #2577 to releases/25.x
Fixes [AB#560987](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/560987)

[releases/25.2] No. Series page closes when Code has special chars

---

src/Business Foundation/App/NoSeries/src/Setup/NoSeriesSetupImpl.Codeunit.al

No. Series page closes unexpectedly when the No. Series Code contains special chars like &
Fixes [AB#560982](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/560982)

No. Series page closes when Code has special chars

---

src/Business Foundation/App/NoSeries/src/Setup/NoSeriesSetupImpl.Codeunit.al

This pull request backports #2577 to releases/25.x
Fixes [AB#560988](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/560988)

[releases/25.x] No. Series page closes when Code has special chars

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.28220.0

[main] Update BCArtifact version. New value: 26.0.28220.0

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.28261.0

[main] Update BCArtifact version. New value: 26.0.28261.0

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.28288.0

[main] Update BCArtifact version. New value: 26.0.28288.0

---

build/Packages.json

- Update app baselines package version. New value: 25.2.27733.28334
- Update translation package version. New value: 25.3.20241219.8

[25.x] Update app baselines package version. New value: 25.2.27733.28334 (+ 1 more update(s))

---

build/Packages.json

- Update app baselines package version. New value: 24.5.23489.28326

[24.x] Update app baselines package version. New value: 24.5.23489.28326

---

build/Packages.json

- Update app baselines package version. New value: 25.3.28327.0
- Update translation package version. New value: 26.0.20241223.4

[main] Update app baselines package version. New value: 25.3.28327.0 (+ 1 more update(s))

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.28335.0

[main] Update BCArtifact version. New value: 26.0.28335.0

---

build/Packages.json

- Update app baselines package version. New value: 23.5.16502.28302

[24.0] Update app baselines package version. New value: 23.5.16502.28302

---

build/Packages.json

- Update app baselines package version. New value: 24.5.23489.28326

[25.0] Update app baselines package version. New value: 24.5.23489.28326

---

build/Packages.json

- Update app baselines package version. New value: 24.1.18927.28330

[24.2] Update app baselines package version. New value: 24.1.18927.28330

---

build/Packages.json

- Update app baselines package version. New value: 24.0.16410.28332

[24.1] Update app baselines package version. New value: 24.0.16410.28332

---

build/Packages.json

- Update app baselines package version. New value: 24.2.20227.28331

[24.3] Update app baselines package version. New value: 24.2.20227.28331

---

build/Packages.json

- Update app baselines package version. New value: 24.4.22295.28328

[24.5] Update app baselines package version. New value: 24.4.22295.28328

---

build/Packages.json

- Update app baselines package version. New value: 24.3.21374.28329

[24.4] Update app baselines package version. New value: 24.3.21374.28329

---

build/Packages.json

- Update app baselines package version. New value: 25.1.25873.28333

[25.2] Update app baselines package version. New value: 25.1.25873.28333

---

build/Packages.json

- Update app baselines package version. New value: 25.0.23364.28296

[25.1] Update app baselines package version. New value: 25.0.23364.28296

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.28370.0

[main] Update BCArtifact version. New value: 26.0.28370.0

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: bcinsider/Sandbox/24.9/base/latest

[24.x] Update BCArtifact version. New value: bcinsider/Sandbox/24.9/base/latest

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.28403.0

[main] Update BCArtifact version. New value: 26.0.28403.0

---

build/Packages.json

- Update app baselines package version. New value: 24.5.23489.28383

[24.x] Update app baselines package version. New value: 24.5.23489.28383

---

build/Packages.json

- Update app baselines package version. New value: 25.3.28408.0

[main] Update app baselines package version. New value: 25.3.28408.0

---

build/Packages.json

- Update app baselines package version. New value: 25.2.27733.28402

[25.x] Update app baselines package version. New value: 25.2.27733.28402

---

build/Packages.json

- Update app baselines package version. New value: 24.5.23489.28383

[25.0] Update app baselines package version. New value: 24.5.23489.28383

---

build/Packages.json

- Update app baselines package version. New value: 23.5.16502.28390

[24.0] Update app baselines package version. New value: 23.5.16502.28390

---

build/Packages.json

- Update app baselines package version. New value: 25.1.25873.28400

[25.2] Update app baselines package version. New value: 25.1.25873.28400

---

build/Packages.json

- Update app baselines package version. New value: 24.0.16410.28380

[24.1] Update app baselines package version. New value: 24.0.16410.28380
