build/Packages.json

- Update app baselines package version. New value: 25.0.23364.28387

[25.1] Update app baselines package version. New value: 25.0.23364.28387

---

build/Packages.json

- Update app baselines package version. New value: 24.3.21374.28361

[24.4] Update app baselines package version. New value: 24.3.21374.28361

---

build/Packages.json

- Update app baselines package version. New value: 24.1.18927.28381

[24.2] Update app baselines package version. New value: 24.1.18927.28381

---

build/Packages.json

- Update app baselines package version. New value: 24.4.22295.28385

[24.5] Update app baselines package version. New value: 24.4.22295.28385

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.28429.0

[main] Update BCArtifact version. New value: 26.0.28429.0

---

.github/AL-Go-Settings.json
.github/workflows/MSDO.yml

- Update BCArtifact version. New value: 26.0.28458.0

[main] Update BCArtifact version. New value: 26.0.28458.0

---

.github/workflows/MSDO.yml

[AB#561623](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/561623)

[25.x] Run MSDO on windows-latest

---

.github/workflows/MSDO.yml

This pull request backports #2636 to releases/25.1

[releases/25.1] Run MSDO on windows-latest

---

.github/workflows/MSDO.yml

This pull request backports #2636 to releases/25.0

[releases/25.0] Run MSDO on windows-latest

---

.github/workflows/MSDO.yml

This pull request backports #2636 to releases/24.x

[releases/24.x] Run MSDO on windows-latest

---

.github/workflows/MSDO.yml

This pull request backports #2636 to releases/24.5

[releases/24.5] Run MSDO on windows-latest

---

.github/workflows/MSDO.yml

This pull request backports #2636 to releases/24.4

[releases/24.4] Run MSDO on windows-latest

---

.github/workflows/MSDO.yml

This pull request backports #2636 to releases/24.3

[releases/24.3] Run MSDO on windows-latest

---

.github/workflows/MSDO.yml

This pull request backports #2636 to releases/24.2

[releases/24.2] Run MSDO on windows-latest

---

.github/workflows/MSDO.yml

This pull request backports #2636 to releases/24.1

[releases/24.1] Run MSDO on windows-latest

---

.github/workflows/MSDO.yml

This pull request backports #2636 to releases/24.0

[releases/24.0] Run MSDO on windows-latest

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.28476.0

[main] Update BCArtifact version. New value: 26.0.28476.0

---

build/Packages.json

- Update app baselines package version. New value: 24.5.23489.28471

[25.0] Update app baselines package version. New value: 24.5.23489.28471

---

build/Packages.json

- Update app baselines package version. New value: 24.4.22295.28433

[24.5] Update app baselines package version. New value: 24.4.22295.28433

---

build/Packages.json

- Update app baselines package version. New value: 24.1.18927.28488

[24.2] Update app baselines package version. New value: 24.1.18927.28488

---

build/Packages.json

- Update app baselines package version. New value: 24.2.20227.28491

[24.3] Update app baselines package version. New value: 24.2.20227.28491

---

build/Packages.json

- Update app baselines package version. New value: 24.3.21374.28486

[24.4] Update app baselines package version. New value: 24.3.21374.28486

---

build/Packages.json

- Update app baselines package version. New value: 25.0.23364.28527

[25.1] Update app baselines package version. New value: 25.0.23364.28527

---

build/Packages.json

- Update app baselines package version. New value: 25.1.25873.28528

[25.2] Update app baselines package version. New value: 25.1.25873.28528

---

build/Packages.json

- Update app baselines package version. New value: 25.3.28522.0
- Update translation package version. New value: 26.0.20250106.3

[main] Update app baselines package version. New value: 25.3.28522.0 (+ 1 more update(s))

---

build/Packages.json

- Update app baselines package version. New value: 25.2.27733.28472
- Update translation package version. New value: 25.3.20250102.5

[25.x] Update app baselines package version. New value: 25.2.27733.28472 (+ 1 more update(s))

---

src/System Application/App/Performance Profiler/src/PerformanceProfileList.Page.al

-->
The platform now supports tracking the amount of http calls in a profile and also their duration, thus we enable them on the UI.
Fixes [AB#501774](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/501774)

Scheduled Profiler - Add http call data

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.28602.0

[main] Update BCArtifact version. New value: 26.0.28602.0

---

src/System Application/App/Email/src/Message/EmailMessageImpl.Codeunit.al

Added indirect modify permission for the codeunit 8905 "Email Message Impl." on the table "Email Message Attachment".
Fixes #2581
Fixes [AB#561782](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/561782)

Added indirect modify permission in "Email Message Impl."

---

src/System Application/App/System Permissions/permissions/CopilotEssentials.PermissionSet.al
src/System Application/App/System Permissions/permissions/CopilotSummary.PermissionSet.al

Adding Copilot summary Permission set
Fixes [AB#561802](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/561802/)

Adding permission set

---

src/System Application/Test/DisabledTests/RestClientTests.DisabledTest.json

Test keeps failing with Error: Function TestGetAsJson The request to "https://httpbin.org/get" failed with status code 502 Bad Gateway.
Fixes [AB#561955](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/561955)

Disable failing test TestGetAsJson

---

src/System Application/App/Auto Format/src/AutoFormat.Enum.al

This pull request includes changes to the `AutoFormat.Enum.al` file to enhance the readability and clarity of the enumeration values by adding captions.
Enhancements to enumeration values:
* [`src/System Application/App/Auto Format/src/AutoFormat.Enum.al`](diffhunk://#diff-53264393ea702e553861d2b6be3e5ae18d3f20c3c330953fc60c69ae059004f2L18-R29): Added captions 'Default Format' and 'Custom Format Expression' to the `DefaultFormat` and `CustomFormatExpr` enumeration values, respectively.
Fixes #2635 
Fixes [AB#561844](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/561844)

#2635 - Add caption to enum 59

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.28669.0

[main] Update BCArtifact version. New value: 26.0.28669.0

---

.github/AL-Go-Settings.json

This pull request backports #2498 to releases/24.1

[releases/24.1] Add Commit Options to AL-Go created pull requests

---

.github/AL-Go-Settings.json

This pull request backports #2498 to releases/24.2

[releases/24.2] Add Commit Options to AL-Go created pull requests

---

.github/AL-Go-Settings.json

This pull request backports #2498 to releases/24.3

[releases/24.3] Add Commit Options to AL-Go created pull requests

---

.github/AL-Go-Settings.json

This pull request backports #2498 to releases/24.4

[releases/24.4] Add Commit Options to AL-Go created pull requests

---

.github/AL-Go-Settings.json

This pull request backports #2498 to releases/24.0

[releases/24.0] Add Commit Options to AL-Go created pull requests

---

.github/AL-Go-Settings.json

This pull request backports #2498 to releases/24.x

[releases/24.x] Add Commit Options to AL-Go created pull requests

---

.github/workflows/VerifyAppChanges.yaml

[AB#561696](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/561696)

Add top-level permissions VerifyAppChanges.yaml

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.28721.0

[main] Update BCArtifact version. New value: 26.0.28721.0

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: bcinsider/Sandbox/25.4/base/latest

[25.x] Update BCArtifact version. New value: bcinsider/Sandbox/25.4/base/latest

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.28826.0

[main] Update BCArtifact version. New value: 26.0.28826.0

---

build/Packages.json

- Update app baselines package version. New value: 23.5.16502.28840

[24.0] Update app baselines package version. New value: 23.5.16502.28840

---

build/Packages.json

- Update app baselines package version. New value: 24.5.23489.28863

[25.0] Update app baselines package version. New value: 24.5.23489.28863

---

build/Packages.json

- Update app baselines package version. New value: 25.3.28795.0
- Update translation package version. New value: 25.3.20250109.2

[25.x] Update app baselines package version. New value: 25.3.28795.0 (+ 1 more update(s))

---

build/Packages.json

- Update app baselines package version. New value: 24.1.18927.28831

[24.2] Update app baselines package version. New value: 24.1.18927.28831

---

build/Packages.json

- Update app baselines package version. New value: 24.3.21374.28837

[24.4] Update app baselines package version. New value: 24.3.21374.28837

---

build/Packages.json

- Update app baselines package version. New value: 24.5.23489.28863
- Update translation package version. New value: 24.9.20250109.1

[24.x] Update app baselines package version. New value: 24.5.23489.28863 (+ 1 more update(s))

---

build/Packages.json

- Update app baselines package version. New value: 25.1.25873.28868

[25.2] Update app baselines package version. New value: 25.1.25873.28868

---

build/Packages.json

- Update app baselines package version. New value: 24.0.16410.28829

[24.1] Update app baselines package version. New value: 24.0.16410.28829

---

build/Packages.json

- Update app baselines package version. New value: 24.2.20227.28834

[24.3] Update app baselines package version. New value: 24.2.20227.28834

---

build/Packages.json

- Update app baselines package version. New value: 25.2.27733.28869
- Update translation package version. New value: 25.3.20250109.2

[25.3] Update app baselines package version. New value: 25.2.27733.28869 (+ 1 more update(s))

---

build/Packages.json

- Update app baselines package version. New value: 25.0.23364.28865

[25.1] Update app baselines package version. New value: 25.0.23364.28865

---

build/Packages.json

- Update app baselines package version. New value: 25.4.28874.0
- Update translation package version. New value: 26.0.20250109.3

[main] Update app baselines package version. New value: 25.4.28874.0 (+ 1 more update(s))

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.28918.0

[main] Update BCArtifact version. New value: 26.0.28918.0

---

.github/AL-Go-Settings.json
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/25.2] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  764fc413d9ab5b31265377c8422a71163b464db6 / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.5] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  764fc413d9ab5b31265377c8422a71163b464db6 / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.1] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  764fc413d9ab5b31265377c8422a71163b464db6 / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.2] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  764fc413d9ab5b31265377c8422a71163b464db6 / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[main] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  764fc413d9ab5b31265377c8422a71163b464db6 / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.0] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  764fc413d9ab5b31265377c8422a71163b464db6 / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.x] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  764fc413d9ab5b31265377c8422a71163b464db6 / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/25.1] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  764fc413d9ab5b31265377c8422a71163b464db6 / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/25.0] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  764fc413d9ab5b31265377c8422a71163b464db6 / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/25.3] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  764fc413d9ab5b31265377c8422a71163b464db6 / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.4] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  764fc413d9ab5b31265377c8422a71163b464db6 / Related to AB#539394

---

src/Business Foundation/Test/NoSeries/src/NoSeriesTests.Codeunit.al

add test for create new no. series from UI
Fixes [AB#560720](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/560720)

add test for create new no. series from UI

---

src/System Application/App/AI/src/Azure OpenAI/AzureOpenAIImpl.Codeunit.al
src/System Application/Test/DisabledTests/AzureOpenAITest.json

Backport of #2781
Fixes [AB#562514](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/562514)

[25.x][Copilot] Revert error in CheckTextCompletionMetaprompt (#2781)

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.28997.0

[main] Update BCArtifact version. New value: 26.0.28997.0

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.29075.0

[main] Update BCArtifact version. New value: 26.0.29075.0

---

build/Packages.json

- Update translation package version. New value: 25.4.20250117.1

[25.x] Update translation package version. New value: 25.4.20250117.1

---

build/Packages.json

- Update app baselines package version. New value: 24.4.22295.29076

[24.5] Update app baselines package version. New value: 24.4.22295.29076

---

build/Packages.json

- Update app baselines package version. New value: 25.0.23364.29122

[25.1] Update app baselines package version. New value: 25.0.23364.29122

---

build/Packages.json

- Update app baselines package version. New value: 25.4.29130.0
- Update translation package version. New value: 26.0.20250120.4

[main] Update app baselines package version. New value: 25.4.29130.0 (+ 1 more update(s))

---

build/Packages.json

- Update app baselines package version. New value: 25.1.25873.29124

[25.2] Update app baselines package version. New value: 25.1.25873.29124

---

build/Packages.json

- Update app baselines package version. New value: 24.3.21374.29101

[24.4] Update app baselines package version. New value: 24.3.21374.29101

---

build/Packages.json

- Update app baselines package version. New value: 24.1.18927.29105

[24.2] Update app baselines package version. New value: 24.1.18927.29105

---

build/Packages.json

- Update app baselines package version. New value: 24.2.20227.29102

[24.3] Update app baselines package version. New value: 24.2.20227.29102

---

build/Packages.json

- Update app baselines package version. New value: 24.5.23489.29100
- Update translation package version. New value: 24.9.20250120.2

[24.x] Update app baselines package version. New value: 24.5.23489.29100 (+ 1 more update(s))

---

build/Packages.json

- Update app baselines package version. New value: 24.0.16410.29104

[24.1] Update app baselines package version. New value: 24.0.16410.29104

---

build/Packages.json

- Update app baselines package version. New value: 24.5.23489.29100

[25.0] Update app baselines package version. New value: 24.5.23489.29100

---

build/Packages.json

- Update app baselines package version. New value: 23.5.16502.28996

[24.0] Update app baselines package version. New value: 23.5.16502.28996

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.29145.0

[main] Update BCArtifact version. New value: 26.0.29145.0

---

build/Packages.json

- Update app baselines package version. New value: 25.2.27733.29140

[25.3] Update app baselines package version. New value: 25.2.27733.29140

---

.github/AL-Go-Settings.json
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/25.3] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  52b990dc650f1be8736a804faebd2b5567e77e09 / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.0] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  52b990dc650f1be8736a804faebd2b5567e77e09 / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.4] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  52b990dc650f1be8736a804faebd2b5567e77e09 / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.2] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  52b990dc650f1be8736a804faebd2b5567e77e09 / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.1] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  52b990dc650f1be8736a804faebd2b5567e77e09 / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.5] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  52b990dc650f1be8736a804faebd2b5567e77e09 / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.3] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  52b990dc650f1be8736a804faebd2b5567e77e09 / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.x] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  52b990dc650f1be8736a804faebd2b5567e77e09 / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/25.2] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  52b990dc650f1be8736a804faebd2b5567e77e09 / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/25.1] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  52b990dc650f1be8736a804faebd2b5567e77e09 / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/25.x] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  52b990dc650f1be8736a804faebd2b5567e77e09 / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/25.0] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  52b990dc650f1be8736a804faebd2b5567e77e09 / Related to AB#539394

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.29217.0

[main] Update BCArtifact version. New value: 26.0.29217.0

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: bcartifacts/Sandbox/25.3/base/latest

[25.3] Update BCArtifact version. New value: bcartifacts/Sandbox/25.3/base/latest

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.29271.0

[main] Update BCArtifact version. New value: 26.0.29271.0

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.29301.0

[main] Update BCArtifact version. New value: 26.0.29301.0

---

src/System Application/App/AI/src/Azure OpenAI/AzureOpenAIImpl.Codeunit.al
src/System Application/App/AI/src/Azure OpenAI/Chat Completion/AOAIChatMessagesImpl.Codeunit.al
src/System Application/Test/DisabledTests/AzureOpenAITest.json

Backport of #2723 and #2781 
Fixes [AB#563282](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/563282)

[Releases/25.2] Backport of Reduce KV Checks for Embed ISV

---

src/System Application/App/Agent/Interaction/AgentTaskList.Page.al
src/System Application/App/Agent/Interaction/AgentTaskMessageList.Page.al
src/System Application/App/Agent/Interaction/AgentTaskStepList.Page.al

Remove agent pages from page search
Fixes [AB#563463](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/563463)

[25.2] Removing pages from page search

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.29372.0

[main] Update BCArtifact version. New value: 26.0.29372.0

---

build/Packages.json

- Update app baselines package version. New value: 24.3.21374.29425

[24.4] Update app baselines package version. New value: 24.3.21374.29425

---

build/Packages.json

- Update app baselines package version. New value: 24.0.16410.29430

[24.1] Update app baselines package version. New value: 24.0.16410.29430

---

build/Packages.json

- Update translation package version. New value: 25.4.20250123.3

[25.x] Update translation package version. New value: 25.4.20250123.3

---

build/Packages.json

- Update app baselines package version. New value: 25.4.29475.0
- Update translation package version. New value: 26.0.20250123.2

[main] Update app baselines package version. New value: 25.4.29475.0 (+ 1 more update(s))

---

build/Packages.json

- Update app baselines package version. New value: 25.0.23364.29450

[25.1] Update app baselines package version. New value: 25.0.23364.29450

---

build/Packages.json

- Update app baselines package version. New value: 25.1.25873.29452

[25.2] Update app baselines package version. New value: 25.1.25873.29452

---

build/Packages.json

- Update app baselines package version. New value: 24.5.23489.29422

[24.x] Update app baselines package version. New value: 24.5.23489.29422

---

build/Packages.json

- Update app baselines package version. New value: 24.2.20227.29428

[24.3] Update app baselines package version. New value: 24.2.20227.29428

---

build/Packages.json

- Update app baselines package version. New value: 24.1.18927.29429

[24.2] Update app baselines package version. New value: 24.1.18927.29429

---

build/Packages.json

- Update app baselines package version. New value: 25.2.27733.29449

[25.3] Update app baselines package version. New value: 25.2.27733.29449

---

build/Packages.json

- Update app baselines package version. New value: 24.4.22295.29423

[24.5] Update app baselines package version. New value: 24.4.22295.29423

---

build/Packages.json

- Update app baselines package version. New value: 24.5.23489.29422

[25.0] Update app baselines package version. New value: 24.5.23489.29422

---

build/Packages.json

- Update app baselines package version. New value: 23.5.16502.29431

[24.0] Update app baselines package version. New value: 23.5.16502.29431

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.29575.0

[main] Update BCArtifact version. New value: 26.0.29575.0

---

src/System Application/App/Agent/Interaction/AgentTaskList.Page.al

Returning agent task list to the page search
Fixes [AB#564040](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/564040)

Returing Agent Task List to the page search

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.29633.0

[main] Update BCArtifact version. New value: 26.0.29633.0

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.29684.0

[main] Update BCArtifact version. New value: 26.0.29684.0

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: bcinsider/Sandbox/25.5/base/latest

[25.x] Update BCArtifact version. New value: bcinsider/Sandbox/25.5/base/latest

---

build/Packages.json

- Update app baselines package version. New value: 24.3.21374.29711

[24.4] Update app baselines package version. New value: 24.3.21374.29711

---

build/Packages.json

- Update app baselines package version. New value: 25.4.29671.0
- Update translation package version. New value: 25.4.20250130.7

[25.x] Update app baselines package version. New value: 25.4.29671.0 (+ 1 more update(s))

---

build/Packages.json

- Update app baselines package version. New value: 25.1.25873.29719

[25.2] Update app baselines package version. New value: 25.1.25873.29719

---

build/Packages.json

- Update app baselines package version. New value: 24.5.23489.29713

[24.x] Update app baselines package version. New value: 24.5.23489.29713

---

build/Packages.json

- Update app baselines package version. New value: 25.2.27733.29716

[25.3] Update app baselines package version. New value: 25.2.27733.29716

---

build/Packages.json

- Update app baselines package version. New value: 24.4.22295.29694

[24.5] Update app baselines package version. New value: 24.4.22295.29694

---

build/Packages.json

- Update app baselines package version. New value: 25.5.29760.0
- Update translation package version. New value: 26.0.20250203.4

[main] Update app baselines package version. New value: 25.5.29760.0 (+ 1 more update(s))

---

build/Packages.json

- Update app baselines package version. New value: 24.2.20227.29715

[24.3] Update app baselines package version. New value: 24.2.20227.29715

---

build/Packages.json

- Update app baselines package version. New value: 24.0.16410.29714

[24.1] Update app baselines package version. New value: 24.0.16410.29714

---

build/Packages.json

- Update translation package version. New value: 25.4.20250130.7

[25.4] Update translation package version. New value: 25.4.20250130.7

---

build/Packages.json

- Update app baselines package version. New value: 23.5.16502.29645

[24.0] Update app baselines package version. New value: 23.5.16502.29645

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.29806.0

[main] Update BCArtifact version. New value: 26.0.29806.0

---

src/System Application/App/Table Information/src/TableInformation.Page.al

Add AboutTitle and AboutText to page 8700
Fixes [AB#564107](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/564107)

Add AboutTitle and AboutText to page 8700

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.29863.0

[main] Update BCArtifact version. New value: 26.0.29863.0

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.29889.0

[main] Update BCArtifact version. New value: 26.0.29889.0

---

src/System Application/Test Library/app.json
src/System Application/Test/app.json

Increment version number incremented the version twice for some apps 
Fixes [AB#565077](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/565077)

Fix Increment Version Number bug

---

src/System Application/App/SharePoint/src/SharePointClient.Codeunit.al
src/System Application/App/SharePoint/src/SharePointClientImpl.Codeunit.al

Adds FolderExists function to the SharePoint System Application Module
Fixes #2897
Fixes [AB#565066](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/565066)

Add FolderExistsByServerRelativeUrl method to SharePoint Client

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.29985.0

[main] Update BCArtifact version. New value: 26.0.29985.0

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: bcinsider/Sandbox/24.11/base/latest

[24.x] Update BCArtifact version. New value: bcinsider/Sandbox/24.11/base/latest

---

build/Packages.json

- Update app baselines package version. New value: 24.5.23489.29954

[25.0] Update app baselines package version. New value: 24.5.23489.29954

---

build/Packages.json

- Update app baselines package version. New value: 23.5.16502.29801

[24.0] Update app baselines package version. New value: 23.5.16502.29801

---

build/Packages.json

- Update app baselines package version. New value: 24.2.20227.29951

[24.3] Update app baselines package version. New value: 24.2.20227.29951

---

build/Packages.json

- Update app baselines package version. New value: 25.0.23364.29957

[25.1] Update app baselines package version. New value: 25.0.23364.29957

---

build/Packages.json

- Update app baselines package version. New value: 24.3.21374.29958

[24.4] Update app baselines package version. New value: 24.3.21374.29958

---

build/Packages.json

- Update app baselines package version. New value: 24.1.18927.29955

[24.2] Update app baselines package version. New value: 24.1.18927.29955

---

src/System Application/App/Agent/Setup/AgentImpl.Codeunit.al
src/System Application/App/Agent/dotnet.al

Remove usage of Agent.Instructions field and replace with  AgentALFunctions.GetInstructions and AgentALFunctions.SetInstructions
Fixes [AB#564038](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/564038)

Uptake agent instructions API changes

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: bcartifacts/Sandbox/25.4/base/latest

[25.4] Update BCArtifact version. New value: bcartifacts/Sandbox/25.4/base/latest

---

src/System Application/App/AI/app.json
src/System Application/App/AI/src/Azure AI Document Intelligence/ADIModelType.Enum.al
src/System Application/App/AI/src/Azure AI Document Intelligence/AzureDIImpl.Codeunit.al
src/System Application/App/AI/src/Azure AI Document Intelligence/AzureDocumentIntelligence.Codeunit.al
src/System Application/App/AI/src/Azure OpenAI/AzureOpenAI.Codeunit.al
src/System Application/App/AI/src/Azure OpenAI/AzureOpenAIImpl.Codeunit.al
src/System Application/App/AI/src/Copilot/AzureAIServiceType.Enum.al
src/System Application/App/AI/src/Copilot/CopilotAICapabilities.Page.al
src/System Application/App/AI/src/Copilot/CopilotCapEarlyPreview.Page.al
src/System Application/App/AI/src/Copilot/CopilotCapabilitiesGA.Page.al
src/System Application/App/AI/src/Copilot/CopilotCapabilitiesPreview.Page.al
src/System Application/App/AI/src/Copilot/CopilotCapabilityImpl.Codeunit.al
src/System Application/App/AI/src/Copilot/CopilotSettings.Table.al
src/System Application/App/AI/src/Copilot/Interfaces/AIServiceName.Interface.al
src/System Application/Test/AI/src/AzureDITest.Codeunit.al

Reverts microsoft/BCApps#2930
Fixes
[AB#563692](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/563692)

Reapply "Azure Document Intelligence Module" (#2834)"

---

src/System Application/App/Agent/Setup/AgentImpl.Codeunit.al
src/System Application/App/Agent/Setup/AgentList.Page.al

Show a notification in the agents page when there are no agents available to be configured.
Fixes [AB#564870](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/564870)

[Agents] Show notification in the Agents list page when no agents available in environment

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.30163.0

[main] Update BCArtifact version. New value: 26.0.30163.0

---

src/System Application/App/Agent/Interaction/AgentTaskList.Page.al
src/System Application/App/Agent/Setup/AgentList.Page.al

Mark agent pages with preview if they are accessible from page search
Fixes [AB#564868](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/564868)

Agents - Marking agent pages with preview

---

src/System Application/App/Agent/TaskPane/AgentTaskTimeline.Page.al
src/System Application/App/Agent/TaskPane/AgentTasks.Page.al

Adding fields to show who agent task was initially created for and further authorization changes
Fixes [AB#565626](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/565626)

Agent task pane - task Created By and Now Authorized By fields

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.30195.0

[main] Update BCArtifact version. New value: 26.0.30195.0

---

build/Packages.json

- Update app baselines package version. New value: 24.5.23489.30235

[25.0] Update app baselines package version. New value: 24.5.23489.30235

---

build/Packages.json

- Update app baselines package version. New value: 23.5.16502.30234

[24.0] Update app baselines package version. New value: 23.5.16502.30234

---

build/Packages.json

- Update app baselines package version. New value: 24.0.16410.30242

[24.1] Update app baselines package version. New value: 24.0.16410.30242

---

build/Packages.json

- Update app baselines package version. New value: 25.2.27733.30243

[25.3] Update app baselines package version. New value: 25.2.27733.30243

---

build/Packages.json

- Update app baselines package version. New value: 24.1.18927.30244

[24.2] Update app baselines package version. New value: 24.1.18927.30244

---

build/Packages.json

- Update app baselines package version. New value: 24.2.20227.30241

[24.3] Update app baselines package version. New value: 24.2.20227.30241

---

build/Packages.json

- Update app baselines package version. New value: 24.5.23489.30235

[24.x] Update app baselines package version. New value: 24.5.23489.30235

---

build/Packages.json

- Update app baselines package version. New value: 24.3.21374.30239

[24.4] Update app baselines package version. New value: 24.3.21374.30239

---

build/Packages.json

- Update app baselines package version. New value: 24.4.22295.30233

[24.5] Update app baselines package version. New value: 24.4.22295.30233

---

build/Packages.json

- Update app baselines package version. New value: 25.0.23364.30236

[25.1] Update app baselines package version. New value: 25.0.23364.30236

---

build/Packages.json

- Update app baselines package version. New value: 25.1.25873.30237

[25.2] Update app baselines package version. New value: 25.1.25873.30237

---

build/Packages.json

- Update translation package version. New value: 25.5.20250217.1

[25.x] Update translation package version. New value: 25.5.20250217.1

---

build/Packages.json

- Update app baselines package version. New value: 25.5.30256.0
- Update translation package version. New value: 26.0.20250217.3

[main] Update app baselines package version. New value: 25.5.30256.0 (+ 1 more update(s))

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.30335.0

[main] Update BCArtifact version. New value: 26.0.30335.0

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.30369.0

[main] Update BCArtifact version. New value: 26.0.30369.0

---

src/System Application/App/Azure Key Vault/src/AzureKeyVaultImpl.Codeunit.al
src/System Application/Test/Azure Key Vault/src/AzureKeyVaultTest.Codeunit.al
src/System Application/Test/Satisfaction Survey/src/SatisfactionSurveyTests.Codeunit.al

[25.4] Get rid of allowedsecretslist from app KV

---

.github/AL-Go-Settings.json

Run incremental builds in "modifiedProjects" mode

Run incremental builds in "modifiedProjects" mode

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.30444.0

[main] Update BCArtifact version. New value: 26.0.30444.0

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[25.4] Revert latest AL-Go uptake

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[25.3] Revert latest AL-Go uptake

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[25.1] Revert latest AL-Go uptake

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[25.2] Revert latest AL-Go uptake

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[25.0] Revert latest AL-Go uptake

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[25.x] Revert latest AL-Go uptake

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[24.x] Revert latest AL-Go uptake

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[24.0] Revert latest AL-Go uptake

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[24.1] Revert latest AL-Go uptake

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[24.2] Revert latest AL-Go uptake

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[24.4] Revert latest AL-Go uptake

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[24.5] Revert latest AL-Go uptake

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[24.3] Revert latest AL-Go uptake

---

src/System Application/App/User Selection/src/UserSelectionImpl.Codeunit.al

Users with License Type = Agent will be filtered out similarly to Entra Applications users, agent users will be managed from a dedicated Agents page.
Fixes [AB#564864](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/564864)

Hide Agent users from Users page and user lookup

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.30544.0

[main] Update BCArtifact version. New value: 26.0.30544.0

---

src/System Application/App/Azure Key Vault/src/AzureKeyVaultImpl.Codeunit.al
src/System Application/Test/Azure Key Vault/src/AzureKeyVaultTest.Codeunit.al
src/System Application/Test/Satisfaction Survey/src/SatisfactionSurveyTests.Codeunit.al

[24.x] Get rid of allowedsecretslist from app KV

---

src/System Application/App/Feature Key/permissions/FeatureKeyView.PermissionSet.al
src/System Application/App/Web Service Management/app.json
src/System Application/App/Web Service Management/permissions/WebServiceManagementAdmin.Permissionset.al
src/System Application/App/Web Service Management/permissions/WebServiceManagementRead.Permissionset.al
src/System Application/App/Web Service Management/src/WebServiceManagementImpl.Codeunit.al
src/System Application/Test/Web Service Management/src/WebServiceManagementTest.Codeunit.al

We're seeing failures in CICDs that look related to a recent PR. Reverting for now until tests are fixed
https://github.com/microsoft/BCApps/actions/runs/13494120331
Related to [AB#566696](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/566696)

Revert "Remove ability to expose a Microsoft page as a SOAP endpoint"

---

src/System Application/App/Azure Key Vault/src/AzureKeyVaultImpl.Codeunit.al
src/System Application/Test/Azure Key Vault/src/AzureKeyVaultTest.Codeunit.al
src/System Application/Test/Satisfaction Survey/src/SatisfactionSurveyTests.Codeunit.al

[25.1] Get rid of allowedsecretslist from app KV

---

src/System Application/App/Azure Key Vault/src/AzureKeyVaultImpl.Codeunit.al
src/System Application/Test/Azure Key Vault/src/AzureKeyVaultTest.Codeunit.al
src/System Application/Test/Satisfaction Survey/src/SatisfactionSurveyTests.Codeunit.al

[25.0] Get rid of allowedsecretslist from app KV

---

src/System Application/App/Azure Key Vault/src/AzureKeyVaultImpl.Codeunit.al
src/System Application/Test/Azure Key Vault/src/AzureKeyVaultTest.Codeunit.al
src/System Application/Test/Satisfaction Survey/src/SatisfactionSurveyTests.Codeunit.al

[24.5] Get rid of allowedsecretslist from app KV

---

src/System Application/App/Azure Key Vault/src/AzureKeyVaultImpl.Codeunit.al
src/System Application/Test/Azure Key Vault/src/AzureKeyVaultTest.Codeunit.al
src/System Application/Test/Satisfaction Survey/src/SatisfactionSurveyTests.Codeunit.al

Fixes # [[AB#544481](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/544481)]

[24.4] Get rid of allowedsecretslist from app KV

---

src/System Application/App/Azure Key Vault/src/AzureKeyVaultImpl.Codeunit.al
src/System Application/Test/Azure Key Vault/src/AzureKeyVaultTest.Codeunit.al
src/System Application/Test/Satisfaction Survey/src/SatisfactionSurveyTests.Codeunit.al

[24.2] Get rid of allowedsecretslist from app KV

---

src/System Application/App/Azure Key Vault/src/AzureKeyVaultImpl.Codeunit.al
src/System Application/Test/Azure Key Vault/src/AzureKeyVaultTest.Codeunit.al
src/System Application/Test/Satisfaction Survey/src/SatisfactionSurveyTests.Codeunit.al

[24.1] Get rid of allowedsecretslist from app KV

---

build/Packages.json

- Update app baselines package version. New value: 24.5.23489.30616

[25.0] Update app baselines package version. New value: 24.5.23489.30616

---

build/Packages.json

- Update app baselines package version. New value: 23.5.16502.30562

[24.0] Update app baselines package version. New value: 23.5.16502.30562

---

build/Packages.json

- Update app baselines package version. New value: 24.4.22295.30617

[24.5] Update app baselines package version. New value: 24.4.22295.30617

---

build/Packages.json

- Update app baselines package version. New value: 24.5.23489.30616

[24.x] Update app baselines package version. New value: 24.5.23489.30616

---

build/Packages.json

- Update app baselines package version. New value: 24.2.20227.30619

[24.3] Update app baselines package version. New value: 24.2.20227.30619

---

build/Packages.json

- Update app baselines package version. New value: 24.3.21374.30615

[24.4] Update app baselines package version. New value: 24.3.21374.30615

---

build/Packages.json

- Update app baselines package version. New value: 25.2.27733.30535

[25.3] Update app baselines package version. New value: 25.2.27733.30535

---

build/Packages.json

- Update translation package version. New value: 25.5.20250225.3

[25.x] Update translation package version. New value: 25.5.20250225.3

---

build/Packages.json

- Update app baselines package version. New value: 24.1.18927.30618

[24.2] Update app baselines package version. New value: 24.1.18927.30618

---

build/Packages.json

- Update app baselines package version. New value: 25.1.25873.30612

[25.2] Update app baselines package version. New value: 25.1.25873.30612

---

build/Packages.json

- Update app baselines package version. New value: 25.0.23364.30611

[25.1] Update app baselines package version. New value: 25.0.23364.30611

---

src/System Application/App/AI/app.json

Increment version number to 27.0 (remaining dependencies)
Fixes [AB#566616](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/566616)

Update dependencies to 27.0

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.30643.30657

[26.0] Update BCArtifact version. New value: 26.0.30643.30657

---

build/Packages.json

- Update app baselines package version. New value: 26.1.30654.0
- Update translation package version. New value: 26.0.20250224.2

[main] Update app baselines package version. New value: 26.1.30654.0 (+ 1 more update(s))

---

src/System Application/App/Agent/TaskPane/AgentTaskDetails.Page.al
src/System Application/App/Agent/TaskPane/AgentTaskTimeline.Page.al

Allow discarding input messages in the Agent Task Timeline.
Fixes [AB#566842](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/566842)

[Agents] Allow discarding input messages

---

src/System Application/App/Agent/TaskPane/AgentTaskDetails.Page.al
src/System Application/App/Agent/TaskPane/AgentTaskTimeline.Page.al

Allow discarding input messages in the Agent Task Timeline.
Fixes
[AB#566842](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/566842)

[Agents 26.0] Allow discarding input messages (#3063)

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 27.0.30742.0

[main] Update BCArtifact version. New value: 27.0.30742.0

---

src/System Application/App/Environment Information/src/EnvironmentInformation.Codeunit.al
src/System Application/App/Environment Information/src/EnvironmentInformationImpl.Codeunit.al

Exposing the EnvironmentSettings for Microsoft published callers.
[AB#565525](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/565525)
---------
Fixes #

Exposing application environment settings.

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.1.30740.0

[26.x] Update BCArtifact version. New value: 26.1.30740.0

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.30643.30741

[26.0] Update BCArtifact version. New value: 26.0.30643.30741

---

src/System Application/App/AI/src/Copilot/CopilotAICapabilities.Page.al
src/System Application/App/AI/src/Copilot/CopilotQuotaImpl.Codeunit.al

This pull request backports #3115 to releases/26.x
Fixes [AB#567346](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/567346)

[releases/26.x] Move quota checks to page background task

---

src/System Application/App/AI/src/Copilot/CopilotAICapabilities.Page.al
src/System Application/App/AI/src/Copilot/CopilotQuotaImpl.Codeunit.al

This pull request backports #3115 to releases/26.0
Fixes [AB#567347](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/567347)

[releases/26.0] Move quota checks to page background task

---

src/System Application/App/Agent/TaskPane/AgentTaskTimeline.Page.al

This PR addresses some issues around the "Task now authorized by" cards in the Agent timeline.
This will now only be set when the user who has performed a user intervention is different from the user who intervened last time (or the user who created the task if there have been no other interventions).
Fixes [AB#567140](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/567140) 
Fixes [AB#567143](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/567143)

[Agents] Fixes for "task now authorized by" scenarios

---

src/System Application/App/Agent/TaskPane/AgentTaskTimeline.Page.al

This pull request backports #3121 to releases/26.x
Fixes [AB#567140](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/567140) 
Fixes [AB#567143](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/567143)

[releases/26.x] [Agents] Fixes for "task now authorized by" scenarios

---

src/System Application/App/Agent/TaskPane/AgentTaskTimeline.Page.al

This pull request backports #3121 to releases/26.0
Fixes [AB#567140](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/567140) 
Fixes [AB#567143](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/567143)

[releases/26.0] [Agents] Fixes for "task now authorized by" scenarios

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 27.0.30807.0

[main] Update BCArtifact version. New value: 27.0.30807.0

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: bcinsider/Sandbox/25.6/base/latest

[25.x] Update BCArtifact version. New value: bcinsider/Sandbox/25.6/base/latest

---

src/System Application/App/AI/src/Copilot/CopilotAICapabilities.Page.al
src/System Application/App/AI/src/Copilot/CopilotQuotaImpl.Codeunit.al

The quota check from platform can be delayed resulting in a delay in opening the page.
We should not be blocking/delaying the opening of page, as such, that logic is moved to page background task.
Fixes [AB#567292](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/567292)

Move quota checks to page background task

---

src/System Application/App/AppSource Gallery/src/AppSourceProductList.Page.al

Fixes [AB#562392](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/562392)

Update ToolTip for Edit User Settings action

---

src/Business Foundation/Test/NoSeries/src/NoSeriesTests.Codeunit.al
src/System Application/Test/DisabledTests/NoSeriesTests.json

Disable TestCreateNewNoSeriesFromUI
Related to [AB#567836](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/567836)

Address errors in TestCreateNewNoSeriesFromUI

---

src/Business Foundation/Test/NoSeries/src/NoSeriesTests.Codeunit.al

This pull request backports #3136 to releases/26.x
Fixes [AB#567836](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/567836)

[releases/26.x] Address errors in TestCreateNewNoSeriesFromUI

---

src/Business Foundation/Test/NoSeries/src/NoSeriesTests.Codeunit.al

This pull request backports #3136 to releases/26.0
Fixes [AB#567836](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/567836)

[releases/26.0] Address errors in TestCreateNewNoSeriesFromUI

---

src/System Application/App/Feature Key/permissions/FeatureKeyView.PermissionSet.al
src/System Application/App/Web Service Management/app.json
src/System Application/App/Web Service Management/permissions/WebServiceManagementAdmin.Permissionset.al
src/System Application/App/Web Service Management/permissions/WebServiceManagementRead.Permissionset.al
src/System Application/App/Web Service Management/src/WebServiceManagementImpl.Codeunit.al
src/System Application/Test/Web Service Management/src/WebServiceManagementTest.Codeunit.al

Changes were reverted in #3045 due to failing tests.
Re-apply changes to web service management and fix failing tests.
Fixes [AB#566696](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/566696)

Remove ability to expose a Microsoft page as a SOAP endpoint

---

build/Packages.json

- Update app baselines package version. New value: 24.5.23489.30936

[25.0] Update app baselines package version. New value: 24.5.23489.30936

---

build/Packages.json

- Update app baselines package version. New value: 23.5.16502.30938

[24.0] Update app baselines package version. New value: 23.5.16502.30938

---

build/Packages.json

- Update app baselines package version. New value: 24.2.20227.30939

[24.3] Update app baselines package version. New value: 24.2.20227.30939

---

build/Packages.json

- Update app baselines package version. New value: 24.5.23489.30936

[24.x] Update app baselines package version. New value: 24.5.23489.30936

---

build/Packages.json

- Update app baselines package version. New value: 24.0.16410.30937

[24.1] Update app baselines package version. New value: 24.0.16410.30937

---

build/Packages.json

- Update translation package version. New value: 25.5.20250225.5

[25.5] Update translation package version. New value: 25.5.20250225.5

---

build/Packages.json

- Update app baselines package version. New value: 26.0.30643.30994

[26.x] Update app baselines package version. New value: 26.0.30643.30994

---

build/Packages.json

- Update app baselines package version. New value: 24.1.18927.30940

[24.2] Update app baselines package version. New value: 24.1.18927.30940

---

build/Packages.json

- Update app baselines package version. New value: 25.0.23364.30930

[25.1] Update app baselines package version. New value: 25.0.23364.30930

---

build/Packages.json

- Update app baselines package version. New value: 24.3.21374.30935

[24.4] Update app baselines package version. New value: 24.3.21374.30935

---

build/Packages.json

- Update app baselines package version. New value: 26.1.30990.0
- Update translation package version. New value: 27.0.20250303.7

[main] Update app baselines package version. New value: 26.1.30990.0 (+ 1 more update(s))

---

build/Packages.json

- Update app baselines package version. New value: 24.4.22295.30933

[24.5] Update app baselines package version. New value: 24.4.22295.30933

---

build/Packages.json

- Update app baselines package version. New value: 25.2.27733.30927

[25.3] Update app baselines package version. New value: 25.2.27733.30927

---

build/Packages.json

- Update app baselines package version. New value: 25.1.25873.30934

[25.2] Update app baselines package version. New value: 25.1.25873.30934

---

build/Packages.json

- Update app baselines package version. New value: 25.5.30921.0
- Update translation package version. New value: 25.6.20250303.16

[25.x] Update app baselines package version. New value: 25.5.30921.0 (+ 1 more update(s))

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 27.0.30997.0

[main] Update BCArtifact version. New value: 27.0.30997.0

---

src/System Application/App/External File Storage/src/Lookup/FileAccountBrowserMgt.Codeunit.al

```
trigger OnAction()
var
ExternalFileStorage: Codeunit "External File Storage";
Path: Text;
begin
ExternalFileStorage.Initialize("File Scenario"::Default);
Path := ExternalFileStorage.SelectAndGetFolderPath('');
end;
```
Shows no Parent Folder ins Sub Folders.
Fixes #3158
Fixes [AB#567964](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/567964)

External File Storage: Fix Parent Folder Navigation in Storage Browset

---

src/System Application/App/Retention Policy/src/Retention Policy Log/RetentionPolicyLogImpl.Codeunit.al
src/System Application/Test Library/Retention Policy/src/RetentionPolicyTestLibrary.Codeunit.al
src/System Application/Test/Retention Policy/src/RetentionPolicyLogTest.Codeunit.al

Only send errors to background session for logging
Fixes [AB#567886](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/567886)

Only send errors to background session for logging

---

.github/AL-Go-Settings.json
src/System Application/App/VS Code Integration/src/VsCodeIntegrationImpl.Codeunit.al
src/System Application/Test/Vs Code Integration/src/VSCodeIntegrationTest.Codeunit.al

Fixes #3114 
Fixes [AB#567859](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/567859)

#3114 Format AppId without brackets and lowercase for VsCode Integration

---

src/System Application/App/Web Service Management/app.json
src/System Application/App/Web Service Management/permissions/WebServiceManagementAdmin.Permissionset.al
src/System Application/App/Web Service Management/permissions/WebServiceManagementRead.Permissionset.al
src/System Application/App/Web Service Management/src/WebServiceManagementImpl.Codeunit.al
src/System Application/Test/Web Service Management/src/WebServiceManagementTest.Codeunit.al

Changes were reverted in #3045 due to failing tests.
Re-apply changes to web service management and fix failing tests.
Fixes [AB#567979](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/567979)

[26.0] Remove ability to expose a Microsoft page as a SOAP endpoint

---

src/System Application/Test Library/Web Service Management/Permissions/WebServiceAdmin.Permissionset.al
src/System Application/Test Library/Web Service Management/app.json
src/System Application/Test/Web Service Management/app.json
src/System Application/Test/Web Service Management/src/WebServiceManagementTest.Codeunit.al

Ensure feature key is always on in tests so there's no dependency on the feature key being setup for tests to pass.
Fixes [AB#567934](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/567934/)

[Web Service Management] Ensure feature key is always on in tests

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 27.0.31076.0

[main] Update BCArtifact version. New value: 27.0.31076.0

---

src/System Application/Test Library/Web Service Management/Permissions/WebServiceAdmin.Permissionset.al
src/System Application/Test Library/Web Service Management/app.json
src/System Application/Test/Web Service Management/app.json
src/System Application/Test/Web Service Management/src/WebServiceManagementTest.Codeunit.al

Ensure feature key is always on in tests so there's no dependency on the feature key being setup for tests to pass.
Fixes [AB#568399](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/568399/)

[26.0] [Web Service Management] Ensure feature key is always on in tests

---

src/System Application/Test Library/Web Service Management/Permissions/WebServiceAdmin.Permissionset.al
src/System Application/Test Library/Web Service Management/app.json
src/System Application/Test/Web Service Management/app.json
src/System Application/Test/Web Service Management/src/WebServiceManagementTest.Codeunit.al

Ensure feature key is always on in tests so there's no dependency on the feature key being setup for tests to pass.
Fixes [AB#568406](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/568406/)

[26.x] [Web Service Management] Ensure feature key is always on in tests

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 27.0.31285.0

[main] Update BCArtifact version. New value: 27.0.31285.0

---

src/rulesets/ruleset.json

Rule https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/appsourcecop-as0077 should only be enabled in release branches, as the rule only applies in hotfix scenarios.
Fixes [AB#568822](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/568822)

Disable rule AS0077 in MAIN branch

---

.github/AL-Go-Settings.json

Adjust CLEAN tags
[AB#568604](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/568604)

Adjust CLEAN tags

---

src/System Application/App/AI/src/Copilot/CopilotNotifications.Codeunit.al

replace the misleading text in agent quote page
Fixes [AB#568396](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/568396)

[Master] replace the misleading text in agent quote page

---

src/System Application/App/AI/src/Copilot/CopilotNotifications.Codeunit.al

replace the misleading text in agent quote page
Fixes [AB#568396](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/568396)

[26.x]replace the misleading text in agent quote page

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: bcartifacts/Sandbox/25.5/base/latest

[25.5] Update BCArtifact version. New value: bcartifacts/Sandbox/25.5/base/latest

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 27.0.31379.0

[main] Update BCArtifact version. New value: 27.0.31379.0

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: bcinsider/Sandbox/24.12/base/latest

[24.x] Update BCArtifact version. New value: bcinsider/Sandbox/24.12/base/latest

---

build/Packages.json

- Update app baselines package version. New value: 24.5.23489.31329

[25.0] Update app baselines package version. New value: 24.5.23489.31329

---

build/Packages.json

- Update app baselines package version. New value: 24.0.16410.31330

[24.1] Update app baselines package version. New value: 24.0.16410.31330

---

build/Packages.json

- Update app baselines package version. New value: 25.2.27733.31353

[25.3] Update app baselines package version. New value: 25.2.27733.31353

---

build/Packages.json

- Update app baselines package version. New value: 24.3.21374.31333

[24.4] Update app baselines package version. New value: 24.3.21374.31333

---

build/Packages.json

- Update app baselines package version. New value: 25.5.30849.31352

[26.0] Update app baselines package version. New value: 25.5.30849.31352

---

build/Packages.json

- Update app baselines package version. New value: 24.2.20227.31325

[24.3] Update app baselines package version. New value: 24.2.20227.31325

---

build/Packages.json

- Update app baselines package version. New value: 25.0.23364.31351

[25.1] Update app baselines package version. New value: 25.0.23364.31351

---

build/Packages.json

- Update app baselines package version. New value: 25.1.25873.31356

[25.2] Update app baselines package version. New value: 25.1.25873.31356

---

build/Packages.json

- Update translation package version. New value: 25.6.20250311.2

[25.x] Update translation package version. New value: 25.6.20250311.2

---

build/Packages.json

- Update app baselines package version. New value: 24.4.22295.31324

[24.5] Update app baselines package version. New value: 24.4.22295.31324

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 27.0.31468.0

[main] Update BCArtifact version. New value: 27.0.31468.0

---

src/System Application/App/AI/src/Azure OpenAI/Chat Completion/Tools/AOAIFunction.Interface.al

* Typo "Azure Open AI"???"Azure OpenAI"
* https://github.com/microsoft/BCApps/blob/main/src/System%20Application/App/AI/src/Azure%20OpenAI/Chat%20Completion/Tools/AOAIFunction.Interface.al
* #PingMSFTDocs
Fixes [AB#569205](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/569205)

Update AOAIFunction.Interface.al (Typo "Azure Open AI"→"Azure OpenAI")

---

build/Packages.json

- Update app baselines package version. New value: 25.2.27733.31472

[25.3] Update app baselines package version. New value: 25.2.27733.31472

---

build/Packages.json

- Update app baselines package version. New value: 25.1.25873.31470

[25.2] Update app baselines package version. New value: 25.1.25873.31470

---

build/Packages.json

- Update app baselines package version. New value: 24.4.22295.31475

[24.5] Update app baselines package version. New value: 24.4.22295.31475

---

build/Packages.json

- Update app baselines package version. New value: 24.5.23489.31474

[24.x] Update app baselines package version. New value: 24.5.23489.31474

---

build/Packages.json

- Update app baselines package version. New value: 25.0.23364.31392

[25.1] Update app baselines package version. New value: 25.0.23364.31392

---

build/Packages.json

- Update app baselines package version. New value: 24.3.21374.31473

[24.4] Update app baselines package version. New value: 24.3.21374.31473

---

build/Packages.json

- Update translation package version. New value: 25.6.20250312.4

[25.x] Update translation package version. New value: 25.6.20250312.4

---

build/Packages.json

- Update app baselines package version. New value: 24.5.23489.31474

[25.0] Update app baselines package version. New value: 24.5.23489.31474

---

build/Packages.json

- Update app baselines package version. New value: 25.5.30849.31476

[26.0] Update app baselines package version. New value: 25.5.30849.31476

---

build/Packages.json

- Update app baselines package version. New value: 26.1.31482.0

[main] Update app baselines package version. New value: 26.1.31482.0

---

build/scripts/PreCompileApp.ps1

This pull request backports #3203 to releases/25.0

[releases/25.0] Enable Minor release ruleset in strict mode

---

build/scripts/PreCompileApp.ps1

This pull request backports #3203 to releases/26.x

[releases/26.x] Enable Minor release ruleset in strict mode

---

build/scripts/PreCompileApp.ps1

This pull request backports #3203 to releases/25.5

[releases/25.5] Enable Minor release ruleset in strict mode

---

build/scripts/PreCompileApp.ps1

This pull request backports #3203 to releases/25.3

[releases/25.3] Enable Minor release ruleset in strict mode

---

build/scripts/PreCompileApp.ps1

This pull request backports #3203 to releases/26.0

[releases/26.0] Enable Minor release ruleset in strict mode

---

build/scripts/PreCompileApp.ps1

This pull request backports #3203 to releases/25.2

[releases/25.2] Enable Minor release ruleset in strict mode

---

build/scripts/PreCompileApp.ps1

Enable Minor release ruleset in strict mode
Related to [AB#568837](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/568837)

Enable Minor release ruleset in strict mode

---

build/Packages.json

[25.4] Update baseline version: 25.3.28755.31479

---

build/Packages.json

- Update app baselines package version. New value: 26.0.30643.31471

[26.x] Update app baselines package version. New value: 26.0.30643.31471

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 27.0.31612.0

[main] Update BCArtifact version. New value: 27.0.31612.0

---

.github/workflows/UpdateGitHubGoSystemFiles.yaml

[main@51f5bc5] Update AL-Go System Files from microsoft/AL-Go-PTE@preview - 6e5bf77 / Related to AB#539394

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 27.0.31701.0

[main] Update BCArtifact version. New value: 27.0.31701.0

---

build/Packages.json

- Update app baselines package version. New value: 25.5.30849.31772

[26.0] Update app baselines package version. New value: 25.5.30849.31772

---

build/Packages.json

- Update app baselines package version. New value: 25.0.23364.31736

[25.1] Update app baselines package version. New value: 25.0.23364.31736

---

build/Packages.json

- Update app baselines package version. New value: 25.3.28755.31734

[25.4] Update app baselines package version. New value: 25.3.28755.31734

---

build/Packages.json

- Update app baselines package version. New value: 26.0.30643.31770

[26.x] Update app baselines package version. New value: 26.0.30643.31770

---

build/Packages.json

- Update app baselines package version. New value: 24.5.23489.31733

[24.x] Update app baselines package version. New value: 24.5.23489.31733

---

build/Packages.json

- Update app baselines package version. New value: 24.3.21374.31727

[24.4] Update app baselines package version. New value: 24.3.21374.31727

---

build/Packages.json

- Update app baselines package version. New value: 26.1.31773.0
- Update translation package version. New value: 27.0.20250312.6

[main] Update app baselines package version. New value: 26.1.31773.0 (+ 1 more update(s))

---

build/Packages.json

- Update app baselines package version. New value: 25.1.25873.31731

[25.2] Update app baselines package version. New value: 25.1.25873.31731

---

build/Packages.json

- Update app baselines package version. New value: 24.5.23489.31733

[25.0] Update app baselines package version. New value: 24.5.23489.31733

---

src/System Application/Test/DisabledTests/RestClientTests.DisabledTest.json

Disable unstable REST Client tests until they are refactored to use mocks.
Fixes [AB#571641](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/571641)

Bug 571641: Disable unstable REST Client tests in gates

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 27.0.31829.0

[main] Update BCArtifact version. New value: 27.0.31829.0

---

src/Tools/Test Framework/Test Runner/src/DataDrivenTest/DataInputs/TestInputJson.Codeunit.al
src/Tools/Test Framework/Test Runner/src/DataDrivenTest/DataOutputs/TestOutputJson.Codeunit.al

Trim ToText output in Test Input Json and Test Output Json.
Fixes [AB#555687](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/555687)

[AI Test Tool] Trim ToText output

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 27.0.31897.0

[main] Update BCArtifact version. New value: 27.0.31897.0

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 27.0.31987.0

[main] Update BCArtifact version. New value: 27.0.31987.0

---

src/System Application/App/Upgrade Tags/src/UpgradeTags.Page.al

Add missing read permission 
Fixes #3325
Fixes [AB#572229](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/572229)

Add missing read permission for Upgrade Tags

---

src/System Application/App/AI/app.json
src/System Application/App/AI/src/Copilot/CopilotAICapabilities.Page.al
src/System Application/App/AI/src/Copilot/CopilotCapabilityImpl.Codeunit.al
src/System Application/App/AI/src/Copilot/CopilotTelemetry.Codeunit.al
src/System Application/App/AI/src/Copilot/CopilotTelemetryInstall.Codeunit.al
src/System Application/App/AI/src/Copilot/CopilotTelemetryUpgrade.Codeunit.al

Add telemetry when data movement is updated. Also emit once during install and upgrade to get current state.
Fixes [AB#571727](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/571727)

[25.4] [Copilot] Add telemetry when data movement is updated

---

src/System Application/App/AI/app.json
src/System Application/App/AI/src/Copilot/CopilotAICapabilities.Page.al
src/System Application/App/AI/src/Copilot/CopilotCapabilityImpl.Codeunit.al
src/System Application/App/AI/src/Copilot/CopilotTelemetry.Codeunit.al
src/System Application/App/AI/src/Copilot/CopilotTelemetryInstall.Codeunit.al
src/System Application/App/AI/src/Copilot/CopilotTelemetryUpgrade.Codeunit.al

Add telemetry when data movement is updated. Also emit once during install and upgrade to get current state.
Fixes [AB#571728](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/571728)

[25.5] [Copilot] Add telemetry when data movement is updated

---

src/System Application/App/AI/app.json
src/System Application/App/AI/src/Copilot/CopilotAICapabilities.Page.al
src/System Application/App/AI/src/Copilot/CopilotCapabilityImpl.Codeunit.al
src/System Application/App/AI/src/Copilot/CopilotTelemetry.Codeunit.al
src/System Application/App/AI/src/Copilot/CopilotTelemetryInstall.Codeunit.al
src/System Application/App/AI/src/Copilot/CopilotTelemetryUpgrade.Codeunit.al

Add telemetry when data movement is updated. Also emit once during install and upgrade to get current state.
Fixes [AB#571729](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/571729)

[25.x] [Copilot] Add telemetry when data movement is updated

---

src/System Application/App/AI/src/Copilot/CopilotTelemetryUpgrade.Codeunit.al

Ensure that we don't emit unnecessary telemetry for cross-geo switch by checking upgrade tag for the database, not per company.
Fixes [AB#572295](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/572295)

[26.x] [Copilot] Check database upgrade tag to avoid emitting unnecessary telemetry for cross-geo switch

---

build/Packages.json

- Update app baselines package version. New value: 25.5.30849.32085

[26.0] Update app baselines package version. New value: 25.5.30849.32085

---

build/Packages.json

- Update app baselines package version. New value: 25.1.25873.32081

[25.2] Update app baselines package version. New value: 25.1.25873.32081

---

build/Packages.json

- Update app baselines package version. New value: 24.3.21374.32119

[24.4] Update app baselines package version. New value: 24.3.21374.32119

---

build/Packages.json

- Update app baselines package version. New value: 24.5.23489.32114

[24.x] Update app baselines package version. New value: 24.5.23489.32114

---

build/Packages.json

- Update app baselines package version. New value: 24.4.22295.32113

[24.5] Update app baselines package version. New value: 24.4.22295.32113

---

build/Packages.json

- Update translation package version. New value: 25.6.20250321.2

[25.x] Update translation package version. New value: 25.6.20250321.2

---

build/Packages.json

- Update app baselines package version. New value: 24.5.23489.32114

[25.0] Update app baselines package version. New value: 24.5.23489.32114

---

build/Packages.json

- Update app baselines package version. New value: 26.1.32102.0
- Update translation package version. New value: 27.0.20250324.2

[main] Update app baselines package version. New value: 26.1.32102.0 (+ 1 more update(s))

---

build/Packages.json

- Update app baselines package version. New value: 26.0.30643.32100
- Update translation package version. New value: 26.1.20250321.1

[26.x] Update app baselines package version. New value: 26.0.30643.32100 (+ 1 more update(s))

---

build/Packages.json

- Update app baselines package version. New value: 25.3.28755.32084

[25.4] Update app baselines package version. New value: 25.3.28755.32084

---

src/System Application/App/Permission Sets/src/xmlports/ImportPermissionSets.xmlport.al
src/System Application/Test/Permission Sets/src/PermissionImportExportTests.Codeunit.al

https://github.com/microsoft/BCApps/pull/3184 Importing Permissions with Overwrite Option
Fixes [AB#572384](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/572384)

[26.x] Importing Permissions with Overwrite Option

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 27.0.32215.0

[main] Update BCArtifact version. New value: 27.0.32215.0

---

src/Business Foundation/App/NoSeries/src/Setup/NoSeriesLines.Page.al
src/System Application/App/Extension Management/permissions/ExtensionManagementObjects.PermissionSet.al

small fix to cleanup
Fixes [AB#572491](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/572491)

fix preprocessor symbols

---

src/System Application/App/AppSource Gallery/src/AppSrcProductDepsProvider.Codeunit.al

Fixes [AB#545722](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/545722)

Update environment information test to include infrastructure.

---

.github/AL-Go-Settings.json
src/System Application/App/Performance Profiler/app.json
src/System Application/App/Performance Profiler/src/PerfProfileActivityType.enum.al
src/System Application/App/Performance Profiler/src/PerfProfilerScheduleCard.Page.al
src/System Application/App/Performance Profiler/src/PerfProfilerSchedulesList.Page.al
src/System Application/App/Performance Profiler/src/PerformanceProfileList.Page.al
src/System Application/App/Performance Profiler/src/ScheduledPerfProfilerImpl.Codeunit.al

Bunch of UX improvements:
needs to be open and approved. Submitting PRs with no linked issues or unapproved issues is highly discouraged. -->
Fixes
Fixes [AB#571991](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/571991)

[26.x] Profile schedules UX improvements

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 27.0.32337.0

[main] Update BCArtifact version. New value: 27.0.32337.0

---

src/Business Foundation/App/NoSeriesCopilot/src/Copilot/NoSeriesCopilotImpl.Codeunit.al
src/Business Foundation/App/NoSeriesCopilot/src/Copilot/NoSeriesExt.PageExt.al

Leverage IsCapabilityRegistered instead of IsSaaS to control visibility of Copilot action.
Fixes [AB#544937](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/544937)

Bug 544937: Copilot actions No. Series suggestions must all check if IsSaaS, IsCapabilityRegistered

---

.github/workflows/SubmitStabilityJobs.yaml
.github/workflows/UpdateBCArtifactVersion.yaml
.github/workflows/UpdatePackageVersions.yaml

Move automation scenarios to use GitHub App authentication instead of personal access tokens
Fixes [AB#572611](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/572611)

Switch to GitHub app authentication

---

CODEOWNERS

This pull request backports #3400 to releases/26.x
Fixes [AB#572904](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/572904)

[releases/26.x] Make Engineering Systems owner of app.json files

---

CODEOWNERS

This pull request backports #3400 to releases/25.x
Fixes [AB#572904](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/572904)

[releases/25.x] Make Engineering Systems owner of app.json files

---

CODEOWNERS

This pull request backports #3400 to releases/24.x
Fixes [AB#572904](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/572904)

[releases/24.x] Make Engineering Systems owner of app.json files

---

src/System Application/App/Cryptography Management/src/CryptographyManagementImpl.Codeunit.al

Simply use the right overload.
Fixes #3438
Fixes [AB#573418](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/573418)

Update SignData procedure to include RSASignaturePadding parameter

---

src/rulesets/ruleset.json

https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/appsourcecop-as0077 should only be enabled in release branches, as the rule only applies in hotfix scenarios.
Fixes [AB#568822](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/568822)

[26.x] Disable rule AS0077 in MAIN branch (#3201)

---

src/rulesets/ruleset.json

https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/appsourcecop-as0077 should only be enabled in release branches, as the rule only applies in hotfix scenarios.
Fixes[AB#568822](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/568822)

[25.x] Disable rule AS0077 in MAIN branch (#3201)

---

src/rulesets/ruleset.json

https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/appsourcecop-as0077 should only be enabled in release branches, as the rule only applies in hotfix scenarios.
Fixes [AB#568822](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/568822)

[24.x] Disable rule AS0077 in MAIN branch (#3201)

---

src/System Application/App/External File Storage/src/FileStorage/ExternalFileStorage.Codeunit.al
src/System Application/App/External File Storage/src/FileStorage/ExternalFileStorageImpl.Codeunit.al
src/System Application/App/External File Storage/src/Lookup/FileAccountBrowserMgt.Codeunit.al
src/System Application/App/External File Storage/src/Lookup/StorageBrowser.Page.al

Backport all changes from the External File Storage module's main branch for release with 26.1
Fixes [AB#567977](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/567977)

Backport changes from main branch.

---

src/System Application/App/Email/src/Email/Email.Codeunit.al

Backport of #3186 
Fixes [AB#572343](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/572343)

[26.x] Bug 572343: [26.x][BCApps #3186]Fixes #3034

---

src/System Application/App/AI/src/Azure OpenAI/AOAIAuthorization.Codeunit.al
src/System Application/App/AI/src/Azure OpenAI/AOAIDeploymentsImpl.Codeunit.al
src/System Application/App/AI/src/Azure OpenAI/AzureOpenAIImpl.Codeunit.al

__BACKPORT:__
Remove the allowlisting logic from the toolkit.
Fixes [AB#573846](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/573846)

[26.x][Copilot] Remove allowlisting logic for toolkit

---

src/System Application/App/Retention Policy/src/Retention Policy Setup/RetentionPolicySetupCard.Page.al

Add Caption for Group that this will be translated in the translation app.
Fixes #3485
Fixes [AB#573971](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/573971)

Caption for General Group on Retention Policy Setup Card

---

src/System Application/App/User Selection/src/UserLookup.Page.al

Fixes [[AB#566789](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/566789)]

[26.x] [Change Request] make UserLookUpPage extensible

---

src/System Application/App/User Selection/src/UserLookup.Page.al

Fixes  [[AB#566789](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/566789)]

[Change Request] Make UserLookUpPage extensible

---

src/System Application/App/Permission Sets/src/xmlports/ImportPermissionSets.xmlport.al
src/System Application/Test/Permission Sets/src/PermissionImportExportTests.Codeunit.al

Fixes [[AB#573207](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/573207)]

[Master] Include security filter when import permissionset from xml

---

src/System Application/App/AI/src/Azure OpenAI/AOAIAuthorization.Codeunit.al
src/System Application/App/AI/src/Azure OpenAI/AOAIDeploymentsImpl.Codeunit.al
src/System Application/App/AI/src/Azure OpenAI/AzureOpenAIImpl.Codeunit.al

This reverts commit bd9adcb9d2ed24ebc009ab974acd8c6933da7971.
We are not yet ready with the backend services to remove the allowlisting for the AI toolkit resources.
Fixes [AB#573846](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/573846)

[26.x] Revert removing allowlisting for AI toolkit

---

src/System Application/App/AI/src/Copilot/CopilotQuotaUsageType.Enum.al

Renaming Monetization option captions
Fixes [AB#572473](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/572473)

Renaming monetization captions

---

src/System Application/App/Upgrade Tags/src/UpgradeTags.Page.al

Add missing read permission
Fixes #3596
Fixes [AB#575545](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/575545)

[26.x] Add missing read permission for Upgrade Tags (#3331)

---

src/System Application/App/Upgrade Tags/src/UpgradeTags.Page.al

Add missing read permission
Fixes #3596
Fixes [AB#575546](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/575546)

[25.x] Add missing read permission for Upgrade Tags (#3331)

---

src/System Application/App/Azure Blob Services API/src/ABSContainerContent.Table.al
src/Tools/Performance Toolkit/App/src/BCPTLine.Table.al
src/Tools/Performance Toolkit/App/src/BCPTLogEntry.Table.al

remove old pragma
Fixes [AB#574355](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/574355)

remove AS0086 pragma

---

src/System Application/App/Language/src/LanguageImpl.Codeunit.al

This pull request backports #3658 to releases/26.1
Fixes [AB#575958](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/575958)

[releases/26.1] [Language] Revert LookupWindowsLanguageId change from #2463

---

src/System Application/App/Language/src/LanguageImpl.Codeunit.al

This pull request backports #3658 to releases/26.0
Fixes [AB#575957](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/575957)

[releases/26.0] [Language] Revert LookupWindowsLanguageId change from #2463

---

src/System Application/App/Language/src/LanguageImpl.Codeunit.al

This pull request backports #3658 to releases/26.x
Fixes [AB#575959](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/575959)

[releases/26.x] [Language] Revert LookupWindowsLanguageId change from #2463

---

src/System Application/App/Email/src/Account/EmailAccountWizard.Page.al

Add Edit Account action to Email Account Wizard.
Fixes [AB#547954](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/547954/)

[Email] Add Edit Account action to Email Account Wizard

---

src/Tools/AI Test Toolkit/src/AITTestRunInputHandler.Codeunit.al
src/Tools/AI Test Toolkit/src/AITTestRunIteration.Codeunit.al
src/Tools/AI Test Toolkit/src/Logs/AITLogEntries.Page.al
src/Tools/AI Test Toolkit/src/TestSuite/AITTestSuiteMgt.Codeunit.al

Add new action to rerun a test.
Fixes [AB#555686](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/555686)

[AI Test Tool] Add support to rerun a test

---

.github/Update AL-Go System Files.settings.json
.github/workflows/UpdateGitHubGoSystemFiles.yaml

Change Update AL-Go System files schedule

---

src/System Application/App/AI/src/Copilot/CopilotAICapabilities.Page.al

Add indirect permissions to the Copilot Settings table.
Fixes [AB#578671](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/578671)

[26.x][AI Toolkit] Copilot & agent capabilities page is missing the indirect read permissions for Copilot Settings

---

src/Business Foundation/App/AuditCodes/src/Legacy/ObsoleteReturnReasonExt.TableExt.al
src/Business Foundation/App/AuditCodes/src/Legacy/ObsoleteSourceCodeExt.TableExt.al
src/Business Foundation/App/AuditCodes/src/Legacy/ObsoleteSourceCodeSetupExt.TableExt.al
src/Business Foundation/App/AuditCodes/src/ReasonCode.Table.al
src/Business Foundation/App/AuditCodes/src/ReturnReason.Table.al
src/Business Foundation/App/AuditCodes/src/SourceCode.Table.al
src/Business Foundation/App/AuditCodes/src/SourceCodeSetup.Table.al
src/Business Foundation/App/NoSeries/src/GlobalNoSeries/NoSeriesTenant.Table.al
src/Business Foundation/App/NoSeries/src/Legacy/NoSeriesObsolete.TableExt.al
src/Business Foundation/App/NoSeries/src/Setup/NoSeries.Table.al
src/Business Foundation/App/NoSeries/src/Setup/NoSeriesLine.Table.al
src/Business Foundation/App/NoSeries/src/Setup/NoSeriesRelationship.Table.al

clean up MovedTo/MovedFrom with CLEANSCHEMA
Fixes [AB#578715](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/578715)

clean up MovedTo/MovedFrom with CLEANSCHEMA

---

src/rulesets/AppSourceCop.ruleset.json

Suppressing new AppSourceCop rules about additive changes.
Fixes [AB#573552](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/573552)

Suppress new rules AS0131, AS0132, AS0133

---

src/rulesets/AppSourceCop.ruleset.json

Suppressing new AppSourceCop rules about additive changes.
Fixes [AB#573552](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/573552)

[26.x] Suppress new rules AS0131, AS0132, AS0133

---

src/rulesets/AppSourceCop.ruleset.json

Suppressing new AppSourceCop rules about additive changes.
Fixes [AB#573552](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/573552)

[26.1] Suppress new rules AS0131, AS0132, AS0133

---

src/rulesets/AppSourceCop.ruleset.json

Suppressing new AppSourceCop rules about additive changes.
Fixes [AB#573552](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/573552)

[26.0] Suppress new rules AS0131, AS0132, AS0133

---

.github/AL-Go-Settings.json

Exclude Test Next Major.settings.json and Test Next Minor.settings.json from the AL-Go updates.
These files are not used.

Exclude Test Next Major.settings.json and Test Next Minor.settings.json

---

src/System Application/App/Email/src/Account/EmailAccounts.Page.al

Adds that you can filter down on V3 accounts only.
Fixes [AB#578780](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/578780)

Allow filter to only V3 Email accounts. 

---

src/System Application/App/AppSource Gallery/src/AppSourceProductDetails.Page.al

This pull request backports #3805 to releases/26.x
Fixes [AB#579933](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/579933)

[releases/26.x] [Appsource] Fix currency values formatting for Appsource Apps plans

---

src/System Application/App/AI/src/Azure OpenAI/AOAIAuthorization.Codeunit.al
src/System Application/App/AI/src/Azure OpenAI/AOAIDeploymentsImpl.Codeunit.al
src/System Application/App/AI/src/Azure OpenAI/AzureOpenAIImpl.Codeunit.al

Remove the allowlisting logic from the toolkit. We target next minor update with these changes.
This is a cherry-pick of the previously reverted changes.
Fixes [AB#573846](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/573846)

[26.x] Remove allowlisting for AI resources (2)

---

src/System Application/App/AppSource Gallery/src/AppSourceProductDetails.Page.al

This pull request backports #3805 to releases/26.1
Fixes [AB#580008](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/580008)

[releases/26.1] [Appsource] Fix currency values formatting for Appsource Apps plans

---

src/System Application/App/AppSource Gallery/src/AppSourceProductDetails.Page.al

This pull request backports #3805 to releases/26.0
Fixes [AB#580009](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/580009)

[releases/26.0] [Appsource] Fix currency values formatting for Appsource Apps plans

---

src/System Application/App/Agent/Interaction/AgentTaskImpl.Codeunit.al
src/System Application/App/Agent/TaskPane/AgentTaskDetails.Page.al
src/System Application/App/Agent/TaskPane/AgentTaskTimeline.Page.al
src/System Application/App/Agent/TaskPane/AgentTasks.Page.al

Fixes
[AB#579777](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/579777)
[AB#579778](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/579778)

Add support for agent suggestions and free text instructions in the agent task pane

---

src/Business Foundation/App/NoSeriesCopilot/src/Copilot/NoSeriesCopilotImpl.Codeunit.al
src/System Application/App/AI/src/Azure OpenAI/AOAIDeployments.Codeunit.al
src/System Application/App/AI/src/Azure OpenAI/AOAIDeploymentsImpl.Codeunit.al
src/System Application/App/Entity Text/src/EntityTextImpl.Codeunit.al

This pull request backports #3924 to releases/26.x
Fixes [AB#580889](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/580889)

[releases/26.x] [AI] Add GPT41 and GPT41 mini to AOAI deployments

---

src/System Application/App/AI/src/Azure OpenAI/AOAIAuthorization.Codeunit.al
src/System Application/App/AI/src/Azure OpenAI/AOAIDeploymentsImpl.Codeunit.al
src/System Application/App/AI/src/Azure OpenAI/AzureOpenAIImpl.Codeunit.al

We are ready to open up for Public Preview.
Fixes [AB#581214](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/581214)

[26.2] Remove allowlisting for Toolkit AI Resources

---

src/System Application/Test/Email/src/EmailRetryTest.Codeunit.al

Change the name of the permission set in tests
Fixes  [AB#581462](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/581462)

[Email Retry] Change the name of the permission set in tests

---

.github/AL-Go-Settings.json
src/System Application/App/ActivityLog/app.json
src/System Application/App/ActivityLog/src/ActivityLogBuilder.Codeunit.al
src/System Application/App/ActivityLog/src/ActivityLogBuilderImpl.Codeunit.al
src/System Application/App/DotNet Aliases/src/dotnet.al

Fixes [AB#578938](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/578938)

Backport activity Log to 26.i

---

src/System Application/App/Email/src/Account/EmailAccounts.Page.al
src/System Application/Test/Email/src/EmailAccountsTest.Codeunit.al
src/System Application/Test/Email/src/EmailRetryTest.Codeunit.al

Fixes [AB#581394](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/581394)

[26.x]Add more tests for email scenarios

---

src/System Application/App/ActivityLog/src/ActivityLogBuilder.Codeunit.al
src/System Application/App/ActivityLog/src/ActivityLogBuilderImpl.Codeunit.al
src/System Application/App/ActivityLog/src/ActivityLogType.Enum.al

Adds the type to activity log. Controls UI
Fixes [AB#578938](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/578938)

Uptake Type in Activity Log

---

src/System Application/App/Email/src/RateLimit/EmailRateLimitImpl.Codeunit.al
src/System Application/Test/Email/src/EmailRetryTest.Codeunit.al

Fixes [AB#582364](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/582364)

[26.3] [Email Retry] Fix concurrency issues

---

src/System Application/App/Email/src/RateLimit/EmailRateLimitImpl.Codeunit.al
src/System Application/Test/Email/src/EmailRetryTest.Codeunit.al

Fixes [AB#582364](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/582364)

[26.x] [Email Retry] Fix concurrency issues

---

src/System Application/App/Email/src/RateLimit/EmailRateLimitImpl.Codeunit.al
src/System Application/Test/Email/src/EmailRetryTest.Codeunit.al

Fixes [AB#582364](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/582364)

[Email] Fix concurrency issues

---

.github/workflows/CICD.yaml
.github/workflows/PullRequestHandler.yaml
build/projects/Apps (W1)/.AL-Go/settings.json

Update AL-Go System Files 

---

src/System Application/App/Language/src/AllowedLanguage.Table.al
src/System Application/App/Language/src/LanguageImpl.Codeunit.al

This pull request backports #4042 to releases/26.0
Fixes [AB#591237](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/591237)

[releases/26.0] [Languages] Show all Windows Languages if no Allowed Languages are configured

---

src/System Application/App/Language/src/AllowedLanguage.Table.al
src/System Application/App/Language/src/LanguageImpl.Codeunit.al

This pull request backports #4042 to releases/26.x
Fixes [AB#591241](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/591241)

[releases/26.x] [Languages] Show all Windows Languages if no Allowed Languages are configured

---

src/System Application/App/User Permissions/src/UserPermissionsImpl.Codeunit.al
src/System Application/Test/User Permissions/src/UserPermissionsTest.Codeunit.al

Fixes [AB#579026](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/579026)

[Permission] Exclude Security Group when delete SUPER 

---

src/System Application/App/Word Templates/src/WordTemplateField.Table.al
src/System Application/App/Word Templates/src/WordTemplatesTable.Table.al

Request from ALAppExtensions - https://github.com/microsoft/ALAppExtensions/issues/28810
Fixes [AB#582288](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/582288)

[Word Templates] Change table access from internal to public

---

src/System Application/App/User Permissions/src/UserPermissionsImpl.Codeunit.al
src/System Application/Test/User Permissions/src/UserPermissionsTest.Codeunit.al

Fixes [AB#579026](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/579026)

[26.x] [Permission] Keep at least one real Super admin excluding Security Group

---

src/System Application/App/Word Templates/src/WordTemplateField.Table.al
src/System Application/App/Word Templates/src/WordTemplatesTable.Table.al

This pull request backports #4079 to releases/26.x
Fixes [AB#591542](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/591542)

[releases/26.x] [Word Templates] Change table access from internal to public

---

src/System Application/App/Agent/TaskPane/AgentTaskDetails.Page.al
src/System Application/App/Agent/TaskPane/AgentTaskTimeline.Page.al
src/System Application/App/Agent/TaskPane/AgentTasks.Page.al

Fix encoding used when reading blob contents in agent timeline pages.
[AB#581902](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/581902)
[AB#581761](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/581761)

Fix encoding when reading blobs in agent timeline pages

---

src/Tools/AI Test Toolkit/src/Evaluation/AITColumnMapping.Table.al
src/Tools/AI Test Toolkit/src/Evaluation/AITEvaluator.Table.al

Do not replicate evaluators and column mappings.
Fixes [AB#591730](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/591730/)

[AI Test Tool] Do not replicate evaluators

---

src/Business Foundation/App/NoSeriesCopilot/src/Copilot/NoSeriesCopilotImpl.Codeunit.al
src/System Application/App/AI/src/Azure OpenAI/AOAIDeployments.Codeunit.al
src/System Application/App/AI/src/Azure OpenAI/AOAIDeploymentsImpl.Codeunit.al
src/System Application/App/Entity Text/src/EntityTextImpl.Codeunit.al

On 15-July we are switching to GPT model 4.1. 
Fixes [AB#581507](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/581507)

[26.3] Update GPT4o to GPT41

---

src/System Application/App/Email/src/Account/EmailAccounts.Page.al
src/System Application/App/Email/src/Email/EmailDispatcher.Codeunit.al
src/System Application/App/Email/src/Email/EmailImpl.Codeunit.al
src/System Application/App/Email/src/Email/EmailRetryDetail.Page.al
src/System Application/App/Email/src/Email/Outbox/EmailOutbox.Page.al
src/System Application/App/Email/src/Email/Outbox/EmailOutbox.Table.al
src/System Application/App/Email/src/Email/Sent/SentEmails.Page.al
src/System Application/App/Email/src/RateLimit/EmailRateLimit.Table.al
src/System Application/App/Email/src/RateLimit/EmailRateLimitImpl.Codeunit.al
src/System Application/App/Email/src/RateLimit/EmailRateLimitWizard.Page.al
src/System Application/Test/Email/src/EmailAccountsTest.Codeunit.al
src/System Application/Test/Email/src/EmailRetryTest.Codeunit.al

Improve the UX. Support customize the max attempt count Add more tests
Fixes
[AB#582584](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/582584)
---------
Fixes #

[26.x] Enable email retry with customized setting up (#4082)

---

src/Business Foundation/App/NoSeriesCopilot/src/Copilot/NoSeriesCopilotImpl.Codeunit.al
src/System Application/App/Entity Text/src/EntityTextImpl.Codeunit.al

Fixes # [AB#581507](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/581507)

[26.2] Remove references to GetGPT4oLatest

---

src/Business Foundation/App/NoSeriesCopilot/src/Copilot/NoSeriesCopilotImpl.Codeunit.al
src/System Application/App/Entity Text/src/EntityTextImpl.Codeunit.al

Fixes # [AB#581507](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/581507)

[26.0] Remove references to GetGPT4oLatest

---

src/Business Foundation/App/NoSeriesCopilot/src/Copilot/NoSeriesCopilotImpl.Codeunit.al
src/System Application/App/Entity Text/src/EntityTextImpl.Codeunit.al

Fixes # [AB#581507](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/581507)

[26.1] Remove references to GetGPT4oLatest

---

src/Tools/AI Test Toolkit/src/TestSuite/AITTestSuiteImportExport.XmlPort.al

Skip evaluators that are already inserted to avoid install issues.
Fixes [AB#592367](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/592367)

 [AI Test Tool] Skip evaluators that are already inserted

---

src/System Application/App/Email/src/Email/EmailDispatcher.Codeunit.al
src/System Application/App/Email/src/EmailUpgrade.Codeunit.al
src/System Application/App/Email/src/RateLimit/EmailRateLimitImpl.Codeunit.al

Add the upgrade code to set default value to the Concurrency limit
Fixes [AB#592800](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/592800)

[26.3] Add upgrade code for email concurrency limit

---

src/System Application/App/Email/src/EmailUpgrade.Codeunit.al
src/System Application/App/Email/src/RateLimit/EmailRateLimitImpl.Codeunit.al

Add the upgrade code to set default value to the Concurrency limit
Fixes [AB#592801](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/592801)

[26.x] Add upgrade code for email concurrency limit

---

src/System Application/App/Email/src/EmailUpgrade.Codeunit.al
src/System Application/App/Email/src/RateLimit/EmailRateLimitImpl.Codeunit.al

Add the upgrade code to set default value to the Concurrency limit
Fixes [AB#592799](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/592799)

[main]Add upgrade code for email concurrency limit

---

src/System Application/App/Email/src/EmailUpgrade.Codeunit.al

Fixes [AB#592799](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/592799)

[26.x]Improve upgrade logic for email concurrency limit

---

src/System Application/App/User Settings/src/UserSettings.Page.al
src/System Application/App/User Settings/src/UserSettingsImpl.Codeunit.al

This pull request backports #2165 to releases/25.5
Fixes [AB#593206](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/593206/)

[releases/25.5] [CES] Remove modern action bar survey

---

src/System Application/App/User Settings/src/UserSettings.Page.al
src/System Application/App/User Settings/src/UserSettingsImpl.Codeunit.al

This pull request backports #2165 to releases/25.4
Fixes [AB#593205](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/593205/)

[releases/25.4] [CES] Remove modern action bar survey

---

src/System Application/App/User Settings/src/UserSettings.Page.al
src/System Application/App/User Settings/src/UserSettingsImpl.Codeunit.al

This pull request backports #2165 to releases/25.3
Fixes [AB#593204](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/593204/)

[releases/25.3] [CES] Remove modern action bar survey

---

src/System Application/App/User Settings/src/UserSettings.Page.al
src/System Application/App/User Settings/src/UserSettingsImpl.Codeunit.al

This pull request backports #2165 to releases/25.0
Fixes [AB#593201](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/593201/)

[releases/25.0] [CES] Remove modern action bar survey

---

src/System Application/App/User Settings/src/UserSettings.Page.al
src/System Application/App/User Settings/src/UserSettingsImpl.Codeunit.al

This pull request backports #2165 to releases/24.x
Fixes [AB#593200](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/593200/)

[releases/24.x] [CES] Remove modern action bar survey

---

build/scripts/GuardingV2ExtensionsHelper.psm1

We ran into an issue where the baseline app (needed by AppSourceCop) had an dependency to an app that the current version of the app doesn't. 
`Error: AS0091 One or more dependencies of the previous version of the extension could not be found in the baseline package cache folder. Details: error AL1022: A package with publisher 'Microsoft', name 'E-Document Connector - Pagero', and a version compatible with '26.4.0.0' could not be found in the package cache folders: c:\shared\build\projects\Apps (W1)\.packages`
The proposed solution is to copy all baseline app symbols into the baselines folder so that those dependencies can be resolved. 
Fixes [AB#593436](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/593436)

Get all app symbols when gathering baselines

---

.azuredevops/SyncMirroredRepository.yml

Consolidate Hosted Pools
Related to [AB#593722](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/593722)
[AB#591705](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/591705)

Hosted Pools Consolidation

---

src/Apps/W1/Shopify/App/src/Base/Pages/ShpfyShopCard.Page.al
src/Apps/W1/Shopify/App/src/Base/Tables/ShpfyShop.Table.al
src/Apps/W1/Shopify/App/src/Order Return Refund Processing/Codeunits/ShpfyCreateSalesDocRefund.Codeunit.al
src/Apps/W1/Shopify/App/src/Order handling/Codeunits/ShpfyProcessOrder.Codeunit.al

Add new setting Cash Roundings Account and create rounding lines to that account
Fixes [AB#592060](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/592060)

[Shopify] Add new setting Cash Roundings Account and create rounding lines to that account

---

.azuredevops/SyncMirroredRepository.yml

This pull request backports #4307 to releases/26.4

[releases/26.4] Hosted Pools Consolidation

---

.azuredevops/SyncMirroredRepository.yml

This pull request backports #4307 to releases/26.3

[releases/26.3] Hosted Pools Consolidation

---

.azuredevops/SyncMirroredRepository.yml

This pull request backports #4307 to releases/26.2

[releases/26.2] Hosted Pools Consolidation

---

.azuredevops/SyncMirroredRepository.yml

This pull request backports #4307 to releases/26.0

[releases/26.0] Hosted Pools Consolidation

---

.azuredevops/SyncMirroredRepository.yml

This pull request backports #4307 to releases/26.x

[releases/26.x] Hosted Pools Consolidation

---

.azuredevops/SyncMirroredRepository.yml

This pull request backports #4307 to releases/25.5

[releases/25.5] Hosted Pools Consolidation

---

.azuredevops/SyncMirroredRepository.yml

This pull request backports #4307 to releases/25.4

[releases/25.4] Hosted Pools Consolidation

---

.azuredevops/SyncMirroredRepository.yml

This pull request backports #4307 to releases/25.1

[releases/25.1] Hosted Pools Consolidation

---

.azuredevops/SyncMirroredRepository.yml

This pull request backports #4307 to releases/24.x

[releases/24.x] Hosted Pools Consolidation

---

.azuredevops/SyncMirroredRepository.yml

This pull request backports #4307 to releases/24.5

[releases/24.5] Hosted Pools Consolidation

---

src/Apps/W1/Shopify/App/src/Base/Codeunits/ShpfyUpgradeMgt.Codeunit.al
src/Apps/W1/Shopify/App/src/Base/Pages/ShpfyShopCard.Page.al
src/Apps/W1/Shopify/App/src/Base/Tables/ShpfyShop.Table.al
src/Apps/W1/Shopify/App/src/Order handling/Codeunits/ShpfyImportOrder.Codeunit.al
src/Apps/W1/Shopify/App/src/Order handling/Pages/ShpfyOrderTotalsFactBox.Page.al

Add new setting Archive Processed Orders
Fixes [AB#593841](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/593841)

[Shopify] Add new setting Archive Processed Orders

---

src/System Application/App/Performance Profiler/src/ScheduledPerfProfilerImpl.Codeunit.al

This pull request backports #4342 to releases/26.3
Fixes [AB#595907](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/595907)

[releases/26.3] Add indirect permissions to ScheduledPerfProfilerImpl codeunit

---

build/scripts/PullRequestValidation/ValidateIssuesForPullRequest.ps1

Skip issue validation if AB workitem is linked
Fixes [AB#596003](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/596003)

Skip issue validation if AB workitem is linked

---

src/Apps/W1/Shopify/App/src/Base/Codeunits/ShpfyCommunicationMgt.Codeunit.al
src/Apps/W1/Shopify/App/src/Base/Pages/ShpfyConnectorGuide.Page.al
src/Apps/W1/Shopify/App/src/Base/Tables/ShpfyShop.Table.al
src/Apps/W1/Shopify/App/src/Integration/Codeunits/ShpfyAuthenticationMgt.Codeunit.al

Safeguard requests by checking Shop URL validity for every call
Fixes [AB#595990](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/595990)

[Shopify] Safeguard requests by checking Shop URL validity for every call

---

.github/AL-Go-Settings.json
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml

Switch to Windows Server 2025 images before GitHub switches windows-latest to 2025 images. Once GitHub is done rolling out WS 2025 on windows-latest (end of September) we should switch back to windows-latest again. 
Can only be merged after #4398
Related to [AB#596461](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/596461)

Switch to Windows Server 2025 images

---

src/rulesets/ruleset.json

Prepare for uptake of platform with new AppSourceCop rules.
Fixes [AB#595767](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/595767)

[AppSourceCop] Prepare rulesets for new AppSourceCop rules

---

src/System Application/App/Email/permissions/EmailObjects.PermissionSet.al
src/System Application/App/Email/src/Email/EmailRetryImpl.Codeunit.al

Set InherentPermissions / InherentEntitlements for codeunit "Email Retry Impl." since this is an internal implementation codeunit.
Fixes #4402
Fixes [AB#596632](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/596632)

Set InherentPermissions / InherentEntitlements for codeunit "Email Retry Impl."

---

src/Apps/W1/Shopify/App/src/Integration/Codeunits/ShpfyAuthenticationMgt.Codeunit.al
src/Apps/W1/Shopify/Test/Base/ShpfyInitializeTest.Codeunit.al

Remove unnecessary scope write_companies
Fixes [AB#596435](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/596435)

[Shopify] Remove unnecessary scope write_companies

---

src/System Application/App/Email/src/Email/EmailRetryImpl.Codeunit.al
src/System Application/Test/Email/src/EmailRetryTest.Codeunit.al

This pull request backports #4392 to releases/26.4
Fixes [AB#596426](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/596426)

[releases/26.4] Add proper permission to email dispatcher

---

src/Apps/W1/Shopify/App/src/Order handling/Codeunits/ShpfyCopySalesDocument.Codeunit.al

Right now we have two codeunits with the same object ID. Updating one of them to get the CICD working again
Fixes [AB#596980](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/596980)

Update duplicate object ID in Shopify

---

src/Apps/W1/Subscription Billing/App/app.json

We should use a new forward link as the old points to Shopify connector documentation 
Fixes #
Work Item(s)
Fixes [AB#592948](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/575790/)

update forward link

---

src/System Application/App/Json/app.json
src/System Application/Test Library/AppSource Gallery/app.json
src/System Application/Test/Json/app.json

Update platform property on select apps so they have the same platform version as all the other apps in the branch. 
Fixes [AB#598009](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/598009)

Update platform property on select apps

---

src/Apps/W1/Shopify/App/src/Base/Pages/ShpfyShopCard.Page.al
src/Apps/W1/Shopify/App/src/Customers/Pages/ShpfyCustomerTemplates.Page.al
src/Apps/W1/Shopify/App/src/Customers/Tables/ShpfyCustomerTemplate.Table.al

Better caption for customer templates page
Fixes [AB#596281](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/596281)

[Shopify] Better caption for customer templates page

---

src/System Application/App/Agent/Interaction/Internal/AgentTaskLogEntryList.Page.al

Adding a Refresh action in the Agent Task Log Entries page.
Fixes [AB#597914](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/597914)

[Agent] Add 'Refresh' action to agent task log entries

---

src/System Application/App/Agent/Setup/AgentCard.Page.al

Align with the User Card and use the terms Active/Inactive in the tooltips.
Fixes [AB#597194](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/597194)

[Agent] Use Active/Inactive instead of Enabled/Disabled in AgentCard tooltip

---

build/scripts/AppExtensionsHelper.psm1
src/Apps/W1/Shopify/App/src/Catalogs/Pages/ShpfyMarketCatalogs.Page.al

Update app.json properties with props from included Directory.App.Props.json
Fixes [AB#598707](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/598707)

Update app.json properties with props from included Directory.App.Props.json

---

build/scripts/AppExtensionsHelper.psm1

This pull request backports #4559 to releases/27.x
Fixes [AB#598707](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/598707)

[releases/27.x] Update app.json properties with props from included Directory.App.Props.json

---

.github/AL-Go-Settings.json

Add CLEAN28 to AL-Go-Settings.json
Related to [AB#597870](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/597870)

[27.x] Add CLEAN28 to AL-Go-Settings.json

---

src/System Application/App/Agent/Setup/SelectAgentAccessControl.Page.al

Added a filter for the users in the selector used from setup pages too.
Fixes [AB#597109](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/597109)

Agent Access Control - Filter to relevant users only

---

src/System Application/App/Agent/Setup/Agent.Codeunit.al
src/System Application/App/Agent/Setup/AgentCard.Page.al
src/System Application/App/Agent/Setup/AgentImpl.Codeunit.al
src/System Application/App/Agent/Setup/AgentUserSettings.Page.al

Adding support for selecting the language from the agent setup card
Fixes [AB#596383](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/596383)

Agents - Implementing the support for region and language

---

src/System Application/App/Agent/Setup/Agent.Codeunit.al
src/System Application/App/Agent/Setup/AgentCard.Page.al
src/System Application/App/Agent/Setup/AgentImpl.Codeunit.al
src/System Application/App/Agent/Setup/AgentUserSettings.Page.al

Adding support for selecting the language from the agent setup card
Fixes [AB#596383](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/596383)

[27.x] Agents - Implementing the support for region and language

---

src/Apps/W1/Shopify/App/src/GraphQL/Codeunits/ShpfyGQLRefundHeader.Codeunit.al
src/Apps/W1/Shopify/App/src/Order Refunds/Codeunits/ShpfyRefundsAPI.Codeunit.al
src/Apps/W1/Shopify/App/src/Order Return Refund Processing/Codeunits/ShpfyCreateSalesDocRefund.Codeunit.al
src/Apps/W1/Shopify/App/src/Order handling/Codeunits/ShpfyOrderMapping.Codeunit.al
src/Apps/W1/Shopify/App/src/Products/Codeunits/ShpfyProductImport.Codeunit.al
src/Apps/W1/Shopify/App/src/Transactions/Tables/ShpfyOrderTransaction.Table.al
src/Apps/W1/Shopify/Test/Order Refunds/ShpfyOrderRefundTest.Codeunit.al

- Add comment line with order info to sales credit memos if setting is enabled
- Fix error when creating unknown item with order sync
- Correct shipping cost account on refunds
- Add testfield for all types of GL accounts
- Introducing payment method mapping for sales credit memos
Fixes [AB#598878](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/598878)
Fixes [AB#598903](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/598903)
Fixes [AB#598886](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/598886)
Fixes [AB#598880](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/598880)
Fixes …

[Shopify] Refund processing improvements

---

src/Apps/W1/Shopify/App/src/Base/Page Extensions/ShpfyBusinessManagerRC.PageExt.al
src/Apps/W1/Shopify/App/src/Order handling/Pages/ShpfyOrders.Page.al

Remove confusing filter and add views instead to orders page
Fixes [AB#599009](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/599009)

[Shopify] Remove confusing filter and add views instead to orders page

---

src/Apps/W1/Shopify/App/src/GraphQL/Codeunits/ShpfyGQLRefundHeader.Codeunit.al
src/Apps/W1/Shopify/App/src/Order Refunds/Codeunits/ShpfyRefundsAPI.Codeunit.al
src/Apps/W1/Shopify/App/src/Order Return Refund Processing/Codeunits/ShpfyCreateSalesDocRefund.Codeunit.al
src/Apps/W1/Shopify/App/src/Order handling/Codeunits/ShpfyOrderMapping.Codeunit.al
src/Apps/W1/Shopify/App/src/Products/Codeunits/ShpfyProductImport.Codeunit.al
src/Apps/W1/Shopify/App/src/Transactions/Tables/ShpfyOrderTransaction.Table.al
src/Apps/W1/Shopify/Test/Order Refunds/ShpfyOrderRefundTest.Codeunit.al

This pull request backports #4617 to releases/27.0
Fixes [AB#599062](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/599062)

[releases/27.0] [Shopify] Refund processing improvements

---

src/System Application/App/AI/src/Copilot/CopilotCapabilityInstall.Codeunit.al
src/System Application/App/AI/src/Copilot/CopilotCapabilityUpgrade.Codeunit.al

Fixes
[AB#571288](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/571288)

[Backport 27x][Copilot] GA Analyze List (#4692)

---

src/Apps/W1/Shopify/App/src/Companies/Codeunits/ShpfyCompanyImport.Codeunit.al

Do not delete existing companies during import
Fixes [AB#600740](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/600740)

[Shopify] Do not delete existing companies during import

---

src/System Application/App/Agent/Interaction/AgentTaskMessageBuilder.Codeunit.al
src/System Application/App/Agent/Interaction/Internal/AgentTaskMsgBuilderImpl.Codeunit.al

Allow attachments to be marked as ignored #
[AB#562490](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/562490)

Allow attachments to be marked as ignored

---

src/System Application/App/Agent/Interaction/AgentTaskMessageBuilder.Codeunit.al
src/System Application/App/Agent/Interaction/Internal/AgentTaskMsgBuilderImpl.Codeunit.al

Allow attachments to be marked as ignored #
[AB#562490](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/562490)
---------
Fixes #

Allow attachments to be marked as ignored (#4701)

---

src/System Application/App/Agent/Interaction/Internal/AgentTaskList.Page.al

Make "Steps" field in Agent Tasks not editable
Fixes [AB#598859](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/598859)

[Agent] Make Agent Tasks page non-editable

---

src/Apps/W1/Shopify/App/src/Order Fulfillments/Pages/ShpfyOrderFulfillment.Page.al
src/Apps/W1/Shopify/App/src/Order Fulfillments/Pages/ShpfyOrderFulfillments.Page.al
src/Apps/W1/Shopify/App/src/Order Fulfillments/Tables/ShpfyFulFillmentOrderLine.Table.al
src/Apps/W1/Shopify/App/src/Order handling/Page Extensions/ShpfyPostSalesShipments.PageExt.al
src/Apps/W1/Shopify/App/src/Order handling/Pages/ShpfyOrder.Page.al

UX improvements
Fixes [AB#603149](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/603149)
Fixes [AB#603159](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/603159)
Fixes [AB#603158](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/603158)

[Shopify] UX improvements

---

src/Apps/W1/Shopify/App/src/Base/Codeunits/ShpfyBackgroundSyncs.Codeunit.al

Wrong id on report dispute sync
Fixes [AB#602783](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/602783)

[Shopify] Wrong id on report dispute sync

---

src/Apps/W1/Shopify/App/src/Base/Pages/ShpfyActivities.Page.al
src/Apps/W1/Shopify/App/src/Base/Tables/ShpfyCue.Table.al

Add missing sync jobs to cue
Fixes [AB#602791](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/602791)

[Shopify] Add missing sync jobs to cue

---

src/Apps/W1/EDocumentConnectors/ForNAV/Test/app.json
src/Apps/W1/EDocumentConnectors/ForNAV/Test/src/IntegrationTests.Codeunit.al
src/Apps/W1/EDocumentConnectors/ForNAV/Test/src/PeppolTest.Codeunit.al

Moves test codeunit to correct range.
Fixes [AB#574584](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/574584)

ForNAV corrections

---

.azuredevops/SyncMirroredRepository.yml

Refine branch patterns in SyncMirroredRepository.yml to avoid syncing old unsupported branches 
Fixes [AB#604128](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/604128)

Refine branch patterns in SyncMirroredRepository.yml

---

src/System Application/App/Email/src/Email/EmailDispatcher.Codeunit.al

This pull request backports #4387 to releases/26.4
Fixes [AB#595997](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/595997)

[releases/26.4] [main] add jitter for reschedule email

---

src/System Application/App/MCP/src/Configuration/Codeunits/MCPConfigImplementation.Codeunit.al
src/System Application/App/MCP/src/Configuration/Pages/MCPConfigCard.Page.al

Add telemetry to configuration module
Fixes [AB#608016](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/608016)

[MCP] Add telemetry to configuration module

---

src/System Application/Test/Extension Management/src/DataverseTableBuilderTest.Codeunit.al

Unpublish extension as part of the cleanup
Fixes [AB#608399](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/608399)

[Dataverse] Unpublish extension as part of the cleanup

---

src/System Application/App/Agent/Interaction/AgentMessage.Codeunit.al
src/System Application/App/Agent/Interaction/AgentTask.Codeunit.al
src/System Application/App/Agent/Interaction/Internal/AgentMessageImpl.Codeunit.al
src/System Application/App/Agent/Interaction/Internal/AgentTaskMessageList.Page.al
src/System Application/App/Agent/Setup/Agent.Codeunit.al
src/System Application/App/Agent/Setup/AgentCard.Page.al
src/System Application/App/Agent/Setup/AgentImpl.Codeunit.al
src/System Application/App/Agent/Setup/AgentUserSettings.Page.al
src/System Application/App/Agent/TaskPane/AgentTaskTimeline.Page.al
src/System Application/App/User Settings/src/UserSettings.Codeunit.al

Backport of these commits:
https://github.com/microsoft/BCApps/commit/6ffe0e00ef1356387ede539f56f32faf48be9ad7
https://github.com/microsoft/BCApps/commit/31f9eef74fe6f13d5f10f1a6b5849c56fcaa0aad
Fixes [AB#605664](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/605664)

[27.x] Backport agent profile utility changes

---

src/Apps/W1/Shopify/App/src/Base/Codeunits/ShpfyBackgroundSyncs.Codeunit.al

This pull request backports #4758 to releases/27.x

[releases/27.x] [Shopify] Wrong id on report dispute sync

---

src/Apps/W1/Shopify/App/src/Companies/Codeunits/ShpfyCompanyImport.Codeunit.al

This pull request backports #4700 to releases/27.x

[releases/27.x] [Shopify] Do not delete existing companies during import

---

src/Apps/W1/Shopify/App/src/Order Return Refund Processing/Page Extensions/ShpfyPostedSalesCrMemos.PageExt.al
src/Apps/W1/Shopify/App/src/Order Return Refund Processing/Page Extensions/ShpfySalesCreditMemos.PageExt.al
src/Apps/W1/Shopify/App/src/Order handling/Page Extensions/ShpfyPostedSalesInvoices.PageExt.al
src/Apps/W1/Shopify/App/src/Order handling/Page Extensions/ShpfySalesInvoiceList.PageExt.al
src/Apps/W1/Shopify/App/src/Order handling/Page Extensions/ShpfySalesOrderList.PageExt.al

This pull request backports #4670 to releases/27.x

[releases/27.x] [Shopify] Add new Shopify views to sales document lists

---

src/Apps/W1/Shopify/App/src/Order handling/Tables/ShpfyOrdersToImport.Table.al

This pull request backports #4582 to releases/27.x

[releases/27.x] [Shopify] Add non restrictive table relation to Sales Channel from Orders to Import

---

src/System Application/App/ActivityLog/src/ActivityLogBuilderImpl.Codeunit.al

Use bookmark instead of filters
Fixes [AB#602504](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/602504)

Use bookmark when creating activity log links

---

src/System Application/App/Agent/Interaction/AgentTask.Codeunit.al
src/System Application/App/Agent/Interaction/AgentTasks.Codeunit.al
src/System Application/App/Agent/TaskPane/AgentTaskDetails.Page.al
src/System Application/App/Agent/TaskPane/AgentTaskTimeline.Page.al
src/System Application/App/Agent/TaskPane/AgentTasks.Page.al

Fixes [AB#606011](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/606011)

Prepare for move of TaskPane objects to Platform symbols

---

src/Apps/W1/PowerBIReports/App/Core/RoleCenterExtensions/ManufacturingManagerRC.PageExt.al
src/Apps/W1/PowerBIReports/App/Core/RoleCenterExtensions/ProductionPlannerRoleCenter.PageExt.al

Fixes [AB#609027](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/609027)

Update PowerBI reports MFG Role Center extensions with AL0432

---

src/System Application/App/MCP/src/Configuration/Codeunits/MCPConfigImplementation.Codeunit.al

Validate non v2.0 standard APIs
Fixes [AB#605567](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/605567)

[MCP] Validate non v2.0 standard APIs

---

src/System Application/Test/Extension Management/src/DataverseTableBuilderTest.Codeunit.al

Uninstall all versions of table builder extension
Fixes [AB#608399](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/608399)

[Dataverse] Uninstall all versions of table builder extension

---

src/Apps/W1/Shopify/App/src/Order handling/Codeunits/ShpfyOrders.Codeunit.al
src/Apps/W1/Shopify/App/src/Order handling/Pages/ShpfyCancelOrder.Page.al
src/Apps/W1/Shopify/App/src/Order handling/Pages/ShpfyOrder.Page.al
src/Apps/W1/Shopify/App/src/PermissionSets/ShpfyObjects.PermissionSet.al

Introduce public facing facade for order management
Fixes #4630
Fixes [AB#575129](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/575129)

[Shopify] Introduce public facing facade for order management

---

src/Apps/W1/Subscription Billing/App/Customer Contracts/Tables/CustomerSubscriptionContract.Table.al
src/Apps/W1/Subscription Billing/App/Import/Tables/ImportedCustSubContract.Table.al

- Ensures that newly created records have the correct default values set automatically.
- Reduces user confusion and prevents missing/incorrect defaults during data entry.
Fixes #4871
Fixes [AB#608986](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/608986)

Init Value for Customer Contracts (#4873)

---

src/Apps/W1/Shopify/App/src/GraphQL/Codeunits/ShpfyGQLPayouts.Codeunit.al

Add missing currencyCode in retriedPayoutsGross node
Fixes [AB#608935](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/608935)

[Shopify] Add missing currencyCode in retriedPayoutsGross node

---

src/Apps/W1/PowerBIReports/Test/E2EPowerBIManufacturingTest.Codeunit.al

Fixes [AB#609027](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/609027)

Update PowerBIReports test with AL0801

---

src/Apps/W1/EDocument/App/src/Processing/EDocImport.Codeunit.al

Use ref no, if no product code no. 
PEPPOL and other formats can send in selleritemidentifier which is ref no, and standarditemidentifier which is No. 
Fixes [AB#609230](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/609230)

E-Document Copy From Purchase Line V1 - Minor improvement. 

---

src/Apps/W1/Shopify/App/src/Order handling/Codeunits/ShpfyOrders.Codeunit.al
src/Apps/W1/Shopify/App/src/Order handling/Pages/ShpfyCancelOrder.Page.al
src/Apps/W1/Shopify/App/src/Order handling/Pages/ShpfyOrder.Page.al
src/Apps/W1/Shopify/App/src/PermissionSets/ShpfyObjects.PermissionSet.al

This pull request backports #4998 to releases/27.x
Fixes [AB#575129](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/575129)

[releases/27.x] [Shopify] Introduce public facing facade for order management

---

src/Apps/W1/PowerBIReports/Test/E2EPowerBIInventoryTest.Codeunit.al
src/Apps/W1/PowerBIReports/Test/E2EPowerBIManufacturingTest.Codeunit.al

Fixes [AB#609027](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/609027)

Update PowerBI Reports test with AL0432
