microsoft/BCApps

- .github/AL-Go-Settings.json
- .github/workflows/UpdateBCArtifactVersion.yaml
- .github/workflows/UpdatePackageVersions.yaml
- build/scripts/AutomatedSubmission.psm1
- build/scripts/UpdateBCArtifactVersion.ps1
- build/scripts/UpdatePackageVersions.ps1
Avoid automation creating duplicate PRs. Instead, look for existing (open) PRs and update them if possible
> Avoid automation creating duplicate PRs

- src/System Application/App/Recurrence Schedule/src/RecurrenceScheduleImpl.Codeunit.al
Summary provided in original GitHub PR: https://github.com/microsoft/ALAppExtensions/pull/25152
Fixes #490884
> Add missing indirect permission in Recurrence Schedule

- build/scripts/SyncMirror.ps1
Sync pipeline is currently failing on 
`fatal: a branch named 'main' already exists
git checkout origin/main --track failed with exit code 128`
Only checkout branch if not the default branch
Fixes [AB#491314](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/491314)
> Fix syncing mechanism

- .github/labeler.yml
Label PRs with changes under build/ with "Build: scripts & configs" label.
> Add one more label area

- .github/PULL_REQUEST_TEMPLATE.md
- Make the sections a bit smaller.
- Add more explanation when linking issues.
Improve the PR template to pretty much look like this one.
> Improve PULL_REQUEST_TEMPLATE.md

- .azuredevops/security-tools.yml
Update poolname in security-tools.yml due to new security requirements
Update poolname in security-tools.yml due to new security requirements
Fixes AB#491322
> Update poolname in security-tools.yml

- .github/workflows/powershell.yaml
- build.ps1
- build/projects/Performance Toolkit/.AL-Go/ImportTestToolkitToBcContainer.ps1
- build/projects/System Application Tests/.AL-Go/ImportTestToolkitToBcContainer.ps1
- build/projects/System Application/.AL-Go/PreCompileApp.ps1
- build/projects/Test Framework/.AL-Go/PreCompileApp.ps1
- build/projects/Test Stability Tools/.AL-Go/PreCompileApp.ps1
- build/scripts/AppTranslations.psm1
- build/scripts/AutomatedSubmission.psm1
- build/scripts/CompileAppInBcContainer.ps1
- build/scripts/GitHub/GitHubPullRequest.class.psm1
- build/scripts/PSScriptAnalyzerSettings.psd1
- build/scripts/PreCompileApp.ps1
- build/scripts/SyncMirror.ps1
Fix errors/warning in the PS scripts after PSScriptAnalyzer was enabled.
Fixes AB#491803
> Fix PS errors and warnings

- src/System Application/App/Feature Key/src/FeatureManagementImpl.Codeunit.al
FeatureManagement.IsEnabled() method should return FALSE if feature key is not enabled yet, without creating Feature Key Update Data record at this place.
Fixes #347
> Update IsEnabled method for feature key

- .github/workflows/WorkitemValidation.yaml
- build/scripts/GitHub/GitHubPullRequest.class.psm1
- build/scripts/PullRequestValidation/ValidateIssuesForPullRequest.ps1
This PR adds workitem validation for all pull requests in BCApps. All PRs must therefore supply either a issue or an ADO workitem. The syntax contributors need to follow is: 
"Fixes #<Issue ID>" for linking a GitHub issue
"Fixes AB#<Workitem ID>" for linking a DevOps workitem 
This PR also gives an example of how we can link both GitHub issues and ADO workitems 
Fixes AB#476348, Fixes #326
> Add workitem validation all pull requests

- build/scripts/PullRequestValidation/AddMilestoneToPullRequest.ps1
Stop adding automation PRs to the milestones as it doesn't provide any value to have lots of version update PRs in the milestone. 
Fixes AB#492092
> Skip adding milestones for automation PRs

- src/System Application/App/Feature Key/src/FeatureManagementImpl.Codeunit.al
This PR reverts commit 078403aae582f82d1a81d2eb68399884ed1358f0 as it seems to be causing errors like: 
`Error:
feature is not enabled yet in your Business Central. An administrator can enable the feature on the Feature Management page.`
Fixes AB#491993
> Revert "Update IsEnabled method for feature key (#348)"

- build/scripts/PullRequestValidation/AddMilestoneToPullRequest.ps1
Fix the skipping logic for milestones
Fixes AB#492092
> Fix the skipping logic for milestones

- CODEOWNERS
Make @d365-bc-copilot-toolkit a codeowner of the AI toolkit in System Application.
Fixes AB#492278
> Make d365-bc-copilot-toolkit codeowner of System Application/AI

- src/System Application/App/Extension Management/src/ExtensionManagement.Page.al
Add false to CurrPage.Update() on uninstall and install. Ignoring any record changes that happen.
Fixes AB#492027
> [Extension Management] Permission error on Extension Management page

- src/Tools/Test Framework/Test Runner/src/TestMethodLine.Table.al
A new key to the app Test Runner. The key is to table test method Line
Fixes #363   ([issue exists in the former ALAppExtensions repo](https://github.com/microsoft/ALAppExtensions/issues/23772))
<br /><br />Internal work item: AB#492549
> New TestMetodLine Key in app Test Runner (issue #23772, ALAppExtension repo)

- src/Tools/Performance Toolkit/App/src/BCPTLine.Codeunit.al
- src/Tools/Performance Toolkit/App/src/BCPTTestSuite.Codeunit.al
Fixes #382 and #381
<br /><br />Internal work item: AB#492609
> BCPT: Added stacktrace for errored interaction

- build.ps1
Fix build.ps1, failing in security tools
Fixes AB#492601, Fixes AB#492573
> Fix build.ps1, failing in security tools

- .github/workflows/UpdateBCArtifactVersion.yaml
- .github/workflows/UpdatePackageVersions.yaml
- build/scripts/AutomatedSubmission.psm1
- build/scripts/GitHub/GitHubPullRequest.class.psm1
- build/scripts/UpdateBCArtifactVersion.ps1
- build/scripts/UpdatePackageVersions.ps1
Add work item in description to automated PRs 
Fixes AB#492093
> Add work item for automated PRs

- src/Tools/Performance Toolkit/App/src/BCPTLine.Codeunit.al
- src/Tools/Performance Toolkit/App/src/BCPTTestSuite.Codeunit.al
Fixes #392
<br /><br />Internal work item: AB#492864
> BCPT: Added "Message" to Telemetry

- src/Tools/Performance Toolkit/App/src/BCPTStartTests.Codeunit.al
- src/Tools/Performance Toolkit/App/src/BCPTTestSuite.Codeunit.al
Fixes #394
<br /><br />Internal work item: AB#492865
> BCPT: RunId when running from CommandLine

- src/Tools/Performance Toolkit/App/src/BCPTTestSuite.Codeunit.al
I have added so it validates "Codeunit ID" when creating a new BCPT Suite line in function:
procedure AddLineToTestSuiteHeader(SuiteCode: Code[10]; CodeunitId: Integer): Integer
What will fetch standard parameters to the test if they have been implemented.
Fixes #389 
<br /><br />Internal work item: AB#493727
> #389 BCPT validate Codeunit ID

- src/Tools/Performance Toolkit/App/src/BCPTLine.Table.al
- src/Tools/Performance Toolkit/App/src/BCPTTestSuite.Codeunit.al
I have added functions to see if Test Suite Lines already exists. On two functions it also returns the lineno.
Fixes #387 
<br /><br />Internal work item: AB#493728
> #387 BCPT TestSuiteLineExists

- .github/AL-Go-Settings.json
Use full artifact URL as value for the artifact property in AL-Go-Settings.json in order to make it easier to resolve the artifact URL when creating a local dev env.
Fixes AB#492033
> Use full artifact URL as value for the artifact property in AL-Go-Settings.json

- src/System Application/App/Language/src/LanguageImpl.Codeunit.al
[Bug]: User Settings Region Lookup does not preselect current setting (like Language Lookup does) #351
Fixes #351 
<br /><br />Internal work item: AB#494608
> [Bug]: User Settings Region Lookup does not preselect current setting (like Language Lookup does) Fixes #351

- README.md
Provide a better summary of the different open-source BC repositories 
Fixes AB#494580
> Update readme to point to other repos

- src/System Application/App/Recurrence Schedule/src/RecurrenceScheduleCard.Page.al
A small change that adding the captions for the groups that were missing them
<br /><br />Internal work item: AB#494699
> Added missing captions on groups in recurrence schedule page

- src/System Application/App/Retention Policy/src/Retention Policy Setup/RetentionPolicySetupCard.Page.al
Improve the "Expired Records" field caption and tooltip on the retention policy card when records are deleted in batches.
Fixes [AB#489298](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/489298)
> Provide more clarity for the "Expired Records" field on the retention policy setup card

- src/System Application/Test/Web Service Management/src/WebServiceManagementTest.Codeunit.al
AS0059 was turned into an error
The test wasn't covered and pragma'd
Fixes [AB#495985](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/495985)
> Add pragma to test AS0059

- .github/AL-Go-Settings.json
- .github/workflows/CICD.yaml
- .github/workflows/DeployReferenceDocumentation.yaml
- .github/workflows/PullRequestHandler.yaml
- .github/workflows/Troubleshooting.yaml
- .github/workflows/UpdateGitHubGoSystemFiles.yaml
- .github/workflows/_BuildALGoProject.yaml
- build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
- build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
- build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
- build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
- build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
- build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
- build/projects/System Application/.AL-Go/cloudDevEnv.ps1
- build/projects/System Application/.AL-Go/localDevEnv.ps1
- build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
- build/projects/Test Framework/.AL-Go/localDevEnv.ps1
- build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
- build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1
> Update AL-Go System Files

- CONTRIBUTING.md
- LOCAL_DEV_ENV.md
Add guidelines on how to create local dev env
Fixes [AB#476342](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/476342)
> Add local dev env guidelines

- build/scripts/PullRequestValidation/ValidateInternalWorkItemForPullRequest.ps1
Improve wording when linking work items.
Fixes [AB#496837](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/496837)
> Improve wording on linking work items.

- .azuredevops/SyncMirroredRepository.yml
Create bug on sync failure
Fixes [AB#496928](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/496928)
> Create bug on sync failure

- .github/workflows/UpdateGitHubGoSystemFiles.yaml
Add environment in UpdateGitHubGoSystemFiles.yaml
[AB#437073](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/437073)
> Add environment in UpdateGitHubGoSystemFiles.yaml

- src/System Application/App/Filter Tokens/src/FilterTokensImpl.Codeunit.al
The case should not get changed in the event, as that might be breaking.
Fixes [AB#483241](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/483241)
> Address code review comments on ResolveTimeToken

- .github/ISSUE_TEMPLATE/bcidea.yaml
- .github/ISSUE_TEMPLATE/bug_report.yaml
Add a checkbox to verify that there is an intention to follow up the issue with a PR. If there isn't, redirect to other channels.
[AB#497509](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/497509)
> Update issue template for bug creation

- .github/ISSUE_TEMPLATE/config.yml
Update URLs and title on issues config
[AB#497509](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/497509)
> Update URLs and title on issues config

- .github/AL-Go-Settings.json
- .github/workflows/UpdateBCArtifactVersion.yaml
- .github/workflows/UpdatePackageVersions.yaml
- .github/workflows/powershell.yaml
Support official branches that start with releases/.
Note: Fix for AL-Go to support releases/ is at https://github.com/microsoft/AL-Go/pull/877
Fixes [AB#437073](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/437073)
> Support official branches that start with releases/

- src/System Application/App/SharePoint/src/SharePointClient.Codeunit.al
- src/System Application/App/SharePoint/src/SharePointClientImpl.Codeunit.al
- src/System Application/App/SharePoint/src/model/file/SharePointFile.Codeunit.al
- src/System Application/App/SharePoint/src/model/file/SharePointFile.Table.al
- src/System Application/App/SharePoint/src/model/folder/SharePointFolder.Table.al
- src/System Application/App/SharePoint/src/model/list/SharePointList.Table.al
- src/System Application/App/SharePoint/src/model/listitem/SharePointListItem.Codeunit.al
- src/System Application/App/SharePoint/src/model/listitem/SharePointListItem.Table.al
- src/System Application/App/SharePoint/src/model/listitemattachment/SharePointListItemAtch.Table.al
Fixes #499 
Fixes [AB#498802](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/498802)
> SharePoint MetaData fixes

- src/System Application/App/Email/src/Email/Outbox/EmailEditor.Page.al
- src/System Application/App/Email/src/Email/Sent/EmailViewer.Page.al
Add missing caption to Email Viewer group
Fixes [AB#498434](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/498434)
> Add missing caption

- src/Business Foundation/App/NoSeries/readme_refactoring.md
- src/Business Foundation/App/NoSeries/src/Legacy/NoSeriesManagement.Codeunit.al
To help developers refactor their code using the old No. Series interface, we are providing refactoring examples from directions.
Fixes [AB#498351](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/498351)
> Add No. Series refactoring examples

- src/System Application/App/AI/src/Copilot/CopilotCapabilityImpl.Codeunit.al
- src/System Application/App/Azure AD Plan/src/AzureADPlanImpl.Codeunit.al
- src/System Application/App/Azure AD User Management/src/AzureADUserMgmtImpl.Codeunit.al
- src/System Application/App/Azure AD User Management/src/User sync/AzureADUserSyncImpl.Codeunit.al
Main uptake already done.
This PR fixes admin checks to include new BC Administrator role.
Fixes [AB#498639](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/498639/)
> Uptake BC Admin

- src/System Application/Test/Cryptography Management/src/RSACryptoServiceProviderTests.Codeunit.al
**BYPASS_SECRET_SCANNING**
Fixes [AB#463599](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/463599)
> Uptake bypass

- CONTRIBUTING.md
Enhanced information to the repo documentation
Fixes #557
Fixes [AB#500610](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/500610)
> Add links to Microsoft Learn resources for System app

- src/System Application/App/Azure AD Plan/src/AzureADPlanImpl.Codeunit.al
Add missing `&` to the filter on plan in `AzureAdPlanImpl`
Fixes [AB#498639](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/498639/)
> Fix plan filter in AzureADPlanImpl

- .github/labeler.yml
- .github/workflows/PullRequestLabeler.yaml
It seems that the labeler syntax has been changed for v5 (See for example: https://github.com/actions/labeler/tree/main?tab=readme-ov-file#basic-examples)
Tested here: https://github.com/microsoft/BCApps/actions/runs/7901694404
Fixes [AB#500792](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/500792)
> Fix PR Labeler syntax

- .github/workflows/UpdateBCArtifactVersion.yaml
[AB#420000](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/420000)
> Uptake BC artifact daily

- src/System Application/App/Feature Key/src/FeatureManagement.Page.al
We have changed the content of the feature key management system table column "Mandatory by" and then we have added a new column to hold the technical version as well. This PR is just to add the new column and some views to the page.
Fixes [AB#497816](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/497816/)
> Add technical version to feature key mgmt page

- .azuredevops/SyncMirroredRepository.yml
- .azuredevops/security-tools.yml
- .github/workflows/CreateBuildTag.yaml
- .github/workflows/WorkitemValidation.yaml
Move 'Report build status' to its own job running on a different pool and set up syncing for release branches as well 
Add releases/* to workflows not currently triggered on release branches
Fixes [AB#498823](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/498823)
> Fix workitem creation on sync failure

- build/scripts/CrossBranchPorting.psm1
Small fixes to backporting tooling
* Fix title truncation 
* Fix mechanism to discover existing branches
Fixes [AB#498430](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/498430)
> Small fixes to backporting tooling

- src/Business Foundation/App/NoSeries/src/Batch/NoSeriesBatchImpl.Codeunit.al
- src/Business Foundation/App/NoSeries/src/Single/NoSeriesSequenceImpl.Codeunit.al
- src/Business Foundation/App/NoSeries/src/Single/NoSeriesStatelessImpl.Codeunit.al
Adding telemetry to No. Series to determine if something fails and why.
Fixes [AB#496416](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/496416)
> No. Series: Add telemetry

- src/System Application/App/AI/src/Azure OpenAI/AzureOpenAIImpl.Codeunit.al
Fixes [AB#502013](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/502013)
> Check if completion token is null before processing its value

- src/System Application/App/Entity Text/src/AzureOpenAiSettings.Table.al
The obsolete tag after the state is `Removed` cannot stay "24.0" as it breaks the clean code checks.
Fixes [AB#502022](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/502022)
> Obsolete AzureOpenAiSettings table properly

- src/System Application/App/ControlAddIns/Resources/PowerBIManagement/js/powerbi.js
- src/System Application/App/ControlAddIns/src/PowerBIManagement.ControlAddin.al
- src/System Application/App/Resources/PowerBIManagement/js/powerbi.js
PowerBIManagement control add-in is missing a reference to powerbi.js.
Fixes [AB#499250](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/499250/)
> [PowerBI]  Add missing script reference to PowerBI Control Addin

- .github/AL-Go-Settings.json
> [releases/24.x] Update BC Artifact version

- .github/AL-Go-Settings.json
> [releases/24.0] Update BC Artifact version

- build/projects/Business Foundation/.AL-Go/settings.json
- build/projects/Performance Toolkit/.AL-Go/settings.json
- build/projects/System Application/.AL-Go/settings.json
- build/projects/Test Framework/.AL-Go/settings.json
Temporarily disable strictmode 
Related to [AB#502108](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/502108)
> [24.0] Temporarily disable strictmode 

- src/System Application/App/User Settings/src/UserSettingsImpl.Codeunit.al
Toggle was not being updated upon open of Settings and wasn't being refreshed upon saving.
Fixes [AB#487282](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/487282)
> Modern action bar toggle

- src/System Application/App/User Settings/app.json
- src/System Application/App/User Settings/src/ApplicationUserSettings.Table.al
- src/System Application/App/User Settings/src/UserPersonalization.Page.al
- src/System Application/App/User Settings/src/UserSettings.Codeunit.al
- src/System Application/App/User Settings/src/UserSettings.Page.al
- src/System Application/App/User Settings/src/UserSettings.Table.al
- src/System Application/App/User Settings/src/UserSettingsImpl.Codeunit.al
Add a setting for Legacy Action Bar on the User Settings and My Settings pages for the user to customize.
Add platform subscriber to provide value of whether the setting has been enabled or not.
Fixes [AB#499142](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/499142)
> [24.x] Add Legacy Action Bar setting

- src/System Application/App/User Settings/app.json
- src/System Application/App/User Settings/src/ApplicationUserSettings.Table.al
- src/System Application/App/User Settings/src/UserPersonalization.Page.al
- src/System Application/App/User Settings/src/UserSettings.Codeunit.al
- src/System Application/App/User Settings/src/UserSettings.Page.al
- src/System Application/App/User Settings/src/UserSettings.Table.al
- src/System Application/App/User Settings/src/UserSettingsImpl.Codeunit.al
Add a setting for Legacy Action Bar on the User Settings and My Settings pages for the user to customize.
Add platform subscriber to provide value of whether the setting has been enabled or not.
Fixes [AB#499142](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/499142)
> [24.0] Add Legacy Action Bar setting

- build/Packages.json
> [releases/24.0] Update package versions

- build/Packages.json
> [releases/24.x] Update package versions

- build/scripts/PreCompileApp.ps1
Return rather than exit strictmode when tag isn't present
Fixes [AB#502108](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/502108)
> Return rather than exit strictmode when tag isn't present

- src/System Application/App/Retention Policy/src/Retention Policy Setup/RetentionPolicySetupCard.Page.al
Backport of  #635
Fixes [AB#502379](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/502379)
> [24.0] When controlling field visibility, use variable instead of field to avoid client error

- build/BuildConfig.json
[AB#502303](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/502303)
> Set MaxAllowedObsoleteVersion to 25

- src/System Application/App/DotNet Aliases/src/dotnet.al
Data Search libraries added to system application, which will be used for our Copilot feature
Related to [AB#485919](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/485919)
> Data Search Libraries Added

- src/Business Foundation/App/NoSeries/src/Batch/NoSeriesBatch.Codeunit.al
This pull request backports #672 to releases/24.0
Fixes [AB#503138](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/503138)
> [releases/24.0] update doc for no. series batch

- src/Business Foundation/App/NoSeries/src/Batch/NoSeriesBatch.Codeunit.al
This pull request backports #672 to releases/24.x
Fixes [AB#503137](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/503137)
> [releases/24.x] update doc for no. series batch

- src/Business Foundation/App/NoSeries/src/Batch/NoSeriesBatch.Codeunit.al
Fixes [AB#503133](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/503133)
> update doc for no. series batch

- .gitignore
Ignore .netpackages.
Internal work item: [AB#496684](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/496684)
> Update .gitignore to ignore .NET packages

- build/scripts/EnlistmentHelperFunctions.psm1
- build/scripts/GitHub/GitHubPullRequest.class.psm1
Add Set-ContentLF to match formatting from AL-Go
Related to [AB#486716](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/486716)
> Add Set-ContentLF to match formatting from AL-Go

- src/System Application/App/Azure Blob Services API/src/ABSBlobClient.Codeunit.al
- src/System Application/App/Azure Blob Services API/src/ABSClientImpl.Codeunit.al
- src/System Application/Test/Azure Blob Services API/src/ABSBlobClientTest.Codeunit.al
- src/System Application/Test/Azure Blob Services API/src/ABSTestLibrary.Codeunit.al
- src/System Application/Test/DisabledTests/ABSBlobClientTest.json
Added PutBlockList overload method with required BlobName param to BlobClient interface
Added PutBlock methods with required BlobName param to BlobClient interface
BlobClient implementation updated to set required BlobName param
New unit test for PutBlock and PutBlockList methods.
Fixes #615 
Fixes [AB#502953](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/502953)
> #615 Fix PutBlockList and PutBlock for Azure BLOB module

- CODEOWNERS
* Reorder codeowners such that e.g. a change to the permissionset in the AI module will trigger a review from the permission set reviewers 
* Added rules for handling case sensitivity of codeowners file and the fact that AL files can be inconsistently named
Fixes [AB#502986](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/502986)
> Codeowners updates

- CODEOWNERS
This pull request backports #667 to releases/24.0
Fixes [AB#502986](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/502986)
> [releases/24.0] Codeowners updates

- src/Business Foundation/App/NoSeries/src/Single/NoSeriesImpl.Codeunit.al
- src/Business Foundation/Test/NoSeries/app.json
- src/Business Foundation/Test/NoSeries/src/ERMNoSeriesTests.Codeunit.al
- src/Business Foundation/Test/app.json
Fixes [AB#504098](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/504098)
> fix No. Series Lookup

- src/Business Foundation/App/NoSeries/src/Single/NoSeriesImpl.Codeunit.al
- src/Business Foundation/Test/NoSeries/app.json
- src/Business Foundation/Test/NoSeries/src/ERMNoSeriesTests.Codeunit.al
- src/Business Foundation/Test/app.json
This pull request backports #680 to releases/24.0
Fixes [AB#504250](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/504250)
> [releases/24.0] fix No. Series Lookup

- src/Business Foundation/App/NoSeries/src/Single/NoSeriesImpl.Codeunit.al
- src/Business Foundation/Test/NoSeries/app.json
- src/Business Foundation/Test/NoSeries/src/ERMNoSeriesTests.Codeunit.al
- src/Business Foundation/Test/app.json
This pull request backports #680 to releases/24.x
Fixes [AB#504248](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/504248)
> [releases/24.x] fix No. Series Lookup

- src/System Application/App/AI/src/Azure OpenAI/AOAIAuthorization.Codeunit.al
Enable allowlisted tenants to go through firstparty auth
[AB#504147](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/504147)
> [24.0][Copilot] Enable allowlisted tenants to go through firstparty auth

- src/System Application/App/AI/src/Azure OpenAI/AOAIAuthorization.Codeunit.al
Enable allowlisted tenants to go through firstparty auth
[AB#504148](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/504148)
> [24.x][Copilot] Enable allowlisted tenants to go through firstparty auth

- src/System Application/App/Entity Text/src/EntityTextImpl.Codeunit.al
While generating marketing text, if you choose format "Tag Line + Paragraph", there is an empty response shown. This PR fixes the issue by making 2 LLM calls, one for each "Tag Line" and Paragraph. This is a short term mitigation to avoid changing prompts.
Fixes [AB#503183](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/503183)
> Marketing Text Empty Response Fix

- src/System Application/App/AppSource Gallery/src/AppSourceProductDetails.Page.al
- src/System Application/App/AppSource Gallery/src/AppSourceProductList.Page.al
- src/System Application/App/Extension Management/src/ExtensionManagement.Page.al
Address feedback from latest bugbash.
[AB#502946](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/502946)
> AppSource Gallery feedback.

- src/System Application/App/Azure File Services API/src/AFSOptionalParameters.Codeunit.al
- src/System Application/Test/Azure File Services API/src/AFSFileClientTest.Codeunit.al
Backport of #670 
Fixes [AB#504264](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/504264)
> [24.x] #668 Actually return parameters (#670)

- build/scripts/AutomatedSubmission.psm1
- build/scripts/PullRequestValidation/AddMilestoneToPullRequest.ps1
- build/scripts/UpdateBCArtifactVersion.ps1
- build/scripts/UpdatePackageVersions.ps1
Fix label name when creating automation PRs.
Fix the check for available labels to be case sensitive.
Fixes [AB#504546](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/504546)
> Fix label name when creating automated PRs

- build/scripts/AutomatedSubmission.psm1
- build/scripts/PullRequestValidation/AddMilestoneToPullRequest.ps1
- build/scripts/UpdateBCArtifactVersion.ps1
- build/scripts/UpdatePackageVersions.ps1
This pull request backports #695 to releases/24.x
Fixes [AB#504546](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/504546)
> [releases/24.x] Fix label name when creating automated PRs

- build/scripts/AutomatedSubmission.psm1
- build/scripts/PullRequestValidation/AddMilestoneToPullRequest.ps1
- build/scripts/UpdateBCArtifactVersion.ps1
- build/scripts/UpdatePackageVersions.ps1
This pull request backports #695 to releases/24.0
Fixes [AB#504546](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/504546)
> [releases/24.0] Fix label name when creating automated PRs

- src/System Application/App/AI/src/Azure OpenAI/AOAIToken.Codeunit.al
- src/System Application/App/AI/src/Azure OpenAI/AzureOpenAIImpl.Codeunit.al
This pull request backports #727 to releases/24.x
Fixes [AB#506437](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/506437)
> [releases/24.x] [Copilot] AOAI Token not returning tokens

- src/System Application/App/AI/src/Azure OpenAI/AOAIToken.Codeunit.al
- src/System Application/App/AI/src/Azure OpenAI/AzureOpenAIImpl.Codeunit.al
This pull request backports #727 to releases/24.0
Fixes [AB#506436](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/506436)
> [releases/24.0] [Copilot] AOAI Token not returning tokens

- src/System Application/App/Customer Experience Survey/src/CustExpSurveyReqImpl.Codeunit.al
Adds missing not on IsEmpty() check, missed when uptaking SecretText
Fixes [AB#506438](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/506438/)
> [CES] Fix missing IsEmpty check

- src/System Application/App/Customer Experience Survey/src/CustExpSurveyReqImpl.Codeunit.al
This pull request backports #730 to releases/24.x
Fixes [AB#506490](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/506490/)
> [releases/24.x] [CES] Fix missing IsEmpty check

- src/System Application/App/Customer Experience Survey/src/CustExpSurveyReqImpl.Codeunit.al
This pull request backports #730 to releases/24.0
Fixes [AB#506493](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/506493/)
> [releases/24.0] [CES] Fix missing IsEmpty check

- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/contribution_bug.yaml
Add bug report for contribution bugs i.e. bugs discovered in the process of contributing to BCApps 
Fixes [AB#506513](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/506513)
> Add bug report for contribution bugs

- src/System Application/App/User Settings/src/UserSettings.Page.al
- src/System Application/App/User Settings/src/UserSettingsImpl.Codeunit.al
Show survey on My Settings page, also show survey before write transaction since it does RunModal
Fixes [AB#507133](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/507133/)
> [CES] Show survey on My Settings page

- src/System Application/App/User Settings/src/UserSettings.Page.al
- src/System Application/App/User Settings/src/UserSettingsImpl.Codeunit.al
This pull request backports #750 to releases/24.0
Fixes [AB#507466](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/507466/)
> [releases/24.0] [CES] Show survey on My Settings page

- src/System Application/App/User Settings/src/UserSettings.Page.al
- src/System Application/App/User Settings/src/UserSettingsImpl.Codeunit.al
This pull request backports #750 to releases/24.x
Fixes [AB#507465](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/507465/)
> [releases/24.x] [CES] Show survey on My Settings page

- src/System Application/App/AI/src/Azure OpenAI/Chat Completion/AOAIToolsImpl.Codeunit.al
This pull request backports #751 to releases/24.x
Fixes [AB#507476](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/507476)
> [releases/24.x] [Copilot] Enable Function calling for all

- src/System Application/App/AI/src/Azure OpenAI/Chat Completion/AOAIToolsImpl.Codeunit.al
This pull request backports #751 to releases/24.0
Fixes [AB#507477](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/507477)
> [releases/24.0] [Copilot] Enable Function calling for all

- src/System Application/App/ControlAddIns/src/MicrosoftDynamicsNavClientBusinessChart.ControlAddin.al
The control addin "Microsoft.Dynamics.Nav.Client.BusinessChart" was removed from the App DB in version 24.0. Any usages of this will fail or new tenants.
Introduce this addin as Obsolete = Pending to ensure that the removal from the App DB is non-breaking.
Fixes [AB#507953](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/507953)
> [24.0] Obsolete legacy BusinessChart addin

- src/System Application/App/ControlAddIns/src/MicrosoftDynamicsNavClientBusinessChart.ControlAddin.al
The control addin "Microsoft.Dynamics.Nav.Client.BusinessChart" was removed from the App DB in version 24.0. Any usages of this will fail or new tenants.
Introduce this addin as Obsolete = Pending to ensure that the removal from the App DB is non-breaking.
Fixes [AB#507954](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/507954)
> [24.x] Obsolete legacy BusinessChart addin

- src/System Application/App/Azure Key Vault/src/AzureKeyVault.Codeunit.al
- src/System Application/App/Azure Key Vault/src/AzureKeyVaultImpl.Codeunit.al
- src/System Application/App/Customer Experience Survey/src/CustExpSurveyReqImpl.Codeunit.al
- src/System Application/App/Entity Text/src/AzureOpenAiSettings.Table.al
- src/System Application/App/OAuth2/OAuth2.Codeunit.al
- src/System Application/App/OAuth2/OAuth2Impl.Codeunit.al
SecretText usages for Certificate parameters in OAuth2 
Fixes [AB#520778](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/520778)
> [OAuth2] Additional SecretText usage on Certificates

- .github/ISSUE_TEMPLATE/bcidea.yaml
- .github/ISSUE_TEMPLATE/bug_report.yaml
Fix labels in issue templates
[AB#521448](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/521448)
> Fix labels in issue templates

- .github/AL-Go-Settings.json
[AB#437073](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/437073)
> Enable IncrementVersionNumber from AL-Go

- src/System Application/App/ControlAddIns/src/MicrosoftDynamicsNavClientFlowIntegration.ControlAddin.al
- src/System Application/App/ControlAddIns/src/MicrosoftDynamicsNavClientOAuthIntegration.ControlAddin.al
- src/System Application/App/ControlAddIns/src/MicrosoftDynamicsNavClientPageReady.ControlAddin.al
- src/System Application/App/ControlAddIns/src/MicrosoftDynamicsNavClientPowerBIManagement.ControlAddin.al
- src/System Application/App/ControlAddIns/src/MicrosoftDynamicsNavClientRoleCenterSelector.ControlAddin.al
- src/System Application/App/ControlAddIns/src/MicrosoftDynamicsNavClientVideoPlayer.ControlAddin.al
- src/System Application/App/ControlAddIns/src/MicrosoftDynamicsNavClientWebPageViewer.ControlAddin.al
- src/System Application/App/ControlAddIns/src/MicrosoftDynamicsNavClientWelcomeWizard.ControlAddin.al
Some legacy style control add-ins were removed from the app DB and introduced as System control add-ins in v. 24.0. Any usages of these will fail or new tenants. 
Introduce replacement addins as Obsolete = _Pending_ to ensure that the removal from the App DB is non-breaking.
Fixes [AB#507954](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/507954)
> [24.x] Add replacements for legacy control add-ins

- src/System Application/App/OAuth2/OAuth2.Codeunit.al
- src/System Application/App/OAuth2/OAuth2Impl.Codeunit.al
24.1 tags were put in before the tag fix by Alex, and now cause baseline failures.
Fixes [AB#524284](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/524284)
> [releases/24.x] Fix tags

- src/System Application/Test/DisabledTests/RestClientTests.DisabledTest.json
Disable Rest Client tests as they are unstable in the builds
See for example https://github.com/microsoft/BCApps/actions/runs/8647066990
Related to [AB#524800](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/524800)
> Disable Rest Client Tests

- src/System Application/Test/DisabledTests/RestClientTests.DisabledTest.json
This pull request backports #925 to releases/24.x
Related to [AB#524844](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/524844)
> [releases/24.x] Disable Rest Client Tests

- src/System Application/Test/DisabledTests/RestClientTests.DisabledTest.json
This pull request backports #925 to releases/24.0
Related to [AB#524845](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/524845)
> [releases/24.0] Disable Rest Client Tests

- build/scripts/GuardingV2ExtensionsHelper.psm1
- src/System Application/App/ControlAddIns/src/PowerBIManagement.ControlAddin.al
- src/System Application/App/OAuth2/OAuth2.Codeunit.al
- src/System Application/App/OAuth2/OAuth2Impl.Codeunit.al
Enable AS0105
Fixes [AB#524959](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/524959)
> Enable AS0105

- src/System Application/App/Extension Management/src/ExtensionOperationImpl.Codeunit.al
This pull request backports #924 to releases/24.0
Fixes [AB#524865](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/524865)
> [releases/24.0] Run extension setup after installing app from AppSource

- src/System Application/App/Extension Management/src/ExtensionOperationImpl.Codeunit.al
This pull request backports #924 to releases/24.x
Fixes [AB#524866](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/524866)
> [releases/24.x] Run extension setup after installing app from AppSource

- src/System Application/App/Retention Policy/src/Retention Period/RetentionPeriodEnum.Enum.al
Add translatable captions to RetentionPeriodEnum
Fixes [AB#502734](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/502734)
> Add translatable captions to RetentionPeriodEnum

- src/System Application/App/Retention Policy/src/Retention Period/RetentionPeriodEnum.Enum.al
This pull request backports #936 to releases/24.x
Fixes [AB#502734](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/502734)
> [releases/24.x] Add translatable captions to RetentionPeriodEnum

- src/System Application/App/AI/src/Azure OpenAI/AzureOpenAIImpl.Codeunit.al
Fix return value for procedure `ProcessFunctionCall`. Also explicit return value false
Fixes [AB#525473](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/525473)
> Fix return value for ProcessFunctionCall

- src/System Application/App/MicrosoftGraph/src/GraphClient.Codeunit.al
- src/System Application/App/MicrosoftGraph/src/GraphClientImpl.Codeunit.al
- src/System Application/App/MicrosoftGraph/src/helper/GraphRequestHelper.Codeunit.al
Backport of #773
Fixes #748
Fixes [AB#522599](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/522599)
> [24.x][BC Idea] Add Put method to 'Graph Client' Codeunit (#773)

- src/System Application/App/AI/src/Azure OpenAI/AOAIAuthorization.Codeunit.al
- src/System Application/App/AI/src/Azure OpenAI/AOAIDeploymentsImpl.Codeunit.al
- src/System Application/App/AI/src/Azure OpenAI/AzureOpenAIImpl.Codeunit.al
In previous workshops and in general for future usage, we want the AOAI deployment names to be accessible to tenants that are allowlisted.
Fixes [AB#524618](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/524618)
> Allow allowlisted tenants to get the first party deployment names

- src/System Application/App/Email/src/Scenario/EmailScenario.Codeunit.al
- src/System Application/App/Email/src/Scenario/EmailScenarioImpl.Codeunit.al
- src/System Application/Test/Email/src/EmailScenarioTest.Codeunit.al
Pick from #959 
Fixes [AB#524050](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/524050)
> [24.x] add IsThereEmailAccountSetForScenario functionality

- src/System Application/App/Guided Experience/src/Guided Experience/GuidedExperienceImpl.Codeunit.al
- src/System Application/App/Guided Experience/src/Guided Experience/GuidedExperienceUpgrade.Codeunit.al
Skip upgrade when correct Code is used in Guided Experience Item, this could happen during cloud migration, and cause data corruption in Guided Experience Item table
Fixes [AB#527474](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/527474)
> Skip upgrade when correct Code is used in Guided Experience Item

- .github/AL-Go-Settings.json
This pull request backports #795 to releases/24.x
Fixes [AB#437073](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/437073)
> [releases/24.x] Enable IncrementVersionNumber from AL-Go

- src/System Application/App/Edit in Excel/README.md
We merged in a PR updating the Edit-In Excel module API https://github.com/microsoft/BCApps/pull/550, but forgot about updating the documentation, namely the README.md which had examples using the old API.
Fixes [AB#527688](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/527688/)
> Cleanup the Edit-In Excel module docs

- src/System Application/App/Rest Client/src/HttpContent.Codeunit.al
- src/System Application/App/Rest Client/src/HttpContentImpl.Codeunit.al
- src/System Application/App/Rest Client/src/RestClient.Codeunit.al
- src/System Application/Test/Rest Client/src/HttpContentTests.Codeunit.al
Updated HTTP content processing to return an empty JsonToken when no content is present instead of failing. This change ensures that REST client functions handling JSON will not raise exceptions on empty responses but will indicate an empty result, enhancing the robustness and predictability of REST API interactions. Accompanying tests ensure correct behavior and documentation updates reflect the improved handling.
Fixes #744 
Fixes [AB#527572](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/527572)
> Implement graceful handling of empty JSON responses

- build/Packages.json
> [releases/24.1] Update package versions

- .github/AL-Go-Settings.json
> [releases/24.1] Update BC Artifact version

- src/System Application/App/Email/src/Message/EmailAttachments.Page.al
Remove page control of drag and drop, because client team decide to postpone this one from 25.x to 26.x.
For now the compiler supports it, but it will turn to an error in the future. So remove it. Add them back when supported.
[AB#484133](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/484133/)
> [Main] One Line Change: remove page control of drag and drop

- .github/workflows/WorkitemValidation.yaml
Add linked label if workitem is already linked in description
Fixes [AB#533076](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/533076)
> Add linked label if workitem is already linked in description

- src/System Application/App/AI/src/Copilot/CopilotDeactivateCapability.Page.al
This pull request backports #1024 to releases/24.x
Fixes [AB#533392](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/533392)
> [releases/24.x] [Copilot] Add an additional deactivation reason

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: https://bcinsider-fvh2ekdjecfjd6gk.b02.azurefd.net/sandbox/24.2.19158.0/base
> Update BCArtifact version. New value: https://bcinsider-fvh2ekdjecfjd6gk.b02.azurefd.net/sandbox/24.2.19158.0/base

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: https://bcinsider-fvh2ekdjecfjd6gk.b02.azurefd.net/sandbox/25.0.19134.0/base
> Update BCArtifact version. New value: https://bcinsider-fvh2ekdjecfjd6gk.b02.azurefd.net/sandbox/25.0.19134.0/base

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: https://bcinsider-fvh2ekdjecfjd6gk.b02.azurefd.net/sandbox/24.1.18927.19155/base
> Update BCArtifact version. New value: https://bcinsider-fvh2ekdjecfjd6gk.b02.azurefd.net/sandbox/24.1.18927.19155/base

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: https://bcartifacts-exdbf9fwegejdqak.b02.azurefd.net/sandbox/24.0.16410.19154/base
> Update BCArtifact version. New value: https://bcartifacts-exdbf9fwegejdqak.b02.azurefd.net/sandbox/24.0.16410.19154/base

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: https://bcinsider-fvh2ekdjecfjd6gk.b02.azurefd.net/sandbox/25.0.19229.0/base
> Update BCArtifact version. New value: https://bcinsider-fvh2ekdjecfjd6gk.b02.azurefd.net/sandbox/25.0.19229.0/base

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: https://bcartifacts-exdbf9fwegejdqak.b02.azurefd.net/sandbox/24.0.16410.19234/base
> Update BCArtifact version. New value: https://bcartifacts-exdbf9fwegejdqak.b02.azurefd.net/sandbox/24.0.16410.19234/base

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: https://bcinsider-fvh2ekdjecfjd6gk.b02.azurefd.net/sandbox/24.1.18927.19235/base
> Update BCArtifact version. New value: https://bcinsider-fvh2ekdjecfjd6gk.b02.azurefd.net/sandbox/24.1.18927.19235/base

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: https://bcinsider-fvh2ekdjecfjd6gk.b02.azurefd.net/sandbox/24.2.19241.0/base
> Update BCArtifact version. New value: https://bcinsider-fvh2ekdjecfjd6gk.b02.azurefd.net/sandbox/24.2.19241.0/base

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: https://bcinsider-fvh2ekdjecfjd6gk.b02.azurefd.net/sandbox/25.0.19293.0/base
> Update BCArtifact version. New value: https://bcinsider-fvh2ekdjecfjd6gk.b02.azurefd.net/sandbox/25.0.19293.0/base

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: https://bcartifacts-exdbf9fwegejdqak.b02.azurefd.net/sandbox/24.0.16410.19284/base
> Update BCArtifact version. New value: https://bcartifacts-exdbf9fwegejdqak.b02.azurefd.net/sandbox/24.0.16410.19284/base

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: https://bcinsider-fvh2ekdjecfjd6gk.b02.azurefd.net/sandbox/24.2.19279.0/base
> Update BCArtifact version. New value: https://bcinsider-fvh2ekdjecfjd6gk.b02.azurefd.net/sandbox/24.2.19279.0/base

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: https://bcinsider-fvh2ekdjecfjd6gk.b02.azurefd.net/sandbox/24.1.18927.19282/base
> Update BCArtifact version. New value: https://bcinsider-fvh2ekdjecfjd6gk.b02.azurefd.net/sandbox/24.1.18927.19282/base

- build/Packages.json
- Update app baselines package version. New value: 23.5.16502.19263
> Update app baselines package version. New value: 23.5.16502.19263

- build/Packages.json
- Update app baselines package version. New value: 24.2.19279.0
> Update app baselines package version. New value: 24.2.19279.0

- build/Packages.json
- Update app baselines package version. New value: 24.1.18927.19282
> Update app baselines package version. New value: 24.1.18927.19282

- build/Packages.json
- Update app baselines package version. New value: 24.0.16410.19284
> Update app baselines package version. New value: 24.0.16410.19284

- src/System Application/App/Azure Blob Services API/src/ABSBlobClient.Codeunit.al
- src/System Application/App/Azure Blob Services API/src/ABSClientImpl.Codeunit.al
Add `OptionalParameters` to `FindBlobsByTags` to provide the possibility of setting `marker` and `maxresults`. This is required to use result paging.
Fixes #893 
Fixes [AB#524630](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/524630)
> Refactor FindBlobsByTags method to accept OptionalParameters

- src/System Application/App/Azure Blob Services API/src/Helper/ABSFormatHelper.Codeunit.al
Lock Label which was mistakenly localized.
Fixes #1065
Fixes [AB#534154](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/534154)
> Fix: Lock Label in ABS

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 25.0.19335.0
> [main] Update BCArtifact version. New value: 25.0.19335.0

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.2.19333.0
> [24.x] Update BCArtifact version. New value: 24.2.19333.0

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.1.18927.19332
> [24.1] Update BCArtifact version. New value: 24.1.18927.19332

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.0.16410.19334
> [24.0] Update BCArtifact version. New value: 24.0.16410.19334

- src/System Application/App/Azure Blob Services API/src/Helper/ABSOptionalParameters.Codeunit.al
Allow listing files/directories only in azure blob storage.
Fixes #894 
Fixes [AB#524631](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/524631)
>  Add ShowOnly procedure to ABSOptionalParameters Codeunit

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.1.18927.19445
> [24.1] Update BCArtifact version. New value: 24.1.18927.19445

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.0.16410.19443
> [24.0] Update BCArtifact version. New value: 24.0.16410.19443

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.2.19447.0
> [24.x] Update BCArtifact version. New value: 24.2.19447.0

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 25.0.19453.0
> [main] Update BCArtifact version. New value: 25.0.19453.0

- src/Business Foundation/App/NoSeries/src/Setup/NoSeriesErrorsImpl.Codeunit.al
- src/System Application/App/Data Administration/src/MediaCleanupImpl.Codeunit.al
- src/System Application/App/Data Classification/src/DataClassificationMgtImpl.Codeunit.al
- src/System Application/App/Email/src/Account/EmailAccountImpl.Codeunit.al
- src/System Application/App/Email/src/Email/EmailImpl.Codeunit.al
- src/System Application/App/Entity Text/src/CopilotInformation.Page.al
- src/System Application/App/Entity Text/src/EntityTextAOAISettings.Codeunit.al
- src/System Application/App/Extension Management/src/ExtensionInstallationImpl.Codeunit.al
- src/System Application/App/Guided Experience/src/Guided Experience/GuidedExperienceImpl.Codeunit.al
- src/System Application/App/Page Summary Provider/src/PageSummarySettings.Page.al
- src/System Application/App/Privacy Notice/src/PrivacyNoticeImpl.Codeunit.al
- src/System Application/App/Retention Policy/src/Retention Policy Setup/RetentionPolicySetupCard.Page.al
- src/System Application/App/Satisfaction Survey/src/SatisfactionSurveyImpl.Codeunit.al
- src/System Application/App/Security Groups/src/SecurityGroupImpl.Codeunit.al
WritePermission() always returns false when any securityfilter is present regardless of what the filter is. 
Fixes [AB#534078](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/534078)
> fix WritePermission

- build/Packages.json
- Update app baselines package version. New value: 24.2.19483.0
> [main] Update app baselines package version. New value: 24.2.19483.0

- build/Packages.json
- Update app baselines package version. New value: 24.1.18927.19484
> [24.x] Update app baselines package version. New value: 24.1.18927.19484

- build/Packages.json
- Update app baselines package version. New value: 24.0.16410.19485
> [24.1] Update app baselines package version. New value: 24.0.16410.19485

- build/Packages.json
- Update app baselines package version. New value: 23.5.16502.19465
> [24.0] Update app baselines package version. New value: 23.5.16502.19465

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 25.0.19488.0
> [main] Update BCArtifact version. New value: 25.0.19488.0

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.2.19483.0
> [24.x] Update BCArtifact version. New value: 24.2.19483.0

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.1.18927.19484
> [24.1] Update BCArtifact version. New value: 24.1.18927.19484

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.2.19537.0
> [24.x] Update BCArtifact version. New value: 24.2.19537.0

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.0.16410.19533
> [24.0] Update BCArtifact version. New value: 24.0.16410.19533

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.1.18927.19532
> [24.1] Update BCArtifact version. New value: 24.1.18927.19532

- src/Business Foundation/App/NoSeries/src/Single/NoSeriesStatelessImpl.Codeunit.al
This pull request backports #1099 to releases/24.x
Fixes [AB#534758](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/534758)
> [releases/24.x] add locktable to no series stateless impl

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.2.19595.0
> [24.x] Update BCArtifact version. New value: 24.2.19595.0

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 25.0.19593.0
> [main] Update BCArtifact version. New value: 25.0.19593.0

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.0.16410.19590
> [24.0] Update BCArtifact version. New value: 24.0.16410.19590

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.1.18927.19589
> [24.1] Update BCArtifact version. New value: 24.1.18927.19589

- src/System Application/App/MicrosoftGraph/src/Authorization/GraphAuthClientCredentials.Codeunit.al
- src/System Application/App/MicrosoftGraph/src/GraphClient.Codeunit.al
Remove NonDebuggable from Graph client to enable easier debugging
Partially fixes #875
Fixes [AB#524277](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/524277)
> Remove NonDebuggable from Microsoft Graph Client

- src/System Application/App/AI/src/Copilot/CopilotCapabilityInstall.Codeunit.al
Enable analysis assist for Canada
Fixes  [AB#533328](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/533328/)
> Enable analysis assist for canada

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.1.18927.19633
> [24.1] Update BCArtifact version. New value: 24.1.18927.19633

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.2.19636.0
> [24.x] Update BCArtifact version. New value: 24.2.19636.0

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.0.16410.19635
> [24.0] Update BCArtifact version. New value: 24.0.16410.19635

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.1.18927.19722
> [24.1] Update BCArtifact version. New value: 24.1.18927.19722

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.2.19725.0
> [24.x] Update BCArtifact version. New value: 24.2.19725.0

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.0.16410.19719
> [24.0] Update BCArtifact version. New value: 24.0.16410.19719

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 25.0.19746.0
> [main] Update BCArtifact version. New value: 25.0.19746.0

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.1.18927.19730
> [24.1] Update BCArtifact version. New value: 24.1.18927.19730

- build/Packages.json
- Update app baselines package version. New value: 23.5.16502.19720
> [24.0] Update app baselines package version. New value: 23.5.16502.19720

- build/Packages.json
- Update app baselines package version. New value: 24.0.16410.19729
> [24.1] Update app baselines package version. New value: 24.0.16410.19729

- build/Packages.json
- Update app baselines package version. New value: 24.2.19745.0
> [main] Update app baselines package version. New value: 24.2.19745.0

- build/Packages.json
- Update app baselines package version. New value: 24.1.18927.19730
> [24.x] Update app baselines package version. New value: 24.1.18927.19730

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.0.16410.19729
> [24.0] Update BCArtifact version. New value: 24.0.16410.19729

- src/Business Foundation/App/NoSeries/src/Single/NoSeriesSequenceImpl.Codeunit.al
- src/Business Foundation/App/NoSeries/src/Single/NoSeriesStatelessImpl.Codeunit.al
- src/Business Foundation/Test Library/NoSeries/src/LibraryNoSeries.Codeunit.al
- src/Business Foundation/Test/NoSeries/src/NoSeriesBatchTests.Codeunit.al
- src/Business Foundation/Test/NoSeries/src/NoSeriesTests.Codeunit.al
Backport of PR#1118
Fixes
[AB#534262](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/534262)
Fixes [AB#534758](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/534758)
> Bugs/534262 (#1118)

- src/System Application/App/Azure Function/AzureFunctionsAuthentication.Codeunit.al
- src/System Application/App/Azure Function/AzureFunctionsOAuth2Cert.Codeunit.al
Port down #1120 
Fixes [AB#535801](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/535801)
> [24.1] azure function support cert auth

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.0.16410.19803
> [24.0] Update BCArtifact version. New value: 24.0.16410.19803

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 25.0.19812.0
> [main] Update BCArtifact version. New value: 25.0.19812.0

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.2.19802.0
> [24.x] Update BCArtifact version. New value: 24.2.19802.0

- src/System Application/App/Azure Function/AzureFunctionsAuthentication.Codeunit.al
- src/System Application/App/Azure Function/AzureFunctionsOAuth2Cert.Codeunit.al
- src/System Application/App/OAuth2/OAuth2.Codeunit.al
- src/System Application/App/OAuth2/OAuth2Impl.Codeunit.al
Port down #1120 
Fixes [AB#535800](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/535800)
> [24.0] azure function support cert auth

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.1.18927.19859
> [24.1] Update BCArtifact version. New value: 24.1.18927.19859

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 25.0.19860.0
> [main] Update BCArtifact version. New value: 25.0.19860.0

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.0.16410.19861
> [24.0] Update BCArtifact version. New value: 24.0.16410.19861

- src/System Application/App/Azure Key Vault/src/AzureKeyVault.Codeunit.al
- src/System Application/App/Azure Key Vault/src/AzureKeyVaultImpl.Codeunit.al
On top of #1153 , also need AKV support
Fixes [AB#535800](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/535800)
> [24.0] azure function support cert auth (with addtional AKV support)

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.2.19938.0
> [24.x] Update BCArtifact version. New value: 24.2.19938.0

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.0.16410.19941
> [24.0] Update BCArtifact version. New value: 24.0.16410.19941

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.1.18927.19939
> [24.1] Update BCArtifact version. New value: 24.1.18927.19939

- src/System Application/App/MicrosoftGraph/src/Authorization/GraphAuthClientCredentials.Codeunit.al
- src/System Application/App/MicrosoftGraph/src/Authorization/GraphAuthorization.Codeunit.al
- src/System Application/App/MicrosoftGraph/src/Authorization/GraphAuthorizationImpl.Codeunit.al
- src/System Application/App/Rest Client/src/Authentication/HttpAuthOAuthClientCredentials.Codeunit.al
Add Authentication with Certificate+Password to RestClient and GraphClient.
Fixes #1093 
Fixes [AB#534910](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/534910)
> Add ClientCredentials Authentication with Certificate

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.0.16410.19983
> [24.0] Update BCArtifact version. New value: 24.0.16410.19983

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.1.18927.19982
> [24.1] Update BCArtifact version. New value: 24.1.18927.19982

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.2.19984.0
> [24.x] Update BCArtifact version. New value: 24.2.19984.0

- build/Packages.json
- Update app baselines package version. New value: 24.0.16410.20073
> [24.1] Update app baselines package version. New value: 24.0.16410.20073

- build/Packages.json
- Update app baselines package version. New value: 24.1.18927.20076
- Update translation package version. New value: 24.2.20240528.3
> [24.x] Update app baselines package version. New value: 24.1.18927.20076 (+ 1 more update(s))

- build/Packages.json
- Update app baselines package version. New value: 24.2.20071.0
- Update translation package version. New value: 25.0.20240527.6
> [main] Update app baselines package version. New value: 24.2.20071.0 (+ 1 more update(s))

- build/Packages.json
- Update app baselines package version. New value: 23.5.16502.20066
> [24.0] Update app baselines package version. New value: 23.5.16502.20066

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.2.20071.0
> [24.x] Update BCArtifact version. New value: 24.2.20071.0

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.0.16410.20077
> [24.0] Update BCArtifact version. New value: 24.0.16410.20077

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.1.18927.20076
> [24.1] Update BCArtifact version. New value: 24.1.18927.20076

- src/System Application/App/AppSource Gallery/src/AppSourceProductManager.Codeunit.al
This pull request backports #1113 to releases/24.x
Fixes [AB#536469](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/536469)
> [releases/24.x] Fix region for Microsoft AppSource Apps page API

- src/System Application/App/AppSource Gallery/src/AppSourceProductManager.Codeunit.al
This pull request backports #1113 to releases/24.x
Fixes [AB#536467](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/536467)
> [releases/24.0] Fix region for Microsoft AppSource Apps page API

- src/System Application/App/AppSource Gallery/src/AppSourceProductManager.Codeunit.al
This pull request backports #1113 to releases/24.x
Fixes [AB#536468](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/536468)
> [releases/24.1] Fix region for Microsoft AppSource Apps page API

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.1.18927.20113
> [24.1] Update BCArtifact version. New value: 24.1.18927.20113

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.2.20122.0
> [24.x] Update BCArtifact version. New value: 24.2.20122.0

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.0.16410.20121
> [24.0] Update BCArtifact version. New value: 24.0.16410.20121

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 25.0.20194.0
> [main] Update BCArtifact version. New value: 25.0.20194.0

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.1.18927.20192
> [24.1] Update BCArtifact version. New value: 24.1.18927.20192

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.0.16410.20193
> [24.0] Update BCArtifact version. New value: 24.0.16410.20193

- .github/AL-Go-Settings.json
- .github/workflows/CreateBuildTag.yaml
- .github/workflows/MSDO.yml
- .github/workflows/PullRequestLabeler.yaml
- .github/workflows/WorkitemValidation.yaml
- .github/workflows/powershell.yaml
Pin GitHub action dependencies by hash
Fixes [AB#536769](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/536769)
> Pin GitHub action dependencies by hash

- src/System Application/App/Permissions/MetadataRead.PermissionSet.al
- src/System Application/App/Permissions/SystemTablesBasic.PermissionSet.al
- src/System Application/App/System Permissions/permissions/SecuritySystem.PermissionSet.al
Use new system profile tables to the existing permission sets.
Fixes [AB#534267](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/534267)
> [Profile] Add new virtual tables to permissionsets

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.2.20239.0
> [24.x] Update BCArtifact version. New value: 24.2.20239.0

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.0.16410.20241
> [24.0] Update BCArtifact version. New value: 24.0.16410.20241

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.1.18927.20242
> [24.1] Update BCArtifact version. New value: 24.1.18927.20242

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 25.0.20246.0
> [main] Update BCArtifact version. New value: 25.0.20246.0

- src/Business Foundation/App/NoSeries/src/Upgrade/NoSeriesInstaller.Codeunit.al
- src/Business Foundation/App/NoSeries/src/Upgrade/NoSeriesUpgrade.Codeunit.al
- src/Business Foundation/App/NoSeries/src/Upgrade/NoSeriesUpgradeTags.Codeunit.al
This pull request backports #1221 to releases/24.1
Fixes [AB#537075](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/537075)
> [releases/24.1] Setup No. Series on upgrade

- src/Business Foundation/App/NoSeries/src/Upgrade/NoSeriesInstaller.Codeunit.al
- src/Business Foundation/App/NoSeries/src/Upgrade/NoSeriesUpgrade.Codeunit.al
- src/Business Foundation/App/NoSeries/src/Upgrade/NoSeriesUpgradeTags.Codeunit.al
This pull request backports #1221 to releases/24.0
Fixes [AB#537074](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/537074)
> [releases/24.0] Setup No. Series on upgrade

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.2.20227.20240
> [24.2] Update BCArtifact version. New value: 24.2.20227.20240

- src/Business Foundation/App/NoSeries/src/Upgrade/NoSeriesInstaller.Codeunit.al
- src/Business Foundation/App/NoSeries/src/Upgrade/NoSeriesUpgrade.Codeunit.al
- src/Business Foundation/App/NoSeries/src/Upgrade/NoSeriesUpgradeTags.Codeunit.al
This pull request backports #1221 to releases/24.2
Fixes [AB#537076](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/537076)
> [releases/24.2] Setup No. Series on upgrade

- src/System Application/App/Satisfaction Survey/src/SatisfactionSurveyImpl.Codeunit.al
Copying of environments can fail when a lock is held on the Net Promoter Score table. This ensures the lock is released.
Fixes [AB#537119](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/537119)
> Add commit to resets

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.0.16410.20290
> [24.0] Update BCArtifact version. New value: 24.0.16410.20290

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.1.18927.20291
> [24.1] Update BCArtifact version. New value: 24.1.18927.20291

- src/System Application/App/Satisfaction Survey/src/SatisfactionSurveyImpl.Codeunit.al
This pull request backports #1226 to releases/24.x
Fixes [AB#537189](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/537189)
> [releases/24.x] Add commit to resets

- src/System Application/App/Satisfaction Survey/src/SatisfactionSurveyImpl.Codeunit.al
This pull request backports #1226 to releases/24.1
Fixes [AB#537187](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/537187)
> [releases/24.1] Add commit to resets

- src/System Application/App/Satisfaction Survey/src/SatisfactionSurveyImpl.Codeunit.al
This pull request backports #1226 to releases/24.0
Fixes [AB#537186](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/537186)
> [releases/24.0] Add commit to resets

- src/System Application/App/Satisfaction Survey/src/SatisfactionSurveyImpl.Codeunit.al
This pull request backports #1238 to releases/24.1
Fixes [AB#537187](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/537187)
> [releases/24.1] Revert added commits to SatisfactionSurvey resets.

- src/System Application/App/Satisfaction Survey/src/SatisfactionSurveyImpl.Codeunit.al
This pull request backports #1238 to releases/24.0
Fixes [AB#537186](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/537186)
> [releases/24.0] Revert added commits to SatisfactionSurvey resets.

- src/System Application/App/Satisfaction Survey/src/SatisfactionSurveyImpl.Codeunit.al
This pull request backports #1238 to releases/24.x
Fixes [AB#537189](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/537189)
> [releases/24.x] Revert added commits to SatisfactionSurvey resets.

- src/System Application/App/Satisfaction Survey/src/SatisfactionSurveyImpl.Codeunit.al
Remove commits from SatisfactionSurvey and add into EnvironmentCleanupSubs in BaseApp instead.
Fixes [AB#537119](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/537119)
> Revert added commits to SatisfactionSurvey resets.

- build/Packages.json
- Update app baselines package version. New value: 24.1.18927.20357
- Update translation package version. New value: 24.2.20240603.2
> [24.2] Update app baselines package version. New value: 24.1.18927.20357 (+ 1 more update(s))

- build/Packages.json
- Update app baselines package version. New value: 23.5.16502.20333
> [24.0] Update app baselines package version. New value: 23.5.16502.20333

- build/Packages.json
- Update app baselines package version. New value: 24.0.16410.20359
> [24.1] Update app baselines package version. New value: 24.0.16410.20359

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.0.16410.20359
> [24.0] Update BCArtifact version. New value: 24.0.16410.20359

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 25.0.20366.0
> [main] Update BCArtifact version. New value: 25.0.20366.0

- build/Packages.json
- Update app baselines package version. New value: 24.2.20355.0
- Update translation package version. New value: 24.3.20240604.3
> [24.x] Update app baselines package version. New value: 24.2.20355.0 (+ 1 more update(s))

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.1.18927.20357
> [24.1] Update BCArtifact version. New value: 24.1.18927.20357

- build/Packages.json
- Update app baselines package version. New value: 24.3.20365.0
- Update translation package version. New value: 25.0.20240603.4
> [main] Update app baselines package version. New value: 24.3.20365.0 (+ 1 more update(s))

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.3.20365.0
> [24.x] Update BCArtifact version. New value: 24.3.20365.0

- src/Business Foundation/App/NoSeries/src/Single/NoSeriesImpl.Codeunit.al
- src/Business Foundation/Test/NoSeries/src/NoSeriesBatchTests.Codeunit.al
This pull request backports #1243 to releases/24.1
Fixes [AB#537307](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/537307)
> [releases/24.1] fix bug related to daily no. series lines

- src/Business Foundation/App/NoSeries/src/Single/NoSeriesImpl.Codeunit.al
- src/Business Foundation/Test/NoSeries/src/NoSeriesBatchTests.Codeunit.al
This pull request backports #1243 to releases/24.0
Fixes [AB#537306](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/537306)
> [releases/24.0] fix bug related to daily no. series lines

- src/Business Foundation/App/NoSeries/src/Single/NoSeriesImpl.Codeunit.al
- src/Business Foundation/Test/NoSeries/src/NoSeriesBatchTests.Codeunit.al
This pull request backports #1243 to releases/24.x
Fixes [AB#537309](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/537309)
> [releases/24.x] fix bug related to daily no. series lines

- .github/AL-Go-Settings.json
- build/Packages.json
- Update BCArtifact version. New value: 24.3.20415.0
> [24.x] Update BCArtifact version. New value: 24.3.20415.0

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.2.20227.20416
> [24.2] Update BCArtifact version. New value: 24.2.20227.20416

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.1.18927.20417
> [24.1] Update BCArtifact version. New value: 24.1.18927.20417

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.0.16410.20418
> [24.0] Update BCArtifact version. New value: 24.0.16410.20418

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 25.0.20419.0
> [main] Update BCArtifact version. New value: 25.0.20419.0

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.3.20464.0
> [24.x] Update BCArtifact version. New value: 24.3.20464.0

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.0.16410.20505
> [24.0] Update BCArtifact version. New value: 24.0.16410.20505

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.1.18927.20507
> [24.1] Update BCArtifact version. New value: 24.1.18927.20507

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.2.20227.20513
> [24.2] Update BCArtifact version. New value: 24.2.20227.20513

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.3.20516.0
> [24.x] Update BCArtifact version. New value: 24.3.20516.0

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.0.16410.20534
> [24.0] Update BCArtifact version. New value: 24.0.16410.20534

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.3.20544.0
> [24.x] Update BCArtifact version. New value: 24.3.20544.0

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.1.18927.20535
> [24.1] Update BCArtifact version. New value: 24.1.18927.20535

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.2.20227.20536
> [24.2] Update BCArtifact version. New value: 24.2.20227.20536

- build/Packages.json
- Update app baselines package version. New value: 24.2.20227.20579
- Update translation package version. New value: 24.3.20240611.2
> [24.x] Update app baselines package version. New value: 24.2.20227.20579 (+ 1 more update(s))

- build/Packages.json
- Update app baselines package version. New value: 24.1.18927.20578
> [24.2] Update app baselines package version. New value: 24.1.18927.20578

- build/Packages.json
- Update app baselines package version. New value: 24.3.20605.0
- Update translation package version. New value: 25.0.20240610.3
> [main] Update app baselines package version. New value: 24.3.20605.0 (+ 1 more update(s))

- build/Packages.json
- Update app baselines package version. New value: 24.0.16410.20592
> [24.1] Update app baselines package version. New value: 24.0.16410.20592

- build/Packages.json
- Update app baselines package version. New value: 23.5.16502.20560
> [24.0] Update app baselines package version. New value: 23.5.16502.20560

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.0.16410.20592
> [24.0] Update BCArtifact version. New value: 24.0.16410.20592

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.1.18927.20578
> [24.1] Update BCArtifact version. New value: 24.1.18927.20578

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.3.20605.0
> [24.x] Update BCArtifact version. New value: 24.3.20605.0

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.2.20227.20579
> [24.2] Update BCArtifact version. New value: 24.2.20227.20579

- src/System Application/App/User Settings/src/UserSettingsImpl.Codeunit.al
Fixes [AB#536861](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/536861)
> Suppress AL0667 on ProfileSystemScope

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.0.16410.20652
> [24.0] Update BCArtifact version. New value: 24.0.16410.20652

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 25.0.20655.0
> [main] Update BCArtifact version. New value: 25.0.20655.0

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.3.20650.0
> [24.x] Update BCArtifact version. New value: 24.3.20650.0

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.2.20227.20651
> [24.2] Update BCArtifact version. New value: 24.2.20227.20651

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.1.18927.20653
> [24.1] Update BCArtifact version. New value: 24.1.18927.20653

- src/Business Foundation/App/NoSeries/src/Upgrade/NoSeriesInstaller.Codeunit.al
Port from #1299 
Fixes [AB#537873](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/537873)
> [24.x] remove unnecessary upgrade code for No Series

- src/Business Foundation/App/NoSeries/src/Upgrade/NoSeriesInstaller.Codeunit.al
Port from #1299 
Fixes [AB#537872](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/537872)
> [24.2] remove unnecessary upgrade code for No Series

- src/Business Foundation/App/NoSeries/src/Upgrade/NoSeriesInstaller.Codeunit.al
Port from #1299
Fixes [AB#537873](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/537873)
> [24.1] remove unnecessary upgrade code for No Series

- src/Business Foundation/App/NoSeries/src/Upgrade/NoSeriesInstaller.Codeunit.al
Port from #1299
Fixes [AB#537870](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/537870)
> [24.0] remove unnecessary upgrade code for No Series

- src/Business Foundation/App/NoSeries/src/Single/NoSeriesImpl.Codeunit.al
No Series Line should be picked in the order of Starting Date
Fixes # [AB#537968](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/537968)
> [HotFix][24.x]No Series Line should be picked in the order of Starting Date

- src/Business Foundation/App/NoSeries/src/Single/NoSeriesImpl.Codeunit.al
Fixes # [AB#537967](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/537967)
> [HotFix][24.2] No Series Line should be picked in the order of Starting Date

- src/Business Foundation/App/NoSeries/src/Single/NoSeriesImpl.Codeunit.al
No Series Line should be picked in the order of Starting Date
Fixes # [AB#537966](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/537966)
> [HotFix][24.1]No Series Line should be picked in the order of Starting Date

- src/Business Foundation/App/NoSeries/src/Single/NoSeriesImpl.Codeunit.al
No Series Line should be picked in the order of Starting Date
Fixes # [AB#537965](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/537965/)
> [HotFix][24.0]No Series Line should be picked in the order of Starting Date

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.0.16410.20709
> [24.0] Update BCArtifact version. New value: 24.0.16410.20709

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.1.18927.20710
> [24.1] Update BCArtifact version. New value: 24.1.18927.20710

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.3.20705.0
> [24.x] Update BCArtifact version. New value: 24.3.20705.0

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 25.0.20714.0
> [main] Update BCArtifact version. New value: 25.0.20714.0

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.2.20227.20697
> [24.2] Update BCArtifact version. New value: 24.2.20227.20697

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.2.20227.20762
> [24.2] Update BCArtifact version. New value: 24.2.20227.20762

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 25.0.20764.0
> [main] Update BCArtifact version. New value: 25.0.20764.0

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.0.16410.20760
> [24.0] Update BCArtifact version. New value: 24.0.16410.20760

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.3.20759.0
> [24.x] Update BCArtifact version. New value: 24.3.20759.0

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.1.18927.20761
> [24.1] Update BCArtifact version. New value: 24.1.18927.20761

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.1.18927.20810
> [24.1] Update BCArtifact version. New value: 24.1.18927.20810

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 25.0.20818.0
> [main] Update BCArtifact version. New value: 25.0.20818.0

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.2.20227.20808
> [24.2] Update BCArtifact version. New value: 24.2.20227.20808

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.0.16410.20811
> [24.0] Update BCArtifact version. New value: 24.0.16410.20811

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.3.20814.0
> [24.x] Update BCArtifact version. New value: 24.3.20814.0

- src/System Application/App/User Settings/src/UserSettingsImpl.Codeunit.al
Fixes [AB#538474](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/538474)
> Suppress AL0667 on ProfileSystemScope (#1296)

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.0.16410.20902
> [24.0] Update BCArtifact version. New value: 24.0.16410.20902

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.1.18927.20890
> [24.1] Update BCArtifact version. New value: 24.1.18927.20890

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.2.20227.20903
> [24.2] Update BCArtifact version. New value: 24.2.20227.20903

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.3.20909.0
> [24.x] Update BCArtifact version. New value: 24.3.20909.0

- build/Packages.json
- Update app baselines package version. New value: 23.5.16502.20861
> [24.0] Update app baselines package version. New value: 23.5.16502.20861

- build/Packages.json
- Update app baselines package version. New value: 24.1.18927.20890
> [24.2] Update app baselines package version. New value: 24.1.18927.20890

- build/Packages.json
- Update app baselines package version. New value: 24.2.20227.20903
- Update translation package version. New value: 24.3.20240618.3
> [24.x] Update app baselines package version. New value: 24.2.20227.20903 (+ 1 more update(s))

- build/Packages.json
- Update app baselines package version. New value: 24.0.16410.20902
> [24.1] Update app baselines package version. New value: 24.0.16410.20902

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.2.20227.20965
> [24.2] Update BCArtifact version. New value: 24.2.20227.20965

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.3.20962.0
> [24.x] Update BCArtifact version. New value: 24.3.20962.0

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 25.0.20968.0
> [main] Update BCArtifact version. New value: 25.0.20968.0

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.1.18927.20964
> [24.1] Update BCArtifact version. New value: 24.1.18927.20964

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.0.16410.20963
> [24.0] Update BCArtifact version. New value: 24.0.16410.20963

- .github/AL-Go-Settings.json
- build/projects/Business Foundation/.AL-Go/settings.json
- build/projects/Performance Toolkit/.AL-Go/settings.json
- build/projects/System Application Modules/.AL-Go/settings.json
- build/projects/System Application Tests/.AL-Go/settings.json
- build/projects/System Application/.AL-Go/settings.json
- build/projects/Test Framework/.AL-Go/settings.json
- build/projects/Test Stability Tools/.AL-Go/settings.json
Update path for ruleset file
Update path for ruleset file
Fixes [AB#538990](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/538990)
> Update path for ruleset file

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.0.16410.20986
> [24.0] Update BCArtifact version. New value: 24.0.16410.20986

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.3.20999.0
> [24.x] Update BCArtifact version. New value: 24.3.20999.0

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.2.20227.20970
> [24.2] Update BCArtifact version. New value: 24.2.20227.20970

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.1.18927.20975
> [24.1] Update BCArtifact version. New value: 24.1.18927.20975

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.0.16410.21040
> [24.0] Update BCArtifact version. New value: 24.0.16410.21040

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.2.20227.21047
> [24.2] Update BCArtifact version. New value: 24.2.20227.21047

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.3.21056.0
> [24.x] Update BCArtifact version. New value: 24.3.21056.0

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.3.21098.0
> [24.x] Update BCArtifact version. New value: 24.3.21098.0

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.1.18927.21093
> [24.1] Update BCArtifact version. New value: 24.1.18927.21093

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.2.20227.21094
> [24.2] Update BCArtifact version. New value: 24.2.20227.21094

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.0.16410.21082
> [24.0] Update BCArtifact version. New value: 24.0.16410.21082

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 25.0.21097.0
> [main] Update BCArtifact version. New value: 25.0.21097.0

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 25.0.21190.0
> [main] Update BCArtifact version. New value: 25.0.21190.0

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.2.20227.21188
> [24.2] Update BCArtifact version. New value: 24.2.20227.21188

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.0.16410.21178
> [24.0] Update BCArtifact version. New value: 24.0.16410.21178

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.1.18927.21189
> [24.1] Update BCArtifact version. New value: 24.1.18927.21189

- build/Packages.json
- Update app baselines package version. New value: 23.5.16502.21172
> [24.0] Update app baselines package version. New value: 23.5.16502.21172

- build/Packages.json
- Update app baselines package version. New value: 24.2.20227.21176
- Update translation package version. New value: 24.3.20240625.3
> [24.x] Update app baselines package version. New value: 24.2.20227.21176 (+ 1 more update(s))

- build/Packages.json
- Update app baselines package version. New value: 24.0.16410.21178
> [24.1] Update app baselines package version. New value: 24.0.16410.21178

- build/Packages.json
- Update app baselines package version. New value: 24.1.18927.21180
> [24.2] Update app baselines package version. New value: 24.1.18927.21180

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.3.21186.0
> [24.x] Update BCArtifact version. New value: 24.3.21186.0

- src/System Application/App/ControlAddIns/Resources/PowerBIManagement/js/PowerBIManagement.js
- src/System Application/App/ControlAddIns/src/PowerBIManagement.ControlAddin.al
- src/System Application/App/Resources/PowerBIManagement/js/PowerBIManagement.js
- src/System Application/App/Resources/PowerBIManagement/stylesheets/PowerBIManagement.css
This PR tackles a few minor limitations with the Power BI embedded experiences.
Allows to set the token for the embed experience separately, removes unnecessary logic to tweak the size of the part hosting the add-in, allows to set more granular settings for the embed experience.
Fixes [AB#538462](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/538462)
> [PowerBI] Add more flexible options for embedding, enable client resizing

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.1.18927.21238
> [24.1] Update BCArtifact version. New value: 24.1.18927.21238

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.2.20227.21239
> [24.2] Update BCArtifact version. New value: 24.2.20227.21239

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 25.0.21245.0
> [main] Update BCArtifact version. New value: 25.0.21245.0

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.0.16410.21240
> [24.0] Update BCArtifact version. New value: 24.0.16410.21240

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.3.21244.0
> [24.x] Update BCArtifact version. New value: 24.3.21244.0

- src/System Application/App/Retention Policy/src/Retention Policy Allowed Tables/RetenPolAllowedTblImpl.Codeunit.al
- src/System Application/Test/Performance Profiler/app.json
- src/System Application/Test/Performance Profiler/src/ScheduledPerfProfilingTest.Codeunit.al
This PR allows System App and Performance Profiler App to create retention policies for system tables
Fixes [AB#539065](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/539065)
> Fix retention policy allowed table issue and add test

- src/System Application/App/AI/src/Azure OpenAI/AzureOpenAIImpl.Codeunit.al
- src/System Application/App/DotNet Aliases/src/dotnet.al
Fixes [AB#539037](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/539037)
> [24.x][Copilot] Pass capability name to ALCopilotFunctions

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.2.20227.21302
> [24.2] Update BCArtifact version. New value: 24.2.20227.21302

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 25.0.21299.0
> [main] Update BCArtifact version. New value: 25.0.21299.0

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.3.21301.0
> [24.x] Update BCArtifact version. New value: 24.3.21301.0

- .github/AL-Go-Settings.json
- .github/workflows/CICD.yaml
- .github/workflows/DeployReferenceDocumentation.yaml
- .github/workflows/IncrementVersionNumber.yaml
- .github/workflows/PullRequestHandler.yaml
- .github/workflows/Troubleshooting.yaml
- .github/workflows/UpdateGitHubGoSystemFiles.yaml
- .github/workflows/_BuildALGoProject.yaml
- build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
- build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
- build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
- build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
- build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
- build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
- build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
- build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
- build/projects/System Application/.AL-Go/cloudDevEnv.ps1
- build/projects/System Application/.AL-Go/localDevEnv.ps1
- build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
- build/projects/Test Framework/.AL-Go/localDevEnv.ps1
- build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
- build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1
> [releases/24.x] Update AL-Go System Files - 4acdc62744cd82c1e8a15695b54a91e59e3d3d7c

- .github/AL-Go-Settings.json
- .github/workflows/CICD.yaml
- .github/workflows/DeployReferenceDocumentation.yaml
- .github/workflows/PullRequestHandler.yaml
- .github/workflows/Troubleshooting.yaml
- .github/workflows/UpdateGitHubGoSystemFiles.yaml
- .github/workflows/_BuildALGoProject.yaml
- build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
- build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
- build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
- build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
- build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
- build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
- build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
- build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
- build/projects/System Application/.AL-Go/cloudDevEnv.ps1
- build/projects/System Application/.AL-Go/localDevEnv.ps1
- build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
- build/projects/Test Framework/.AL-Go/localDevEnv.ps1
- build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
- build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1
> [releases/24.0] Update AL-Go System Files - 4acdc62744cd82c1e8a15695b54a91e59e3d3d7c

- .github/AL-Go-Settings.json
- .github/workflows/CICD.yaml
- .github/workflows/DeployReferenceDocumentation.yaml
- .github/workflows/IncrementVersionNumber.yaml
- .github/workflows/PullRequestHandler.yaml
- .github/workflows/Troubleshooting.yaml
- .github/workflows/UpdateGitHubGoSystemFiles.yaml
- .github/workflows/_BuildALGoProject.yaml
- build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
- build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
- build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
- build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
- build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
- build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
- build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
- build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
- build/projects/System Application/.AL-Go/cloudDevEnv.ps1
- build/projects/System Application/.AL-Go/localDevEnv.ps1
- build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
- build/projects/Test Framework/.AL-Go/localDevEnv.ps1
- build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
- build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1
> [releases/24.2] Update AL-Go System Files - 4acdc62744cd82c1e8a15695b54a91e59e3d3d7c

- .github/AL-Go-Settings.json
- .github/workflows/CICD.yaml
- .github/workflows/DeployReferenceDocumentation.yaml
- .github/workflows/IncrementVersionNumber.yaml
- .github/workflows/PullRequestHandler.yaml
- .github/workflows/Troubleshooting.yaml
- .github/workflows/UpdateGitHubGoSystemFiles.yaml
- .github/workflows/_BuildALGoProject.yaml
- build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
- build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
- build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
- build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
- build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
- build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
- build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
- build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
- build/projects/System Application/.AL-Go/cloudDevEnv.ps1
- build/projects/System Application/.AL-Go/localDevEnv.ps1
- build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
- build/projects/Test Framework/.AL-Go/localDevEnv.ps1
- build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
- build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1
> [main] Update AL-Go System Files - 4acdc62744cd82c1e8a15695b54a91e59e3d3d7c

- .github/AL-Go-Settings.json
- .github/workflows/CICD.yaml
- .github/workflows/DeployReferenceDocumentation.yaml
- .github/workflows/PullRequestHandler.yaml
- .github/workflows/Troubleshooting.yaml
- .github/workflows/UpdateGitHubGoSystemFiles.yaml
- .github/workflows/_BuildALGoProject.yaml
- build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
- build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
- build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
- build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
- build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
- build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
- build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
- build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
- build/projects/System Application/.AL-Go/cloudDevEnv.ps1
- build/projects/System Application/.AL-Go/localDevEnv.ps1
- build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
- build/projects/Test Framework/.AL-Go/localDevEnv.ps1
- build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
- build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1
> [releases/24.1] Update AL-Go System Files - 4acdc62744cd82c1e8a15695b54a91e59e3d3d7c

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.3.21333.0
> [24.x] Update BCArtifact version. New value: 24.3.21333.0

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 25.0.21343.0
> [main] Update BCArtifact version. New value: 25.0.21343.0

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.1.18927.21342
> [24.1] Update BCArtifact version. New value: 24.1.18927.21342

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.0.16410.21308
> [24.0] Update BCArtifact version. New value: 24.0.16410.21308

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.2.20227.21340
> [24.2] Update BCArtifact version. New value: 24.2.20227.21340

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.3.21374.0
> [24.3] Update BCArtifact version. New value: 24.3.21374.0

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.1.18927.21358
> [24.1] Update BCArtifact version. New value: 24.1.18927.21358

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.0.16410.21355
> [24.0] Update BCArtifact version. New value: 24.0.16410.21355

- src/Business Foundation/App/NoSeries/readme_refactoring.md
- src/Business Foundation/App/NoSeries/src/Legacy/NoSeriesManagement.Codeunit.al
If anyone has a better suggestion for the text within the documentation or the obsolete attribute. Please let me know.
Fixes #1405
Fixes [AB#539886](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/539886)
> Improve documentation and obsolete attribute for no. series refactoring

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.0.16410.21465
> [24.0] Update BCArtifact version. New value: 24.0.16410.21465

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.3.21374.21443
> [24.3] Update BCArtifact version. New value: 24.3.21374.21443

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.1.18927.21466
> [24.1] Update BCArtifact version. New value: 24.1.18927.21466

- build/Packages.json
- Update app baselines package version. New value: 23.5.16502.21459
> [24.0] Update app baselines package version. New value: 23.5.16502.21459

- build/Packages.json
- Update app baselines package version. New value: 24.2.20227.21467
- Update translation package version. New value: 24.3.20240628.3
> [24.3] Update app baselines package version. New value: 24.2.20227.21467 (+ 1 more update(s))

- build/Packages.json
- Update app baselines package version. New value: 24.1.18927.21466
> [24.2] Update app baselines package version. New value: 24.1.18927.21466

- build/Packages.json
- Update app baselines package version. New value: 24.0.16410.21465
> [24.1] Update app baselines package version. New value: 24.0.16410.21465

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.2.20227.21357
> [24.2] Update BCArtifact version. New value: 24.2.20227.21357

- src/Business Foundation/App/NoSeries/src/Legacy/NoSeriesManagement.Codeunit.al
- src/Business Foundation/App/NoSeries/src/Single/NoSeriesImpl.Codeunit.al
fixes an issue where a subscriber can no longer change the result from GetNextNo or PeekNextNo. The fix is for obsolete code only.
https://github.com/microsoft/BCApps/issues/1268
https://github.com/microsoft/ALAppExtensions/issues/26721
Fixes [AB#539238](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/539238)
> fixes an issue where a subscriber can no longer change the result from GetNextNo or PeekNextNo. The fix is for obsolete code only.

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.4.21521.0
> [24.x] Update BCArtifact version. New value: 24.4.21521.0

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.3.21374.21517
> [24.3] Update BCArtifact version. New value: 24.3.21374.21517

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.0.16410.21514
> [24.0] Update BCArtifact version. New value: 24.0.16410.21514

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.1.18927.21516
> [24.1] Update BCArtifact version. New value: 24.1.18927.21516

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.2.20227.21515
> [24.2] Update BCArtifact version. New value: 24.2.20227.21515

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.4.21546.0
> [24.x] Update BCArtifact version. New value: 24.4.21546.0

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.2.20227.21529
> [24.2] Update BCArtifact version. New value: 24.2.20227.21529

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.3.21374.21547
> [24.3] Update BCArtifact version. New value: 24.3.21374.21547

- src/Tools/AI Test Toolkit/app.json
- src/Tools/AI Test Toolkit/src/AITTestContext.Codeunit.al
- src/Tools/AI Test Toolkit/src/AITTestRunner.Codeunit.al
- src/Tools/AI Test Toolkit/src/API/AITLogEntryAPI.Page.al
- src/Tools/AI Test Toolkit/src/API/AITSuiteAPI.Page.al
- src/Tools/AI Test Toolkit/src/API/AITSuiteLineAPI.Page.al
- src/Tools/AI Test Toolkit/src/CommandLineCard.Page.al
- src/Tools/AI Test Toolkit/src/Logs/AITLogEntries.Page.al
- src/Tools/AI Test Toolkit/src/Logs/AITLogEntry.Codeunit.al
- src/Tools/AI Test Toolkit/src/Logs/AITLogEntry.Table.al
- src/Tools/AI Test Toolkit/src/Logs/AITTestMethodLinesCompare.Page.al
- src/Tools/AI Test Toolkit/src/Logs/AITTestSuiteCompare.Page.al
- src/Tools/AI Test Toolkit/src/SampleTests/DemoSuite/SentenceValidator.Codeunit.al
- src/Tools/AI Test Toolkit/src/SampleTests/MarketingTextSample/MarketingTextQualityTest.Codeunit.al
- src/Tools/AI Test Toolkit/src/SampleTests/SalesLinesSuggestionsSample/SLSAccuracyTest.Codeunit.al
- src/Tools/AI Test Toolkit/src/TestSuite/AITALTestSuiteMgt.Codeunit.al
- src/Tools/AI Test Toolkit/src/TestSuite/AITLineStatus.Enum.al
- src/Tools/AI Test Toolkit/src/TestSuite/AITTestMethodLine.Table.al
- src/Tools/AI Test Toolkit/src/TestSuite/AITTestMethodLines.Page.al
- src/Tools/AI Test Toolkit/src/TestSuite/AITTestSuite.Page.al
- src/Tools/AI Test Toolkit/src/TestSuite/AITTestSuite.Table.al
- src/Tools/AI Test Toolkit/src/TestSuite/AITTestSuiteImportExport.XmlPort.al
- src/Tools/AI Test Toolkit/src/TestSuite/AITTestSuiteList.Page.al
- src/Tools/AI Test Toolkit/src/TestSuite/AITTestSuiteMgt.Codeunit.al
- src/Tools/AI Test Toolkit/src/TestSuite/AITTestSuiteStatus.Enum.al
- src/Tools/Test Framework/Test Runner/app.json
- src/Tools/Test Framework/Test Runner/src/TestMethodLine.Table.al
> Nikolak/stefan maron review/ai test tooklit

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.0.16410.21569
> [24.0] Update BCArtifact version. New value: 24.0.16410.21569

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.4.21579.0
> [24.x] Update BCArtifact version. New value: 24.4.21579.0

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.1.18927.21567
> [24.1] Update BCArtifact version. New value: 24.1.18927.21567

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.3.21374.21561
> [24.3] Update BCArtifact version. New value: 24.3.21374.21561

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.2.20227.21613
> [24.2] Update BCArtifact version. New value: 24.2.20227.21613

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.4.21616.0
> [24.x] Update BCArtifact version. New value: 24.4.21616.0

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.1.18927.21622
> [24.1] Update BCArtifact version. New value: 24.1.18927.21622

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.3.21374.21615
> [24.3] Update BCArtifact version. New value: 24.3.21374.21615

- src/Tools/Test Framework/Test Runner/app.json
Revert Test Runner to v 25.0
Fixes [AB#540487](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/540487)
> Revert Test Runner to v 25.0

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.0.16410.21633
> [24.0] Update BCArtifact version. New value: 24.0.16410.21633

- src/System Application/App/Performance Profiler/permissions/PerfProfilerTablesEdit.permissionset.al
- src/System Application/App/Performance Profiler/src/PerfProfilerScheduleCard.Page.al
- src/System Application/App/Performance Profiler/src/PerfProfilerSchedulesList.Page.al
This PR gives the correct permissions for the scheduled profile pages to insert,delete and modify data in SaaS.
It gives permissions to insert,modify, delete on the pages.
Fixes [AB#501774](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/501774)
> Scheduled Profiler - Fix permissions

- src/Tools/Test Framework/Test Runner/src/DataDrivenTest/DataInputs/TestInput.Table.al
- src/Tools/Test Framework/Test Runner/src/DataDrivenTest/DataInputs/TestInputGroup.Table.al
- src/Tools/Test Framework/Test Runner/src/DataDrivenTest/DataOutputs/TestOutput.Table.al
> Add replicate data false properties

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.4.21700.0
> [24.x] Update BCArtifact version. New value: 24.4.21700.0

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.3.21374.21695
> [24.3] Update BCArtifact version. New value: 24.3.21374.21695

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.1.18927.21698
> [24.1] Update BCArtifact version. New value: 24.1.18927.21698

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.0.16410.21699
> [24.0] Update BCArtifact version. New value: 24.0.16410.21699

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.2.20227.21697
> [24.2] Update BCArtifact version. New value: 24.2.20227.21697

- build/Packages.json
- Update app baselines package version. New value: 23.5.16502.21696
> [24.0] Update app baselines package version. New value: 23.5.16502.21696

- build/Packages.json
- Update app baselines package version. New value: 24.2.20227.21697
> [24.3] Update app baselines package version. New value: 24.2.20227.21697

- build/Packages.json
- Update app baselines package version. New value: 24.1.18927.21698
> [24.2] Update app baselines package version. New value: 24.1.18927.21698

- build/Packages.json
- Update app baselines package version. New value: 24.3.21374.21695
> [24.x] Update app baselines package version. New value: 24.3.21374.21695

- src/System Application/App/VS Code Integration/Permissions/VSCIntgrAdmin.PermissionSet.al
- src/System Application/App/VS Code Integration/app.json
- src/System Application/App/VS Code Integration/src/VsCodeIntegration.Codeunit.al
- src/System Application/App/VS Code Integration/src/VsCodeIntegrationImpl.Codeunit.al
Fixes AB#1525
Fixes #1525 1525
> Move objects out of the Cloud Manager scope

- .github/AL-Go-Settings.json
- .github/workflows/CICD.yaml
- .github/workflows/DeployReferenceDocumentation.yaml
- .github/workflows/IncrementVersionNumber.yaml
- .github/workflows/PullRequestHandler.yaml
- .github/workflows/Troubleshooting.yaml
- .github/workflows/UpdateGitHubGoSystemFiles.yaml
- .github/workflows/_BuildALGoProject.yaml
- build/projects/AI Test Toolkit/.AL-Go/cloudDevEnv.ps1
- build/projects/AI Test Toolkit/.AL-Go/localDevEnv.ps1
- build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
- build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
- build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
- build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
- build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
- build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
- build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
- build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
- build/projects/System Application/.AL-Go/cloudDevEnv.ps1
- build/projects/System Application/.AL-Go/localDevEnv.ps1
- build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
- build/projects/Test Framework/.AL-Go/localDevEnv.ps1
- build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
- build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1
[AB#420000](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/420000)
> [main] Update AL-Go System Files - 0aab342a0ddd80612fafbc5149c8e95b3476b12a

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.0.16410.21743
> [24.0] Update BCArtifact version. New value: 24.0.16410.21743

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.4.21738.0
> [24.x] Update BCArtifact version. New value: 24.4.21738.0

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.3.21374.21739
> [24.3] Update BCArtifact version. New value: 24.3.21374.21739

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.1.18927.21740
> [24.1] Update BCArtifact version. New value: 24.1.18927.21740

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.2.20227.21742
> [24.2] Update BCArtifact version. New value: 24.2.20227.21742

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.2.20227.21781
> [24.2] Update BCArtifact version. New value: 24.2.20227.21781

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.3.21374.21783
> [24.3] Update BCArtifact version. New value: 24.3.21374.21783

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.0.16410.21764
> [24.0] Update BCArtifact version. New value: 24.0.16410.21764

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.1.18927.21780
> [24.1] Update BCArtifact version. New value: 24.1.18927.21780

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.4.21774.0
> [24.x] Update BCArtifact version. New value: 24.4.21774.0

- src/Business Foundation/App/NoSeries/src/Single/NoSeriesImpl.Codeunit.al
- src/Business Foundation/Test/NoSeries/src/NoSeriesTests.Codeunit.al
Improve the error message for trying to get a No Series Line with empty No Series Code.
Fixes [AB#540869](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/540869)
> Improve error message

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.3.21374.21813
> [24.3] Update BCArtifact version. New value: 24.3.21374.21813

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.1.18927.21812
> [24.1] Update BCArtifact version. New value: 24.1.18927.21812

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.0.16410.21814
> [24.0] Update BCArtifact version. New value: 24.0.16410.21814

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.4.21815.0
> [24.x] Update BCArtifact version. New value: 24.4.21815.0

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.2.20227.21811
> [24.2] Update BCArtifact version. New value: 24.2.20227.21811

- src/Business Foundation/App/NoSeries/src/Setup/NoSeriesSetupImpl.Codeunit.al
- src/Business Foundation/App/NoSeries/src/Single/NoSeries.Codeunit.al
- src/Business Foundation/App/NoSeries/src/Single/NoSeriesImpl.Codeunit.al
- src/Business Foundation/Test/NoSeries/src/NoSeriesTests.Codeunit.al
This pull request backports #1519 to releases/24.x
Fixes [AB#540058](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/540058)
> [releases/24.x] Fix empty No Series code in GetNoSeriesLine

- src/System Application/App/Entitlements/DelegatedAdminagentPartner.Entitlement.al
- src/System Application/App/Entitlements/DelegatedBCAdminAgentPartner.Entitlement.al
- src/System Application/App/Entitlements/DelegatedHelpdeskagentPartner.Entitlement.al
- src/System Application/App/Entitlements/Dynamics365AdminPartner.Entitlement.al
- src/System Application/App/VS Code Integration/Permissions/VSCIntgrAdmin.PermissionSet.al
Fixes [AB#536535](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/536535)
> Fix permissions for 'VS Code Integration - Admin'

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.2.20227.21875
> [24.2] Update BCArtifact version. New value: 24.2.20227.21875

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.3.21374.21873
> [24.3] Update BCArtifact version. New value: 24.3.21374.21873

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.4.21878.0
> [24.x] Update BCArtifact version. New value: 24.4.21878.0

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.0.16410.21874
> [24.0] Update BCArtifact version. New value: 24.0.16410.21874

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.1.18927.21876
> [24.1] Update BCArtifact version. New value: 24.1.18927.21876

- src/System Application/App/AI/app.json
- src/System Application/App/Entity Text/app.json
- src/System Application/App/Entity Text/src/EntityText.Codeunit.al
- src/System Application/App/Entity Text/src/EntityTextFactboxPart.Page.al
- src/System Application/App/Entity Text/src/EntityTextImpl.Codeunit.al
- src/System Application/App/Entity Text/src/EntityTextPart.Page.al
- src/System Application/App/Entity Text/src/EntityTextPrompts.Codeunit.al
- src/System Application/App/Entity Text/src/FunctionsImpl/GenerateProdMktAdFunction.Codeunit.al
- src/System Application/App/Entity Text/src/FunctionsImpl/MagicFunction.Codeunit.al
Improvements done to marketing text feature by introduction functions and upgrading the model to gpt4o. The changes were merged into main as part of this PR  #1275 
This PR backports this change into 24.x
-  #1275 
Fixes # [AB#521281](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/521281)
> [24X][Copilot] Marketing Text Improvements - Functions and GPT4o 

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.2.20227.21882
> [24.2] Update BCArtifact version. New value: 24.2.20227.21882

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.0.16410.21899
> [24.0] Update BCArtifact version. New value: 24.0.16410.21899

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.1.18927.21904
> [24.1] Update BCArtifact version. New value: 24.1.18927.21904

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.3.21374.21898
> [24.3] Update BCArtifact version. New value: 24.3.21374.21898

- build/Packages.json
- Update app baselines package version. New value: 23.5.16502.21869
> [24.0] Update app baselines package version. New value: 23.5.16502.21869

- build/Packages.json
- Update app baselines package version. New value: 24.2.20227.21882
> [24.3] Update app baselines package version. New value: 24.2.20227.21882

- build/Packages.json
- Update app baselines package version. New value: 24.0.16410.21899
> [24.1] Update app baselines package version. New value: 24.0.16410.21899

- build/Packages.json
- Update app baselines package version. New value: 24.3.21374.21898
> [24.x] Update app baselines package version. New value: 24.3.21374.21898

- build/Packages.json
- Update app baselines package version. New value: 24.1.18927.21904
> [24.2] Update app baselines package version. New value: 24.1.18927.21904

- src/Business Foundation/Test Library/NoSeries/src/LibraryNoSeries.Codeunit.al
This PR introduces a helper function to easily create a No. Series with all the common parameters you may need and a function to quickly create relationships between two No. Series.
This is needed to cleanup No. Series from our utility library codeunit in BaseApp.
Fixes [AB#541694](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/541694)
> [No. Series] Test Library helper functions to create No. Series and Relationship

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.4.21986.0
> [24.x] Update BCArtifact version. New value: 24.4.21986.0

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.1.18927.21974
> [24.1] Update BCArtifact version. New value: 24.1.18927.21974

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.0.16410.21990
> [24.0] Update BCArtifact version. New value: 24.0.16410.21990

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.3.21374.21987
> [24.3] Update BCArtifact version. New value: 24.3.21374.21987

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.2.20227.21988
> [24.2] Update BCArtifact version. New value: 24.2.20227.21988

- src/System Application/App/Entity Text/app.json
- src/System Application/App/Entity Text/src/EntityText.Codeunit.al
- src/System Application/App/Entity Text/src/EntityTextFactboxPart.Page.al
- src/System Application/App/Entity Text/src/EntityTextImpl.Codeunit.al
- src/System Application/App/Entity Text/src/EntityTextPart.Page.al
- src/System Application/App/Entity Text/src/EntityTextPrompts.Codeunit.al
- src/System Application/App/Entity Text/src/FunctionsImpl/GenerateProdMktAdFunction.Codeunit.al
- src/System Application/App/Entity Text/src/FunctionsImpl/MagicFunction.Codeunit.al
Improvements done to marketing text feature by introduction functions and upgrading the model to gpt4o. The changes were merged into main as part of this PR  #1275 
This PR backports this change into 24.3
-  #1275 
Fixes # [AB#521281](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/521281)
> [242][Copilot] Marketing Text Improvements - Functions and GPT4o

- src/System Application/App/Entity Text/app.json
Update dependency version in Entity Text app.json
[AB#521281](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/521281)
[AB#542450](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/542450)
> Update dependency version in Entity Text app.json

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.3.21374.22091
> [24.3] Update BCArtifact version. New value: 24.3.21374.22091

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.4.22094.0
> [24.x] Update BCArtifact version. New value: 24.4.22094.0

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.1.18927.22093
> [24.1] Update BCArtifact version. New value: 24.1.18927.22093

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.0.16410.22090
> [24.0] Update BCArtifact version. New value: 24.0.16410.22090

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.2.20227.22092
> [24.2] Update BCArtifact version. New value: 24.2.20227.22092

- src/Tools/AI Test Toolkit/src/AITCommandLineCard.Page.al
- src/Tools/AI Test Toolkit/src/API/AITLogEntryAPI.Page.al
- src/Tools/AI Test Toolkit/src/Logs/AITLogEntries.Page.al
- src/Tools/AI Test Toolkit/src/Logs/AITTestMethodLinesCompare.Page.al
- src/Tools/AI Test Toolkit/src/TestSuite/AITALTestSuiteMgt.Codeunit.al
- src/Tools/AI Test Toolkit/src/TestSuite/AITTestMethodLine.Table.al
- src/Tools/AI Test Toolkit/src/TestSuite/AITTestMethodLines.Page.al
- src/Tools/AI Test Toolkit/src/TestSuite/AITTestSuite.Page.al
- src/Tools/AI Test Toolkit/src/TestSuite/AITTestSuite.Table.al
- src/Tools/AI Test Toolkit/src/TestSuite/AITTestSuiteList.Page.al
- src/Tools/AI Test Toolkit/src/TestSuite/AITTestSuiteMgt.Codeunit.al
Fixes [AB#540527](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/540527)
> Bugs/540527 AI test toolkit fix pending code review comments and minor improvements

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.2.20227.22123
> [24.2] Update BCArtifact version. New value: 24.2.20227.22123

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.4.22126.0
> [24.x] Update BCArtifact version. New value: 24.4.22126.0

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.1.18927.22100
> [24.1] Update BCArtifact version. New value: 24.1.18927.22100

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.0.16410.22101
> [24.0] Update BCArtifact version. New value: 24.0.16410.22101

- build/Packages.json
- Update app baselines package version. New value: 24.0.16410.22101
> [24.1] Update app baselines package version. New value: 24.0.16410.22101

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.3.21374.22127
> [24.3] Update BCArtifact version. New value: 24.3.21374.22127

- build/Packages.json
- Update app baselines package version. New value: 24.1.18927.22100
> [24.2] Update app baselines package version. New value: 24.1.18927.22100

- build/Packages.json
- Update app baselines package version. New value: 23.5.16502.22087
> [24.0] Update app baselines package version. New value: 23.5.16502.22087

- build/Packages.json
- Update app baselines package version. New value: 24.3.21374.22127
- Update translation package version. New value: 24.4.20240719.1
> [24.x] Update app baselines package version. New value: 24.3.21374.22127 (+ 1 more update(s))

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 25.0.22173.0
> [main] Update BCArtifact version. New value: 25.0.22173.0

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.3.21374.22150
> [24.3] Update BCArtifact version. New value: 24.3.21374.22150

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.2.20227.22149
> [24.2] Update BCArtifact version. New value: 24.2.20227.22149

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.1.18927.22151
> [24.1] Update BCArtifact version. New value: 24.1.18927.22151

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.4.22170.0
> [24.x] Update BCArtifact version. New value: 24.4.22170.0

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.0.16410.22152
> [24.0] Update BCArtifact version. New value: 24.0.16410.22152

- .github/actions/RunAutomation/run.ps1
> Link automations to 539394

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.2.20227.22205
> [24.2] Update BCArtifact version. New value: 24.2.20227.22205

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.1.18927.22200
> [24.1] Update BCArtifact version. New value: 24.1.18927.22200

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.4.22212.0
> [24.x] Update BCArtifact version. New value: 24.4.22212.0

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.0.16410.22202
> [24.0] Update BCArtifact version. New value: 24.0.16410.22202

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.3.21374.22201
> [24.3] Update BCArtifact version. New value: 24.3.21374.22201

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.2.20227.22265
> [24.2] Update BCArtifact version. New value: 24.2.20227.22265

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.1.18927.22264
> [24.1] Update BCArtifact version. New value: 24.1.18927.22264

- .github/AL-Go-Settings.json
- Update BCArtifact version. New value: 24.4.22260.0
> [24.x] Update BCArtifact version. New value: 24.4.22260.0
