microsoft/BCApps

.azuredevops/SyncMirroredRepository.yml

Remove GitHubPAT from Sync pipeline. Not needed anymore now that BCApps is public

Remove GitHubPAT from Sync pipeline

---

src/System Application/App/Extension Management/src/UploadAndDeployExtension.Page.al

Make it clear in the UI that we are referring to 3rd party extensions, not Microsoft extensions.
* Remove the “Microsoft Business Central “ – have “Per Tenant Extension (PTE) Disclaimer”
* Remove completely the link to our Privacy and  cookies
* Add to the following UI (after clicking Deploy) the following sentences “By deploying this extension you acknowledge that your data may be sent outside the compliance boundary of Business Central. Each per tenant extension is subject to its own third party terms and conditions and privacy policies.”

Update UploadAndDeployExtension.Page.al to make it clear that we are referring to 3rd party extensions

---

src/System Application/App/Extension Management/src/ExtensionMarketplace.Page.al

I often find myself searching for 'AppSource' via 'Tell me' to install apps from AppSource, but don't get the expected 'Extension Marketplace' page in the search results. 
It would be nice if the 'Extension Marketplace' page was discoverable using the same keywords (at least 'appsource'), similar to the 'Extension Management' page. 
`AdditionalSearchTerms = 'app,add-in,customize,plug-in,appsource';`
_AppSource_ seems to be a valid search term as well in the BC community, compared to just 'marketplace'...
---
Fixes #370
<br /><br />Internal work item: AB#492551

Make the 'Extension Marketplace' page discoverable with 'AppSource' search term

---

src/System Application/App/Email/src/Email/Sent/EmailViewer.Page.al

The EmailViewer is using the Email Account's "Email Address" field. This is always the current user's email and not the email address of the user who sent the email.
This PR uses the stored Sent Email's "Sent From" to show the correct email address of the sender.
Fixes AB#491830

[Email] Use Sent From email in EmailViewer

---

src/System Application/App/Azure AD Tenant/src/AzureADTenant.Codeunit.al
src/System Application/App/Azure AD Tenant/src/AzureADTenantImpl.Codeunit.al

When working with W1 base applications it is challenging to figure out the country or prefered language.
Exposing countryLetterCode and preferredLanguage form the Organizational Information page in Microsoft Administration Center enables better defaulting.
Fixes #408
Internal work item: AB#493149

Add access to countryLetterCode and preferredLanguage from tenant info.

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

- `templateSha`: The SHA of the version of AL-Go currently used
- `DumpWorkflowInfo`: Dump information about running workflow
- `Troubleshooting` : Run troubleshooting for repository
Add another parameter when running Update AL-Go System Files, called downloadLatest, used to indicate whether to download latest version from template repository. Default value is true.
If false, the templateSha repository setting is used to download specific AL-Go System Files when calculating new files.
- Issue 782 Exclude '.altestrunner/' from template .gitignore
- Issue 823 Dependencies from prior build jobs are not included when …

Updated AL-Go System Files

---

src/Tools/Test Framework/Test Libraries/Any/src/Any.Codeunit.al

GetSeed() procedure for CU Any. It required a small refactoring for the SetDefaultSeed() procedure to explicitly define the seed instead of the implicit definition using Randomize(). The value used as seed is still the same.
Fixes #398
<br /><br />Internal work item: AB#493044

#398 GetSeed for CU Any

---

src/System Application/App/Confirm Management/src/ConfirmManagement.Codeunit.al

In most cases where we want the user to confirm an action, we set the default button to true. This will set the focus to the specific button so that the user can simply press enter and continue.
DefaultButton should be set to false on critical actions manually.
*Note*: When I first read the DefaultButton parameter, I thought that this parameter would also be applied if the confirmation page was canceled by pressing <kbd>Esc</kbd>, for example. However, this is not the case. The DefaultButton parameter only sets the focus on the button.
Fixes #436
<br /><br />Internal work item: AB#495008

Add procedures with defaultButton true

---

.github/workflows/WorkitemValidation.yaml

Right now work item validation also runs when the PR is closed. Let's not do that 😄 
Fixes [AB#495038](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/495038)

Skip workitem validation when PR is closed

---

src/Tools/Test Framework/Test Libraries/Any/src/Any.Codeunit.al

Time-0T will throw an error.
Fixes [AB#495083](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/495083)

Fix error "The date is not valid." in SetDefaultSeed

---

src/System Application/Test/URI/src/UriBuilderTest.Codeunit.al

This updates port validation error text assertions in UriBuilderTest.Codeunit.al to align with updated underlying exception message changed in .NET 8. The old validation texts remain to keep compatibility with platform versions based on .NET 6.
Fixes [AB#477674](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/477674)

[main] [net8] UriBuilderTest.Codeunit.al - update port validation error text

---

src/System Application/App/Azure Blob Services API/src/Helper/ABSFormatHelper.Codeunit.al

**Description**
When the "FindBlobsByTags" function is invoked, the expression is encoded during the creation using the "TagsDictionaryToSearchExpression" function. Later in the functionality,
"PrepareRequestMsg -> ConstructUri -> AddOptionalUriParameters -> AppendToUri"
the URL along with the parameter string (expression) will be encoded again, leading to incorrect encoding of the parameters.
**Resolution**
Removed the encoding step in the "TagsDictionaryToSearchExpression" function.
Fixes #450
**Work Item(s)**
[Bug]: "FindBlobsByTags" feature escapes parameters two timest https://github.com/microsoft/BCApps/issues/450
#450 https://github.com/microsoft/BCApps/issues/450
<br /><br />Internal work item: [AB#495470](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_ …

"FindBlobsByTags" feature escapes parameters two times

---

src/System Application/App/Guided Experience/src/Guided Experience/GuidedExperienceItemCleanup.Page.al

When no duplicated guided experience item is presented, the current logic will show an empty line.
Adding check to see if there is any record retrieved.
Fixes [AB#485933](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/485933)

fix empty record is shown when no data is fetched

---

src/System Application/App/Data Administration/src/MediaCleanupFactbox.Page.al
src/System Application/App/Email/src/Account/EmailAccountWizard.Page.al
src/System Application/App/Email/src/Account/EmailAccounts.Page.al
src/System Application/App/Web Service Management/src/WebServiceManagementImpl.Codeunit.al
src/rulesets/ruleset.json

Turn codecop AW0009 and AS0059 into errors.
Using pragmas instead of fixing due to following reasons:
AS0059: Table needs to be changed to temporary. Codecop was added due to their specific apparently.
AW0009: The places where the bitmaps are used, aren't one of the supported places for media/mediaset fields.
Fx, list of records. The only time it works, is if it is showing in a tile view, which for Emails, we are not.
The MediaCleanup uses Tenant Media record directly, which is a blob.
Fixes [AB#487172](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/487172)

Turn AW0009 and AS0059 warnings into errors

---

src/System Application/App/Security Groups/src/SecurityGroupImpl.Codeunit.al

**Problem:**
The code for deleting orphaned security groups starts with:
```
if not User.WritePermission() then
exit;
```
But in SaaS no entitlement has insert permission to the user table, so this check always fails. Unfortunately, there is no way to check for delete permission separately.
**Solution:**
Remove the check and protect the deletion operation with `if not ... then`.
Fixes [AB#496007](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/496007)

Remove the faulty permission check in the RemoveOrphanedEntraGroups function

---

.github/AL-Go-Settings.json

Setting `enableCodeAnalyzersOnTestApps` to true means code analyzers will be applied to test apps the same way they are applied to normal (non-test) apps.
Pending AL-Go preview release and uptake ✅
Fixes [AB#495937](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/495937)

Set enableCodeAnalyzersOnTestApps to true

---

src/System Application/App/app.json

Clean AllowExtensionAndTargetInSameModule from manifests because the flag isn't needed and has been removed from the compiler
Fixes [AB#496866](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/496866)

Clean AllowExtensionAndTargetInSameModule from manifests

---

src/System Application/Test/Auto Format/src/AutoFormatTest.EnumExt.al

Ignores rule PTE0023 inline because ID space is too small to accommodate enum value.
Fixes
[AB#487991](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/487991)

Address upcoming PTECop rule in test enum extension - part 2

---

src/System Application/App/Azure Key Vault/src/AzureKeyVault.Codeunit.al
src/System Application/App/Azure Key Vault/src/AzureKeyVaultImpl.Codeunit.al
src/System Application/App/Secrets/src/AppKeyVaultSecretPrImpl.Codeunit.al
src/System Application/App/Secrets/src/AppKeyVaultSecretProvider.Codeunit.al
src/System Application/App/Secrets/src/InMemorySecretProvImpl.Codeunit.al
src/System Application/App/Secrets/src/InMemorySecretProvider.Codeunit.al
src/System Application/App/Secrets/src/SecretProvider.Interface.al
src/System Application/App/Secrets/src/SecretProviderv2.Interface.al
src/System Application/Test/Secrets/app.json
src/System Application/Test/Secrets/src/AppKeyVaultSecretProTest.Codeunit.al
src/System Application/Test/Secrets/src/InMemorySecretProviderTest.Codeunit.al

When working with Azure KeyVault it should be possible to get secrets as SecretText.
Fixes [AB#493425](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/493425)

Add SecretText overload

---

src/System Application/App/Edit in Excel/src/EditinExcelImpl.Codeunit.al
src/System Application/Test/Edit in Excel/src/EditInExcelTest.Codeunit.al

The issue
Edit-In Excel module does not externalize page field names the same way the platform does, when the field name contains an apostrophe.
For a page field defined as:
```
field("new vendor's name"; rec."New Vendor's Name")
{
ApplicationArea = All;
}
```
The platform will externalize this name as `new_vendor_x0027_s_name` while the Edit-In Excel module will externalize it as `new_vendor_s_name`.
Expected behavior
Within reason the platform and the Edit-In Excel module should externalize fields the same way to avoid discrepancies between the API metadata and the Edit-In Excel field bindings.
Steps to reproduce
Create a page field with an apostrophe in its name on a card page, then try to export its corresponding list page using Edit-In Excel and observe the error dialog in the Excel …

Allow apostrophes in page field names for edit in excel

---

src/System Application/App/Azure AD Plan/src/AzureADPlanImpl.Codeunit.al
src/System Application/App/User Permissions/src/UserPermissionsImpl.Codeunit.al
src/System Application/Test/Azure AD Plan/src/AzureADPlanTests.Codeunit.al
src/System Application/Test/DisabledTests/AzureADPlanTests.DisabledTest.json

**Problem:**
`User Permissions` module implementation only considers permission sets directly assigned to the user. This means that a lot of scenarios don't work when certain permission sets are assigned to users via security groups.
**Solution:**
Uptake a new platform function `NavUserAccountHelper.IsPermissionSetAssigned` that checks both direct and inherited permission sets.
Fixes [AB#481017](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/481017)

Consider permission sets from security groups in the User Permissions module 

---

src/System Application/App/Permissions/SystemApplicationObjects.PermissionSet.al
src/System Application/App/Table Keys/app.json
src/System Application/App/Table Keys/permissions/TableKeyObjects.PermissionSet.al
src/System Application/App/Table Keys/src/TableKey.Codeunit.al
src/System Application/App/Table Keys/src/TableKeyImpl.Codeunit.al

It has been shown that disabling keys (indexes) allows for faster mass deletion of records.
Introducing a new module that would allow AL code to disable indexes before mass deletion / insertion / modification of records in a table.
Fixes [AB#494937](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/494937)

Introduce the "Table Key" module

---

src/System Application/Test/Azure AD User Management/src/AzureADUserSyncTest.Codeunit.al

**Problem:**
The test `TestMixedPlansDetected` is currently not verifying the correct error message. It was always meant to check for non-admin error, as the test does not set up the current user as the admin user. The PR #497 uncovered this issue, but the test is disabled in the BC Apps gate, so this was not cought before.
**Solution:**
Use the correct error message in the test verification step.
Fixes [AB#497693](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/497693)

Fix the error message in the TestMixedPlansDetected test

---

src/System Application/App/Filter Tokens/src/FilterTokensImpl.Codeunit.al

The case expects uppercase tokens. We must turn the input filter token into uppercase before we do the compare.
Fixes [AB#483241](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/483241)

Turn time token to uppercase before compare

---

src/Tools/Performance Toolkit/App/src/BCPTHeader.Table.al

Updated the max runtime from 4 hrs to 8 hrs
Fixes [AB#492402](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/492402)

Updating the max runtime for a BCPT suite from 4 hrs to 8 hrs

---

src/System Application/App/Entity Text/src/EntityTextImpl.Codeunit.al

When setting Marketing Text authorization parameters, passed endpoint was set as both endpoint and deployment.
When calling from 1st party module, custom auth was overwritten with default one.
Both issues are addressed in this PR
Fixes [AB#498109](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/498109)

Fix setting marketing text authorization

---

src/System Application/App/Email/src/Email/Email.Codeunit.al
src/System Application/App/Email/src/Email/EmailImpl.Codeunit.al
src/System Application/App/Email/src/Email/Sent/SentEmails.Page.al

Extended the access to the filter field "NewerThanDate" in the sent emails:
- new function with extended parameters for opening sent emails filtered to the source record and a specific date.
- removed the internal flag to set the date directly when opening the sent emails.
- "If" added so that the NewerThanDate is only overwritten with the "30 days filter" if it was previously empty.
Fixes #430  
Fixes [AB#497966](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/497966)

#430 | Access to NewerThanDate in sent emails

---

src/System Application/App/Extension Management/permissions/ExtensionManagementObjects.PermissionSet.al
src/System Application/App/Extension Management/src/ExtensionManagement.Page.al
src/System Application/App/Extension Management/src/ExtensionMarketplace.Codeunit.al
src/System Application/App/Extension Management/src/ExtensionMarketplace.Page.al

The Extension Marketplace page is using an embeded view of Microsoft AppSource and the endpoint will be discontinued in 2024.
Marking the page as obsolete and that it will be replaced with a new Microsoft AppSource apps feature providing similar functionality.
Fixes [AB#493421](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/493421)

Obsolete Extension Marketplace page

---

src/Business Foundation/App/NoSeries/Permissions/NoSeriesObjects.permissionset.al
src/Business Foundation/App/NoSeries/src/Batch/NoSeriesBatch.Codeunit.al
src/Business Foundation/App/NoSeries/src/Batch/NoSeriesBatchImpl.Codeunit.al
src/Business Foundation/App/NoSeries/src/GlobalNoSeries/CrossCompanyNoSeries.Codeunit.al
src/Business Foundation/App/NoSeries/src/GlobalNoSeries/NoSeriesTenant.Table.al
src/Business Foundation/App/NoSeries/src/Legacy/NoSeriesLinePurchase.Table.al
src/Business Foundation/App/NoSeries/src/Legacy/NoSeriesLineSales.Table.al
src/Business Foundation/App/NoSeries/src/Legacy/NoSeriesManagement.Codeunit.al
src/Business Foundation/App/NoSeries/src/Legacy/NoSeriesMgt.Codeunit.al
src/Business Foundation/App/NoSeries/src/Setup/NoSeries.Table.al
src/Business Foundation/App/NoSeries/src/Setup/NoSeriesLine.Table.al
src/Business Foundation/App/NoSeries/src/Setup/NoSeriesRelationship.Table.al
src/Business Foundation/App/NoSeries/src/Setup/NoSeriesSetupImpl.Codeunit.al
src/Business Foundation/App/NoSeries/src/Single/NoSeries.Codeunit.al
src/Business Foundation/App/NoSeries/src/Single/NoSeriesImpl.Codeunit.al
src/Business Foundation/App/NoSeries/src/Single/NoSeriesSequenceImpl.Codeunit.al
src/Business Foundation/App/NoSeries/src/Single/NoSeriesStatelessImpl.Codeunit.al
src/Business Foundation/Test/NoSeries/src/NoSeriesBatchTests.Codeunit.al
src/Business Foundation/Test/NoSeries/src/NoSeriesTest.PermissionSet.al
src/Business Foundation/Test/NoSeries/src/NoSeriesTests.Codeunit.al
src/Tools/Test Framework/Test Libraries/Permissions Mock/src/PermissionsMock.Codeunit.al

The No. Series module should be able to use regardless of your permissions (but not the setup). Adding tests to that end.
Fixes [AB#498331](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/498331)

Add permissions test for No. Series

---

build/projects/System Application Modules/.AL-Go/settings.json
src/Business Foundation/App/NoSeries/Permissions/NoSeriesObjects.permissionset.al

[This commit](https://github.com/microsoft/BCApps/commit/c3d7199abd512b097f2ee14b64d2fca748ca662a#diff-77a9a7aace577cc7e70bf88632510803ab1784e976b4b1132f19cb1f1a97e224) changes the app folders for _System Application Modules_ project which cause no apps to be built:
> No performance test apps found in bcptTestFolders in .AL-Go\settings.json
Warning: No test apps found in testFolders in .AL-Go\settings.json
Warning: No apps found in appFolders in .AL-Go\settings.json
Checking appDependencyProbingPaths
Repository is empty, exiting
Fixes [AB#498753](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/498753)

Make app folders relative to the AL-Go project folder

---

src/System Application/App/Permissions/SystemApplicationAdmin.PermissionSet.al
src/System Application/App/Permissions/SystemApplicationEdit.PermissionSet.al
src/System Application/App/System Permissions/permissions/PageScriptingPlay.Permissionset.al
src/System Application/App/System Permissions/permissions/PageScriptingRec.Permissionset.al

Add system permissions to control the access to Page Scripting. 
Two permission added to allow to give access to record and playback a Page Script.
Feature [AB#462095](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/462095/)

Add system permissions to control the access to Page Scripting

---

src/Business Foundation/App/NoSeries/src/Legacy/NoSeriesLineObsolete.TableExt.al
src/Business Foundation/App/NoSeries/src/Legacy/NoSeriesObsolete.TableExt.al
src/Business Foundation/App/NoSeries/src/Setup/NoSeries.Table.al
src/Business Foundation/App/NoSeries/src/Setup/NoSeriesLine.Table.al

move obsolete fields to table extension
Fixes [AB#498277](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/498277)

move obsolete fields to table extension

---

src/System Application/App/Environment Information/src/EnvironmentInformation.Codeunit.al
src/System Application/App/Environment Information/src/EnvironmentInformationImpl.Codeunit.al

This commit adds GetLinkedPowerPlatformEnvironmentId() method to Environment Information codeunit which helps get the linked Power Platform environment id for the current session's environment, if it is set. The internal implementation is added to the Environment Information Impl. codeunit.
Fixes [AB#499267](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/499267)

Add GetLinkedPowerPlatformEnvironmentId() method to Environment Information codeunit

---

src/System Application/App/User Permissions/src/UserPermissionsImpl.Codeunit.al
src/System Application/Test Library/User Permissions/src/TestUserPermissionsSubs.Codeunit.al

`NavUserAccountHelper.IsPermissionSetAssigned` doesn't work with buffered inserts, so when user records are inserted without a `Commit` (e. g. in tests), it throws the "User does not exist" exception. So far this problem has been solved with an internal event that skips the call alltogether in tests.
Call `User.Get` before calling `NavUserAccountHelper.IsPermissionSetAssigned` to make sure buffered inserts are flushed.
Fixes [AB#497548](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/497548)

Remove redundant internal event in the User Permissions module

---

.github/workflows/CreateBuildTag.yaml
.github/workflows/MSDO.yml
.github/workflows/PullRequestLabeler.yaml
.github/workflows/UpdateBCArtifactVersion.yaml
.github/workflows/UpdatePackageVersions.yaml
.github/workflows/WorkitemValidation.yaml
.github/workflows/powershell.yaml

Fix for warnings:
> Node.js 16 actions are deprecated... For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
and 
> CodeQL Action v2 will be deprecated on December 5th, 2024. Please update all occurrences of the CodeQL Action in your workflow files to v3. For more information, see https://github.blog/changelog/2024-01-12-code-scanning-deprecation-of-codeql-action-v2/
Fixes [AB#500607](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/500607)

Bump action versions. Fix for "Node.js actions are deprecated" warnings

---

src/System Application/App/Environment Information/src/EnvironmentInformationImpl.Codeunit.al
src/System Application/Test Library/Environment Information/src/EnvironmentInfoTestLibrary.Codeunit.al
src/System Application/Test/Environment Information/src/EnvironmentInformationTest.Codeunit.al
src/System Application/Test/Satisfaction Survey/src/SatisfactionSurveyTests.Codeunit.al

Reverts microsoft/BCApps#342
Reverts [AB#495664](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/495664)

Revert "Allowed to set more Environment Infos in tests"

---

src/Business Foundation/App/NoSeries/src/Setup/NoSeries.Page.al
src/Business Foundation/App/NoSeries/src/Setup/NoSeriesSetupImpl.Codeunit.al

This PR introduces the ability to see No. Series that are expiring. Whether that means there are no open lines or at least one line is in warning state.
Fixes [AB#476364](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/476364)

No. Series: Ability to show only expiring lines

---

src/Business Foundation/App/NoSeries/src/Single/NoSeriesStatelessImpl.Codeunit.al

In number series, when the last no. is at the warning threshold we want to provide a nice message explaining what is happening. Currently this looks like an error.
Fixes [AB#500462](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/500462)

No. Series: Update running out of numbers warning

---

src/System Application/App/Edit in Excel/src/EditinExcelImpl.Codeunit.al
src/System Application/Test/Edit in Excel/src/EditInExcelTest.Codeunit.al

The issue
Edit-In Excel module does not externalize page field names the same way the platform does, when the field name contains an plus sign.
For a page field defined as:
```
field("new vendor+s name"; rec."New Vendor+s Name")
{
ApplicationArea = All;
}
```
The platform will externalize this name as `new_vendor_x002b_name` while the Edit-In Excel module will externalize it as `new_vendor_name`.
Expected behavior
Within reason the platform and the Edit-In Excel module should externalize fields the same way to avoid discrepancies between the API metadata and the Edit-In Excel field bindings.
Steps to reproduce
Create a page field with an plus sign in its name on a card page, then try to export its corresponding list page using Edit-In Excel and observe the error dialog in the Excel side …

Allow plus sign in field names when using Edit-In Excel

---

src/System Application/App/ControlAddIns/src/OAuthControlAddIn.ControlAddIn.al
src/System Application/App/ControlAddIns/src/OAuthIntegration.Controladdin.al
src/System Application/App/OAuth2/OAuth2ControlAddIn.Page.al

OAuthControlAddin was obsoleted in previous PR in favor of OAuthIntegration.
Both should exist, as OAuthIntegration is used to create an authorization link and needs a min height and width to do that. The OAuthControlAddin has no height and width.
Fixes [AB#502131](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/502131/)

[OAuth] Reintroduce OAuthControlAddin for OnPrem support

---

build/scripts/PreCompileApp.ps1

This pull request backports #641 to releases/24.x
Fixes [AB#502108](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/502108)

[releases/24.x] Return rather than exit strictmode when tag isn't present

---

build/projects/Business Foundation/.AL-Go/settings.json
build/projects/Performance Toolkit/.AL-Go/settings.json
build/projects/System Application/.AL-Go/settings.json
build/projects/Test Framework/.AL-Go/settings.json
build/scripts/PreCompileApp.ps1

This pull request backports #641 to releases/24.0
+ Reenable strict mode 
Fixes [AB#502108](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/502108)

[releases/24.0] Return rather than exit strictmode when tag isn't present

---

src/System Application/App/Retention Policy/src/Retention Policy Setup/RetentionPolicySetupCard.Page.al

Backport of #635
Fixes [AB#502380](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/502380)

[24.x] When controlling field visibility, use variable instead of field to avoid client error

---

src/System Application/App/Azure File Services API/src/AFSOptionalParameters.Codeunit.al
src/System Application/Test/Azure File Services API/src/AFSFileClientTest.Codeunit.al

Actually return parameters to request to return attributes, timestamps, etag if requested.
Fixes #668 
Fixes [AB#503067](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/503067)

#668 Actually return parameters

---

src/System Application/App/Azure File Services API/src/AFSDirectoryContent.Table.al
src/System Application/App/Azure File Services API/src/AFSFileClientImpl.Codeunit.al
src/System Application/Test/Azure File Services API/src/AFSFileClientTest.Codeunit.al

Properly handle paging (max. results and marker) for ListDirectory(). This has been aligned with the existing implementation of ListFileHandles(). Furthermore, error returns are handled properly.
Fixes #509 
Fixes [AB#503159](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/503159)

Properly handle paging (max. results and marker) for ListDirectory()

---

build/scripts/CrossBranchPorting.psm1
build/scripts/EnlistmentHelperFunctions.psm1

* If gh cli isn't installed, link to a winget command rather than a URL 
* Improved error message if branch doesn't exist
* Ability to run New-BCAppsBackport from outside your local BCApps repository folder 
Fixes [AB#498430](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/498430)

Improvements to backporting tool

---

src/System Application/App/Azure AD User Management/src/User sync/AzureADUserUpdateWizard.Page.al

Currently it's possible to open the user sync with only e.g. Security. However, SUPER permissions are required to create new users and thus sync will fail if user does not have SUPER.
Fixes [AB#497926](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/497926/)

Require SUPER permission to run AAD user sync

---

src/System Application/App/AI/src/Copilot/CopilotCapabilityImpl.Codeunit.al

Adjusting the notification message displayed when user opens Copilot & AI capabilities page on-prem
Fixes [AB#504478](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/504478)

Adjust notification about Copilot capabilities not available on-prem

---

src/System Application/App/Language/app.json
src/System Application/App/Language/src/Language.Codeunit.al
src/System Application/App/Language/src/LanguageImpl.Codeunit.al

This pull request backports #549 to releases/24.0
Fixes [[AB#507000](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/507000)]

[releases/24.0] Language Id and Format Region override methods

---

src/System Application/App/Language/app.json
src/System Application/App/Language/src/Language.Codeunit.al
src/System Application/App/Language/src/LanguageImpl.Codeunit.al

This pull request backports #549 to releases/24.x
Fixes [[AB#506999](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/506999)]

[releases/24.x] Language Id and Format Region override methods

---

.github/AL-Go-Settings.json
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

Update AL-Go System Files

---

src/System Application/App/Entity Text/src/EntityTextImpl.Codeunit.al

Remove lower boundary check as this blocks languages where spaces are not used.
Fixes # [AB#507432](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/507432)

Marketing Text: Remove lower boundary check as this blocks languages where spaces are not used

---

src/System Application/App/Entity Text/src/EntityTextImpl.Codeunit.al

Remove lower boundary check as this blocks languages where spaces are not used.
Fixes # [AB#506451](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/506451)

Marketing Text: Remove lower boundary check as this blocks languages where spaces are not used 

---

src/System Application/App/MicrosoftGraph/src/GraphClient.Codeunit.al
src/System Application/App/MicrosoftGraph/src/GraphClientImpl.Codeunit.al
src/System Application/App/MicrosoftGraph/src/helper/GraphRequestHelper.Codeunit.al

This implement's HTTP Put Method in Graph API Wrapper.
Fixes microsoft/BCApps#748
Fixes [AB#507963](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/507963)

[BC Idea] Add Put method to 'Graph Client' Codeunit

---

src/System Application/App/ControlAddIns/src/MicrosoftDynamicsNavClientFlowIntegration.ControlAddin.al
src/System Application/App/ControlAddIns/src/MicrosoftDynamicsNavClientOAuthIntegration.ControlAddin.al
src/System Application/App/ControlAddIns/src/MicrosoftDynamicsNavClientPageReady.ControlAddin.al
src/System Application/App/ControlAddIns/src/MicrosoftDynamicsNavClientPowerBIManagement.ControlAddin.al
src/System Application/App/ControlAddIns/src/MicrosoftDynamicsNavClientRoleCenterSelector.ControlAddin.al
src/System Application/App/ControlAddIns/src/MicrosoftDynamicsNavClientVideoPlayer.ControlAddin.al
src/System Application/App/ControlAddIns/src/MicrosoftDynamicsNavClientWebPageViewer.ControlAddin.al
src/System Application/App/ControlAddIns/src/MicrosoftDynamicsNavClientWelcomeWizard.ControlAddin.al

Some legacy style control add-ins were removed from the app DB and introduced as System control add-ins in v. 24.0. Any usages of these will fail or new tenants.
Introduce replacement addins as Obsolete = Pending to ensure that the removal from the App DB is non-breaking.
Fixes [AB#507953](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/507953/)

[24.0] Add replacements for legacy control add-ins

---

src/System Application/App/MicrosoftGraph/src/GraphOptionalParameters.Codeunit.al

Add setter for more Request Headers
Fixes #791
Fixes [AB#521501](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/521501)

Improve Microsoft Graph Client by adding more setter for Request Headers

---

.github/workflows/CreateBuildTag.yaml
.github/workflows/MSDO.yml
.github/workflows/UpdateBCArtifactVersion.yaml
.github/workflows/UpdatePackageVersions.yaml
.github/workflows/powershell.yaml
.github/workflows/scorecard-analysis.yml

Uptake Scorecard workflow and run analysis once per week. The workflow looks at various things like permissions for the GitHub Token, dependencies and branch protection rules to determine if we're following best practices. 
Fixes [AB#523687](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/523687)

Uptake Scorecard workflow 

---

build/BuildConfig.json
build/scripts/GuardingV2ExtensionsHelper.psm1

Determine maxAllowedObsoleteVersion from config in main
Right now it's not possible to backport PRs with 25.0 as an obsolete tag because we didn't update the config value when we branched: https://github.com/microsoft/BCApps/actions/runs/8449290970?pr=841
Fixes [AB#523764](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/523764)

Determine maxAllowedObsoleteVersion from config in main

---

build/BuildConfig.json
build/scripts/GuardingV2ExtensionsHelper.psm1

This pull request backports #856 to releases/24.x
Fixes [AB#523764](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/523764)

[releases/24.x] Determine maxAllowedObsoleteVersion from config in main

---

build/BuildConfig.json
build/scripts/GuardingV2ExtensionsHelper.psm1

This pull request backports #856 to releases/24.0
Fixes [AB#523764](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/523764)

[releases/24.0] Determine maxAllowedObsoleteVersion from config in main

---

src/System Application/App/Azure Key Vault/src/AzureKeyVault.Codeunit.al
src/System Application/App/Azure Key Vault/src/AzureKeyVaultImpl.Codeunit.al
src/System Application/App/Customer Experience Survey/src/CustExpSurveyReqImpl.Codeunit.al
src/System Application/App/Entity Text/src/AzureOpenAiSettings.Table.al
src/System Application/App/OAuth2/OAuth2.Codeunit.al
src/System Application/App/OAuth2/OAuth2Impl.Codeunit.al

This pull request backports #792 to releases/24.x
Fixes [AB#521447](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/521447)

[releases/24.x] [OAuth2] Additional SecretText usage on Certificates

---

src/Business Foundation/App/NoSeries/src/Upgrade/NoSeriesInstaller.Codeunit.al
src/Business Foundation/App/NoSeries/src/Upgrade/NoSeriesUpgrade.Codeunit.al

Adds TriggerMovedTableSchemaCheck
Fixes [AB#523755](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/523755)

Add TriggerMovedTableSchemaCheck

---

src/Business Foundation/App/NoSeries/src/Upgrade/NoSeriesInstaller.Codeunit.al
src/Business Foundation/App/NoSeries/src/Upgrade/NoSeriesUpgrade.Codeunit.al

This pull request backports #855 to releases/24.0
Fixes [AB#523955](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/523955)

[releases/24.0] Add TriggerMovedTableSchemaCheck

---

src/System Application/App/SharePoint Authorization/src/SharePointAuth.Codeunit.al
src/System Application/App/SharePoint Authorization/src/SharePointAuthImpl.Codeunit.al
src/System Application/App/SharePoint Authorization/src/SharePointClientCredentials.Codeunit.al

Backport to 24.x of https://github.com/microsoft/BCApps/pull/705.
Add Client Credentials Support for Sharepoint
Fixes #524 
Fixes [AB#522796](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/522796)
Fixes [AB#457003](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/457003)

[24.x] Client Credentials Support for Sharepoint (#705)

---

build/scripts/EnlistmentHelperFunctions.psm1
build/scripts/UpdateBCArtifactVersion.ps1

Calculating BC artifact might switch between _bcinsider_ and _bcartifacts_ (typically around branching when a new version is available but not yet released). This PR addresses the issue when the storage account needs to be changed as well.
[AB#524129](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/524129)

Calculate full BC artifact URL when updating it

---

build/scripts/EnlistmentHelperFunctions.psm1
build/scripts/UpdateBCArtifactVersion.ps1

Cherry-pick:
- Implement different fallback mechanism when determining baselines for main branch: https://github.com/microsoft/BCApps/commit/e41c068cfa2ff5a6877f452e5f3399498f2b79e8
- Calculate full BC artifact URL when updating it: https://github.com/microsoft/BCApps/commit/db97751818611fb1e537cf6a5f4482e3eea6e250
[AB#524129](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/524129)

 [24.0] Implement different fallback mechanism when determining baselines

---

build/scripts/EnlistmentHelperFunctions.psm1
build/scripts/UpdateBCArtifactVersion.ps1

Cherry-pick:
- Implement different fallback mechanism when determining baselines for main branch: https://github.com/microsoft/BCApps/commit/e41c068cfa2ff5a6877f452e5f3399498f2b79e8
- Calculate full BC artifact URL when updating it: https://github.com/microsoft/BCApps/commit/db97751818611fb1e537cf6a5f4482e3eea6e250
[AB#524129](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/524129)

[24.x] Implement different fallback mechanism when determining baselines

---

src/System Application/App/Guided Experience/src/Guided Experience/GuidedExperienceImpl.Codeunit.al
src/System Application/Test/Guided Experience/src/GuidedExperienceTest.Codeunit.al

Porting down from #881 
Fixes [AB#524168](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/524168)

[24.x] ResetAssistedSetup doesn't take filter into consideration

---

src/System Application/App/DotNet Aliases/src/dotnet.al

Remove unused legacy Office Add-in that was based on COM Office interop. Not being used in production since version 14 as it had dependencies to the windows client.
Fixes [AB#523970](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/523970)

Remove legacy add-in Microsoft.Dynamics.Nav.Integration.Office

---

src/System Application/App/ControlAddIns/Resources/WaitSpinner/js/WaitSpinner.js
src/System Application/App/Resources/WaitSpinner/js/WaitSpinner.js

When control add-in resources where moved, these paths where not updated, hence they currently don't render in the web client.
Fixes [AB#524024](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/524024)

Fix path to loading image resource

---

src/System Application/App/DotNet Aliases/src/dotnet.al

Breaking change in OpenXml3, where type OpenXmlUnknownElement is moved to the assembly DocumentFormat.OpenXml.Framework. The OpenXmlUnknownElement type reference has been removed in Base application and the functionality is replaced with a function in the BC OpenXml add-in which prevents compile issues with the new assembly.
Fixes [AB#524860](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/524860)

Move OpenXml type to framework

---

src/System Application/App/ControlAddIns/Resources/WaitSpinner/js/WaitSpinner.js
src/System Application/App/Resources/WaitSpinner/js/WaitSpinner.js

When control add-in resources where moved, these paths where not updated, hence they currently don't render in the web client.
Fixes [AB#524865](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/524865)

[24.x] Fix path to loading image resource

---

src/System Application/App/Data Classification/src/DataClassificationMgt.Codeunit.al
src/System Application/App/Data Classification/src/DataClassificationMgtImpl.Codeunit.al
src/System Application/Test Library/Data Classification/src/LibraryDataClassification.Codeunit.al
src/System Application/Test/Data Classification/src/DataClassWorksheetTests.Codeunit.al
src/System Application/Test/Data Classification/src/DataClassificationMgtTests.Codeunit.al

Porting down from #903
Fixes [AB#523733](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/523733)

[24.x] Only table with type Normal is supported in Data Classification Worksheet and Data Privacy Utilities

---

src/System Application/App/ControlAddIns/src/MicrosoftDynamicsNavClientBusinessChart.ControlAddin.al
src/System Application/App/ControlAddIns/src/MicrosoftDynamicsNavClientFlowIntegration.ControlAddin.al
src/System Application/App/ControlAddIns/src/MicrosoftDynamicsNavClientOAuthIntegration.ControlAddin.al
src/System Application/App/ControlAddIns/src/MicrosoftDynamicsNavClientPageReady.ControlAddin.al
src/System Application/App/ControlAddIns/src/MicrosoftDynamicsNavClientPowerBIManagement.ControlAddin.al
src/System Application/App/ControlAddIns/src/MicrosoftDynamicsNavClientRoleCenterSelector.ControlAddin.al
src/System Application/App/ControlAddIns/src/MicrosoftDynamicsNavClientVideoPlayer.ControlAddin.al
src/System Application/App/ControlAddIns/src/MicrosoftDynamicsNavClientWebPageViewer.ControlAddin.al
src/System Application/App/ControlAddIns/src/MicrosoftDynamicsNavClientWelcomeWizard.ControlAddin.al

Some legacy style control add-ins were removed from the app DB and introduced as System control add-ins in v. 24.0. Any usages of these will fail or new tenants.
Introduce replacement addins as Obsolete = Pending to ensure that the removal from the App DB is non-breaking.
Fixes [AB#506521](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/506521/)

Add replacements for legacy control add-ins

---

src/System Application/App/ControlAddIns/Resources/WaitSpinner/js/WaitSpinner.js
src/System Application/App/Resources/WaitSpinner/js/WaitSpinner.js

When control add-in resources where moved, these paths where not updated, hence they currently don't render in the web client.
Fixes [AB#524865](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/524865)

[24.0] Fix path to loading image resource

---

build/scripts/EnlistmentHelperFunctions.psm1

Fix `Get-CurrentBranch` to always rely on git (and not GITHUB_REF env variable)
`$env:GITHUB_REF` is not the same as the checked out branch. `$env:GITHUB_REF` is the branch the workflow is running on.
Fixes [AB#525684](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/525684)

[24.x] Fix Get-CurrentBranch to always rely on git (and not GITHUB_REF env variable)

---

build/scripts/EnlistmentHelperFunctions.psm1

Fix `Get-CurrentBranch` to always rely on git (and not GITHUB_REF env variable)
`$env:GITHUB_REF` is not the same as the checked out branch. `$env:GITHUB_REF` is the branch the workflow is running on.
Fixes [AB#525684](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/525684)

Fix Get-CurrentBranch to always rely on git (and not GITHUB_REF env variable)

---

src/System Application/App/Email/src/Scenario/EmailScenario.Codeunit.al
src/System Application/App/Email/src/Scenario/EmailScenarioImpl.Codeunit.al
src/System Application/Test/Email/src/EmailScenarioTest.Codeunit.al

Add the ability to check if there is an email account set for a scanrio
Fixes [AB#524050](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/524050)

Add the ability to check if there is an email account set for a scanrio

---

src/System Application/App/AI/src/Azure OpenAI/AOAIAuthorization.Codeunit.al
src/System Application/App/AI/src/Azure OpenAI/AOAIDeploymentsImpl.Codeunit.al
src/System Application/App/AI/src/Azure OpenAI/AzureOpenAIImpl.Codeunit.al

Backporting: In previous workshops and in general for future usage, we want the AOAI deployment names to be accessible to tenants that are allowlisted.
Fixes [AB#527326](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/527326)

[24.x][CopilotToolkit] Allow allowlisted tenants to get the first party deployment names

---

src/System Application/App/Guided Experience/src/Guided Experience/GuidedExperienceImpl.Codeunit.al
src/System Application/App/Guided Experience/src/Guided Experience/GuidedExperienceUpgrade.Codeunit.al

Port from #990 
Fixes [AB#527479](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/527479)

[24.x] Skip upgrade when correct Code is used in Guided Experience Item

---

src/rulesets/CodeCop.ruleset.json

New code cop rule is coming, but is causing too many diagnostics right now. 
Related to
[AB#480821](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/480821): [AL] [Idea] Codeunit self-reference (this keyword)

No error on CodeCop rule 0248

---

src/System Application/App/Azure File Services API/src/AFSOperationPayloadImpl.Codeunit.al
src/System Application/App/Azure File Services API/src/Helper/AFSHttpContentHelper.Codeunit.al
src/System Application/Test/Azure File Services API/src/AFSFileClientTest.Codeunit.al
src/System Application/Test/Azure File Services API/src/AFSGetTestStorageAuth.Codeunit.al

This is a PR, that should fix the error that occured when creating or sending file to Azure File Share with AFS Library.
I also created a simple test to ensure it doesn't happen again.
The issue was with two things:
1. Sorting of the headers - In BC the order of the headers in the string to sign was different than in the documentation, which led azure to calculate a different hash for the authorization. I added sorting of the headers in the same way as implemented in ABS module, which should ensure correct order.
2. The header x-ms-content-length required when using CreateFile call, was added to the content headers, which led to it not being correctly added to the string to sign. I changed it to be added to request headers.
Fixes #961 #685 
Fixes …

Fix error in AFS shared key authorization (#961)

---

src/System Application/App/Email/src/Message/EmailMessage.Codeunit.al
src/System Application/App/Email/src/Message/EmailMessageImpl.Codeunit.al

This PR provides the ability to clean up orphaned email messages you may have created without an email outbox or sent email referencing them.
This is not a normal situation to end up in and only occurs if you simply create the message without linking.
It's not the most optimized solution, it's simply there to allow cleaning up incorrectly created messages.
Fixes [AB#524544](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/524544)

Add ability to delete orphaned email messages

---

src/System Application/App/Email/src/Message/EmailMessage.Codeunit.al
src/System Application/App/Email/src/Message/EmailMessageImpl.Codeunit.al

This PR provides the ability to clean up orphaned email messages you may have created without an email outbox or sent email referencing them. This is not a normal situation to end up in and only occurs if you simply create the message without linking.
It's not the most optimized solution, it's simply there to allow cleaning up incorrectly created messages.
Fixes [AB#533515](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/533515)

[24.x] Add ability to delete orphaned email messages (#1029)

---

src/System Application/App/Cryptography Management/src/RSACryptoServiceProvider.Codeunit.al
src/System Application/App/Cryptography Management/src/RSACryptoServiceProviderImpl.Codeunit.al
src/System Application/Test/Cryptography Management/src/RSACryptoServiceProviderTests.Codeunit.al

- Added a procedure in the facade and implementation codeunits that allows the public key of the RSA key pair to be retrieved as Text instead of SecretText.
- Also amended the obsolete message of the original procedure to reflect this change.
- Amended the automated test to include the new procedure.
Fixes #987
Fixes [AB#533942](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/533942)

Allow public key to be retrieved as plaintext

---

src/System Application/App/SharePoint/src/SharePointClient.Codeunit.al
src/System Application/App/SharePoint/src/SharePointClientImpl.Codeunit.al
src/System Application/App/SharePoint/src/helpers/SharePointHttpContent.Codeunit.al

Sharepoint SetXHttpMethod should set data to global variable. Cleanup
Fixes #666 
Fixes [AB#532990](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/532990)

Sharepoint SetXHttpMethod should set data to global variable. Cleanup

---

.github/actions/RunAutomation/UpdateBCArtifact/run.ps1
.github/actions/RunAutomation/run.ps1
build/scripts/AutomatedSubmission.psm1

- Fix automation branch name to include the automation name as category
- Improve automation PR title to include the branch name. E.g. "[24.x] Update BC Artifact"
[AB#486716](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/486716)

Fix automation PRs title and branch name

---

src/System Application/App/MicrosoftGraph/src/GraphClientImpl.Codeunit.al
src/System Application/App/MicrosoftGraph/src/GraphODataQueryParameter.Enum.al
src/System Application/App/MicrosoftGraph/src/GraphOptionalParameters.Codeunit.al
src/System Application/App/MicrosoftGraph/src/GraphOptionalParametersImpl.Codeunit.al
src/System Application/App/MicrosoftGraph/src/GraphRequestHeader.Enum.al
src/System Application/App/MicrosoftGraph/src/helper/GraphUriBuilder.Codeunit.al
src/System Application/Test/MicrosoftGraph/app.json
src/System Application/Test/MicrosoftGraph/src/GraphClientTest.Codeunit.al

Backport of #827 
Fixes #802
Fixes [AB#533480](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/533480)
Fixes [AB#522447](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/522447)

[24.x] Add Support to specifiy ODataQuery Parameters in Microsoft Graph Client

---

src/Business Foundation/App/NoSeries/src/Single/NoSeriesStatelessImpl.Codeunit.al

Two or more sessions cannot work simultaneously and get new numbers from number series when using the stateteless impl. because it doesn't lock the no. series line. This PR adds a locktable.
Fixes [AB#534262](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/534262)

add locktable to no series stateless impl

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 25.0.19538.0

[main] Update BCArtifact version. New value: 25.0.19538.0

---

src/System Application/App/Azure Blob Services API/src/ABSBlobClient.Codeunit.al
src/System Application/App/Azure Blob Services API/src/ABSClientImpl.Codeunit.al
src/System Application/App/Azure Blob Services API/src/ABSContainerClient.Codeunit.al
src/System Application/App/Azure Blob Services API/src/ABSOperationPayload.Codeunit.al
src/System Application/App/Azure Blob Services API/src/Helper/ABSContainerContentHelper.Codeunit.al
src/System Application/App/Azure Blob Services API/src/Helper/ABSContainerHelper.Codeunit.al
src/System Application/App/Azure Blob Services API/src/Helper/ABSFormatHelper.Codeunit.al
src/System Application/App/Azure Blob Services API/src/Helper/ABSHelperLibrary.Codeunit.al
src/System Application/App/Azure Blob Services API/src/Helper/ABSHttpContentHelper.Codeunit.al
src/System Application/App/Azure Blob Services API/src/Helper/ABSHttpHeaderHelper.Codeunit.al
src/System Application/App/Azure Blob Services API/src/Helper/ABSURIHelper.Codeunit.al
src/System Application/App/Azure Blob Services API/src/Helper/ABSWebRequestHelper.Codeunit.al
src/System Application/App/Azure Storage Services Authorization/src/AuthFormatHelper.Codeunit.al
src/System Application/App/Azure Storage Services Authorization/src/SAS/StorServAuthSAS.Codeunit.al
src/System Application/App/Azure Storage Services Authorization/src/SharedKey/StorServAuthSharedKey.Codeunit.al
src/System Application/App/Azure Storage Services Authorization/src/StorServAuthImpl.Codeunit.al
src/System Application/App/Azure Storage Services Authorization/src/StorageServiceAuthorization.Codeunit.al
src/System Application/Test/Azure File Services API/src/AFSGetTestStorageAuth.Codeunit.al
src/System Application/Test/Azure Storage Services Authorization/src/StorServAccountSASTest.Codeunit.al

Remove NonDebuggable from Azure Blob Storage and Storage Authorization
This PR removes the NonDebuggable from Helper procedure and other procedures where the data of the procedures is already known, since it's provided from upper codeunits.
I skipped the RequestHelper Codeunit for the moment, since I'm not sure if we can remove the NonDebuggable property there.
e.g. if we use the ReadSAS Authorization where the Secret is part of the request uri.
I added new Overloads to the `codeunit 9062 "Storage Service Authorization"` for `CreateAccountSAS` with SecretText.
Partially Fixes #875
Fixes [AB#524277](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/524277)

Remove NonDebuggable from Azure Blob Storage

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 25.0.19639.0

[main] Update BCArtifact version. New value: 25.0.19639.0

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 25.0.19727.0

[main] Update BCArtifact version. New value: 25.0.19727.0

---

src/Business Foundation/App/NoSeries/src/Upgrade/NoSeriesInstaller.Codeunit.al
src/Business Foundation/App/NoSeries/src/Upgrade/NoSeriesUpgrade.Codeunit.al
src/Business Foundation/App/NoSeries/src/Upgrade/NoSeriesUpgradeTags.Codeunit.al
src/System Application/App/Azure AD Plan/src/PlanUpgradeTag.Codeunit.al

Make sure No. Series are setup whenever you upgrade to a v24 or newer tenant.
Fixes [AB#535765](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/535765)

Setup No. Series on upgrade

---

src/System Application/App/Extension Management/src/ExtensionDeploymentStatus.Page.al

Added new actions to page "Extensions Deployment Status"
- Refresh: for refreshing the status of the deployment
- Upload Extension: to re-upload an extension if the first try failed for some reason
- Extension Management: to go back to the extension management page
Unfortunately it's not possible to test this Onprem and there does not seem to be a whole lot of test automation for this which I could re-use. Hopefully you can qualitity check this manually.
Fixes #977
Fixes [AB#527490](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/527490)

ExtensionDeploymentStatus new Actions

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 25.0.19942.0

[main] Update BCArtifact version. New value: 25.0.19942.0

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 25.0.19986.0

[main] Update BCArtifact version. New value: 25.0.19986.0

---

src/System Application/App/System Permissions/permissions/UserPersonalizationEdit.PermissionSet.al

The "User Metadata" table was removed and thus now platform uptake is broken on master. This PR removes it from the permission set.
[AB#536536](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/536536)

UserPersonalization.Edit permission set - Remove removed table

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 25.0.20123.0

[main] Update BCArtifact version. New value: 25.0.20123.0

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 24.2.20189.0

[24.x] Update BCArtifact version. New value: 24.2.20189.0

---

src/Business Foundation/App/NoSeries/src/Upgrade/NoSeriesInstaller.Codeunit.al
src/Business Foundation/App/NoSeries/src/Upgrade/NoSeriesUpgrade.Codeunit.al
src/Business Foundation/App/NoSeries/src/Upgrade/NoSeriesUpgradeTags.Codeunit.al

Make sure No. Series are setup whenever you upgrade to a v24 or newer tenant.
Fixes [AB#537077](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/537077)

[24.x] Setup No. Series on upgrade

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 25.0.20293.0

[main] Update BCArtifact version. New value: 25.0.20293.0

---

src/Business Foundation/App/NoSeries/src/Single/NoSeriesImpl.Codeunit.al
src/Business Foundation/Test/NoSeries/src/NoSeriesBatchTests.Codeunit.al

The No.  Series module tries to use the No Series Line given before looking for a new line to use. This has the effect that as long as the usagedate is newer the given line would be used even though a closer match exists. 
This fix makes it so the given line is only used if the starting dates from the given line and the new line match. If the dates don't match, the new line is used. 
Fixes [AB#537258](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/537258)

fix bug related to daily no. series lines

---

src/Business Foundation/App/NoSeries/src/Single/NoSeriesImpl.Codeunit.al
src/Business Foundation/Test/NoSeries/src/NoSeriesBatchTests.Codeunit.al

This pull request backports #1243 to releases/24.2
Fixes [AB#537308](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/537308)

[releases/24.2] fix bug related to daily no. series lines

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 25.0.20538.0

[main] Update BCArtifact version. New value: 25.0.20538.0

---

src/Business Foundation/App/NoSeries/src/Upgrade/NoSeriesInstaller.Codeunit.al

There are some issues with No. Series upgrade (timeout), could not figure out the root cause. However, when inspecting the upgrade code, notice the second `ModifyAll` is not really needed.
The change should be low risk, because it will not be executed on already upgraded tenants.
Fixes [AB#537864](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/537864)

remove unnecessary upgrade code for No Series

---

src/System Application/App/Entity Text/src/EntityTextAOAISettings.Codeunit.al

Make Marketing Text support users having mysettings.language set to Portuguese
Fixes #[AB#534724](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/534724/)

Make Marketing Text support users having settings.language set to pt

---

src/System Application/App/Data Classification/src/DataClassificationWorksheet.Page.al

Manually calculate Field Type in OnAfterGetCurrRecord, as it might not be calculated if the field is invisible.
Needed for [AB#537292](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/537292)

Manually calculate Field Type in OnAfterGetCurrRecord

---

src/System Application/App/Azure Blob Services API/src/ABSOperationPayload.Codeunit.al

Escapes special characters in blob file names in the ABS Blob Storage module so that operations on these files work as intended.
Fixes #1088
Fixes [AB#539027](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/539027)

Escape special characters in ABS Blob Storage blob filenames

---

src/Business Foundation/App/NoSeries/src/Single/NoSeriesImpl.Codeunit.al
src/Business Foundation/Test/NoSeries/Permissions/NoSeriesTest.PermissionSet.al
src/Business Foundation/Test/NoSeries/src/NoSeriesTests.Codeunit.al

This PR addresses a bug in the `GetNoSeriesLine` function where it failed to properly handle closed lines. Previously, if a line for a specific month was closed, the system would incorrectly issue a number from a prior month instead of signaling an error. This fix ensures that an error is thrown as expected in such scenarios, aligning with the intended behavior when dealing with closed series lines.
- Fixes [AB#538011](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/538011)

GetNextNo should error when line is closed, not take a number from an earlier line

---

src/Business Foundation/App/NoSeries/src/Single/NoSeriesImpl.Codeunit.al
src/Business Foundation/Test/NoSeries/Permissions/NoSeriesTest.PermissionSet.al
src/Business Foundation/Test/NoSeries/src/NoSeriesTests.Codeunit.al

This pull request backports #1406 to releases/24.x
Fixes [AB#539651](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/539651)

[releases/24.x] GetNextNo should error when line is closed, not take a number from an earlier line

---

src/Business Foundation/App/NoSeries/src/Single/NoSeriesImpl.Codeunit.al
src/Business Foundation/Test/NoSeries/Permissions/NoSeriesTest.PermissionSet.al
src/Business Foundation/Test/NoSeries/src/NoSeriesTests.Codeunit.al

This pull request backports #1406 to releases/24.0
Fixes [AB#539648](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/539648)

[releases/24.0] GetNextNo should error when line is closed, not take a number from an earlier line

---

src/Business Foundation/App/NoSeries/src/Single/NoSeriesImpl.Codeunit.al
src/Business Foundation/Test/NoSeries/Permissions/NoSeriesTest.PermissionSet.al
src/Business Foundation/Test/NoSeries/src/NoSeriesTests.Codeunit.al

This pull request backports #1406 to releases/24.2
Fixes [AB#539650](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/539650)

[releases/24.2] GetNextNo should error when line is closed, not take a number from an earlier line

---

src/Business Foundation/App/NoSeries/src/Single/NoSeriesImpl.Codeunit.al
src/Business Foundation/Test/NoSeries/Permissions/NoSeriesTest.PermissionSet.al
src/Business Foundation/Test/NoSeries/src/NoSeriesTests.Codeunit.al

This pull request backports #1406 to releases/24.1
Fixes [AB#539649](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/539649)

[releases/24.1] GetNextNo should error when line is closed, not take a number from an earlier line

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

Fixes [AB#539951](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/539951)
- Issue 1084 Automatic updates for AL-Go are failing when main branch requires Pull Request
- `PowerPlatformSolutionFolder`: Contains the name of the folder containing a PowerPlatform Solution (only one)
- `DeployTo<environment>` now has two additional properties `companyId` is the Company Id from Business Central (for PowerPlatform connection) and `ppEnvironmentUrl` is the Url of the PowerPlatform environment to deploy to.
- `BuildPowerPlatform`: to build a PowerPlatform Solution
- `DeployPowerPlatform`: to deploy a PowerPlatform Solution
- `PullPowerPlatformChanges`: to pull changes made in PowerPlatform studio into the repository
- `ReadPowerPlatformSettings`: to read …

[main] Update AL-Go System Files from microsoft/AL-Go-PTE@main -  81cff3d03e8fe6b88ee3fc0848594bfd4d9039a4

---

src/System Application/App/AI/src/Azure OpenAI/AzureOpenAIImpl.Codeunit.al
src/System Application/App/DotNet Aliases/src/dotnet.al

For tracking purposes, we need the AI AL module to pass the copilot capability information to the ALCopilotFunctions dotnet object.
Fixes [AB#539627](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/539627)

[24.2][Copilot] Pass capability name to ALCopilotFunctions

---

src/System Application/App/AI/src/Azure OpenAI/AzureOpenAIImpl.Codeunit.al
src/System Application/App/DotNet Aliases/src/dotnet.al

For tracking purposes, we need the AI AL module to pass the copilot capability information to the ALCopilotFunctions dotnet object.
Fixes [AB#539626](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/539626)

[24.1][Copilot] Pass capability name to ALCopilotFunctions

---

src/Business Foundation/App/NoSeries/src/Legacy/NoSeriesManagement.Codeunit.al
src/Business Foundation/App/NoSeries/src/Single/NoSeriesImpl.Codeunit.al

This pull request backports #1446 to releases/24.0
Fixes [AB#540013](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/540013)

[releases/24.0] fixes an issue where a subscriber can no longer change the result from GetNextNo or PeekNextNo. The fix is for obsolete code only.

---

src/Business Foundation/App/NoSeries/src/Legacy/NoSeriesManagement.Codeunit.al
src/Business Foundation/App/NoSeries/src/Single/NoSeriesImpl.Codeunit.al

This pull request backports #1446 to releases/24.2
Fixes [AB#540015](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/540015)

[releases/24.2] fixes an issue where a subscriber can no longer change the result from GetNextNo or PeekNextNo. The fix is for obsolete code only.

---

src/Business Foundation/App/NoSeries/src/Legacy/NoSeriesManagement.Codeunit.al
src/Business Foundation/App/NoSeries/src/Single/NoSeriesImpl.Codeunit.al

This pull request backports #1446 to releases/24.x
Fixes [AB#540017](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/540017)

[releases/24.x] fixes an issue where a subscriber can no longer change the result from GetNextNo or PeekNextNo. The fix is for obsolete code only.

---

src/Business Foundation/App/NoSeries/src/Legacy/NoSeriesManagement.Codeunit.al
src/Business Foundation/App/NoSeries/src/Single/NoSeriesImpl.Codeunit.al

This pull request backports #1446 to releases/24.1
Fixes [AB#540014](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/540014)

[releases/24.1] fixes an issue where a subscriber can no longer change the result from GetNextNo or PeekNextNo. The fix is for obsolete code only.

---

src/System Application/App/Performance Profiler/src/PerfProfilerSchedulesList.Page.al
src/System Application/App/Performance Profiler/src/PerformanceProfileList.Page.al
src/System Application/App/Performance Profiler/src/ScheduledPerfProfiler.Codeunit.al
src/System Application/App/Performance Profiler/src/ScheduledPerfProfilerImpl.Codeunit.al
src/System Application/App/Performance Profiler/src/dotnet.al

This PR adds two features:
1) It adds an event subscriber to link the new help page link with the profiler schedules page
2) It adds a new group to show the scheduled profiling status on the schedules page. This new group contains information about if profiling is active for the current session and shows the active schedule.
Fixes [AB#501774](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/501774)

Scheduled Profiler - Add event subscriber to link help page with schedules + profiling status on the schedules page

---

build/scripts/DevEnv/NewDevEnv.ps1
build/scripts/DevEnv/NewDevEnv.psm1

**Problem** 
Sometimes we roll out new compiler features and start using them in BCApps before they're released through VS Code Marketplace. Therefore, right now you will get the following error with the latest VS Code extension and latest BCApps source code:
`error AL0132: 'NavApp' does not contain a definition for 'GetCallerCallstackModuleInfos'`
**Solution**
Install AL Extension included in container. 
Fixes [AB#521408](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/521408)

Install AL Extension included in container

---

src/Business Foundation/App/NoSeries/src/Legacy/NoSeriesManagement.Codeunit.al
src/Business Foundation/App/NoSeries/src/Single/NoSeriesImpl.Codeunit.al

This pull request backports #1446 to releases/24.3
Fixes [AB#540016](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/540016)

[releases/24.3] fixes an issue where a subscriber can no longer change the result from GetNextNo or PeekNextNo. The fix is for obsolete code only.

---

src/System Application/App/Azure File Services API/src/AFSFileClientImpl.Codeunit.al

if NodeList is empty no temprecords are beiing inserted and an error will occur because of the modify on an not inserted temprecord
Fixes #1409
Fixes [AB#540616](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/540616)

Bugfix nextmarker in AFSFileClientImpl.Codeunit

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.x] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  0aab342a0ddd80612fafbc5149c8e95b3476b12a

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.0] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  0aab342a0ddd80612fafbc5149c8e95b3476b12a

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.2] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  0aab342a0ddd80612fafbc5149c8e95b3476b12a

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.1] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  0aab342a0ddd80612fafbc5149c8e95b3476b12a

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.3] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  0aab342a0ddd80612fafbc5149c8e95b3476b12a

---

src/Business Foundation/App/NoSeries/src/Setup/NoSeriesSetupImpl.Codeunit.al
src/Business Foundation/App/NoSeries/src/Single/NoSeries.Codeunit.al
src/Business Foundation/App/NoSeries/src/Single/NoSeriesImpl.Codeunit.al
src/Business Foundation/Test/NoSeries/src/NoSeriesTests.Codeunit.al

Issue happens when we have a combination of No Series that does not have a No Series Line. 
And also have an No Series Line with empty "Series Code".
When No Series dont have a No Series Line, it is empty initialized. 
Then the code to GetNoSeries will do a findlast that will find that No Series Line with empty code. And then because logic says it found the line, it will try and do a Get later, which then fails.
Fixes [AB#540058](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/540058)

Fix empty No Series code in GetNoSeriesLine

---

src/Tools/Test Framework/Test Runner/src/DataDrivenTest/DataInputs/TestInputJson.Codeunit.al
src/Tools/Test Framework/Test Runner/src/DataDrivenTest/DataInputs/TestInputsManagement.Codeunit.al

Improve error message when
1. Uploading a faulty jsonl dataset
2. Accessing Test Input Element which does not exist
Fixes [AB#541849](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/541849)

Data Driven Tests: Show better error message when parsing of JSONL fails

---

.github/RELEASENOTES.copy.md

[main] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  0aab342a0ddd80612fafbc5149c8e95b3476b12a

---

src/System Application/App/Performance Profiler/src/PerfProfilerScheduleCard.Page.al
src/System Application/App/Performance Profiler/src/PerfProfilerSchedulesList.Page.al
src/System Application/App/Performance Profiler/src/PerformanceProfileList.Page.al
src/System Application/App/Performance Profiler/src/ScheduledPerfProfiler.Codeunit.al
src/System Application/App/Performance Profiler/src/ScheduledPerfProfilerImpl.Codeunit.al

Right now, it's only possible to create or set start/end dates of a schedule for the next week. The reason why is because due to how we made the validation triggers, the start time and end time triggers block each other from ever completing when one gets an incorrect value.
The solution is to keep one validate trigger on the "End Time" and also validate that the dates are correct before saving the values to the database. This way, there's no way the triggers can block each other.
Furthermore, this fixes a few minor issues from internal testing, like field order, descriptions and an incorrect reference for the retention policy.
Fixes [AB#501774](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/501774)

Scheduled Profiler - Fix value update deadlock with different validation strategy + misc fixes

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.2] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  e23536e3e226943446586ba1222608a2025935d7

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.0] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  e23536e3e226943446586ba1222608a2025935d7

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.1] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  e23536e3e226943446586ba1222608a2025935d7

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.x] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  e23536e3e226943446586ba1222608a2025935d7

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.3] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  e23536e3e226943446586ba1222608a2025935d7

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/AI Test Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/AI Test Toolkit/.AL-Go/localDevEnv.ps1
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[main] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  e23536e3e226943446586ba1222608a2025935d7

---

src/System Application/App/ControlAddIns/Resources/PowerBIManagement/js/PowerBIManagement.js
src/System Application/App/ControlAddIns/src/PowerBIManagement.ControlAddin.al
src/System Application/App/Resources/PowerBIManagement/js/PowerBIManagement.js
src/System Application/App/Resources/PowerBIManagement/stylesheets/PowerBIManagement.css

This PR is a backport of a PR in main branch, and enables some additional options in the Power BI add-in. It also removes the logic to hardcode the height and width of the addin, allowing the client to decide on its size instead, for a much improved user experience.
Fixes [AB#542753](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/542753)

[24.x][PowerBI] Enable client resizing

---

src/System Application/App/Edit in Excel/src/EditinExcelImpl.Codeunit.al

We merged in this [PR](https://github.com/microsoft/BCApps/pull/1249) earlier for Edit-In Excel. Which shows a dialog when users try to filter on fields that are not keys and is not exposed on the page(therefore not available in OData either, so Edit-In Excel cannot use those filters).
This PR is just to make the dialog a little nicer, so now it will look like this:
Fixes 
[AB#542876](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/542876/)

[Edit-In Excel] Improve the invalid filter error message

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/AI Test Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/AI Test Toolkit/.AL-Go/localDevEnv.ps1
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[main] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  6d77148c1f6eb4bde3f4a4b1d47443b233c7595d

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.2] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  6d77148c1f6eb4bde3f4a4b1d47443b233c7595d

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.3] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  6d77148c1f6eb4bde3f4a4b1d47443b233c7595d

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.4] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  6d77148c1f6eb4bde3f4a4b1d47443b233c7595d

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.x] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  6d77148c1f6eb4bde3f4a4b1d47443b233c7595d

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.0] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  6d77148c1f6eb4bde3f4a4b1d47443b233c7595d

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.1] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  6d77148c1f6eb4bde3f4a4b1d47443b233c7595d

---

src/System Application/App/Email/src/Account/EmailAccounts.Page.al

Add functionality to filter Email Accounts page to only those that are using Connector v2 interface

[Email] Allow filtering of EmailAccounts page to only v2 accounts

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.2] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  4fd6c113536be76423b0eafc1b60e0ea8d077042

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/AI Test Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/AI Test Toolkit/.AL-Go/localDevEnv.ps1
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[main] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  4fd6c113536be76423b0eafc1b60e0ea8d077042

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.3] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  4fd6c113536be76423b0eafc1b60e0ea8d077042

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.1] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  4fd6c113536be76423b0eafc1b60e0ea8d077042

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.0] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  4fd6c113536be76423b0eafc1b60e0ea8d077042

---

src/System Application/App/Feature Key/src/FeatureManagementFacade.Codeunit.al
src/System Application/App/Feature Key/src/FeatureManagementImpl.Codeunit.al
src/System Application/Test/Feature Key/src/FeatureKeyTest.Codeunit.al

Add an overload to IsEnabled procedure to be able to avoid inserts when checking the feature enabled state, since in some circumstances (init of a report) we cannot afford a transaction without error.
Fixes [AB#543746](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/543746)

Feature Management. Add an overload to IsEnabled procedure.

---

src/System Application/Test Library/AI/src/CopilotTestLibrary.Codeunit.al

To be able to run SLS tests in pipeline, we need overwritten procedure
"Register Copilot Capability", that will allow us to register copilot
capability for specifi app id.
[AB#543582](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/543582)
Add Register Copilot Capability for specific app id procedure to "Copilot Test Library"

Add Register Copilot Capability for specific app id  procedure to "Copilot Test Library"

---

src/System Application/App/Feature Key/src/FeatureManagementFacade.Codeunit.al
src/System Application/App/Feature Key/src/FeatureManagementImpl.Codeunit.al
src/System Application/Test/Feature Key/src/FeatureKeyTest.Codeunit.al

Backport of [this merged PR](https://github.com/microsoft/BCApps/pull/1720) to 24.x
Add an overload to IsEnabled procedure to be able to avoid inserts when checking the feature enabled state, since in some circumstances (init of a report) we cannot afford a transaction without error.
Fixes [AB#543746](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/543746)

[24.x] Feature Management. Add an overload to IsEnabled procedure. (#1720)

---

src/System Application/App/Performance Profiler/src/PerfProfilerScheduleCard.Page.al
src/System Application/App/Performance Profiler/src/PerformanceProfileList.Page.al
src/System Application/App/Performance Profiler/src/ScheduledPerfProfiler.Codeunit.al
src/System Application/App/Performance Profiler/src/ScheduledPerfProfilerImpl.Codeunit.al

Some bugs were identified on further testing of the feature. These are:
1) While non-admin users cannot see other users' profiles and schedules, they can create them as insert wasn't guarded on the page.
2) The description is not correctly validated to be non-empty
3) On the performance profiles page, we incorrectly include "(ms)" in the caption although the duration type is formatted with a textual form of the duration.
Fixes [AB#544034](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/544034)

Scheduled Profiler - Bugfixes from testing

---

src/System Application/App/User Settings/src/UserSettingsImpl.Codeunit.al

When picking a profile in My Settings, the sorting behind the scenes happens by profile ID and not by profile display name, causing a weird sorting.
Fixes [AB#544052](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/544052)

Sort available profiles by caption (= display name)

---

src/System Application/App/Azure Function/AzureFunctionsAuthentication.Codeunit.al
src/System Application/App/Azure Function/AzureFunctionsOAuth2Cert.Codeunit.al

**Actions:**
```
var
i: Integer;
begin
end;
``` …

[releases/24.4] Authentication failure when Get/Post request is sent to Azure Function multiple times with the same authentication parameters

---

src/System Application/App/Azure Function/AzureFunctionsAuthentication.Codeunit.al
src/System Application/App/Azure Function/AzureFunctionsOAuth2Cert.Codeunit.al

**Actions:**
```
var
i: Integer;
begin
end;
``` …

[releases/24.3] Authentication failure when Get/Post request is sent to Azure Function multiple times with the same authentication parameters

---

src/System Application/App/Azure Function/AzureFunctionsAuthentication.Codeunit.al
src/System Application/App/Azure Function/AzureFunctionsOAuth2Cert.Codeunit.al

**Actions:**
```
var
i: Integer;
begin
end;
``` …

[releases/24.2] Authentication failure when Get/Post request is sent to Azure Function multiple times with the same authentication parameters

---

src/System Application/App/Azure Function/AzureFunctionsAuthentication.Codeunit.al
src/System Application/App/Azure Function/AzureFunctionsOAuth2Cert.Codeunit.al

**Actions:**
```
var
i: Integer;
begin
end;
``` …

[releases/24.1] Authentication failure when Get/Post request is sent to Azure Function multiple times with the same authentication parameters

---

src/System Application/App/Azure Function/AzureFunctionsAuthentication.Codeunit.al
src/System Application/App/Azure Function/AzureFunctionsOAuth2Cert.Codeunit.al

**Actions:**
```
var
i: Integer;
begin
end;
``` …

[releases/24.0] Authentication failure when Get/Post request is sent to Azure Function multiple times with the same authentication parameters

---

src/System Application/App/Azure Function/AzureFunctionsAuthentication.Codeunit.al
src/System Application/App/Azure Function/AzureFunctionsOAuth2Cert.Codeunit.al

**Actions:**
```
var
i: Integer;
begin
end;
``` …

[24.x] Authentication failure when Get/Post request is sent to Azure Function multiple times with the same authentication parameters

---

src/System Application/App/Retention Policy/src/Retention Policy Setup/RetentionPolicySetupCard.Page.al
src/System Application/App/Retention Policy/src/Retention Policy Setup/RetentionPolicySetupList.Page.al

Currently this action is only on the card page which is not user friendly. Copy the action to list page too.
Fixes [AB#542890](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/542890)

Add Refresh Allowed Tables action to Retention Policy list page

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.1] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  73f489ec1d9a34fa2ed69fbafd5e0ec9bd67f48b

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.3] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  73f489ec1d9a34fa2ed69fbafd5e0ec9bd67f48b

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.0] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  73f489ec1d9a34fa2ed69fbafd5e0ec9bd67f48b

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.2] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  73f489ec1d9a34fa2ed69fbafd5e0ec9bd67f48b

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.4] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  73f489ec1d9a34fa2ed69fbafd5e0ec9bd67f48b

---

src/Tools/AI Test Toolkit/src/AITTestContext.Codeunit.al
src/Tools/AI Test Toolkit/src/AITTestContextImpl.Codeunit.al
src/Tools/AI Test Toolkit/src/API/AITLogEntryAPI.Page.al
src/Tools/AI Test Toolkit/src/Logs/AITLogEntry.Table.al
src/Tools/AI Test Toolkit/src/TestSuite/AITTestSuite.Page.al
src/Tools/AI Test Toolkit/src/TestSuite/AITTestSuite.Table.al
src/Tools/AI Test Toolkit/src/TestSuite/AITTestSuiteImportExport.XmlPort.al
src/Tools/AI Test Toolkit/src/TestSuite/AITTestSuiteMgt.Codeunit.al

Remove the unused field. This will be considered in future version where we might be able to override the model version from the test toolkit
Fixes [AB#545545](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/545545)

AI Test Toolkit: Remove AOAI Model Version

---

src/System Application/App/Page Summary Provider/permissions/PageSummaryProviderObj.PermissionSet.al
src/System Application/App/Page Summary Provider/src/PageSummaryParameters.Table.al
src/System Application/App/Page Summary Provider/src/PageSummaryProvider.Codeunit.al
src/System Application/App/Page Summary Provider/src/PageSummaryProviderImpl.Codeunit.al
src/System Application/App/Page Summary Provider/src/PageSummarySettings.Table.al
src/System Application/Test Library/Page Summary Provider/Permissions/PageSumAdminTest.PermissionSet.al
src/System Application/Test Library/Page Summary Provider/Permissions/PageSummaryRead.PermissionSet.al
src/System Application/Test Library/Page Summary Provider/app.json
src/System Application/Test Library/Page Summary Provider/src/PageProviderSummaryTest3.Table.al
src/System Application/Test Library/Page Summary Provider/src/PageSummaryMediaTestCard.Page.al
src/System Application/Test/Page Summary Provider/src/PageSummaryProviderTest.Codeunit.al

Fixes [AB#540386](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/540386)

Page Summary provider - Add ability to exclude media, media set and blobs from page summary provider

---

src/System Application/App/Base64 Convert/src/Base64Convert.Codeunit.al
src/System Application/App/Base64 Convert/src/Base64ConvertImpl.Codeunit.al

Adds support for base64 for secrettexts
Fixes #1855 
Fixes [AB#545707](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/545707)

#1855 Base64 convert for secret text

---

src/System Application/App/User Login Times/src/UserLoginTimeTrackerImpl.Codeunit.al

SelectLatestVersion ensures data from the cache older than the current time is disregarded. Calling this on every login effectively makes any cached values from before the login unusable. Instead, uptake the new version of SelectLatestVersion that only disregards the cache for a specific table.
Fixes [AB#544663](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/544663)

Only disregard cache for the user login table when updating the login time tracker

---

src/System Application/App/Email/src/Email/EmailRelatedRecord.Table.al

The `Email Related Record` is an extensibility point of the email module, providing lookup of relations between emails and entities in BC, but currently it's marked as Internal. Like the `Email Outbox` and `Sent Email` tables, this table should be public.
Fixes [AB#546670](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/546670/)

[24.x] [Email] Make Email Related Record table public

---

src/System Application/App/Email/src/Message/EmailMessage.Codeunit.al
src/System Application/App/Email/src/Message/EmailMessageImpl.Codeunit.al
src/System Application/Test/Email/src/EmailTest.Codeunit.al

This pull request backports #1894 to releases/25.x

[releases/25.x] [Email] Add subject to API and docs

---

src/System Application/App/Performance Profiler/src/PerfProfilerScheduleCard.Page.al

Fixes a caption on the profiler schedule card as it was incorrect, due to an overeager copilot and a less than careful eye of the author of this PR.
Fixes [AB#547281](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/547281)

Profiler Schedules - Incorrect caption

---

src/System Application/App/Performance Profiler/src/PerfProfilerScheduleCard.Page.al

Fixes a caption on the profiler schedule card as it was incorrect, due to an overeager copilot and a less than careful eye of the author of this PR.
Work Item(s)
Fixes [AB#547281](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/547281)

[25.x]  Profiler Schedules - Incorrect caption 

---

src/System Application/App/Performance Profiler/src/PerfProfilerScheduleCard.Page.al

Fixes a caption on the profiler schedule card as it was incorrect, due to an overeager copilot and a less than careful eye of the author of this PR.
Work Item(s)
Fixes [AB#547281](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/547281)

[25.0] Profiler Schedules - Incorrect caption

---

src/System Application/App/VS Code Integration/src/VsCodeIntegrationImpl.Codeunit.al

This pull request backports #1900 to releases/25.0
Fixes [AB#547341](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/547341)

[releases/25.0] Fix get app id for object

---

src/System Application/App/Data Administration/src/MediaCleanup.Codeunit.al
src/System Application/App/Data Administration/src/MediaCleanupImpl.Codeunit.al

port from #1990
Fixes [AB#548339](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/548339)

[25.x] Delete TenantMediaSet in Batch and safeguard loading detached media

---

src/System Application/App/Data Administration/src/MediaCleanup.Codeunit.al
src/System Application/App/Data Administration/src/MediaCleanupImpl.Codeunit.al

port from #1990 
Fixes [AB#548338](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/548338)

[25.0] Delete TenantMediaSet in Batch and safeguard loading detached media

---

src/System Application/App/Extension Management/src/ExtensionInstallationImpl.Codeunit.al
src/System Application/App/Extension Management/src/ExtnOrphanedAppDetails.Page.al

Fixes: [AB#534788](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/534788)

Use AppId function to delete orphaned extension data AB#534788

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.24026.0

[main] Update BCArtifact version. New value: 26.0.24026.0

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.x] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  ff5817559912b8a13b51c09368f01a623acd2082

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.5] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  ff5817559912b8a13b51c09368f01a623acd2082

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/25.x] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  ff5817559912b8a13b51c09368f01a623acd2082

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[main] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  ff5817559912b8a13b51c09368f01a623acd2082

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.2] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  ff5817559912b8a13b51c09368f01a623acd2082

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.3] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  ff5817559912b8a13b51c09368f01a623acd2082

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.4] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  ff5817559912b8a13b51c09368f01a623acd2082

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.0] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  ff5817559912b8a13b51c09368f01a623acd2082

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/25.0] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  ff5817559912b8a13b51c09368f01a623acd2082

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.1] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  ff5817559912b8a13b51c09368f01a623acd2082

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.24098.0

[main] Update BCArtifact version. New value: 26.0.24098.0

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.24196.0

[main] Update BCArtifact version. New value: 26.0.24196.0

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.24278.0

[main] Update BCArtifact version. New value: 26.0.24278.0

---

src/System Application/App/AI/src/Azure OpenAI/AzureOpenAI.Codeunit.al
src/System Application/App/AI/src/Copilot/CopilotCapabilityImpl.Codeunit.al

Porting the main fix
1. Add a new procedure overload that allows checking of another AppId's
capability if it is enabled.
2. Update the GetCopilotCapabilityStatus subscriber with silent
parameter.
Fixes [AB#548376](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/548376)

Porting fix to 25.x - Client does not check Copilot Capability

---

src/System Application/App/Page Summary Provider/src/PageSummaryProviderImpl.Codeunit.al

Fixes [AB#549212](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/549212)

25.x - Page summary telemetry - fix wrong condition

---

src/Business Foundation/App/NoSeriesCopilot/src/Copilot/NoSeriesCopilotImpl.Codeunit.al
src/Business Foundation/App/NoSeriesCopilot/src/Copilot/NoSeriesExt.PageExt.al
src/Business Foundation/App/NoSeriesCopilot/src/Copilot/NoSeriesGenerationDetail.Table.al
src/Business Foundation/App/NoSeriesCopilot/src/Copilot/NoSeriesGenerationSub.Page.al
src/Business Foundation/App/NoSeriesCopilot/src/Copilot/Tools/NoSeriesCopAddIntent.Codeunit.al
src/Business Foundation/App/NoSeriesCopilot/src/Copilot/Tools/NoSeriesCopToolsImpl.Codeunit.al
src/Business Foundation/App/NoSeriesCopilot/src/Register/NoSeriesCopilotInstall.Codeunit.al
src/Business Foundation/App/NoSeriesCopilot/src/Register/NoSeriesCopilotRegister.Codeunit.al
src/Business Foundation/Test/NoSeriesCopilot/src/NoSeriesCopilotHarmsTests.Codeunit.al

Backporting all changes from the MAIN version and enabling the feature.
Fixes #659
Fixes [AB#503148](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/503148)

[Suggest No. Series] Enable feature and sync version with version from MAIN branch.

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.24375.0

[main] Update BCArtifact version. New value: 26.0.24375.0

---

src/Business Foundation/App/NoSeriesCopilot/app.json
src/Business Foundation/App/NoSeriesCopilot/src/Copilot/NoSeriesCopilotImpl.Codeunit.al
src/Business Foundation/App/NoSeriesCopilot/src/Copilot/NoSeriesExt.PageExt.al
src/Business Foundation/App/NoSeriesCopilot/src/Copilot/NoSeriesGenerationDetail.Table.al
src/Business Foundation/App/NoSeriesCopilot/src/Copilot/NoSeriesGenerationSub.Page.al
src/Business Foundation/App/NoSeriesCopilot/src/Copilot/Tools/NoSeriesCopAddIntent.Codeunit.al
src/Business Foundation/App/NoSeriesCopilot/src/Copilot/Tools/NoSeriesCopToolsImpl.Codeunit.al
src/Business Foundation/App/NoSeriesCopilot/src/Register/NoSeriesCopilotInstall.Codeunit.al
src/Business Foundation/App/NoSeriesCopilot/src/Register/NoSeriesCopilotRegister.Codeunit.al
src/Business Foundation/Test Library/NoSeriesCopilot/app.json
src/Business Foundation/Test/NoSeriesCopilot/app.json
src/Business Foundation/Test/NoSeriesCopilot/src/NoSeriesCopilotHarmsTests.Codeunit.al

Backporting all changes from the MAIN version and enabling the feature.
Fixes #659
Fixes [AB#503148](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/503148)

[25.0][Suggest No. Series] Enable feature and sync version with version from MAIN branch.

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.24499.0

[main] Update BCArtifact version. New value: 26.0.24499.0

---

src/System Application/App/Edit in Excel/src/EditinExcelImpl.Codeunit.al
src/System Application/Test/Edit in Excel/src/EditInExcelTest.Codeunit.al

… dash` instead of `em dash` (#2032)
Can see the following two screenshots where the first line is using `em dash` and the second line is using `en dash`, where the `en dash` is encoded and the `em dash` is removed.
Code:
Fixes
[AB#548471](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/548471/)
Fixes [AB#550127](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/550127/)

[25.0] Private/mattinielsen/backport metadata generation error for en dash in norway tenants v25 0

---

src/System Application/App/DotNet Aliases/src/dotnet.al

Added three DotNet types to enable the use of Purview telemetry (audit logging) in BaseApp (24.x).
Required for deliverables [AB#549389](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/549389) and [AB#548176](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/548176)

Added dotnet wrappers for Purview telemetry

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.24649.0

[main] Update BCArtifact version. New value: 26.0.24649.0

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.5] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  becb26e1f895fb75145bbc10535afb19c09bff5c

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.0] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  becb26e1f895fb75145bbc10535afb19c09bff5c

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.1] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  becb26e1f895fb75145bbc10535afb19c09bff5c

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.x] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  becb26e1f895fb75145bbc10535afb19c09bff5c

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.3] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  becb26e1f895fb75145bbc10535afb19c09bff5c

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.2] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  becb26e1f895fb75145bbc10535afb19c09bff5c

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/25.x] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  becb26e1f895fb75145bbc10535afb19c09bff5c

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/25.0] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  becb26e1f895fb75145bbc10535afb19c09bff5c

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[main] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  becb26e1f895fb75145bbc10535afb19c09bff5c

---

.github/workflows/VerifyAppChanges.yaml

The current SHA is from another branch.
[AB#549296](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/549296)

Fix TestPreprocessorSymbols action ref

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.4] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  becb26e1f895fb75145bbc10535afb19c09bff5c

---

src/System Application/App/VS Code Integration/src/VsCodeIntegrationImpl.Codeunit.al

GetAppIdForObject wouldn't work on System objects, since it's not on the "NAV App Installed App" record.
Fixes [AB#548696](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/548696)

Fix getting app ID for system objects

---

src/System Application/App/Azure AD Plan/src/PlanInstaller.Codeunit.al
src/System Application/App/Azure AD Plan/src/PlanUpgrade.Codeunit.al
src/System Application/App/Azure AD Plan/src/PlanUpgradeTag.Codeunit.al
src/System Application/Test/Azure AD Plan/src/AzureADPlanTests.Codeunit.al

**Problem**
The delegated dynamics 365 administrator is not added to the plan table. As a consequence, license configuration can not be set up for the role.
**Solution**
Add `Delegated Dynamics 365 Admin agent - Partner` plan.
Fixes [AB#548582](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/548582)

[Plans] Add plan for delegated dynamics 365 administrator

---

src/System Application/App/Data Administration/src/MediaCleanupImpl.Codeunit.al

**Problem**
**Solution**
Fixes [AB#550939](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/550939/)

[Tenant Media Cleanup] Only delete if filter is not empty

---

src/System Application/App/Data Administration/src/MediaCleanupImpl.Codeunit.al

**Problem**
**Solution**
Fixes [AB#550957](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/550957)

[24.5] [Tenant Media Cleanup] Only delete if filter is not empty

---

src/System Application/App/Data Administration/src/MediaCleanupImpl.Codeunit.al

**Problem**
**Solution**
Fixes [AB#550956](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/550956)

[24.4] [Tenant Media Cleanup] Only delete if filter is not empty

---

src/System Application/Test/Data Administration/src/MediaCleanupTest.Codeunit.al
src/System Application/Test/Data Administration/src/TestMediaCleanup.Table.al

Previously, we are only testing to see if Medias are cleaned up properly, adding test to ensure that we are not cleanup Media that aren't supposed to be cleaned up.
Fixes [AB#550939](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/550939)

Enhance test for Media Cleanup

---

src/System Application/App/Data Administration/src/MediaCleanupImpl.Codeunit.al

**Problem**
**Solution**
Fixes [AB#550958](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/550958/)

[24.x] [Tenant Media Cleanup] Only delete if filter is not empty

---

src/System Application/App/Data Administration/src/MediaCleanupImpl.Codeunit.al

**Problem**
**Solution**
Fixes [AB#550959](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/550959)

[25.0] [Tenant Media Cleanup] Only delete if filter is not empty 

---

src/System Application/App/Data Administration/src/MediaCleanupImpl.Codeunit.al

**Problem**
**Solution**
Fixes [AB#550960](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/550960)

[25.x] [Tenant Media Cleanup] Only delete if filter is not empty

---

src/System Application/App/DotNet Aliases/src/dotnet.al

Added dotnet wrappers for Purview telemetry 24.5 for use in BaseApp 24.5
[Original PR for 24.x](https://github.com/microsoft/BCApps/pull/2064)
Fixes [AB#550961](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/550961)

[Hotfix] Added dotnet wrappers for Purview telemetry 24.5

---

src/System Application/App/AI/src/Copilot/CopilotCapabilitiesGA.Page.al
src/System Application/App/Azure AD Plan/src/Plan Configuration/PlanConfiguration.Table.al
src/System Application/App/Azure AD Plan/src/Plan Configuration/PlanConfigurationCard.Page.al
src/System Application/App/Azure AD User Management/src/User sync/AzureADUserUpdateWizard.Page.al
src/System Application/App/Data Classification/app.json
src/System Application/App/Data Classification/src/DataClassificationMgtImpl.Codeunit.al
src/System Application/App/Feature Key/app.json
src/System Application/App/Feature Key/src/FeatureManagementImpl.Codeunit.al
src/System Application/App/Permission Sets/src/PermissionImpl.Codeunit.al
src/System Application/App/Permission Sets/src/PermissionSet.Page.al
src/System Application/App/Permission Sets/src/PermissionSetCopyImpl.Codeunit.al
src/System Application/App/Privacy Notice/app.json
src/System Application/App/Privacy Notice/src/PrivacyNoticeApproval.Codeunit.al
src/System Application/App/Retention Policy/src/Apply Retention Policy/ApplyRetentionPolicyImpl.Codeunit.al
src/System Application/App/Retention Policy/src/Retention Policy Setup/RetentionPolicySetup.Table.al
src/System Application/App/Security Groups/src/SecurityGroupPermissionSets.Page.al
src/System Application/App/User Settings/src/UserSettingsImpl.Codeunit.al
src/System Application/App/Web Service Management/src/WebServiceManagementImpl.Codeunit.al

Backporting [those changes](https://github.com/microsoft/BCApps/pull/2067) to 24.5.
It requires the use of DotNet wrappers for audit logging, made available with [this PR](https://github.com/microsoft/BCApps/pull/2114)
Fixes [AB#550437](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/550437)

[24.5] Adding Purview telemetry to the System apps

---

src/System Application/App/AI/src/Copilot/CopilotCapabilitiesGA.Page.al
src/System Application/App/Azure AD Plan/src/Plan Configuration/PlanConfiguration.Table.al
src/System Application/App/Azure AD Plan/src/Plan Configuration/PlanConfigurationCard.Page.al
src/System Application/App/Azure AD User Management/src/User sync/AzureADUserUpdateWizard.Page.al
src/System Application/App/Data Classification/app.json
src/System Application/App/Data Classification/src/DataClassificationMgtImpl.Codeunit.al
src/System Application/App/Feature Key/app.json
src/System Application/App/Feature Key/src/FeatureManagementImpl.Codeunit.al
src/System Application/App/Permission Sets/src/PermissionImpl.Codeunit.al
src/System Application/App/Permission Sets/src/PermissionSet.Page.al
src/System Application/App/Permission Sets/src/PermissionSetCopyImpl.Codeunit.al
src/System Application/App/Privacy Notice/app.json
src/System Application/App/Privacy Notice/src/PrivacyNoticeApproval.Codeunit.al
src/System Application/App/Retention Policy/src/Apply Retention Policy/ApplyRetentionPolicyImpl.Codeunit.al
src/System Application/App/Retention Policy/src/Retention Policy Setup/RetentionPolicySetup.Table.al
src/System Application/App/Security Groups/src/SecurityGroupPermissionSets.Page.al
src/System Application/App/User Settings/src/UserSettingsImpl.Codeunit.al
src/System Application/App/Web Service Management/src/WebServiceManagementImpl.Codeunit.al

Backporting [those changes](https://github.com/microsoft/BCApps/pull/2067) to 24.4.
It requires the use of DotNet wrappers for audit logging, made available with [this PR](https://github.com/microsoft/BCApps/pull/2116)
Fixes [AB#550434](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/550434)

[24.4] Adding Purview telemetry to the System apps

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.x] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  aae02ad59c6f4cd9d551a613b1d230d93e5a3098

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.1] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  aae02ad59c6f4cd9d551a613b1d230d93e5a3098

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.3] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  aae02ad59c6f4cd9d551a613b1d230d93e5a3098

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[main] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  aae02ad59c6f4cd9d551a613b1d230d93e5a3098

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.0] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  aae02ad59c6f4cd9d551a613b1d230d93e5a3098

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/25.x] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  aae02ad59c6f4cd9d551a613b1d230d93e5a3098

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/25.0] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  aae02ad59c6f4cd9d551a613b1d230d93e5a3098

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.2] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  aae02ad59c6f4cd9d551a613b1d230d93e5a3098

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.4] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  aae02ad59c6f4cd9d551a613b1d230d93e5a3098

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.5] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  aae02ad59c6f4cd9d551a613b1d230d93e5a3098

---

src/System Application/App/User Settings/src/UserSettingsImpl.Codeunit.al

Currently we are specifying that all users are in the current company, however we should only fall back to this if the user personalization does not specify otherwise.
This fixes an issue on users list where all users are shown to be in the current company.
Fixes [AB#537109](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/537109)

Fetching user settings should return the company specified in the user personalization if specified

---

src/System Application/App/User Permissions/src/UserSubform.Page.al

**Problem**
Permission lookup for assigning permission sets to users use an incorrect pattern of skipping the OnValidate trigger. This causes an issue when for example using F8 to copy a line after selecting one using the lookup.
**Solution**
Do not skip validation, instead set a filter on lookup which is used in the OnValidate trigger.
Fixes [AB#477318](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/477318/)

[User Subform] Fix permission set lookup

---

src/System Application/App/Extension Management/src/ExtensionSettings.Page.al

Surface an extension's build metadata Extension Settings page. More specifically, the system that compiled it and the URL where the package is located. These properties are defined in the app.json and/or stamped by some CI/CD pipelines, like AL-Go for Github:
Fixes [AB#547675](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/547675)

Add build metadata to Extension Settings page

---

src/Business Foundation/App/NoSeriesCopilot/Permissions/NoSeriesCopilotObjects.permissionset.al
src/Business Foundation/App/NoSeriesCopilot/src/Copilot/NoSeriesCopilotImpl.Codeunit.al
src/Business Foundation/App/NoSeriesCopilot/src/Copilot/NoSeriesGeneration.Page.al
src/Business Foundation/App/NoSeriesCopilot/src/Copilot/Search/Classic/NoSeriesTextMatchImpl.Codeunit.al
src/Business Foundation/App/NoSeriesCopilot/src/Copilot/Tools/NoSeriesCopAddIntent.Codeunit.al
src/Business Foundation/App/NoSeriesCopilot/src/Copilot/Tools/NoSeriesCopChangeIntent.Codeunit.al
src/Business Foundation/App/NoSeriesCopilot/src/Copilot/Tools/NoSeriesCopNxtYrIntent.Codeunit.al
src/Business Foundation/App/NoSeriesCopilot/src/Copilot/Tools/NoSeriesCopToolsImpl.Codeunit.al
src/Business Foundation/App/NoSeriesCopilot/src/Register/NoSeriesCopilotRegister.Codeunit.al

This PR addresses three critical bugs in the Number Series Copilot:
1. **Bug 1: Incorrect Intent Mapping for "Generate" Command**
- The system was misinterpreting the "generate" command, often preparing Number Series for the next period instead of creating a new one. The fix involves updating the tools definition and prompt to clarify the distinction between creating new Number Series and generating Number Series for the next period.
2. **Bug 2: Incorrect Field Check for Existing Number Series**
- The system was incorrectly performing checks on all fields for existing Number Series. The fix modifies the behavior to exclude pre-existing Number Series from the field validation checks, ensuring that only mandatory fields are validated for AI generated series.
3. **Bug 3: Blank Fields Causing …

[Number Series Copilot] Bug Fixes in Intent Understanding and Field Validation

---

src/System Application/App/Email/src/Scenario/EmailScenarioSetup.Page.al

If you open email scenarios and click assign scenarios, it fails if there is no email account due to an unguarded findfirst check.
Fixes [AB#551605](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/551605)

Fix unguarded record lookup which fails choosing email scenario with no email account

---

src/System Application/App/AppSource Gallery/src/AppSourceProductManager.Codeunit.al

Changes the market on the list page to all and only uses the Entra Id market when querying for the details (market is mandatory and all cannot be used).
Fixes [AB#555868](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/555868)

Get applications from all market in the AppSource Apps list page.

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.3] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  c62bf167f8c516d997bed1ed600a9d03d5093ad5

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.2] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  c62bf167f8c516d997bed1ed600a9d03d5093ad5

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.5] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  c62bf167f8c516d997bed1ed600a9d03d5093ad5

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[main] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  c62bf167f8c516d997bed1ed600a9d03d5093ad5

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.1] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  c62bf167f8c516d997bed1ed600a9d03d5093ad5

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.4] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  c62bf167f8c516d997bed1ed600a9d03d5093ad5

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.0] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  c62bf167f8c516d997bed1ed600a9d03d5093ad5

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/25.1] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  c62bf167f8c516d997bed1ed600a9d03d5093ad5

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/25.x] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  c62bf167f8c516d997bed1ed600a9d03d5093ad5

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/25.0] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  c62bf167f8c516d997bed1ed600a9d03d5093ad5

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.x] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  c62bf167f8c516d997bed1ed600a9d03d5093ad5

---

src/System Application/Test/Date and Time/src/UnixTimestampTest.Codeunit.al

This pull request backports #2287 to releases/25.0
The current date may have daylights savings or not. This will cause the test to fail if daylight savings is in effect. Hence getting the offset based on the given date instead.
Fixes [AB#555973](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/555973)

[releases/25.0] Unix Timestamp test should use offset for the specified date

---

src/System Application/Test/Date and Time/src/UnixTimestampTest.Codeunit.al

This pull request backports #2287 to releases/25.1
The current date may have daylights savings or not. This will cause the test to fail if daylight savings is in effect. Hence getting the offset based on the given date instead.
Fixes [AB#555972](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/555972)

[releases/25.1] Unix Timestamp test should use offset for the specified date

---

src/System Application/Test/Date and Time/src/UnixTimestampTest.Codeunit.al

This pull request backports #2287 to releases/25.x
The current date may have daylights savings or not. This will cause the test to fail if daylight savings is in effect. Hence getting the offset based on the given date instead.
Fixes [AB#555974](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/555974)

[releases/25.x] Unix Timestamp test should use offset for the specified date

---

src/System Application/App/Email/src/EmailInstaller.Codeunit.al

During upgrade and data migration, for some environments, they are running into an error that the Email Inbox is not in the allowed list of tables.
This PR fixes it by combining both upgrade functions into one, and exiting if the table is not in the list of allowed tables.
Fixes [AB#556484](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/556484)

[Email/RetPol] Harden retention policy for Email Inbox setup.

---

src/System Application/App/Email/src/EmailInstaller.Codeunit.al

This pull request backports #2324 to releases/25.x
Fixes [AB#557160](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/557160)

[releases/25.x] [Email/RetPol] Harden retention policy for Email Inbox setup.

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.2] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  50903624159826257124c0f799a1b4add9b0260b

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.5] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  50903624159826257124c0f799a1b4add9b0260b

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.x] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  50903624159826257124c0f799a1b4add9b0260b

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/25.0] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  50903624159826257124c0f799a1b4add9b0260b

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.3] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  50903624159826257124c0f799a1b4add9b0260b

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/25.1] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  50903624159826257124c0f799a1b4add9b0260b

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[main] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  50903624159826257124c0f799a1b4add9b0260b

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.1] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  50903624159826257124c0f799a1b4add9b0260b

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.4] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  50903624159826257124c0f799a1b4add9b0260b

---

src/System Application/App/Extension Management/src/ExtensionInstallationImpl.Codeunit.al
src/System Application/App/Extension Management/src/ExtnOrphanedAppDetails.Page.al

Fixes:
[AB#534788](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/534788)
Fixes #
Backport of https://github.com/microsoft/BCApps/pull/1976

[25.x] Use AppId function to delete orphaned extension data AB#557275

---

src/System Application/App/URI/src/UriBuilder.Codeunit.al
src/System Application/App/URI/src/UriBuilderImpl.Codeunit.al
src/System Application/Test/URI/src/UriBuilderQueryTest.Codeunit.al

UriBuilder procedures can only Add/Replace Query Flags/Parameters, while the internal procedure can parse them and set them, so I want to be able to use that to only Get/Remove from the collection.
There are different ways to implement this and many ways to test this, I just wanted to propose this approach which reuses what's already there for AddQueryFlag/Parameter, figuring we might need something like this for the upcoming HttpClient mocking: https://www.yammer.com/dynamicsnavdev/#/threads/show?threadId=3029127257333760 (why expose a special QueryParameter dictionary if we already have Uri/UriBuilder codeunits that are supposed to expose these structures for us?)
The new procedures added are:
```al
procedure RemoveQueryFlag(Flag: Text; DuplicateAction: Enum "Uri Query Duplicate …
```

Add procedures to Get/Remove for UriBuilder Query Paramaters/Flags

---

src/System Application/App/Extension Management/src/ExtensionInstallationImpl.Codeunit.al
src/System Application/App/Extension Management/src/ExtnOrphanedAppDetails.Page.al

Fixes:
[AB#534788](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/534788)
Summary
Work Item(s)
Fixes #
Backport of https://github.com/microsoft/BCApps/pull/1976

[25.0] Use AppId function to delete orphaned extension data AB#557278

---

src/System Application/App/Extension Management/src/ExtensionInstallationImpl.Codeunit.al
src/System Application/App/Extension Management/src/ExtnOrphanedAppDetails.Page.al

Fixes:
[AB#534788](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/534788)
Summary
Work Item(s)
Fixes #
Backport of https://github.com/microsoft/BCApps/pull/1976

[24.x] Use AppId function to delete orphaned extension data AB#557277 #557279

---

src/System Application/App/Extension Management/src/ExtensionInstallationImpl.Codeunit.al
src/System Application/App/Extension Management/src/ExtnOrphanedAppDetails.Page.al

Fixes:
[AB#534788](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/534788)
Summary
Work Item(s)
Fixes #
Backport of https://github.com/microsoft/BCApps/pull/1976

[24.5] Use AppId function to delete orphaned extension data AB#557280

---

src/System Application/App/OAuth2/OAuth2.Codeunit.al
src/System Application/App/OAuth2/OAuth2Impl.Codeunit.al
src/System Application/App/OAuth2/app.json

Adds a new function to the OAuth2 module, GetClaims().
It takes a JSON Web Token (JWT) and returns the Claims as a JSONObject.
Fixes #2296
Fixes [AB#556573](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/556573)

OAuth2.GetClaims()

---

src/System Application/App/Image/src/ImageImpl.Codeunit.al

Increase the file size limit from 5MB to 50MB so more image processing can be done within BC rather than externally
Fixes #1970
Fixes [AB#550942](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/550942)

Fixes #1970 Increasing Image File Size Limit to 50MB

---

src/Business Foundation/App/NoSeriesCopilot/src/Copilot/NoSeriesCopilotImpl.Codeunit.al
src/Business Foundation/App/NoSeriesCopilot/src/Copilot/NoSeriesGeneration.Page.al
src/Business Foundation/App/NoSeriesCopilot/src/Copilot/Telemetry/NoSeriesCopilotTelemetry.Codeunit.al
src/Business Foundation/App/NoSeriesCopilot/src/Copilot/Tools/NoSeriesCopAddIntent.Codeunit.al
src/Business Foundation/App/NoSeriesCopilot/src/Copilot/Tools/NoSeriesCopChangeIntent.Codeunit.al

Adding telemetry to the number series copilot:
- usage statistics
- what tool was used
- how many number series where generated
- did user specified patterns
- did user specified entities
- how many retries were done
- did the user applied the generated number series
- areas for which user generated number series
- entities for which user generated number series
Fixes #2252
Fixes [AB#558485](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/558485)

[Number Series Copilot] Adding Telemetry

---

src/Business Foundation/App/NoSeries/src/Setup/NoSeriesSetupImpl.Codeunit.al
src/Business Foundation/App/NoSeries/src/Single/NoSeries.Codeunit.al
src/Business Foundation/App/NoSeries/src/Single/NoSeriesImpl.Codeunit.al

Add Event for No. Series
Fixes #1362
Fixes [AB#558102](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/558102)

No. Series: Ability to extend filters on finding No. Series Lines when getting new numbers

---

src/System Application/App/Privacy Notice/src/PrivacyNoticeImpl.Codeunit.al

It is not possible in the current privacy notice telemetry to know which logs relate to what privacy notice IDs, which limits its usefulness
Fixes [AB#549916](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/549916/)

Add Privacy Notice IDs to telemetry statements

---

src/Tools/AI Test Toolkit/src/AITCommandLineCard.Page.al
src/Tools/AI Test Toolkit/src/TestSuite/AITALTestSuiteMgt.Codeunit.al
src/Tools/Test Framework/Test Runner/src/DataDrivenTest/DataDrivenTestTool.PageExt.al
src/Tools/Test Framework/Test Runner/src/DataDrivenTest/DataInputs/TestInputGroups.Page.al
src/Tools/Test Framework/Test Runner/src/DataDrivenTest/DataInputs/TestInputPart.Page.al
src/Tools/Test Framework/Test Runner/src/DataDrivenTest/DataInputs/TestInputsManagement.Codeunit.al

Add support in the Data-driven Test Tool for uploading datasets in `YAML` file format. 
`YAML` files are converted to `JSON `format and are as such a destructive action. Once uploaded and converted they are treated as `JSON`.
Multiple test cases are supported by defining a dictionary `tests`, e.g.:
```
tests:
- name: TEST01
description: (...)
- name: TEST02
description: (...)
(...)
```
A single test case can be uploaded with or without the `tests` key.
Fixes [AB#555676](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/548276)

[Data Driven Test Tool] Add YAML support

---

build/scripts/EnlistmentHelperFunctions.psm1
build/scripts/GuardingV2ExtensionsHelper.psm1

_**Issue**_:
Builds sometimes fail with:
```
Error: Unexpected error when running action. Error Message: Unable to find repoVersion in AL-Go-Settings.json, StackTrace: at Get-MaxAllowedObsoleteVersion, D:\a\BCApps\BCApps\build\scripts\GuardingV2ExtensionsHelper.psm1: line 264 <- at Update-AppSourceCopVersion, D:\a\BCApps\BCApps\build\scripts\GuardingV2ExtensionsHelper.psm1: line 208 <- at Enable-BreakingChangesCheck, D:\a\BCApps\BCApps\build\scripts\GuardingV2ExtensionsHelper.psm1: line 67 <- at <ScriptBlock>, D:\a\BCApps\BCApps\build\scripts\PreCompileApp.ps1: line 63 <- at <ScriptBlock>, D:\a\BCApps\BCApps\build\projects\System Application\.AL-Go\PreCompileApp.ps1: line 7 <- at <ScriptBlock>, C:\ProgramData\BcContainerHelper\6.0.29-preview1267\BcContainerHelper\AppHandling\Run-AlPipeline …
```

Add retries when running git fetch

---

src/System Application/App/Email/src/Account/EmailAccounts.Page.al

Variable Show Logo on Email Accounts page have no function:
It's always set to true.
We could do cleanup and remove it, behavior would stay same.
Fixes #2365
Fixes [AB#559267](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/559267)

Unnecessary variable ShowLogo in Email Accounts Page

---

build/scripts/EnlistmentHelperFunctions.psm1

Limit the minor version for baselines to 5 to avoid updating the baseline to a version that is not released for SaaS.
Fixes [AB#555469](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/555469)

Limit the minor version for baselines to 5

---

build/scripts/EnlistmentHelperFunctions.psm1

This pull request backports #2438 to releases/25.x
Fixes [AB#555469](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/555469)

[releases/25.x] Limit the minor version for baselines to 5

---

build/scripts/EnlistmentHelperFunctions.psm1

This pull request backports #2438 to releases/24.x
Fixes [AB#555469](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/555469)

[releases/24.x] Limit the minor version for baselines to 5

---

src/System Application/App/Email/src/EmailInstaller.Codeunit.al

Remove setup of Email Inbox retention policy and only add it to the Allowed Tables.
This has been a cause of upgrade failures.
Fixes [AB#559547](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/559547)

Remove emailinbox retention policy, just keep allowed tables

---

src/System Application/App/Table Information/src/TableInformationCacheImpl.Codeunit.al

Fix GetTableUrl for Tables with `DataPerCompany=false`
Fixes #2262
Fixes [AB#557526](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/557526)

Fix GetTableUrl for DataPerCompany=false

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.5] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  affc76e00812eaa4656997452d2f141c482cf3cc

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/25.1] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  affc76e00812eaa4656997452d2f141c482cf3cc

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.2] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  affc76e00812eaa4656997452d2f141c482cf3cc

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.3] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  affc76e00812eaa4656997452d2f141c482cf3cc

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.0] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  affc76e00812eaa4656997452d2f141c482cf3cc

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/25.0] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  affc76e00812eaa4656997452d2f141c482cf3cc

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.1] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  affc76e00812eaa4656997452d2f141c482cf3cc

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.4] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  affc76e00812eaa4656997452d2f141c482cf3cc

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.x] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  affc76e00812eaa4656997452d2f141c482cf3cc

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/25.x] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  affc76e00812eaa4656997452d2f141c482cf3cc

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[main] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  affc76e00812eaa4656997452d2f141c482cf3cc

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/25.2] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  affc76e00812eaa4656997452d2f141c482cf3cc

---

src/System Application/App/Agent/TaskPane/AgentTaskDetails.Page.al
src/System Application/App/Agent/TaskPane/AgentTaskTimeline.Page.al
src/System Application/App/Agent/TaskPane/AgentTasks.Page.al

Fixes [AB#536497](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/536497)

[25.2] Renaming agent objects

---

src/Business Foundation/App/NoSeries/src/Setup/NoSeriesSetupImpl.Codeunit.al

This pull request backports #2543 to releases/25.x
Fixes [AB#560710](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/560710)

[releases/25.x] Fixes an issue when comparing a blank no. series code to a filter for blank

---

src/Business Foundation/App/NoSeries/src/Setup/NoSeriesSetupImpl.Codeunit.al

This pull request backports #2543 to releases/25.2
Fixes [AB#560711](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/560711)

[releases/25.2] Fixes an issue when comparing a blank no. series code to a filter for blank

---

src/System Application/App/Email/src/Email/Inbox/EmailRetrievalFilters.Table.al

This filter allows each connector to parse and keep only the last message of the email contents of emails retrieved. Email clients automatically append the history messages when replying to an email.
Each connector still needs to implement this functionality.
Fixes [AB#560747](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/560747)

[Email] Add Last Message Only into the email filters table

---

src/System Application/App/Email/src/Email/Inbox/EmailRetrievalFilters.Table.al

This pull request backports #2547 to releases/25.2
Fixes [AB#560756](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/560756)

[releases/25.2] [Email] Add Last Message Only into the email filters table

---

src/System Application/App/ControlAddIns/Resources/PowerBIManagement/js/PowerBIManagement.js
src/System Application/App/Resources/PowerBIManagement/js/PowerBIManagement.js

In the Power BI embed addin, we allow AL code to set report filters through the add-in.
How that works in our current implementation is:
1. We open the AL page hosting the addin
1. Once the addin is ready, we Embed the Power BI report
1. Once the report is `loaded`, we set the initial filters
1. The filters can then be changed by AL code
The issue here happens in step 3, because we set the initial filters after the report is `loaded` and before it's `rendered`. In some cases and depending on the machine performances/internet connection/browser/Power BI service load, there can occur a race condition between the report being `rendered` and the filters being applied.
This is more visible when using the action "Expand Report", because the initial filter will always be in place there, and in …

[PowerBI] Avoid race condition when setting filters for a loaded report before it's rendered

---

src/System Application/App/External File Storage/src/Connector/FileStorageConnectorLogo.Table.al
src/System Application/App/External File Storage/src/Scenario/FileScenario.Table.al

Data should not be replicated, as data is created by the module itself.
Fixes [AB#561192](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/561192)

Bug 561192: Don't replicate data of Ext. File Storage tables

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/25.x] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  f38e373bfc51cc2349114b04a159f7179de47502

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[main] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  f38e373bfc51cc2349114b04a159f7179de47502 / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.1] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  f38e373bfc51cc2349114b04a159f7179de47502

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.0] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  f38e373bfc51cc2349114b04a159f7179de47502

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/25.0] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  f38e373bfc51cc2349114b04a159f7179de47502

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/25.1] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  f38e373bfc51cc2349114b04a159f7179de47502

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.2] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  f38e373bfc51cc2349114b04a159f7179de47502

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.4] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  f38e373bfc51cc2349114b04a159f7179de47502

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.3] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  f38e373bfc51cc2349114b04a159f7179de47502

---

src/rulesets/ruleset.json

The new PTECop is meant to block moves in PTEs as it is not supported yet. However, we run PTECop on apps like the business foundation which is not a PTE
Fixes [AB#561076](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/561076)

Exception for PTE0024 - Unblock uptake

---

.github/actions/RunAutomation/run.ps1

_**Issue**_: 
The target branch part when creating automation PRs is duplicated:
Fixes [AB#561456](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/561456)

Remove duplicate part in branch name when running automations

---

src/System Application/App/Data Compression/src/DataCompression.Codeunit.al

Multiple apps are still depending on this function and will stop working. Hence delaying the obsoletion of the function further and more announcements should also be provided about it now. This is not to start a trend but one time since many tenants will be affected by the removal at this time (see bug).
Fixes [AB#561369](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/561369)

Delay obsoletion of ExtractEntry

---

.github/AL-Go-Settings.json

This pull request backports #2498 to releases/24.5

[releases/24.5] Add Commit Options to AL-Go created pull requests

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[main] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  044c659dce8d72c3f1750a55dd7792c4db0a0a56 / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.0] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  044c659dce8d72c3f1750a55dd7792c4db0a0a56 / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.x] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  044c659dce8d72c3f1750a55dd7792c4db0a0a56 / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.3] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  044c659dce8d72c3f1750a55dd7792c4db0a0a56 / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/25.1] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  044c659dce8d72c3f1750a55dd7792c4db0a0a56 / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/25.0] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  044c659dce8d72c3f1750a55dd7792c4db0a0a56 / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.1] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  044c659dce8d72c3f1750a55dd7792c4db0a0a56 / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.4] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  044c659dce8d72c3f1750a55dd7792c4db0a0a56 / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.2] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  044c659dce8d72c3f1750a55dd7792c4db0a0a56 / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/25.2] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  044c659dce8d72c3f1750a55dd7792c4db0a0a56 / Related to AB#539394

---

src/System Application/App/Word Templates/src/WordTemplatesRelatedPart.Page.al

The issue was reported here: https://github.com/microsoft/ALAppExtensions/issues/23867
In essence, if you ever got the error message that more than 250 fields were selected and you tried to delete a row, the count wouldn't get updated and you couldn't get past it. Now you can.
Fixes [AB#501006](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/501006)

Bug 501006: [Bug] Page "Word Template Creation Wizard" (9995) - missing variable update leads to an error #23867

---

.github/AL-Go-Settings.json

This pull request backports #2721 to releases/25.x
Fixes [AB#562071](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/562071)

[releases/25.x] Migrate cleanModePreProcessorSymbols to a conditional setting

---

.github/AL-Go-Settings.json

This pull request backports #2732 to releases/25.3

[releases/25.3] Run CLEAN mode only on main and major release branches

---

.github/AL-Go-Settings.json

This pull request backports https://github.com/microsoft/BCApps/pull/2732 to releases/25.2

[releases/25.2] Run CLEAN mode only on main and major release branches

---

.github/AL-Go-Settings.json

This pull request backports #2732 to releases/25.1

[releases/25.1] Run CLEAN mode only on main and major release branches

---

.github/AL-Go-Settings.json

This pull request backports #2732 to releases/25.0

[releases/25.0] Run CLEAN mode only on main and major release branches

---

.github/AL-Go-Settings.json

This pull request backports #2732 to releases/24.x

[releases/24.x] Run CLEAN mode only on main and major release branches

---

.github/AL-Go-Settings.json

This pull request backports #2732 to releases/24.5

[releases/24.5] Run CLEAN mode only on main and major release branches

---

.github/AL-Go-Settings.json

This pull request backports #2732 to releases/24.4

[releases/24.4] Run CLEAN mode only on main and major release branches

---

.github/AL-Go-Settings.json

This pull request backports #2732 to releases/24.3

[releases/24.3] Run CLEAN mode only on main and major release branches

---

.github/AL-Go-Settings.json

This pull request backports #2732 to releases/24.2

[releases/24.2] Run CLEAN mode only on main and major release branches

---

.github/AL-Go-Settings.json

This pull request backports #2732 to releases/24.1

[releases/24.1] Run CLEAN mode only on main and major release branches

---

.github/AL-Go-Settings.json

This pull request backports #2732 to releases/24.0

[releases/24.0] Run CLEAN mode only on main and major release branches

---

src/System Application/App/AI/src/Azure OpenAI/AzureOpenAIImpl.Codeunit.al
src/System Application/App/AI/src/Azure OpenAI/Chat Completion/AOAIChatMessagesImpl.Codeunit.al

This pull request backports #2723 to releases/25.x
Fixes [AB#562309](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/562309)

[releases/25.x] [Copilot] Reduce KV checks for embed ISVs

---

src/System Application/App/Edit in Excel/src/EditinExcelImpl.Codeunit.al
src/System Application/Test/Edit in Excel/src/EditInExcelTest.Codeunit.al

Support plus signs in field names when using Edit In Excel. Currently plus is interpreted as x002b by Edit In Excel and x002B by the platform.
In response to [(95) Viva Engage : Dynamics 365 Business Central Partner Community (Formerly: Development) : View Conversation](https://www.yammer.com/dynamicsnavdev/#/Threads/show?threadId=3120316127158272)
Fixes [AB#562349](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/562349)

[Edit In Excel] Support plus signs in field names (Currently plus is interpreted as x002b by Edit In Excel and x002B by the platform)

---

.github/AL-Go-Settings.json

This pull request backports #2732 to releases/25.x

[releases/25.x] Run CLEAN mode only on main and major release branches

---

src/System Application/App/ControlAddIns/Resources/BusinessChart/js/BusinessChartAddIn.js
src/System Application/App/ControlAddIns/Resources/RoleCenterSelector/js/RoleCenterSelector.js
src/System Application/App/ControlAddIns/Resources/WelcomeWizard/js/WelcomeWizard.js
src/System Application/App/ControlAddIns/src/BusinessChart.ControlAddin.al
src/System Application/App/ControlAddIns/src/MicrosoftDynamicsNavClientBusinessChart.ControlAddin.al
src/System Application/App/ControlAddIns/src/MicrosoftDynamicsNavClientRoleCenterSelector.ControlAddin.al
src/System Application/App/ControlAddIns/src/MicrosoftDynamicsNavClientWelcomeWizard.ControlAddin.al
src/System Application/App/ControlAddIns/src/RoleCenterSelector.ControlAddin.al
src/System Application/App/ControlAddIns/src/WelcomeWizard.ControlAddin.al
src/System Application/App/Resources/BusinessChart/js/BusinessChartAddIn.js
src/System Application/App/Resources/RoleCenterSelector/js/RoleCenterSelector.js
src/System Application/App/Resources/WelcomeWizard/js/WelcomeWizard.js

jQuery is being removed from the client and this PR migrates from jQuery to native javascript code in the highchart add-in.
Fixes [AB#560172](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/560172)

Remove jQuery from add-ins

---

src/System Application/App/Extension Management/src/MarketplaceExtnDeployment.Page.al

Minor cleanup of the installation page.
Fixes [AB#547941](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/547941)

Update extension installation page

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.3] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  b608fc6787759aaac18f1407750c3436b6553b88 / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.0] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  b608fc6787759aaac18f1407750c3436b6553b88 / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.x] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  b608fc6787759aaac18f1407750c3436b6553b88 / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.5] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  b608fc6787759aaac18f1407750c3436b6553b88 / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/25.x] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  b608fc6787759aaac18f1407750c3436b6553b88 / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/25.0] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  b608fc6787759aaac18f1407750c3436b6553b88 / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.2] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  b608fc6787759aaac18f1407750c3436b6553b88 / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.4] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  b608fc6787759aaac18f1407750c3436b6553b88 / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[main] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  b608fc6787759aaac18f1407750c3436b6553b88 / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/25.3] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  b608fc6787759aaac18f1407750c3436b6553b88 / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/25.2] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  b608fc6787759aaac18f1407750c3436b6553b88 / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/25.1] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  b608fc6787759aaac18f1407750c3436b6553b88 / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.1] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  b608fc6787759aaac18f1407750c3436b6553b88 / Related to AB#539394

---

src/Tools/Test Framework/Test Runner/src/TestSuiteMgt.Codeunit.al

Fix for the update of the test methods for multiple codeunits
Fixes [AB#563441](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/563441)

[25.x] Fixing update of the test methods

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.29478.0

[main] Update BCArtifact version. New value: 26.0.29478.0

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.29538.0

[main] Update BCArtifact version. New value: 26.0.29538.0

---

src/Tools/AI Test Toolkit/src/TestSuite/AITTestSuite.Page.al
src/Tools/AI Test Toolkit/src/TestSuite/AITTestSuiteMgt.Codeunit.al

Changed action "Reset Status" to "Cancel" to make it more clear that a run can be cancelled. 
Changed caption and promoted action. Action only shows for runs that are currently running. Cancelling the run will set the status to Cancelled instead of Completed.
Fixes [AB#544429](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/544429/)

[AI Test Tool] Add cancel action for running suites

---

src/System Application/App/Permissions/SystemApplicationAdmin.PermissionSet.al

Adds missing admin permissions for the Ext. File Storage module to the admin set of the System Application
Fixes [AB#564482](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/564482)

Bug 564482: W1 2025 - Bug Bash I: Cannot setup Ext. File Storage module - probably missing permissions

---

src/System Application/App/Security Groups/src/SecurityGroupImpl.Codeunit.al
src/System Application/App/User Permissions/src/UserSubform.Page.al

Add missing audit log events:
- Assign permission sets to user or user group
- Add security group
Fixes [AB#563993](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/563993)

[Purview] Add missing audit log events

---

.github/AL-Go-Settings.json

Memory limit 16G was added in order to successfully uptake latest artifact: https://github.com/microsoft/BCApps/pull/2888

Remove memory limit 16G

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.29926.0

[main] Update BCArtifact version. New value: 26.0.29926.0

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.x] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  b637e79b7209c4b6e42696e1efdb066a0a25f3fb / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.2] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  b637e79b7209c4b6e42696e1efdb066a0a25f3fb / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.0] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  b637e79b7209c4b6e42696e1efdb066a0a25f3fb / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.3] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  b637e79b7209c4b6e42696e1efdb066a0a25f3fb / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.1] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  b637e79b7209c4b6e42696e1efdb066a0a25f3fb / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.5] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  b637e79b7209c4b6e42696e1efdb066a0a25f3fb / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/25.2] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  b637e79b7209c4b6e42696e1efdb066a0a25f3fb / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/25.0] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  b637e79b7209c4b6e42696e1efdb066a0a25f3fb / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/25.x] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  b637e79b7209c4b6e42696e1efdb066a0a25f3fb / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/25.4] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  b637e79b7209c4b6e42696e1efdb066a0a25f3fb / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/25.3] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  b637e79b7209c4b6e42696e1efdb066a0a25f3fb / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/25.1] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  b637e79b7209c4b6e42696e1efdb066a0a25f3fb / Related to AB#539394

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.30068.0

[main] Update BCArtifact version. New value: 26.0.30068.0

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.30098.0

[main] Update BCArtifact version. New value: 26.0.30098.0

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.30142.0

[main] Update BCArtifact version. New value: 26.0.30142.0

---

.github/AL-Go-Settings.json

- Update BCArtifact version. New value: 26.0.30278.0

[main] Update BCArtifact version. New value: 26.0.30278.0

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/25.0] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  4c9ea6f8e445c270e93ff18ec7cf07153256ec8f / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/25.1] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  4c9ea6f8e445c270e93ff18ec7cf07153256ec8f / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.x] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  4c9ea6f8e445c270e93ff18ec7cf07153256ec8f / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.4] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  4c9ea6f8e445c270e93ff18ec7cf07153256ec8f / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/25.x] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  4c9ea6f8e445c270e93ff18ec7cf07153256ec8f / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.5] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  4c9ea6f8e445c270e93ff18ec7cf07153256ec8f / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/25.3] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  4c9ea6f8e445c270e93ff18ec7cf07153256ec8f / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.1] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  4c9ea6f8e445c270e93ff18ec7cf07153256ec8f / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.2] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  4c9ea6f8e445c270e93ff18ec7cf07153256ec8f / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.3] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  4c9ea6f8e445c270e93ff18ec7cf07153256ec8f / Related to AB#539394

---

src/System Application/Test/Feature Key/src/FeatureKeyTest.Codeunit.al

The feature key SAFTAuditFileExport must be removed, but the test T009_EnableOneWayFeatureThatDoesNotRequireDataUpdate fails in platform repository when the key is removed.
Test must be fixed before the key is removed.
Test fails when there are no FeatureKey records with specific field values were not found. The error is: "The following UI handlers were not executed: ConfirmYesHandler"
I added dummy confirm to prevent such failure.
Fixes [AB#564916](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/564916)

[Feature Management] Fix test to be able to remove the Feature Key SAFTAuditFileExport

---

src/Business Foundation/App/NoSeries/src/Setup/NoSeriesLine.Table.al

When the No. Series "Warning No." field is set to empty, we don't need to validate that "Ending No." is set. It should always be possible to remove the "Warning No.".
Fixes [AB#563048](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/563048)

Updated Warning No Field of No Series Line table

---

src/System Application/App/Feature Key/permissions/FeatureKeyView.PermissionSet.al
src/System Application/App/Web Service Management/app.json
src/System Application/App/Web Service Management/permissions/WebServiceManagementAdmin.Permissionset.al
src/System Application/App/Web Service Management/permissions/WebServiceManagementRead.Permissionset.al
src/System Application/App/Web Service Management/src/WebServiceManagementImpl.Codeunit.al
src/System Application/Test/Web Service Management/src/WebServiceManagementTest.Codeunit.al

When the feature key `DisableSOAPwebservicesonMicrosoftUIpages` is on, it's no longer possible to expose a Microsoft page as a SOAP endpoint. Starting version 29.0 it will be on by default. 
This PR shows the endpoints as "Not applicable" for these pages when the feature key is on.
Fixes [AB#566342](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/566342)

Remove ability to expose a Microsoft page as a SOAP endpoint

---

.github/AL-Go-Settings.json
src/System Application/App/Environment Information/src/EnvironmentInformation.Codeunit.al
src/System Application/App/Environment Information/src/EnvironmentInformationImpl.Codeunit.al

Exposing the EnvironmentSettings for Microsoft published callers.
[AB#565525](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/565525)

Exposing application environment settings.

---

src/System Application/App/Extension Management/src/ExtensionManagement.Page.al
src/System Application/App/VS Code Integration/src/VsCodeIntegrationImpl.Codeunit.al

This pull request backports #3118 to releases/26.x
Fixes [AB#565834](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/565834)
Fixes [AB#565829](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/565829)

[releases/26.x] [VS Code Integration] Fix filtering of extensions and enabling of "Get selected as dependencies" actions

---

src/System Application/App/Extension Management/src/ExtensionManagement.Page.al
src/System Application/App/VS Code Integration/src/VsCodeIntegrationImpl.Codeunit.al

This pull request backports #3118 to releases/26.0
Fixes [AB#565834](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/565834)
Fixes [AB#565829](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/565829)

[releases/26.0] [VS Code Integration] Fix filtering of extensions and enabling of "Get selected as dependencies" actions

---

src/System Application/App/Extension Management/src/ExtensionManagement.Page.al

Two bug fixes:
- List view changes when selecting extensions and running "Get selected as dependencies"
- "Get selected as dependencies" actions were not enabled for apps which were not installed
Fixes [AB#565834](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/565834)
Fixes [AB#565829](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/565829)

[VS Code Integration] Fix filtering of extensions and enabling of "Get selected as dependencies" actions

---

src/System Application/App/VS Code Integration/src/VsCodeIntegrationImpl.Codeunit.al

When trying to navigate to the source code for objects  belonging to the System app, this would not work. This is because the id was wrongly set.
Fixes [AB#548696](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/548696)

[VS Code Integration] Fix navigating to System app objects definition

---

src/Tools/AI Test Toolkit/src/Logs/AITTestData.Codeunit.al

Add support to view specific elements when data is multi-turn. The selected element will be displayed in the test data view with the associated turn number specified.
Example of comparing expected data and answer:
Fixes [AB#559325](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/559325)

[AI Test Tool] Add support for multi-turn in test data view

---

src/System Application/App/Word Templates/src/WordTemplate.Codeunit.al
src/System Application/App/Word Templates/src/WordTemplateImpl.Codeunit.al
src/System Application/Test/Word Templates/app.json
src/System Application/Test/Word Templates/src/WordTemplatesTest.Codeunit.al

This change addresses two issues that were present in the AddUnrelatedTable method.
1. The result of the implementation method call is returned so that callers know if the record was successfully added.
2. The "Word Templates Related Table" record that is created has the word template code assigned to it that was provided by the caller.
Fixes #3105 
Fixes [AB#567861](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/567861)

[Word Template] Fix unexpected behavior of AddUnrelatedTable

---

src/Business Foundation/App/NoSeries/src/Batch/NoSeriesBatchImpl.Codeunit.al

The MI5 and MI4 logs uses a lot of space and aren't really useful. Hence removing these to telemetry tags.
Fixes [AB#567206](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/567206)

Remove MI5 and MI4 logs

---

src/System Application/App/External File Storage/src/Lookup/FileAccountBrowserMgt.Codeunit.al

```
ExternalFileStorage.Initialize("File Scenario"::Default);
Path := ExternalFileStorage.SelectAndGetFilePath('', '*.png');
```
Shows now only png files and folders.
Fixes #3127
Fixes [AB#567860](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/567860)

External File Storage: Fix File Name Filter in Storage Browser

---

src/System Application/App/Retention Policy/src/Retention Policy Log/RetentionPolicyLogImpl.Codeunit.al
src/System Application/Test Library/Retention Policy/src/RetentionPolicyTestLibrary.Codeunit.al
src/System Application/Test/Retention Policy/src/RetentionPolicyLogTest.Codeunit.al

This pull request backports #3140 to releases/25.x
Fixes [AB#568056](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/568056)

[releases/25.x] Only send errors to background session for logging

---

src/System Application/App/Retention Policy/src/Retention Policy Log/RetentionPolicyLogImpl.Codeunit.al
src/System Application/Test Library/Retention Policy/src/RetentionPolicyTestLibrary.Codeunit.al
src/System Application/Test/Retention Policy/src/RetentionPolicyLogTest.Codeunit.al

This pull request backports #3140 to releases/26.0
Fixes [AB#568057](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/568057)

[releases/26.0] Only send errors to background session for logging

---

src/System Application/App/Retention Policy/src/Retention Policy Log/RetentionPolicyLogImpl.Codeunit.al
src/System Application/Test Library/Retention Policy/src/RetentionPolicyTestLibrary.Codeunit.al
src/System Application/Test/Retention Policy/src/RetentionPolicyLogTest.Codeunit.al

This pull request backports #3140 to releases/26.x
Fixes [AB#568055](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/568055)

[releases/26.x] Only send errors to background session for logging

---

src/System Application/App/AI/src/Copilot/CopilotTelemetry.Codeunit.al

Custom dimensions for data movement are emitted in local language. They should always be emitted in default language.
Fixes [AB#567744](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/567744)

[26.x] [Copilot] Ensure custom dimensions for data movement telemetry are emitted in default language

---

src/System Application/App/Language/src/Language.Codeunit.al
src/System Application/App/Language/src/LanguageImpl.Codeunit.al

Power BI add-in and other functionalities require the user language in the form of the user language tag. Currently we are using GetCurrentCultureName which references the Dotnet object CultureInfo, but recommendations from the server team advise to resolve GlobalLanguage using the system tables instead.
Related [AB#568067](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/568067)

[Language] Add function to get current user language tag (e.g. 'en-US')

---

src/System Application/App/AI/src/Copilot/CopilotTelemetry.Codeunit.al

Custom dimensions for data movement are emitted in local language. They should always be emitted in default language.
Fixes [AB#567743](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/567743)

[26.0] [Copilot] Ensure custom dimensions for data movement telemetry are emitted in default language

---

src/System Application/App/Email/src/Account/EmailAccount.Codeunit.al
src/System Application/App/Email/src/Account/EmailAccountImpl.Codeunit.al

Call event during account deletion.
When using an SMTP account, for example, it is possible to delete the account from the card page. The card page is not part of the system or base application, so this will add an event which captures all potential email account types.
Fixes #2957 
Fixes [AB#559950](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/559950)

Add integration event.

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[main] Update AL-Go System Files from microsoft/AL-Go-PTE@preview -  6e5bf7752c8288a922c50393814925d794e9ec38 / Related to AB#539394

---

src/Business Foundation/App/NoSeries/readme_refactoring.md
src/Business Foundation/App/NoSeries/src/Legacy/NoSeriesManagement.Codeunit.al
src/Business Foundation/App/NoSeries/src/Setup/NoSeriesSetup.Codeunit.al
src/Business Foundation/App/NoSeries/src/Setup/NoSeriesSetupImpl.Codeunit.al
src/Business Foundation/App/NoSeries/src/Single/NoSeriesStatelessImpl.Codeunit.al

IncStr can now handle incrementing numbers higher or lower than 1. Hence we should be using that platform functionality instead as it's also much faster.
Fixes [AB#557645](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/557645)

Obsolete IncrementNoText in favor of IncStr

---

src/System Application/App/Retention Policy/src/Apply Retention Policy/ApplyRetentionPolicyImpl.Codeunit.al

Every time SafeApplyRetentionPolicy is called, the number of records deleted more than doubles. This is because we first set number of deleted records to the number already deleted ex. 1000, then cleanup records (it will increase this value further say it deletes 100, now 1100), then TotalNumberOfRecordsDeleted is incremented to 2100 instead of just 1100.
Fixes [AB#571294](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/571294)

The number of records deleted are doubled every run

---

src/System Application/App/Retention Policy/src/Apply Retention Policy/ApplyRetentionPolicyImpl.Codeunit.al

Every time SafeApplyRetentionPolicy is called, the number of records
deleted more than doubles. This is because we first set number of
deleted records to the number already deleted ex. 1000, then cleanup
records (it will increase this value further say it deletes 100, now
1100), then TotalNumberOfRecordsDeleted is incremented to 2100 instead
of just 1100.
Fixes [AB#571357](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/571357)

[26.x] The number of records deleted are doubled every run

---

src/System Application/App/Retention Policy/src/Apply Retention Policy/ApplyRetentionPolicyImpl.Codeunit.al

Every time SafeApplyRetentionPolicy is called, the number of records
deleted more than doubles. This is because we first set number of
deleted records to the number already deleted ex. 1000, then cleanup
records (it will increase this value further say it deletes 100, now
1100), then TotalNumberOfRecordsDeleted is incremented to 2100 instead
of just 1100.
Fixes [AB#571356](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/571356)

[26.0] The number of records deleted are doubled every run

---

src/System Application/App/Retention Policy/src/Apply Retention Policy/ApplyRetentionPolicyImpl.Codeunit.al

Every time SafeApplyRetentionPolicy is called, the number of records
deleted more than doubles. This is because we first set number of
deleted records to the number already deleted ex. 1000, then cleanup
records (it will increase this value further say it deletes 100, now
1100), then TotalNumberOfRecordsDeleted is incremented to 2100 instead
of just 1100.
Fixes [AB#571354](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/571354)

[25.5] The number of records deleted are doubled every run

---

src/System Application/App/Retention Policy/src/Apply Retention Policy/ApplyRetentionPolicyImpl.Codeunit.al

Every time SafeApplyRetentionPolicy is called, the number of records
deleted more than doubles. This is because we first set number of
deleted records to the number already deleted ex. 1000, then cleanup
records (it will increase this value further say it deletes 100, now
1100), then TotalNumberOfRecordsDeleted is incremented to 2100 instead
of just 1100.
Fixes [AB#571355](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/571355)

[25.x] The number of records deleted are doubled every run

---

src/rulesets/PTECop.ruleset.json

Change ruleset to allow app names of 1st party apps to be larger than 50 characters, the PTE0010 diagnostic is meant for PTEs that are stored in EMRS which imposes such limit. This is not the case for 1st party apps in FAME.
[AB#571703](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/571703)

Allowing app names of 1st party apps to be larger than 50 characters.

---

src/System Application/App/External File Storage/src/FileStorage/ExternalFileStorage.Codeunit.al
src/System Application/App/External File Storage/src/FileStorage/ExternalFileStorageImpl.Codeunit.al
src/System Application/App/External File Storage/src/Lookup/StorageBrowser.Page.al

Allows to predefine the FileName:
```
trigger OnAction()
var
ExternalFileStorage: Codeunit "External File Storage";
Path: Text;
begin
ExternalFileStorage.Initialize("File Scenario"::Default);
Path := ExternalFileStorage.SaveFile('2023', 'Invoice_1234', 'pdf', 'Save invoice...');
end;
```
Fixes #3272
Fixes [AB#571521](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/571521)

External File Storage: Allow to suggest a filename in SaveFile

---

src/System Application/App/Data Administration/app.json
src/System Application/App/Data Administration/src/MediaCleanupImpl.Codeunit.al
src/System Application/Test/Data Administration/src/MediaCleanupTest.Codeunit.al

Fix media cleanup runtime error
Update SplitListIntoSubLists procedure to get consistent result
Tests for edge cases for SplitListIntoSubLists and Media Cleanup
Fixes #3271
Fixes [AB#571724](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/571724)

Fix media cleanup runtime error

---

src/System Application/App/Performance Profiler/app.json
src/System Application/App/Performance Profiler/src/PerfProfileActivityType.enum.al
src/System Application/App/Performance Profiler/src/PerfProfilerScheduleCard.Page.al
src/System Application/App/Performance Profiler/src/PerfProfilerSchedulesList.Page.al
src/System Application/App/Performance Profiler/src/PerformanceProfileList.Page.al
src/System Application/App/Performance Profiler/src/ScheduledPerfProfilerImpl.Codeunit.al

Bunch of UX improvements:
Fixes [AB#567095](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/567095)

Profile schedules UX improvements

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.3@344b2e8] Update AL-Go System Files from microsoft/AL-Go-PTE@preview - 81401b5 / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/26.0@a4cade9] Update AL-Go System Files from microsoft/AL-Go-PTE@preview - 81401b5 / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.4@a7c5a0c] Update AL-Go System Files from microsoft/AL-Go-PTE@preview - 81401b5 / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/26.x@16be982] Update AL-Go System Files from microsoft/AL-Go-PTE@preview - 81401b5 / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/25.x@198fa28] Update AL-Go System Files from microsoft/AL-Go-PTE@preview - 81401b5 / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/25.4@ff5fd77] Update AL-Go System Files from microsoft/AL-Go-PTE@preview - 81401b5 / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/25.2@5a00209] Update AL-Go System Files from microsoft/AL-Go-PTE@preview - 81401b5 / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.5@467626e] Update AL-Go System Files from microsoft/AL-Go-PTE@preview - 81401b5 / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/25.1@ddefca2] Update AL-Go System Files from microsoft/AL-Go-PTE@preview - 81401b5 / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.x@5d5ebdf] Update AL-Go System Files from microsoft/AL-Go-PTE@preview - 81401b5 / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/25.3@630c484] Update AL-Go System Files from microsoft/AL-Go-PTE@preview - 81401b5 / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/Packages.json
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/25.5@2e1e988] Update AL-Go System Files from microsoft/AL-Go-PTE@preview - 81401b5 / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[main@e6ed0c2] Update AL-Go System Files from microsoft/AL-Go-PTE@preview - 81401b5 / Related to AB#539394

---

src/System Application/App/Email/src/Email/Email.Codeunit.al

Changed EmailScenarioAttachments record to be by var in an event to be able to set filters.
Fixes #3034 
Fixes [AB#568527](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/568527)

Fixes #3034

---

src/System Application/App/Permission Sets/src/xmlports/ImportPermissionSets.xmlport.al
src/System Application/Test/Permission Sets/src/PermissionImportExportTests.Codeunit.al

With this change, I have enabled the user to be able to overwrite permission sets contained in the import file. Up until now, the permissions from the import file were merged with the permissions already present in the permission sets.
The majority of changes were done in this repo but the text for a confirmation dialog has been changed in the repo containing the Base App
https://github.com/microsoft/BusinessCentralApps/pull/1287
Importing user defined permissions sets leaves permissions in inconsistent state.
Users tend to test the permissions sets in multiple rounds in a test system. After they are satisfied with the result they decide to import it in a production. However the outcome of the import is not reliable. Users would like to overwrite current user defined permission set with …

Importing Permissions with Overwrite Option

---

src/Tools/AI Test Toolkit/src/AITTestContextImpl.Codeunit.al

Causes indexing error in multi-turn testing. 
Current turn should never be larger than number of turns. Otherwise GetTestInput will fail:
`TestInputJson := TestInput.GetTestInput(TurnsTok).ElementAt(CurrentTurn - 1).Element(ElementName)`
Fixes [AB#571847](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/571847)

[AI Test Tool] Fix GetNextTurn

---

src/System Application/App/Agent/Interaction/AgentMessage.Codeunit.al
src/System Application/App/Agent/Interaction/AgentMessageImpl.Codeunit.al
src/System Application/App/Agent/Interaction/AgentTask.Codeunit.al
src/System Application/App/Agent/Interaction/AgentTaskImpl.Codeunit.al

Add agent message API to add attachment to task message.
Fixes [AB#547967](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/547967)

[Agent] Add API to add attachment to task message

---

src/Tools/Test Framework/Test Runner/src/CommandLineTestTool.Page.al

Adds information about the current execution to Command Line Test Tool (CompanyName, TenantID & LanguageID).
This should make it possible to read information about the current environment when executing tests.
Fixes #3278
Fixes [AB#566597](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/566597)

Add CompanyName, TenantID, LanguageID to Command Line Test Tool

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/26.0@91e8027] Update AL-Go System Files from microsoft/AL-Go-PTE@preview - ad07b06 / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/26.x@eb516d4] Update AL-Go System Files from microsoft/AL-Go-PTE@preview - ad07b06 / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.5@b6ac54d] Update AL-Go System Files from microsoft/AL-Go-PTE@preview - ad07b06 / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/25.1@ed877ba] Update AL-Go System Files from microsoft/AL-Go-PTE@preview - ad07b06 / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/25.4@f76f18b] Update AL-Go System Files from microsoft/AL-Go-PTE@preview - ad07b06 / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[main@a96c2ae] Update AL-Go System Files from microsoft/AL-Go-PTE@preview - ad07b06 / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/25.0@13030b2] Update AL-Go System Files from microsoft/AL-Go-PTE@preview - ad07b06 / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/25.2@d91e0ee] Update AL-Go System Files from microsoft/AL-Go-PTE@preview - ad07b06 / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/25.x@8ff8c2b] Update AL-Go System Files from microsoft/AL-Go-PTE@preview - ad07b06 / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Framework/.AL-Go/cloudDevEnv.ps1
build/projects/Test Framework/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/24.x@9e05c63] Update AL-Go System Files from microsoft/AL-Go-PTE@preview - ad07b06 / Related to AB#539394

---

.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/CICD.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
build/projects/Business Foundation/.AL-Go/cloudDevEnv.ps1
build/projects/Business Foundation/.AL-Go/localDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/cloudDevEnv.ps1
build/projects/Performance Toolkit/.AL-Go/localDevEnv.ps1
build/projects/System Application Modules/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Modules/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests (No Isolation)/.AL-Go/localDevEnv.ps1
build/projects/System Application Tests/.AL-Go/cloudDevEnv.ps1
build/projects/System Application Tests/.AL-Go/localDevEnv.ps1
build/projects/System Application/.AL-Go/cloudDevEnv.ps1
build/projects/System Application/.AL-Go/localDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/cloudDevEnv.ps1
build/projects/Test Stability Tools/.AL-Go/localDevEnv.ps1

[releases/25.3@90ab4b3] Update AL-Go System Files from microsoft/AL-Go-PTE@preview - ad07b06 / Related to AB#539394

---

src/System Application/App/Azure AD User Management/src/AzureADUserMgmtImpl.Codeunit.al

When application users are used for API calls, they're not users that can be logged into BC directly through a webclient session.
This bypasses the checks to graph in app which is only done the first time a user logs in. The check is always done by platform when any user logs into BC.
Fixes [AB#569521](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/569521)

Skip API and ODATAV4 client types in Azure AD User Mgt

---

CODEOWNERS

Make Engineering Systems owner of app.json files.
This is mainly needed around branching, when versions need to be changed.
[AB#572904](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/572904)

Make Engineering Systems owner of app.json files

---

build/scripts/CrossBranchPorting.psm1

Sometimes backporting doesn't require new work items and it's useful to reuse the work item number from the original pull request.
Plus, a support for `SupportsShouldProcess`.
[AB#572904](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/572904)

Add ability to reuse the work item when backporting PRs

---

src/System Application/App/Cryptography Management/src/CryptographyManagementImpl.Codeunit.al

Backport of https://github.com/microsoft/BCApps/pull/3443
Fixes #3438
Fixes [AB#573459](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/573459)

Bug 573459: [26.x][BCApps #3443]Update SignData procedure to include RSASignaturePadding parameter

---

build/Packages.json
build/scripts/EnlistmentHelperFunctions.psm1

Version 27.0.25098.1 is the latest version of the package, but due to a change in the versioning, it's lower than the current version.
Fixes [AB#573748](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/573748)

Uptake version 27.0.25098.1 of Microsoft.Dynamics.BusinessCentral.Translations

---

src/System Application/App/AI/app.json
src/System Application/App/AI/src/Azure OpenAI/AzureOpenAIImpl.Codeunit.al

__BACKPORT:__
When the AL developer toolkit was introduced, our AI systems were still in an early stage, and we did not have an infrastructure capable of supporting high volumes of calls, or throttling capabilities, or use cases that required running AI capabilities in the background.
Now we have a strong Copilot backend that can throttle high usage, measure consumption, as well as Agents that run in the background and can use AI to provide huge business values for customers and users of the system.
Removing the gating that doesn't allow using capabilities in background sessions.
Fixes [AB#569021](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/569021)

[26.x][Copilot] Allow capabilities to run in background (#3225)

---

src/System Application/Test/Retention Policy/src/RetentionPolicyTest.Codeunit.al

Error:
```
Compilation started for project 'System Application Test' containing '218' files at '20:48:05.670'.
App\BCApps\src\System Application\Test\Retention Policy\src\RetentionPolicyTest.Codeunit.al(1785,67): error AA0202: The name of the local variable 'RetentionPolicyCode' is identical to a field, method, or action in the same scope.
Compilation ended at '20:48:16.381'
```
[AB#574429](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/574429)

Fix AA0202 in RetentionPolicyTest.Codeunit.al

---

src/System Application/App/Azure Blob Services API/src/API Enums/ABSBlobAccessTier.Enum.al

Archive enum value (3) is unsupported for Azure Blob Storage, Archive value is eligible only for Azure Files.
Azure Blob has a similar, called 'Cold'.
Thus, this PR adds 'Cold' enum value with id = 2 to enum 9042 "ABS Blob Access Tier".
Fixes #3399
Fixes [AB#574979](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/574979)

Fixes #3399

---

.github/Update AL-Go System Files.settings.json
.github/actions/GetGitBranches/action.ps1
.github/workflows/SubmitStabilityJobs.yaml
.github/workflows/UpdateBCArtifactVersion.yaml
.github/workflows/UpdatePackageVersions.yaml
build/scripts/EnlistmentHelperFunctions.psm1

Currently we run some weekly automations on all branches that matches "main" or "releases/*". However, some branches like releases/24.0 is out of support. 
This PR enables us to stop running automations on out of support branches. The steps to take when a branch goes out of support is: 
* Add the branch to the "Branch is out of support" ruleset
* Update "Update AL-Go System Files.settings.json" so it doesn't include the branch
Fixes [AB#574801](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/574801)

Only run automation on supported branches

---

src/System Application/App/Email/src/Message/EmailMessage.Codeunit.al
src/System Application/App/Email/src/Message/EmailMessageImpl.Codeunit.al
src/System Application/Test/Email/src/EmailMessageUnitTest.Codeunit.al

Adding a requested functionality for deleting orphaned Email Recipients.
As the primary key is related to the Email Message, it validates if the Email Message still exists before deleting.
The dict of orphans are used for caching to reduce checking on the DB.
Fixes [AB#572212](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/572212)

[Email] Add functionality to delete orphaned email recipients.

---

src/Tools/Test Framework/Test Runner/src/CodeCoverage/ALCodeCoverage.Page.al
src/Tools/Test Framework/Test Runner/src/CodeCoverage/ALCodeCoverageMgt.Codeunit.al

Hardening the UI around Code Coverage
We will update the status when the page is opened. If there is a misalignment in any way, now it is easy to restart the code coverage.
Fixes [AB#564436](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/564436)

Test Runner - Hardening the UI around Code Coverage

---

src/System Application/App/Azure AD User Management/src/AzureADUserMgmtImpl.Codeunit.al

In certain situations when we sync users from M365 they have multiple identical permissions. This means we will attempt to add the same access control to TempAccessControlWithDefaultPermissions multiple times.
Solution, if it's already added once, don't re-add it.
Fixes [AB#575613](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/575613)

M365 Sync may fail as multiple identical permissions are added to the same temporary table

---

src/System Application/App/AI/src/Copilot/CopilotQuotaImpl.Codeunit.al

The telemetry is not a warning but is being published as a warning.
Fixes [AB#575607](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/575607)

[AI] Update telemetry verbosity for CanConsume from warning to normal.

---

src/System Application/App/Azure AD User Management/src/AzureADUserMgmtImpl.Codeunit.al

In certain situations when we sync users from M365 they have multiple identical permissions. This means we will attempt to add the same access control to TempAccessControlWithDefaultPermissions multiple times.
Solution, if it's already added once, don't re-add it.
Fixes [AB#575639](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/575639)

[releases/26.x] M365 Sync may fail as multiple identical permissions are added to the same temporary table

---

src/System Application/App/Azure AD User Management/src/AzureADUserMgmtImpl.Codeunit.al

In certain situations when we sync users from M365 they have multiple identical permissions. This means we will attempt to add the same access control to TempAccessControlWithDefaultPermissions multiple times.
Solution, if it's already added once, don't re-add it.
Fixes [AB#575638](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/575638)

[releases/26.1] M365 Sync may fail as multiple identical permissions are added to the same temporary table

---

src/System Application/App/Azure AD User Management/src/AzureADUserMgmtImpl.Codeunit.al

In certain situations when we sync users from M365 they have multiple identical permissions. This means we will attempt to add the same access control to TempAccessControlWithDefaultPermissions multiple times.
Solution, if it's already added once, don't re-add it.
Fixes [AB#575637](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/575637)

[releases/26.0] M365 Sync may fail as multiple identical permissions are added to the same temporary table

---

src/System Application/Test/Rest Client/app.json
src/System Application/Test/Rest Client/src/MockRestClientService.Codeunit.al
src/System Application/Test/Rest Client/src/RestClientTests.Codeunit.al

We must refactor the Rest Client tests not to use actual services. The tests are fragile and we must not call actual endpoints from our automation gates. It is a horrible practice that must be avoided at all costs. We are introducing the cost on the endpoint. No automated test should target actual live services. This can only be done with semiautomated or manual testing. 
Fixes [AB#564620](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/564620)

Refactoring Rest Client Tests to use HttpClient Mocking instead of an actual service

---

src/Business Foundation/App/NoSeriesCopilot/src/Copilot/Telemetry/NoSeriesCopilotTelemetry.Codeunit.al

The function `LogApply` does not take the record as var. As such when it does a count, the result is always 0 and the telemetry is never sent.
Fixes [AB#575872](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/575872)

[Bug fix] The function logapply does not take the record as var. As such the telemetry is never sent

---

src/System Application/App/Language/src/LanguageImpl.Codeunit.al

Change from #2463 limited the Region selection to application languages. This change reverts the LookupWindowsLanguageId change to allow users to select any language available from the Windows Languages.
Fixes [AB#575955](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/575955)

[Language] Revert LookupWindowsLanguageId change from #2463

---

src/System Application/App/AI/src/Copilot/CopilotQuotaImpl.Codeunit.al

This pull request backports #3621 to releases/26.x
Fixes [AB#575635](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/575635)

[releases/26.x] [AI] Update telemetry verbosity for CanConsume from warning to normal.

---

src/System Application/App/Page Summary Provider/src/PageSummaryProviderImpl.Codeunit.al
src/System Application/Test/Page Summary Provider/src/PageSummaryProviderTest.Codeunit.al

In the Payables Agent, the agent can finish in the Purchase Invoice page, this triggers the summarization in this page within a try function.
Try functions don't allow write transactions to be started, so if the onopen logic requires write transactions, it crashes, in this particular case inserting a notification is crashing it.
Fixes [AB#575512](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/575512)

26.x: No try functions in Page Summary

---

src/System Application/App/Cryptography Management/src/SignatureKey.Codeunit.al

I need to sign some data with the private key of the certificate that is stored in Azure Key Vault.
- The private key is obtained in base64 format by running AzureKeyVault.GetAzureKeyVaultCertificate('Key', Certificate).
- Then dotnet object X509Certificate2 is initialized from that base64 string by running SignatureKey.FromBase64String(Certificate.Unwrap(), EmptySecretText, true).
- And finally the function CryptographyManagement.SignData() is used, but it accepts private key only in XML format.
To convert X509Certificate2 to XML format, SignatureKey.ToXmlString() function can be used, but it is now internal, so I want to make it external to use for that purpose.
Full code:
```
[NonDebuggable]
procedure SignDataWithAKVCertificate(DataToSign: Text)
var
AzureKeyVault: Codeunit "Azure Key …
```

Make ToXmlString() function of codeunit "Signature Key" external

---

src/System Application/App/Base64 Convert/src/Base64Convert.Codeunit.al
src/System Application/App/Base64 Convert/src/Base64ConvertImpl.Codeunit.al

Backport from main to releases/26.x
When base64 string is sent as a part of URL, it must be URL-safe, i.e. must not contain characters +, / and =:
"+" must be replaced with "-"
"/" must be replaced with "_"
"=" must be removed
I want to add a new function that will do base64url encoding to the "Base64 Convert" codeunit.
Fixes [AB#578358](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/578358)

[26.x] Add Base64UrlEncode() function to "Base64 Convert" codeunit

---

src/System Application/App/Cryptography Management/src/SignatureKey.Codeunit.al

Backport from main to releases/26.x
I need to sign some data with the private key of the certificate that is stored in Azure Key Vault.
- The private key is obtained in base64 format by running AzureKeyVault.GetAzureKeyVaultCertificate('Key', Certificate).
- Then dotnet object X509Certificate2 is initialized from that base64 string by running SignatureKey.FromBase64String(Certificate.Unwrap(), EmptySecretText, true).
- And finally the function CryptographyManagement.SignData() is used, but it accepts private key only in XML format.
To convert X509Certificate2 to XML format, SignatureKey.ToXmlString() function can be used, but it is now internal, so I want to make it external to use for that purpose.
Full code:
```
[NonDebuggable]
procedure SignDataWithAKVCertificate(DataToSign: Text)
var …
```

[26.x] Make ToXmlString() function of codeunit "Signature Key" external

---

src/Tools/Test Framework/Test Runner/src/SelectTestRunner.Page.al
src/Tools/Test Framework/Test Runner/src/SelectTests.Page.al
src/Tools/Test Framework/Test Runner/src/TestMethodLine.Table.al
src/Tools/Test Framework/Test Runner/src/TestSuiteMgt.Codeunit.al

`AllObjWithCaption` was used to power TestRunner probably because we don't have `Codeunit Metadata` until recently.
Switching to `Codeunit Metadata` will:
1. Speed things up (naturally, with less data in the table)
2. Laying down the foundation to uptake `TestType` property on codeunits
Checking Telemetry for Symbol Usage:
1. The 2 pages have no usage, using pragma to suppress warnings
2. There is usage for `procedure GetTestMethods`. Properly obsolete it instead. 
Fixes [AB#579962](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/579962)

TestRunner will be powered by CodeunitMetadata instead

---

src/System Application/App/VS Code Integration/src/VsCodeIntegrationImpl.Codeunit.al
src/System Application/Test/Vs Code Integration/src/VSCodeIntegrationTest.Codeunit.al

This pull request backports #3137 to releases/26.x
Fixes [AB#579978](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/579978)

[releases/26.x] #3114 Format AppId without brackets and lowercase for VsCode Integration

---

src/System Application/App/VS Code Integration/src/VsCodeIntegrationImpl.Codeunit.al
src/System Application/Test/Vs Code Integration/src/VSCodeIntegrationTest.Codeunit.al

This pull request backports #3137 to releases/26.2
Fixes [AB#579978](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/579978)

[releases/26.2] #3114 Format AppId without brackets and lowercase for VsCode Integration

---

src/Business Foundation/App/NoSeriesCopilot/src/Copilot/NoSeriesCopilotImpl.Codeunit.al
src/System Application/App/AI/src/Azure OpenAI/AOAIDeployments.Codeunit.al
src/System Application/App/AI/src/Azure OpenAI/AOAIDeploymentsImpl.Codeunit.al
src/System Application/App/Entity Text/src/EntityTextImpl.Codeunit.al

AI Resources are adding support for GPT41 and GPT41 mini and phasing out GPT4o.
Fixes [AB#580889](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/580889)

[AI] Add GPT41 and GPT41 mini to AOAI deployments

---

src/System Application/App/Azure AD Plan/src/Plan Configuration/Default Permssions/DefaultPermissionSetInPlan.Page.al
src/System Application/App/Azure AD Plan/src/Plan Configuration/PlanConfigurationCard.Page.al
src/System Application/App/Azure AD Plan/src/Plan Configuration/PlanConfigurationImpl.Codeunit.al

**Problem**
Few customers have default license configurations that have tenant permission sets mixed in with their default license configuration. This is likely due to the conversion of User Groups to permission sets.
**Solution**
Add an action to remove the tenant permission sets from the selected license configuration.
Fixes [AB#581156](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/581156)

[Permissions] Functionality to restore license configuration default to defaults without tenant permission sets

---

src/System Application/App/Language/src/AllowedLanguage.Table.al
src/System Application/App/Language/src/LanguageImpl.Codeunit.al

The filters on "Localization Exist" and "Globally Enabled" limited the list of languages that were previously allowed to be selected from. This removed numerous languages resulting in incidents.
Removal of the filter resets this back to how it worked before 26.0 and only if you set up Allowed Languages, then the list of languages will be filtered.
Fixes [AB#591234](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/591234)

[Languages] Show all Windows Languages if no Allowed Languages are configured

---

build/projects/Business Foundation/.AL-Go/settings.json
build/projects/System Application/.AL-Go/settings.json
build/projects/Test Framework/.AL-Go/settings.json

This pull request backports #4095 to releases/24.5

[releases/24.5] Disable Translated mode due to instabilities with error "End of Central Directory record could not be found"

---

build/projects/Business Foundation/.AL-Go/settings.json
build/projects/System Application/.AL-Go/settings.json
build/projects/Test Framework/.AL-Go/settings.json

This pull request backports #4095 to releases/24.x

[releases/24.x] Disable Translated mode due to instabilities with error "End of Central Directory record could not be found"

---

build/projects/Business Foundation/.AL-Go/settings.json
build/projects/System Application/.AL-Go/settings.json

This pull request backports #4095 to releases/25.3

[releases/25.3] Disable Translated mode due to instabilities with error "End of Central Directory record could not be found"

---

build/projects/Business Foundation/.AL-Go/settings.json
build/projects/System Application/.AL-Go/settings.json

This pull request backports #4095 to releases/25.2

[releases/25.2] Disable Translated mode due to instabilities with error "End of Central Directory record could not be found"

---

build/projects/Business Foundation/.AL-Go/settings.json
build/projects/System Application/.AL-Go/settings.json

This pull request backports #4095 to releases/25.0

[releases/25.0] Disable Translated mode due to instabilities with error "End of Central Directory record could not be found"

---

build/projects/Business Foundation/.AL-Go/settings.json
build/projects/System Application/.AL-Go/settings.json

This pull request backports #4095 to releases/25.x

[releases/25.x] Disable Translated mode due to instabilities with error "End of Central Directory record could not be found"

---

build/projects/Business Foundation/.AL-Go/settings.json
build/projects/System Application/.AL-Go/settings.json

This pull request backports #4095 to releases/26.3

[releases/26.3] Disable Translated mode due to instabilities with error "End of Central Directory record could not be found"

---

build/projects/Business Foundation/.AL-Go/settings.json
build/projects/System Application/.AL-Go/settings.json

This pull request backports #4095 to releases/26.1

[releases/26.1] Disable Translated mode due to instabilities with error "End of Central Directory record could not be found"

---

src/System Application/Test/Cryptography Management/src/RSACryptoServiceProviderTests.Codeunit.al

This pull request backports #4116 to releases/26.x
Fixes [AB#575006](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/575006)

[releases/26.x] [Cryptography Management] Failing test

---

src/Business Foundation/App/NoSeriesCopilot/src/Copilot/NoSeriesCopilotImpl.Codeunit.al
src/System Application/App/AI/src/Azure OpenAI/AOAIDeployments.Codeunit.al
src/System Application/App/AI/src/Azure OpenAI/AOAIDeploymentsImpl.Codeunit.al
src/System Application/App/Entity Text/src/EntityTextImpl.Codeunit.al

On July 15th, BIC will switch to the model GPT 4.1, so this is a step into that direction. 
Fixes [AB#591910](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/591910)

[26.2] Azure OpenAI app - Expose GPT 4.1

---

src/Business Foundation/App/NoSeriesCopilot/src/Copilot/NoSeriesCopilotImpl.Codeunit.al
src/System Application/App/AI/src/Azure OpenAI/AOAIDeployments.Codeunit.al
src/System Application/App/AI/src/Azure OpenAI/AOAIDeploymentsImpl.Codeunit.al
src/System Application/App/Entity Text/src/EntityTextImpl.Codeunit.al

On July 15th, BIC will switch to the model GPT 4.1, so this is a step into that direction.
Work Item(s)
Fixes [AB#591908](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/591908)

[26.0] Azure OpenAI app - Expose GPT 4.1

---

src/System Application/App/Performance Profiler/src/PerfProfilerScheduleCard.Page.al
src/System Application/App/User Selection/src/UserLookup.Page.al
src/System Application/App/User Selection/src/UserSelection.Codeunit.al
src/System Application/App/User Selection/src/UserSelectionImpl.Codeunit.al
src/System Application/Test/User Selection/src/UserSelectionTest.Codeunit.al

Recent change to show user name instead of ID in the scheduler card regressed ability to schedule for external users. That is because the user lookup page filters out external users. Added an API to the facade to not filter out external users.
Fixes [AB#591952](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/591952)

[26.x][Performance Scheduler] Allow scheduling profilers for all user types except external

---

src/Apps/W1/Subscription Billing/App/Sales Service Commitments/Report Extensions/ContractSalesOrderConf.ReportExt.al

The fix includes changes for "Standard Sales - Order Conf." report extension in Subscription billing app.
Fixes [AB#575361](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/575361)

[Subscription Billing] Test StdSalesOrderConfAssemblyComponentsRDLC fails when Subscription Billing is installed

---

src/System Application/App/Email/src/RateLimit/EmailRateLimitImpl.Codeunit.al

The root cause is if our customer scheduled too many emails at the same time, for every email sending we shall check if it exceeds the max concurrency limit in background -> too many reading to the same table emailOutbox at the same time. And this table is also used in the following sending steps -> this causes the deadlock.
I shall create a hotfix for this issue -
Use readIsolate:Uncommitted because we don't care a lot if the table is changed or not.
Change the order to processing email sending to ensure the lock time is shortest.
Fixes [AB#592726](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/592726)

[26.x] Fix email concurrency limit issue with read Isolation 

---

src/System Application/App/Email/src/RateLimit/EmailRateLimitImpl.Codeunit.al

The root cause is if our customer scheduled too many emails at the same time, for every email sending we shall check if it exceeds the max concurrency limit in background -> too many reading to the same table emailOutbox at the same time. And this table is also used in the following sending steps -> this causes the deadlock.
I shall create a hotfix for this issue -
Use readIsolate:Uncommitted because we don't care a lot if the table is changed or not.
Change the order to processing email sending to ensure the lock time is shortest.
Fixes [AB#592720](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/592720)

[main] fix issue with read Isolation

---

build/projects/System Application Tests/.AL-Go/settings.json
build/projects/System Application/.AL-Go/settings.json

Move system application test library to another AL-Go project
This fixes the linked bug because right now testapp dependencies can only be properly picked up if the appFolders setting isn't empty. 
Fixes [AB#593430](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/593430)

Move system application test library to another AL-Go project

---

src/System Application/App/Email/src/EmailInstaller.Codeunit.al
src/System Application/App/Email/src/EmailUpgrade.Codeunit.al
src/System Application/App/Performance Profiler/src/PerformanceProfilerInstaller.Codeunit.al
src/System Application/App/Retention Policy/src/Install/RetentionPolicyInstaller.Codeunit.al
src/System Application/App/Retention Policy/src/Retention Policy Setup/RetentionPolicySetupList.Page.al

Backporting ##4178 and #4236 , this is causing more problems in PROD
Fixes [AB#593447](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/593447)

[26.3] Insert Retention Policy Allowed Tables when open page instead 

---

src/System Application/App/Performance Profiler/src/ScheduledPerfProfilerImpl.Codeunit.al

GDAP users are affected when this code is run from various places and prevents them from performing their action.
They have the license permission for indirect insert but not direct insert. 
This adds indirect read and indirect insert to the permissions on the codeunit.
Fixes [AB#595852](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/595852)

Add indirect permissions to ScheduledPerfProfilerImpl codeunit

---

src/System Application/App/Performance Profiler/src/ScheduledPerfProfilerImpl.Codeunit.al

This pull request backports #4342 to releases/26.x
Fixes [AB#595909](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/595909)

[releases/26.x] Add indirect permissions to ScheduledPerfProfilerImpl codeunit

---

build/projects/Apps (W1)/.AL-Go/RunTestsInBcContainer.ps1
src/Apps/W1/Subscription Billing/Test/Billing/BillingCorrectionTest.Codeunit.al
src/Apps/W1/Subscription Billing/Test/Billing/RecurringBillingDocsTest.Codeunit.al
src/Apps/W1/Subscription Billing/Test/Billing/RecurringBillingTest.Codeunit.al
src/Apps/W1/Subscription Billing/Test/Billing/RecurringDiscountTest.Codeunit.al
src/Apps/W1/Subscription Billing/Test/Contract Price Update/ContractPriceProposalTest.Codeunit.al
src/Apps/W1/Subscription Billing/Test/Contract Price Update/ContractPriceUpdateTest.Codeunit.al
src/Apps/W1/Subscription Billing/Test/Contract Renewal/ContractRenewalTest.Codeunit.al
src/Apps/W1/Subscription Billing/Test/Customer Contracts/ContractDimensionsTest.Codeunit.al
src/Apps/W1/Subscription Billing/Test/Customer Contracts/ContractsTest.Codeunit.al
src/Apps/W1/Subscription Billing/Test/Customer Contracts/ExtendContractTest.Codeunit.al
src/Apps/W1/Subscription Billing/Test/Deferrals/CustomerDeferralsTest.Codeunit.al
src/Apps/W1/Subscription Billing/Test/Deferrals/VendorDeferralsTest.Codeunit.al
src/Apps/W1/Subscription Billing/Test/Import/ImpServiceAndContractTest.Codeunit.al
src/Apps/W1/Subscription Billing/Test/Service Commitments/SalesServiceCommitmentTest.Codeunit.al
src/Apps/W1/Subscription Billing/Test/Service Commitments/ServiceCommArchiveTest.Codeunit.al
src/Apps/W1/Subscription Billing/Test/Service Commitments/ServiceCommDimensions.Codeunit.al
src/Apps/W1/Subscription Billing/Test/Service Commitments/ServiceCommitmentTest.Codeunit.al
src/Apps/W1/Subscription Billing/Test/Service Objects/ItemServCommTest.Codeunit.al
src/Apps/W1/Subscription Billing/Test/Service Objects/ItemServiceCommTypeTest.Codeunit.al
src/Apps/W1/Subscription Billing/Test/Service Objects/ServiceObjectTest.Codeunit.al
src/Apps/W1/Subscription Billing/Test/Service Objects/TemplatesTest.Codeunit.al
src/Apps/W1/Subscription Billing/Test/UBB/GenericImportTest.Codeunit.al
src/Apps/W1/Subscription Billing/Test/UBB/ItemReferenceTest.Codeunit.al
src/Apps/W1/Subscription Billing/Test/UBB/LinkSubscriptionToSOTest.Codeunit.al
src/Apps/W1/Subscription Billing/Test/UBB/UsageBasedBillingTest.Codeunit.al
src/Apps/W1/Subscription Billing/Test/UBB/UsageBasedExtendContrTest.Codeunit.al
src/Apps/W1/Subscription Billing/Test/UBB/UsageBasedRebillingTest.Codeunit.al
src/Apps/W1/Subscription Billing/Test/UBB/UsageBasedServiceCommTest.Codeunit.al
src/Apps/W1/Subscription Billing/Test/Vendor Contracts/VendorContractsTest.Codeunit.al

Marking all Subscription Billing's tests as `Uncategroized`.
This is needed because we haven't gotten to this project yet, marking tests as `Uncategroized` will ensure tests run exactly as before.
Fixes [AB#593048](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/593048)

Marking all Subscription Billing's tests as Uncategroized

---

src/Apps/W1/Shopify/App/src/Order handling/Codeunits/ShpfyOrderMapping.Codeunit.al

Auto create new customer toggle prevents connector from using default customer
Fixes [AB#595971](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/592060)

[Shopify] Auto create new customer toggle prevents connector from using default customer

---

src/System Application/App/Agent/Interaction/AgentTaskImpl.Codeunit.al
src/System Application/App/Agent/TaskPane/AgentTaskDetails.Page.al
src/System Application/App/Agent/TaskPane/AgentTaskTimeline.Page.al
src/System Application/App/Agent/TaskPane/AgentTasks.Page.al

Add support for agent suggestions and free text instructions in the agent task pane (#3784)
Fixes
[AB#579777](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/579777)
[AB#579778](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/579778)
[AB#596026](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/596026)

[26.1] Add support for agent suggestions and free text instructions in the agent task pane

---

src/System Application/App/Agent/Interaction/AgentTaskImpl.Codeunit.al
src/System Application/App/Agent/TaskPane/AgentTaskDetails.Page.al
src/System Application/App/Agent/TaskPane/AgentTaskTimeline.Page.al
src/System Application/App/Agent/TaskPane/AgentTasks.Page.al

Add support for agent suggestions and free text instructions in the agent task pane (#3784)
Fixes
[AB#579777](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/579777)
[AB#579778](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/579778)
[AB#596027](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/596027)

[26.0] Add support for agent suggestions and free text instructions in the agent task pane

---

src/System Application/App/Cryptography Management/src/Xml/SignedXml.Codeunit.al
src/System Application/Test/Cryptography Management/src/Xml/SignedXmlModuleTest.Codeunit.al

Added methods in SignedXml accepting the signing key as a SecretText:
```
SetSigningKey(XmlString: SecretText)
SetSigningKey(XmlString: SecretText; SignatureAlgorithm: Enum SignatureAlgorithm)
```
Fixes #4176 
Fixes [AB#596370](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/596370)

SetSigningKey in SignedXml accepts the key as SecretText

---

src/Apps/W1/Shopify/App/src/Order handling/Codeunits/ShpfyCopySalesDocument.Codeunit.al
src/Apps/W1/Shopify/App/src/Order handling/Table Extensions/ShpfySalesHeaderArchive.TableExt.al
src/Apps/W1/Shopify/App/src/Order handling/Table Extensions/ShpfySalesLineArchive.TableExt.al
src/Apps/W1/Shopify/App/src/PermissionSets/ShpfyObjects.PermissionSet.al
src/Apps/W1/Shopify/Test/Order Handling/ShpfyOrderTest.Codeunit.al

Add Shopify related fields to sales order achives
Fixes [AB#596501](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/596501)

[Shopify] Add Shopify related fields to sales order archives

---

src/System Application/Test/Translation/src/TranslationTests.Codeunit.al

The format of record Id is being changed to include the namespace. however in one of the tests the incorrect format of record id option is used to be compared with the caption. This PR will address the test defect
[Slice 501761](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/501761): [AL][Namespaces] Adding namespace to the metadata system and the system tables
Fixes [AB#501761](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/501761)
Addresses the incorrect format option on a recordId

Fixing the format option used for the recordId 

---

src/Apps/W1/Shopify/App/src/Base/Codeunits/ShpfyCommunicationMgt.Codeunit.al
src/Apps/W1/Shopify/App/src/Webhooks/Codeunits/ShpfyWebhooksAPI.Codeunit.al

Outgoing request check is meant for not overriding data in Shopify, creating or deleting webhooks have very little to do with it. Iy blocks enabling connection since we register a bulk operation webhook on enable
Fixes [AB#597635](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/597635)

[Shopify] Do not check outgoing requests for webhook create and delete calls

---

build/scripts/AppExtensionsHelper.psm1

This pull request backports #4558 to releases/27.x
Related to [AB#598707](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/598707)

[releases/27.x] Hardcode platform version to 27.0.0.0 for now

---

src/Apps/W1/Shopify/Test/Base/ShpfyInitializeTest.Codeunit.al
src/Apps/W1/Shopify/Test/Catalogs/ShpfyMarketCatalogAPITest.Codeunit.al
src/Apps/W1/Shopify/Test/Companies/ShpfyCompanyLocationsTest.Codeunit.al
src/Apps/W1/Shopify/Test/Products/ShpfyCreateItemAPITest.Codeunit.al
src/Apps/W1/Shopify/Test/Staff/ShpfyStaffTest.Codeunit.al

This pull request backports #4501 to releases/27.0
Fixes [AB#598714](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/598714)

[releases/27.0] [Shopify] Add HttpClientHandler request path check from a single place

---

src/Business Foundation/App/NoSeries/src/Upgrade/NoSeriesInstaller.Codeunit.al
src/Business Foundation/App/NoSeries/src/Upgrade/NoSeriesUpgrade.Codeunit.al
src/Business Foundation/App/NoSeries/src/Upgrade/NoSeriesUpgradeTags.Codeunit.al

`"Allow Gaps in Nos."` field is obsoleted, but we are still referencing it in `Install` codeunit.
Moving the upgrade logic completely into `Upgrade` codeunit.
Fixes [AB#599301](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/599301)

Fix obsoletion in v27.0 for No Series

---

src/Apps/W1/Shopify/App/src/Products/Codeunits/ShpfyCreateItem.Codeunit.al
src/Apps/W1/Shopify/App/src/Products/Codeunits/ShpfyProductImport.Codeunit.al
src/Apps/W1/Shopify/Test/Products/ShpfyCreateItemAPITest.Codeunit.al

This pull request backports #4628 to releases/27.0
Fixes [AB#599038](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/599038)

[releases/27.0] [Shopify] Add error to item creation when setting is not enabled

---

src/Apps/W1/Shopify/App/src/Products/Codeunits/ShpfyCreateItem.Codeunit.al
src/Apps/W1/Shopify/App/src/Products/Codeunits/ShpfyProductImport.Codeunit.al
src/Apps/W1/Shopify/Test/Products/ShpfyCreateItemAPITest.Codeunit.al

This pull request backports #4628 to releases/27.x
Fixes [AB#599307](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/599307)

[releases/27.x] [Shopify] Add error to item creation when setting is not enabled

---

src/Apps/W1/Subscription Billing/App/Billing/Codeunits/CreateBillingDocuments.Codeunit.al

When Subscription Billing app creates a new billing document it
validates the vendor number and posting date. Then the IRS forms app,
which is the US specific app, not related to subscription billing, run
an update of certain fields related to this app. This kind of update in
the IRS forms app from the other side triggers the Subscription billing
app code - the CreatePurchaseHeaderForVendorNo procedure. This procedure
throws the following error:
You cannot make this change because the document is linked to a
contract. If you still want to change the field, first delete this
document and then make the change to the contract.
This procedure has a list of fields for exclusion. It would be great to
add IRS forms app fields to the exclusion list, but that is not possible
unless i create a …

Subscription billing app conflicts with IRS Forms app

---

src/Tools/Test Framework/Test Runner/src/DataDrivenTest/DataInputs/TestInputsManagement.Codeunit.al

**Problem:**
When failing to parse YAML file, a generic error is thrown.
**Solution:**
Improve error message when failing to parse YAML due to the data not representing valid YAML.
Fixes [AB#592948](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/592948/)

Improve error message when failing to parse yaml

---

.github/AL-Go-Settings.json
build/projects/Apps (W1)/.AL-Go/NewBcContainer.ps1

During the Apps (W1) build where we compile, publish and test the add-on apps we start out by creating the container and then we uninstall all apps and unpublish a certain set of apps. The set of apps we unpublish contains the apps under the Apps/W1 folder here in BCApps. 
Right now, the unpublish step fails in #4757 due to the fact that there are apps that take dependency on the Power BI app. To avoid having to unpublish a lot of apps, we can instead just uninstall all apps but keep the apps published. 
There is one slight challenge with this though. When we want to publish a new version of App A that takes dependency on App B. If App B is already published to the container in two different versions, it will use the version with the highest version number. Right now, the apps with the …

Keep apps installed during Apps build and add RunNumberOffset to build numbers

---

src/Apps/W1/Shopify/App/src/Companies/Codeunits/ShpfySyncCompanies.Codeunit.al
src/Apps/W1/Shopify/App/src/Customers/Codeunits/ShpfySyncCustomers.Codeunit.al

Sync only mapped customers if import setting is "with order import"
Fixes [AB#602510](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/602510)

[Shopify] Sync only mapped customers if import setting is "with order import"

---

src/Apps/W1/Subscription Billing/App/Sales Service Commitments/Table Extensions/SalesHeader.TableExt.al

Added ReadIsolation for preventing unnecessary locking.
Fixes #4810
Fixes [AB#598652](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/598652)

[Subscription billing] Unnecessary locking in Subscription Billing causing lock timeout in sales post

---

src/System Application/Test/DisabledTests/ImageTests.DisabledTest.json

This pull request backports #4874 to releases/25.x

[releases/25.x] Disable image tests 

---

src/System Application/Test/DisabledTests/ImageTests.DisabledTest.json

This pull request backports #4874 to releases/24.x

[releases/24.x] Disable image tests 

---

src/System Application/Test/DisabledTests/ImageTests.DisabledTest.json

This pull request backports #4874 to releases/25.5

[releases/25.5] Disable image tests 

---

src/System Application/Test/DisabledTests/ImageTests.DisabledTest.json

This pull request backports #4874 to releases/25.4

[releases/25.4] Disable image tests 

---

src/System Application/Test/DisabledTests/ImageTests.DisabledTest.json

This pull request backports #4874 to releases/25.2

[releases/25.2] Disable image tests 

---

src/System Application/Test/DisabledTests/ImageTests.DisabledTest.json

This pull request backports #4874 to releases/25.1

[releases/25.1] Disable image tests 

---

src/System Application/Test/DisabledTests/ImageTests.DisabledTest.json

This pull request backports #4874 to releases/26.3

[releases/26.3] Disable image tests 

---

src/System Application/App/Email/src/RateLimit/EmailRateLimitImpl.Codeunit.al
src/System Application/Test/Email/src/EmailRetryTest.Codeunit.al

Now the email sending could be blocked because the status of the emails' updating failed. For example, the email sending already completed, but for permission issue or any other issue, the email status of the email in email outbox is not updated correctly. Then if more than 10 emails stuck there with status "processing", it will block the whole email sending.
To solve this issue, we consider to add a time range when consider the concurrency of email. 
Fixes [AB#603459](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/603459)

[Email] Add filter on time when counting email concurrency to avoid fake "Processing" email block email sending

---

src/System Application/App/Email/src/RateLimit/EmailRateLimitImpl.Codeunit.al
src/System Application/Test/Email/src/EmailRetryTest.Codeunit.al

This pull request backports #4820 to releases/27.0
Fixes [AB#606061](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/606061)

[releases/27.0] [Email] Add filter on time when counting email concurrency to avoid fake "Processing" email block email sending

---

src/System Application/App/Email/src/RateLimit/EmailRateLimitImpl.Codeunit.al
src/System Application/Test/Email/src/EmailRetryTest.Codeunit.al

This pull request backports #4820 to releases/27.x
Fixes [AB#606062](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/606062)

[releases/27.x] [Email] Add filter on time when counting email concurrency to avoid fake "Processing" email block email sending

---

src/System Application/App/Email/src/RateLimit/EmailRateLimitImpl.Codeunit.al
src/System Application/Test/Email/src/EmailRetryTest.Codeunit.al

This pull request backports #4820 to releases/26.x
Fixes [AB#606060](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/606060)

[releases/26.x] [Email] Add filter on time when counting email concurrency to avoid fake "Processing" email block email sending

---

src/Apps/W1/Shopify/App/src/Base/Pages/ShpfyActivities.Page.al
src/Apps/W1/Shopify/App/src/Base/Tables/ShpfyCue.Table.al

This pull request backports #4759 to releases/27.x

[releases/27.x] [Shopify] Add missing sync jobs to cue

---

src/Apps/W1/Shopify/App/src/Base/Page Extensions/ShpfyBusinessManagerRC.PageExt.al
src/Apps/W1/Shopify/App/src/Order handling/Pages/ShpfyOrders.Page.al

This pull request backports #4627 to releases/27.x

[releases/27.x] [Shopify] Remove confusing filter and add views instead to orders page

---

src/Apps/W1/Shopify/App/src/Base/Tables/ShpfyShop.Table.al

This pull request backports #4877 to releases/27.0
Fixes [AB#608911](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/608911)

[releases/27.0] [Shopify] Replace deprecated shop.plan.displayName with publicDisplayName

---

src/Apps/W1/EDocument/App/src/Processing/Import/Purchase/EDocPurchaseDraftSubform.Page.al
src/Apps/W1/EDocument/App/src/Processing/Import/Purchase/EDocumentPurchaseLine.Table.al

This PR fixes the following UX issues:
- The new feature of the currency symbol of the AutoFormat property was showing in the Quantity field of the purchase draft since the field was misclassified.
- The DecimalPlaces property of the quantity was not aligned with other quantities in the product.
- The Line Amount in the draft page had a value when adding a new line.
Fixes [AB#602181](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/602181)
Fixes [AB#608430](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/608430)

UX fixes on amount formats and OnNewRecord on E-Documents draft page

---

src/Apps/W1/Subscription Billing/App/Billing/Codeunits/BillingProposal.Codeunit.al
src/Apps/W1/Subscription Billing/App/Billing/Pages/ArchivedBillingLines.Page.al
src/Apps/W1/Subscription Billing/App/Billing/Pages/ArchivedBillingLinesList.Page.al
src/Apps/W1/Subscription Billing/App/Billing/Pages/BillingLines.Page.al
src/Apps/W1/Subscription Billing/App/Billing/Pages/BillingLinesList.Page.al
src/Apps/W1/Subscription Billing/App/Billing/Pages/RecurringBilling.Page.al
src/Apps/W1/Subscription Billing/App/Billing/Tables/BillingLine.Table.al
src/Apps/W1/Subscription Billing/App/Billing/Tables/BillingLineArchive.Table.al
src/Apps/W1/Subscription Billing/App/Service Commitments/Tables/SubscriptionLine.Table.al
src/Apps/W1/Subscription Billing/App/Usage Based Billing/Codeunits/ProcessUsageDataBilling.Codeunit.al
src/Apps/W1/Subscription Billing/Test/Billing/RecurringBillingTest.Codeunit.al

For a contract starting on **27.02.2020**, billed quarterly with **"Align to End of Month"** enabled:
This fix corrects the **Billing-To Date** calculation for quarterly contracts that use the **"Align to End of Month"** option.
- For example, a contract starting on **27.02.2020** with the first billing period split manually (**27.02.2020–29.02.2020**) and the next period beginning **01.03.2020** should end on **31.05.2020**.
- Previously, the system incorrectly calculated the end date as **27.06.2020**.
- The fix ensures that when the start of the billing period is adjusted to the **first of the month**, the system correctly determines the end of the full billing quarter, preserving alignment with the “End of Month” rule.
Fixes #5089 
Fixes …

[27.0] Incorrect Billing To Date for Billing Lines (#4621)
